# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/client/const/lobby_model_display_const.py
_reload_all = True
DEFAULT_RIGHT = '1'
DEFAULT_MID = '2'
DEFAULT_LEFT = '3'
BATTLE_PASS = '4'
WEAPON_SHOW = '5'
MALL_WEAPON = '7'
BATTLE_PASS_02 = '8'
DEFAULT_LEFT_NEAR = '9'
MECHA_1_5_LEFT = '10'
MECHA_1_5_LEFT_NEAR = '11'
LOTTERY = '6'
LUCKY_HOUSE = '12'
LUCKY_HOUSE_SMALL = '13'
LUCKY_HOUSE_GUN = '14'
ART_COLLECTION = '15'
MECHA_CHUCHANG = '16'
ITEMBOOKS_GESTURE_DISPLAY = '17'
ITEMBOOKS_GESTURE_MANAGE = '18'
ART_COLLECTION_GUN = '19'
MAIN_RANK_SCENE = '20'
SCHOOL_COLLECTION_GUN = '21'
ITEMBOOKS_KILL_SFX_DISPLAY = '22'
GVG_CHOOSE_MECHA_SCENE = '23'
GVG_CHOOSE_LITTLE_MECHA_SCENE = '24'
ART_COLLECTION_5 = '28'
ART_COLLECTION_6 = '29'
CLONE_VOTE_MECHA_SCENE = '31'
SCENE_ZHANSHI_UI = '32'
GET_DECORATION_DISPLAY_CAMERA = '33'
FFA_CHOOSE_MECHA_SCENE = '35'
MECHA_DEATH_CHOOSE_MECHA_SCENE = '36'
FLASH_LUCKY_HOUSE = '37'
SCENE_MECHA_RECONSTRUCT = '38'
SKIN_DEFINE = '39'
GET_MECHA_MODEL_DISPLAY = '43'
ZOMBIEFFA_CHOOSE_MECHA_SCENE = '40'
GET_WEAPON_DISPLAY = '46'
TOP_NATIVE_SCENE = '47'
SMALL_BP_SCENE_1 = '50'
SMALL_BP_SCENE_2 = '51'
TEAM_RECRUIT_SCENE = '55'
PVE_MAIN_UI = '60'
PVE_BOOK_WIDGET_UI = '61'
PVE_END_UI = '62'
GLIDE_EFFECT_DISPLAY = '63'
ROLE_VIEW_PIC = 1
ROLE_VIEW_MODEL = 2
CAM_MODE_NEAR = 1
CAM_MODE_FAR = 2
CAM_MODE_NEAR_LEG = 3
CAM_MODE_NEAR_HEAD = 4
CAM_DISPLAY_PIC = {CAM_MODE_NEAR: 'gui/ui_res_2/common/icon/icon_glass_small.png',
   CAM_MODE_FAR: 'gui/ui_res_2/common/icon/icon_glass_big.png'
   }
ROTATE_FACTOR = 850
CT_GET_MODEL_DISPLAY = 1
CT_GET_MECHA_MODEL_DISPLAY = 2
CHANGE_CAMERA_MODE_NONE = 0
CHANGE_CAMERA_MODE_CALLBACK_IMMEDIATE = 1
CHANGE_CAMERA_MODE_CALLBACK_ON_END_ANIM = 2
CHANGE_CAMERA_MODE_DONT_CHANGE = 3
CHANGE_CAMERA_MODE_KEEP_FAR = 4