# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/common_const/battle_const.py
from __future__ import absolute_import
_reload_all = True
from logic.gcommon.common_const import statistics_const
from logic.gcommon.const import NEOX_UNIT_SCALE
import math
import math3d
BATTLE_ENV_DEFAULT = 'default'
BATTLE_ENV_NIGHT = 'night'
BATTLE_ENV_SNOW = 'snow'
BATTLE_ENV_SNOW_NIGHT = 'snow_night'
BATTLE_ENV_NEUTRAL_SHOP = 'neutral_shop'
BATTLE_ENV_GRANBELM = 'granbelm'
BATTLE_ENV_SUMMER = 'summer'
BATTLE_ENV_AJLD_NIGHT = 'ajld_night'
BATTLE_ENV_KONGDAO = 'kongdao'
BATTLE_ENV_BOUNTY = 'bounty'
ENV_SUN_OFFSET_DICT = {BATTLE_ENV_BOUNTY: -3.0
   }
ENV_SUN_LIGHT_OFFSET_DICT = {BATTLE_ENV_BOUNTY: -30.0
   }
BATTLE_SCENE_NORMAL = 'bw_all06'
BATTLE_SCENE_KONGDAO = 'kongdao'
BATTLE_SCENE_TEST_JIJIA = 'test_jijia'
INVALID_LANDSCAPE_SCENE = (
 BATTLE_SCENE_KONGDAO, BATTLE_SCENE_TEST_JIJIA)
SHADER_EVN_NORMAL = 0
SHADER_EVN_NIGHT = 1
SHADER_EVN_SNOW = 2
SHADER_EVN_SNOW_NIGHT = 3
SHADER_ENV_MAP = {BATTLE_ENV_NIGHT: SHADER_EVN_NIGHT,
   BATTLE_ENV_SNOW: SHADER_EVN_SNOW,
   BATTLE_ENV_SNOW_NIGHT: SHADER_EVN_SNOW_NIGHT,
   BATTLE_ENV_AJLD_NIGHT: SHADER_EVN_NIGHT
   }
SYNC_TYPE_CREATE = 0
SYNC_TYPE_HIDE = 1
SYNC_TYPE_DESTROY = 2
SYNC_TYPE_LOGIC = 3
SYNC_TYPE_BATTLE = 4
COMBAT_STATE_NONE = 0
COMBAT_STATE_DIE = 1
COMBAT_STATE_FIGHT = 2
COMBAT_STATE_SPECTATE = 3
FIGHT_TYPE_SHOOT = 1
FIGHT_TYPE_POISON = 2
FIGHT_TYPE_BOMB = 3
FIGHT_TYPE_BLEED = 4
FIGHT_TYPE_X_BOMB = 5
FIGHT_TYPE_MELEE = 6
FIGHT_TYPE_CRASH = 7
FIGHT_TYPE_SCENE = 8
FIGHT_TYPE_BUFF = 9
FIGHT_TYPE_SKILL = 10
FIGHT_TYPE_BUILDING = 11
FIGHT_TYPE_SIGNAL = 12
FIGHT_TYPE_THUNDER = 13
FIGHT_TYPE_KILL = 14
FIGHT_TYPE_SHOCK_WAVE = 15
FIGHT_INJ_UNKNOWN = 0
FIGHT_INJ_SHOOT = 1
FIGHT_INJ_MELEE = 2
FIGHT_INJ_BOMB = 3
FIGHT_INJ_POISON = 4
FIGHT_INJ_BLEED = 5
FIGHT_INJ_X_BOMB = 6
FIGHT_INJ_FALLING = 7
FIGHT_INJ_CRASH = 8
FIGHT_INJ_BUFF = 9
FIGHT_INJ_SKILL = 10
FIGHT_INJ_SIGNAL = 11
FIGHT_INJ_THUNDER = 12
FIGHT_INJ_KILL = 14
FIGHT_INJ_SHOCK_WAVE = 15
FIGHT_INJ_MECHA_RELATED = 100
FIGHT_ARTIFICIAL_TYPES = frozenset([
 FIGHT_INJ_SHOOT, FIGHT_INJ_MELEE, FIGHT_INJ_BOMB, FIGHT_INJ_X_BOMB, FIGHT_INJ_CRASH,
 FIGHT_INJ_BUFF, FIGHT_INJ_SKILL, FIGHT_INJ_THUNDER])
MECHA_BROKEN_DAMAGE = 20
RATE_REDUCE_WATER = 0.7
FIGHT_EVENT_BLEED = 1
FIGHT_EVENT_DEATH = 2
FIGHT_EVENT_MECHA_DEATH = 3
FIGHT_EVENT_DEFEAT = 4
FIGHT_EVENT_ELIMINATE = 5
FIGHT_EVENT_DAMAGE = 6
FIGHT_EVENT_MONSTER_DEATH = 7
FIGHT_EVENT_KING_CONTROL = 8
FIGHT_EVENT_RESET_MECHA = 9
FIGHT_EVENT_KILL_GROUP = 10
FIGHT_EVENT_HIT_OTHER = 11
FIGHT_EVENT_REVIVE = 12
HP_RECOVER_NONE = 0
HP_RECOVER_DRUG = 1
HP_RECOVER_ENERGY = 2
ENERGY_ACC_THRESHOLD = 50
MARK_NORMAL = 0
MARK_GOTO = 1
MARK_DANGER = 2
MARK_RES = 3
MARK_ROUTE = 4
MARK_NONE = 5
MARK_WAY_MAP = 1
MARK_WAY_QUICK = 2
MARK_WAY_DOUBLE_CLICK = 3
MAP_POS_NO_Y = -9999
SOS_RESCUE = 1
SOS_FIGHT = 2
SOS_ESCAPE = 3
SOS_COVER = 4
MARK_REPAIR = 6
MARK_BULLET = 7
MARK_FOOD = 8
MARK_GATHER = 9
MARK_CLASS_RES = 101
MARK_CLASS_WARNING = 102
MARK_CLASS_CNT = {MARK_CLASS_RES: 1,
   MARK_CLASS_WARNING: 1
   }
MARK_CLASS_CLEAR_TIME = {MARK_CLASS_RES: 90
   }
MARK_TYPE_CLEAR_TIME = {MARK_DANGER: 30,
   MARK_GOTO: 140,
   MARK_GATHER: 140
   }
MARK_TYPE_TO_CLASS = {MARK_NORMAL: MARK_CLASS_WARNING,
   MARK_GOTO: MARK_CLASS_WARNING,
   MARK_DANGER: MARK_CLASS_WARNING,
   MARK_RES: MARK_CLASS_RES,
   MARK_ROUTE: MARK_CLASS_WARNING,
   MARK_NONE: MARK_CLASS_WARNING,
   MARK_GATHER: MARK_CLASS_WARNING
   }
LOCATE_NORMAL = 1
LOCATE_RECOURSE = 2
LOCATE_DEAD = 3
LOCATE_DRIVE = 4
LOCATE_PARACHUTE = 5
LOCATE_OFFLINE = 6
LOCATE_MECHA = 7
LOCATE_PARACHUTE_PREPARE = 8
LOCATE_FOLLOW = 9
LOCATE_MECHA_TRANS = 10
LOCATE_SKATE = 11
LOCATE_COCKPIT = 12
SINGLE_MODE_MAP = 1
TEAM_MODE_MAP = 2
MAP_COL_BLUE = 0
MAP_COL_YELLOW = 1
MAP_COL_RED = 2
MAP_COL_GREEN = 3
MAP_COL_WHITE = 4
BUILDING_LIST = [
 4001]
MATCH_MODE_INVALID = 0
MATCH_SOLO = 1
MATCH_TWO = 2
MATCH_TEAM = 3
MATCH_DEATH = 4
CHN_SURVIVALS_TYPE_WIN_RANK = 5
PLAY_TYPE_CHICKEN = 1
PLAY_TYPE_DEATH = 2
PLAY_TYPE_HUMAN = 3
PLAY_TYPE_CHICKEN_FAST = 4
PLAY_TYPE_KING = 5
PLAY_TYPE_FFA = 7
PLAY_TYPE_GVG = 6
PLAY_TYPE_SNIPE = 8
PLAY_TYPE_CLONE = 9
PLAY_TYPE_IMPROVISE = 10
PLAY_TYPE_MECHA_DEATH = 11
PLAY_TYPE_ZOMBIEFFA = 12
PLAY_TYPE_HTDM = 13
PLAY_TYPE_ARMRACE = 14
PLAY_TYPE_RANDOMDEATH = 15
PLAY_TYPE_EXERCISE = 21
PLAY_TYPE_CONCERT = 22
PLAY_TYPE_CONTROL = 23
PLAY_TYPE_FLAG = 24
PLAY_TYPE_RECRUITMENT = 25
PLAY_TYPE_CROWN = 26
PLAY_TYPE_HUNTING = 27
PLAY_TYPE_CRYSTAL = 28
PLAY_TYPE_MUTIOCCUPY = 29
PLAY_TYPE_ADCRYSTAL = 30
PLAY_TYPE_SCAVENGE = 31
PLAY_TYPE_TRAIN = 32
PLAY_TYPE_FLAG2 = 34
PLAY_TYPE_DEATH_IMBA = 35
PLAY_TYPE_DUEL = 36
PLAY_TYPE_DEATH_AGRAVITY = 37
PLAY_TYPE_SNATCHEGG = 38
PLAY_TYPE_GOOSEBEAR = 39
PLAY_TYPE_NEWBIE = 40
PLAY_TYPE_ASSAULT = 41
PLAY_TYPE_PVE = 98
PLAY_TYPE_PVE_EDIT = 99
PLAY_TYPE_TDMS = [
 PLAY_TYPE_DEATH, PLAY_TYPE_DEATH_IMBA, PLAY_TYPE_DEATH_AGRAVITY, PLAY_TYPE_GVG, PLAY_TYPE_CLONE, PLAY_TYPE_IMPROVISE, PLAY_TYPE_MECHA_DEATH, PLAY_TYPE_HTDM, PLAY_TYPE_RANDOMDEATH, PLAY_TYPE_CONTROL, PLAY_TYPE_FLAG, PLAY_TYPE_CROWN, PLAY_TYPE_HUNTING, PLAY_TYPE_CRYSTAL, PLAY_TYPE_MUTIOCCUPY, PLAY_TYPE_ADCRYSTAL, PLAY_TYPE_SCAVENGE, PLAY_TYPE_TRAIN, PLAY_TYPE_FLAG2,
 PLAY_TYPE_SNATCHEGG, PLAY_TYPE_DUEL, PLAY_TYPE_GOOSEBEAR, PLAY_TYPE_ASSAULT]
PLAY_TYPE_WITHOUT_TEAM_SELECTION = (
 PLAY_TYPE_DEATH, PLAY_TYPE_DEATH_IMBA, PLAY_TYPE_DEATH_AGRAVITY, PLAY_TYPE_HUMAN, PLAY_TYPE_SNIPE, PLAY_TYPE_CLONE, PLAY_TYPE_MECHA_DEATH, PLAY_TYPE_ZOMBIEFFA, PLAY_TYPE_HTDM, PLAY_TYPE_RANDOMDEATH, PLAY_TYPE_CONTROL, PLAY_TYPE_FLAG, PLAY_TYPE_CROWN, PLAY_TYPE_HUNTING, PLAY_TYPE_CRYSTAL, PLAY_TYPE_MUTIOCCUPY, PLAY_TYPE_SCAVENGE, PLAY_TYPE_FLAG2, PLAY_TYPE_SNATCHEGG, PLAY_TYPE_TRAIN, PLAY_TYPE_IMPROVISE, PLAY_TYPE_GVG, PLAY_TYPE_GOOSEBEAR, PLAY_TYPE_ASSAULT)
PLAY_TYPE_WITHOUT_DEFAULT_STRING = [
 PLAY_TYPE_RECRUITMENT]
PLAYER_TYPE_ROBOT_AI_SET = set([PLAY_TYPE_CHICKEN, PLAY_TYPE_HUMAN, PLAY_TYPE_CHICKEN_FAST, PLAY_TYPE_RECRUITMENT])
PLAY_TYPE_HAS_CHOOSE_MECHA_STAGE = {PLAY_TYPE_GVG, PLAY_TYPE_MECHA_DEATH, PLAY_TYPE_ZOMBIEFFA, PLAY_TYPE_FFA, PLAY_TYPE_DUEL, PLAY_TYPE_GOOSEBEAR}
PLAY_TYPE_WITH_MECHA_SKIN_CHANGE = {
 PLAY_TYPE_CHICKEN, PLAY_TYPE_DEATH, PLAY_TYPE_DEATH_IMBA, PLAY_TYPE_DEATH_AGRAVITY, PLAY_TYPE_CHICKEN_FAST, PLAY_TYPE_CONTROL, PLAY_TYPE_FLAG, PLAY_TYPE_CROWN, PLAY_TYPE_CRYSTAL, PLAY_TYPE_RANDOMDEATH, PLAY_TYPE_EXERCISE, PLAY_TYPE_TRAIN, PLAY_TYPE_FLAG2, PLAY_TYPE_SNATCHEGG, PLAY_TYPE_ASSAULT}
PLAY_TYPE_WITH_FIRST_VICTORY = {
 PLAY_TYPE_CHICKEN, PLAY_TYPE_DEATH}
SETTLE_TYPE_GROUP = 1
SETTLE_TYPE_ALL = 2
PLAY_TYPE_2_SETTLE_TYPE = {PLAY_TYPE_CHICKEN: SETTLE_TYPE_GROUP,
   PLAY_TYPE_DEATH: SETTLE_TYPE_ALL,
   PLAY_TYPE_DEATH_IMBA: SETTLE_TYPE_ALL,
   PLAY_TYPE_HUMAN: SETTLE_TYPE_GROUP,
   PLAY_TYPE_CHICKEN_FAST: SETTLE_TYPE_GROUP,
   PLAY_TYPE_FFA: SETTLE_TYPE_ALL,
   PLAY_TYPE_GVG: SETTLE_TYPE_ALL,
   PLAY_TYPE_SNIPE: SETTLE_TYPE_ALL,
   PLAY_TYPE_CLONE: SETTLE_TYPE_ALL,
   PLAY_TYPE_IMPROVISE: SETTLE_TYPE_ALL,
   PLAY_TYPE_MECHA_DEATH: SETTLE_TYPE_ALL,
   PLAY_TYPE_ZOMBIEFFA: SETTLE_TYPE_ALL,
   PLAY_TYPE_HTDM: SETTLE_TYPE_ALL,
   PLAY_TYPE_ARMRACE: SETTLE_TYPE_ALL,
   PLAY_TYPE_RANDOMDEATH: SETTLE_TYPE_ALL,
   PLAY_TYPE_CONCERT: SETTLE_TYPE_GROUP,
   PLAY_TYPE_CONTROL: SETTLE_TYPE_ALL,
   PLAY_TYPE_FLAG: SETTLE_TYPE_ALL,
   PLAY_TYPE_CROWN: SETTLE_TYPE_ALL,
   PLAY_TYPE_HUNTING: SETTLE_TYPE_ALL,
   PLAY_TYPE_CRYSTAL: SETTLE_TYPE_ALL,
   PLAY_TYPE_MUTIOCCUPY: SETTLE_TYPE_ALL,
   PLAY_TYPE_ADCRYSTAL: SETTLE_TYPE_ALL,
   PLAY_TYPE_SCAVENGE: SETTLE_TYPE_ALL,
   PLAY_TYPE_TRAIN: SETTLE_TYPE_ALL,
   PLAY_TYPE_FLAG2: SETTLE_TYPE_ALL,
   PLAY_TYPE_DEATH_AGRAVITY: SETTLE_TYPE_ALL,
   PLAY_TYPE_SNATCHEGG: SETTLE_TYPE_ALL,
   PLAY_TYPE_DUEL: SETTLE_TYPE_ALL,
   PLAY_TYPE_GOOSEBEAR: SETTLE_TYPE_ALL,
   PLAY_TYPE_ASSAULT: SETTLE_TYPE_ALL
   }
PLAY_TYPE_SURVIVALS = {
 PLAY_TYPE_CHICKEN, PLAY_TYPE_HUMAN, PLAY_TYPE_CHICKEN_FAST, PLAY_TYPE_RECRUITMENT}
SPECTATE_PLAY_TYPES = {
 PLAY_TYPE_CHICKEN, PLAY_TYPE_DEATH, PLAY_TYPE_CHICKEN_FAST, PLAY_TYPE_HUMAN, PLAY_TYPE_GVG,
 PLAY_TYPE_FFA, PLAY_TYPE_CLONE, PLAY_TYPE_IMPROVISE, PLAY_TYPE_MECHA_DEATH, PLAY_TYPE_ZOMBIEFFA,
 PLAY_TYPE_HTDM, PLAY_TYPE_ARMRACE, PLAY_TYPE_RANDOMDEATH, PLAY_TYPE_CONTROL, PLAY_TYPE_FLAG,
 PLAY_TYPE_CROWN, PLAY_TYPE_HUNTING, PLAY_TYPE_CRYSTAL, PLAY_TYPE_MUTIOCCUPY, PLAY_TYPE_ADCRYSTAL,
 PLAY_TYPE_SCAVENGE, PLAY_TYPE_TRAIN, PLAY_TYPE_FLAG2, PLAY_TYPE_SCAVENGE, PLAY_TYPE_DEATH_IMBA,
 PLAY_TYPE_SNATCHEGG, PLAY_TYPE_DUEL, PLAY_TYPE_GOOSEBEAR, PLAY_TYPE_ASSAULT}
MATCH_CONFIRM_PLAY_TYPES = set([PLAY_TYPE_GVG])
SPECTATE_NOT_NEED_DIE_PLAY_TYPES = set([PLAY_TYPE_GVG, PLAY_TYPE_IMPROVISE])
ONLY_SPECTATE_FRIEND_PLAY_TYPES = set([PLAY_TYPE_GVG, PLAY_TYPE_IMPROVISE])
SPECTATE_FRIEND_NO_NEED_NOTIFY_FINISH_TYPES = {PLAY_TYPE_IMPROVISE}
GLOBAL_SPECTATE_NO_PARACHUTE_DELAY_PLAY_TYPES = set([PLAY_TYPE_GVG, PLAY_TYPE_IMPROVISE, PLAY_TYPE_ARMRACE, PLAY_TYPE_HUNTING, PLAY_TYPE_SCAVENGE, PLAY_TYPE_DUEL])
PLAY_TYPE_DEATH_NEED_PLAYER_LEVEL = 2
PLAY_TYPE_DEATH_LIKE = {
 PLAY_TYPE_DEATH, PLAY_TYPE_DEATH_IMBA, PLAY_TYPE_DEATH_AGRAVITY, PLAY_TYPE_SNIPE, PLAY_TYPE_CLONE, PLAY_TYPE_MECHA_DEATH, PLAY_TYPE_HTDM, PLAY_TYPE_RANDOMDEATH, PLAY_TYPE_CONTROL, PLAY_TYPE_FLAG, PLAY_TYPE_CROWN, PLAY_TYPE_HUNTING, PLAY_TYPE_CRYSTAL, PLAY_TYPE_MUTIOCCUPY, PLAY_TYPE_ADCRYSTAL, PLAY_TYPE_SCAVENGE, PLAY_TYPE_TRAIN, PLAY_TYPE_FLAG2, PLAY_TYPE_ASSAULT}
PLAY_TYPE_TDM_MODE = {
 PLAY_TYPE_DEATH, PLAY_TYPE_DEATH_IMBA, PLAY_TYPE_DEATH_AGRAVITY, PLAY_TYPE_HTDM, PLAY_TYPE_RANDOMDEATH, PLAY_TYPE_CONTROL, PLAY_TYPE_FLAG, PLAY_TYPE_CROWN, PLAY_TYPE_HUNTING, PLAY_TYPE_CRYSTAL, PLAY_TYPE_MUTIOCCUPY, PLAY_TYPE_ADCRYSTAL, PLAY_TYPE_SCAVENGE, PLAY_TYPE_TRAIN, PLAY_TYPE_FLAG2, PLAY_TYPE_ASSAULT}
PLAY_TYPE_ELASTICITY_CD = {
 PLAY_TYPE_DEATH, PLAY_TYPE_DEATH_IMBA, PLAY_TYPE_DEATH_AGRAVITY, PLAY_TYPE_SNIPE, PLAY_TYPE_CLONE, PLAY_TYPE_MECHA_DEATH, PLAY_TYPE_RANDOMDEATH, PLAY_TYPE_CONTROL, PLAY_TYPE_FLAG, PLAY_TYPE_CROWN, PLAY_TYPE_HUNTING, PLAY_TYPE_CRYSTAL, PLAY_TYPE_MUTIOCCUPY, PLAY_TYPE_ADCRYSTAL, PLAY_TYPE_SCAVENGE, PLAY_TYPE_TRAIN, PLAY_TYPE_FLAG2, PLAY_TYPE_DUEL, PLAY_TYPE_ASSAULT}
BATTLE_TYPE_COMPETITION = 1
BATTLE_TYPE_CUSTOM = 2
BATTLE_TYPE_TRANING = 3
BATTLE_TYPE_MECHA = 4
BATTLE_TYPE_EXERCISE = 5
DEFAULT_SINGLE_TID = 4
DEFAULT_INVITE_TID = 5
DEFAULT_BATTLE_TID = 6
DEFAULT_KOTH_TID = 31
DEFAULT_DEATH_TID = 42
DEFAULT_EXERCISE_TID = 200
DEFAULT_EXERCISE_PRIVATE_TID = 201
DEFAULT_GVG_SINGLE_TID = 121
DEFAULT_GVG_DUAL_TID = 122
DEFAULT_COMPETITION_TID_LIST = set([90005, 90006, 90007, 90008, 90053])
DEFAULT_NEWBIE_FOUR_GUIDE_TID = 204
DEFAULT_RECRUITMENT_TID = 301
DEFAULT_PVE_TID = 210
DEFAULT_DUEL_TID = 363
KIZUNA_AI_CONCERT_TID = 2002
NOT_NEED_READY_TIDS = set([KIZUNA_AI_CONCERT_TID])
OPEN_MATCH_MODE = [
 DEFAULT_BATTLE_TID, DEFAULT_SINGLE_TID]
AGAIN_GAME_TYPE = [
 DEFAULT_SINGLE_TID, DEFAULT_INVITE_TID, DEFAULT_BATTLE_TID,
 DEFAULT_DEATH_TID, DEFAULT_GVG_SINGLE_TID, DEFAULT_GVG_DUAL_TID]
BEGINNER_BATTLE_TYPE_BEGIN = 10000
WARM_BATTLE_TYPE_BEGIN = 20000
NEWBIE_BATTLE_TYPE_BEGIN = 30000
NEWBIE_BATTLE_TYPE_END = 39999
FOLLOW_JUMP_ROBOT = 1
AUTO_JUMP_ROBOT = 2
AUTO_AIM_YAW = 1
AUTO_AIM_PITCH = 2
AUTO_AIM_DISTANCE = 3
AIM_MODE_NORMAL = 0
AIM_MODE_AT = 1
POSITION_GROUND = 1
POSITION_WALL = 2
POSITION_TYPES = frozenset([POSITION_GROUND, POSITION_WALL])
SHOOT_MASK_AT_AIM = 1
SHOOT_MASK_WITH_RAY = 2
KEY_WATER_POS = 1
KEY_AIRWALL_POS = 2
KEY_AIRWALL_NORMAL = 3
RESCUE_TIME = 5
HUMAN_RESCUE_DIS = NEOX_UNIT_SCALE * 2
MECHA_RESCUE_DIS = NEOX_UNIT_SCALE * 4
RESCUE_TIME_KEY = 'rescue_time_factor'
RESCUE_RECRUIT_ALIVE_NUM = 5
RESCUE_CANCEL_NONE = 0
RESCUE_CANCEL_LOSE = 1
RESCUE_CANCEL_REFUSE = 2
RESCUE_CANCEL_GIVEUP = 3
LG_MASK_DMG_COLLECT_CD = 1
BATTLE_SOUND_STATE_LOW = 2
BATTLE_SOUND_STATE_MEDIUM = 5
BATTLE_SOUND_STATE_HARD = 7
MSG_UP_TIP = 1
MSG_MED_TIP = 2
MSG_DWN_TIP = 3
MAIN_DWN_TIP = 4
MAIN_NODE_COMMON_INFO = 2
MAIN_NODE_RANK_AWARD = 3
MAIN_NODE_POINT = 4
MAIN_NODE_SPECIAL_POINT = 5
MAIN_NODE_KILL_ACHIEVEMENT = 6
UP_NODE_DOUBLE_POINT = 1
UP_NODE_POISON_CIRCLE = 2
UP_NODE_PARADROP = 3
UP_NODE_ENEMYSCAN = 4
UP_NODE_PLAYER_NUMBER = 5
UP_NODE_TURN_WARN = 6
UP_NODE_TURN_COUNTDOWN = 7
UP_NODE_AREA_INFO = 8
UP_NODE_ANCHOR_VOICE = 9
UP_NODE_CANDY_SHOP = 10
UP_NODE_PARADROP_BALL = 11
UP_NODE_HUMAN_TIP = 13
UP_NODE_ARMRACE_UZI = 14
UP_NODE_CONCERT_ANCHOR = 15
UP_NODE_COMMON_RIKO_TIPS = 16
UP_NODE_GOOSEBEAR_RIKO_TIPS = 17
MED_NODE_KILL_INFO = 1
MED_NODE_KILL_MECHA_INFO = 2
MED_NODE_DEFEATED_INFO = 3
MED_NODE_TURN_COUNTDOWN = 4
MED_NODE_COMMON_INFO = 5
MED_NODE_RECRUIT_COMMON_INFO = 6
MED_R_NODE_COMMON_INFO = 1
MAIN_ENHANCE_INFO = 1
MAIN_FIGHT_CAPACITY_UPGRADE = 2
MED_KILL_INFO = 3
MAIN_KILL_KING = 4
MED_R_EQUIPMENT_INFO = 5
MED_R_MODUL_INFO = 6
MAIN_RANK_AWAED = 7
MAIN_KILL_AWARD = 8
MAIN_END_KILL_KING = 9
MAIN_NODE_PLAYER_LEVEL_UP = 10
MED_R_MECHA_RESET_INFO = 11
TDM_BATTLE_LAST_COUNT_DOWN_TIME = 10
MAIN_ACE_TIME = 11
MAIN_MECHA_RECALL_INFO = 12
MAIN_KOTH_B_SIDE_TEN_POINTS = 13
MAIN_KOTH_R_SIDE_TEN_POINTS = 14
MAIN_KOTH_O_SIDE_TEN_POINTS = 15
MAIN_KOTH_LEFT_TIME = 16
MAIN_KOTH_OCCUPY = 17
MAIN_KOTH_OCCUPY_POINT = 18
MAIN_KOTH_DAMAGE_POINT = 19
MAIN_KOTH_RESCUE_POINT = 20
MAIN_KOTH_KILL_POINT = 21
MAIN_KOTH_REVENGE_POINT = 22
MAIN_KOTH_END_COMBO_KILL_POINT = 23
MAIN_KOTH_END_COMBO_KILL_POINT_ALL = 24
MAIN_KOTH_COMBO_KILL_POINT = 25
MAIN_KOTH_COMBO_KILL_POINT_ALL = 26
MAIN_KOTH_KILL_MECHA_POINT = 27
TDM_BLUE_FIRST_ARRIVE_40_POINT = 28
TDM_RED_FIRST_ARRIVE_40_POINT = 29
TDM_THREE_TIMES_POINT = 30
TDM_ABOUT_TO_GET_MODULE_UPGRADE = 31
SECOND_ACE_TIME_NEW = 32
TDM_THREE_TIMES_POINT_NEW = 33
TDM_KNOCKOUT_LAST_POINT_MAX_INTERVAL = 39
TDM_FIRST_POINTS_TIPS_THRE = 40
COMMON_AIM_POISON_TIPS = 41
TDM_OTHER_KILL_KING = 42
TDM_KILL_TIPS = 43
TDM_ACHIEVE_TIPS = 44
TDM_BLUE_DOOR_DESTROYED = 45
TDM_BLUE_DOOR_RECOVER = 46
TDM_RED_DOOR_DESTROYED = 47
TDM_RED_DOOR_RECOVER = 48
MAIN_WILL_ACE_TIME = 49
TDM_COME_HOME = 50
FFA_BLOODTHIRST_BUFF = 51
BATTLE_LEFT_TIME = 52
FFA_COUNT_POINT = 53
GVG_KILL_TIPS = 54
GVG_MULTI_KILL_TIPS = 55
GRANBELM_PORTAL_REFRESH_TIPS = 56
ONLY_JOIN_ONE_SHARE_MECHA_TIPS = 57
SECOND_ACE_TIME = 58
ZOMBIEFFA_ACE_TIME = 59
ZOMBIEFFA_MECHA_EXTINCTION = 60
MED_R_EQUIPMENT_INFO_WEAK = 61
MED_R_MODUL_INFO_WEAK = 62
MED_R_EQUIPMENT_INFO_OLD = 63
TEAMMATE_LOCATE_UI = 64
MAIN_NODE_RESCUE_FAILED_REASON = 65
ARMRACE_LEFT_TIME = 66
ARMRACE_ACE_TIME = 67
ARMRACE_UZI_TIP = 68
ARMRACE_LEVEL_UP = 69
ARMRACE_LEVEL_DOWN = 70
ARMRACE_BLOODTHIRST_BUFF = 71
RANDOM_DEATH_GET_ITEM_TIP = 72
RANDOM_DEATH_LOST_ITEM_TIP = 73
RANDOM_DEATH_GET_WEAPON_TIP = 74
MAIN_MED_GET_ITEM_INFO = 75
CONCERT_SINGLE_BEAT = 76
CONCERT_MULTIPLE_BEAT = 77
CONCERT_LONG_BEAT = 78
FALL_RETURN_LEFT_TIMES = 79
BOUNTY_CENTER_TIPS = 80
FLAG_BATTLE_ACE_TIME = 81
FLAG_BATTLE_ACE_BUFF_TIP = 82
FLAG_BATTLE_FLAG_BASE_BLUE_LOCATE_UI = 83
FLAG_BATTLE_FLAG_BASE_RED_LOCATE_UI = 84
FLAG_BATTLE_FLAG_LOCATE_UI = 85
FLAG_BATTLE_FLAG_PICKED_SELF_TEAM = 86
FLAG_BATTLE_FLAG_PICKED_OTHER_TEAM = 87
FLAG_BATTLE_FLAG_RECOVER_TO_ORIGIN = 88
FLAG_BATTLE_FLAG_DROPPED_SELF_TEAM = 89
FLAG_BATTLE_FLAG_DROPPED_OTHER_TEAM = 90
FLAG_BATTLE_FLAG_PLANTED_SELF_TEAM = 91
FLAG_BATTLE_FLAG_PLANTED_OTHER_TEAM = 92
RECRUITMENT_BATTLE_ACCEPT = 93
RECRUITMENT_BATTLE_LEAVE = 94
RECRUITMENT_BATTLE_REJECT = 95
COMMON_OTHER_FIRST_BLOOD = 100
CROWN_BATTLE_CROWN_SELF_LOCATE_UI = 101
CROWN_BATTLE_CROWN_OTHER_LOCATE_UI = 102
CROWN_BATTLE_CROWN_TEAMMATE_LOCATE_UI = 103
CROWN_BATTLE_CROWN_TEAM_BORN_TIPS = 104
CROWN_BATTLE_CROWN_TEAM_DIE_TIPS = 105
CROWN_BATTLE_CROWN_OTHER_BORN_TIPS = 106
CROWN_BATTLE_CROWN_OTHER_DIE_TIPS = 107
COMMON_SURVIVAL_SS_KILL_MESSAGE = 108
COMMON_SURVIVAL_SS_KILL_MESSAGE_PC = 109
COMMON_SURVIVAL_KILL_MVP_MESSAGE = 110
COMMON_SURVIVAL_KILL_MVP_MESSAGE_PC = 111
FIRE_BATTLE_IMMUNE_TIPS = 112
FIRE_BATTLE_HAVE_AWARD_TIPS = 113
FIRE_BATTLE_FIRE_STATE_TIPS = 114
CRYSTAL_BATTLE_CRYSTAL_MARK_BLUE = 115
CRYSTAL_BATTLE_CRYSTAL_MARK_RED = 116
MAIN_KILL_MVP = 117
MAIN_SOUND_VISIBLE_INFO = 118
MUTIOCCUPY_USE_ITEM = 119
MUTIOCCUPY_BECOME_KING = 120
MUTIOCCUPY_SELF_OCCUPY_A = 121
MUTIOCCUPY_SELF_OCCUPY_B = 122
MUTIOCCUPY_SELF_OCCUPY_C = 123
MUTIOCCUPY_ENEMY_OCCUPY_A = 124
MUTIOCCUPY_ENEMY_OCCUPY_B = 125
MUTIOCCUPY_ENEMY_OCCUPY_C = 126
ADCRYSTAL_TIP_ATK_START = 127
ADCRYSTAL_TIP_DEF_START = 128
ADCRYSTAL_TIP_SEC_STAGE_ATK = 129
ADCRYSTAL_TIP_SEC_STAGE_DEF = 130
ADCRYSTAL_TIP_POS_CHANGE_ATK = 131
ADCRYSTAL_TIP_POS_CHANGE_DEF = 132
ADCRYSTAL_TIP_LOW_HP_BUFF_ATK = 133
ADCRYSTAL_TIP_LOW_HP_BUFF_DEF = 134
ADCRYSTAL_TIP_LOW_DIE_CNT_BUFF_ATK = 135
ADCRYSTAL_TIP_LOW_DIE_CNT_BUFF_DEF = 136
ADCRYSTAL_TIP_PRE_CRYSTAL_DESTROY_ATK = 137
ADCRYSTAL_TIP_PRE_CRYSTAL_DESTROY_DEF = 138
TDM_PRE_NOTIFY_ROGUE_GIFT = 139
SCAVENGE_TIP_GAME_START = 140
SCAVENGE_TIP_WEAPON_PICKED_BY_GROUPMATE = 141
SCAVENGE_TIP_WEAPON_PICKED_BY_ENEMY = 142
TDM_CHOOSE_ROGUE_NOT_IN_BASE = 143
CONCERT_PLAYER_NORMAL_ROUND_REWARD = 144
CONCERT_PLAYER_FINAL_ROUND_REWARD = 145
CONCERT_RECEIVED_REWARD = 146
DEATH_DOOR_DISAPPEAR = 147
TRAIN_USE_SKILL_PUSH = 148
TRAIN_USE_SKILL_STOP = 149
TRAIN_TIP_ATK_START = 150
TRAIN_TIP_DEF_START = 151
TRAIN_USE_NORMAL_SKILL = 152
TRAIN_ARRIVE_STATION = 153
TRAIN_CAN_USE_SKILL = 154
TRAIN_ARRIVE_END = 155
TRAIN_USE_ALL_TIME = 156
PVE_LEVEL_PORTAL = 10001
MAGIC_MONSTER_TIP = 157
MAGIC_GET_ITEM = 158
MAGIC_USE_MAGIC = 159
MAGIC_ACHIEVE = 160
FLAG2_BATTLE_ACE_TIME = 161
FLAG2_BATTLE_ACE_BUFF_TIP = 162
FLAG2_BATTLE_FLAG_BASE_BLUE_LOCATE_UI = 163
FLAG2_BATTLE_FLAG_BASE_RED_LOCATE_UI = 164
FLAG2_BATTLE_FLAG_PICKED_SELF_TEAM = 166
FLAG2_BATTLE_FLAG_PICKED_OTHER_TEAM = 167
FLAG2_BATTLE_FLAG_RECOVER_TO_ORIGIN = 168
FLAG2_BATTLE_FLAG_DROPPED_SELF_TEAM = 169
FLAG2_BATTLE_FLAG_DROPPED_OTHER_TEAM = 170
FLAG2_BATTLE_FLAG_PLANTED_SELF_TEAM = 171
FLAG2_BATTLE_FLAG_PLANTED_OTHER_TEAM = 172
FLAG2_BATTLE_START_TIP = 173
SNATCHEGG_ROUND_TIP = 174
OUR_GROUP_PICK_EGG_TIP = 175
OTHER_GROUP_PICK_EGG_TIP = 176
OUR_GROUP_DROP_EGG_TIP = 177
OUR_GROUP_DROP_LAST_EGG_TIP = 178
OTHER_GROUP_DROP_EGG_TIP = 179
SNATCHEGG_BATTLE_EGG_LOCATE_UI = 180
SNATCHEGG_CREATE_EGG_TIP = 181
DUEL_ROUND_TIP = 182
DUEL_ROUND_TIP2 = 183
GOOSEBEAR_MAP_COLLAPSE_TIP = 184
GOOSEBEAR_OVER_GRAVITY_FIRST_TIP = 185
GOOSEBEAR_OVER_GRAVITY_REFRESH_TIP = 186
GOOSEBEAR_GAME_START_TIP = 187
GOOSEBEAR_PROP_FIRST_TIP = 188
GOOSEBEAR_PROP_REFRESH_TIP = 189
GOOSEBEAR_LESS_GRAVITY_FIRST_TIP = 190
GOOSEBEAR_LESS_GRAVITY_REFRESH_TIP = 191
ASSAULT_TEAMMATE_PLAYER_TIP = 203
ASSAULT_ENEMY_PLAYER_TIP = 204
ASSAULT_GAME_START_TIP = 205
NBOMB_DEVICE_EXPLOSION = 192
NBOMB_DEVICE_PLACE_ERROR = 193
NBOMB_DEVICE_PLACE_SUCCEED = 194
NBOMB_DEVICE_REMOVE = 195
NBOMB_DEVICE_BE_HIT = 196
NBOMB_DEVICE_STATUS_ERROR = 197
NBOMB_CORE_APPEAR = 198
NBOMB_CORE_TRANSFER = 199
NBOMB_CORE_COLLECT_COMPLETE = 200
NBOMB_CORE_DROP = 201
NBOMB_CORE_PICKUP = 202
KOTH_BATTLE_KING_POINT_PARTICIPATE_REWARD_TIME_INTERVAL = 10
KOTH_BATTLE_REVIVE_METHOD_BY_ALIVE_GROUPMATE = 1
KOTH_BATTLE_REVIVE_METHOD_BY_SELF_TAKEN_AREA = 2
KOTH_BATTLE_REVIVE_METHOD_BY_SELF_BASE_AREA = 3
KOTH_BATTLE_TIP_ROUND_FINISH_TIME_WARN_BEFORE_TIME = 30
KOTH_BATTLE_TIP_ROUND_FINISH_TIME_COUNT_DOWN_TIME = 5
KOTH_BATTLE_TIP_ROUND_FINISH_TIME_LAST_ROUND_COUNT_DOWN_TIME = 10
KOTH_BATTLE_TIP_TYPE_ROUND_WARN_TIME = 1
KOTH_BATTLE_TIP_TYPE_ROUND_COUNTDOWN_TIME = 2
KOTH_BATTLE_TIP_TYPE_ROUND_SPECIAL_REWARD_RATE = 3
KOTH_BATTLE_TIP_TYPE_ROUND_BEGIN = 4
KOTH_BATTLE_MANUAL_REVIVE_WAIT_TIME = 10
KOTH_BATTLE_REVIVE_GROUPMATE_BEEN_HIT_NEED_INTERVAL = 5
KOTH_BATTLE_REVIVE_GROUPMATE_RADIUS = 1.5
BEACON_NEUTRAL = 1
BEACON_OCCUPIED = 2
BEACON_OCCUPY_ON = 1
BEACON_OCCUPY_STOP = 2
BEACON_OCCUPY_SUCC = 3
CONN_STATE_ONLINE = 0
CONN_STATE_OFFLINE = 1
CONN_STATE_EXIT = 2
BATTLE_SETTLE_REASON_NORMAL = 1
BATTLE_SETTLE_REASON_OTHER_GROUP_QUIT = 2
BATTLE_SETTLE_REASON_SERVER_CLOSING = 3
BATTLE_SETTLE_REASON_SURRENDER = 4
MECHA_DAMAGED_HP_RATE = 25
AFK_PUNISHMENT = [
 [
  1, 60],
 [
  2, 300],
 [
  999999999, 600]]
TRY_TELE_POS_REASON_DEFAULT = 1
TRY_TELE_POS_REASON_HMAP = 2
TRY_TELE_POS_REASON_NORMAL = 100
TRY_TELE_POS_REASON_BATTLE_AREA = 101
RB_POS_REASON_WAIT_ROLL = 51
RB_POS_REASON_ROLLING = 52
RB_POS_REASON_VERIFY = 53
RB_POS_REASON_JITTER = 54
RB_POS_REASON_EJECT_ERROR = 55
RB_POS_REASON_HEIGHT = 56
RB_POS_REASON_OUTBLOCK = 57
RB_POS_REASON_OUTBLOCK_YU = 58
RB_POS_REASON_SUICIDE = 59
RB_POS_REASON_NEW_ROUND = 60
CURE_TYPE_NORMAL = 0
CURE_TYPE_ATTACK = 1
CURE_TYPE_BOND_GIFT = 2
CURE_TYPE_REAL_VALUE = 3
NO_COMMON_FACTOR_CURE_LIST = [
 CURE_TYPE_BOND_GIFT, CURE_TYPE_REAL_VALUE]
GRANBELM_RUNE_DROP_RATE = 0.5
GRANBELM_MAX_RUNE_COUNT = 200
GRANBELM_RUNE_INCREASE_PERIOD_COMMON = 60
GRANBELM_RUNE_INCREASE_PERIOD_SPECIAL = 3
GRANBELM_RUNE_INCREASE_RATE_COMMON = 3
GRANBELM_RUNE_INCREASE_RATE_SPECIAL = 1
GRANBELM_RUNE_MIN_CHECK_INTERVAL = 1
GRANBELM_PORTAL_START_POISON_LV = 1
GRANBELM_PORTAL_END_POISON_LV = 5
GRANBELM_RUNE_REGION_START_POISON_LV = 1
GRANBELM_RUNE_REGION_END_POISON_LV = 5
GRANBELM_PORTAL_PREPARE_TELEPORT = 0
GRANBELM_PORTAL_FIRST_TELEPORT = 1
GRANBELM_PORTAL_SECOND_TELEPORT = 2
GRANBELM_PORTAL_TYPE_POISON = 1
GRANBELM_PORTAL_TYPE_PARADROP = 2
PORTAL_TYPE_DEATH = 1
PORTAL_TYPE_PVE = 2
PORTAL_TYPE_PVE_BOSS = 3
GRANBELM_PORTAL_TELE_ROLE_HUMAN = 'human'
GRANBELM_PORTAL_TELE_ROLE_MECHA = 'mecha'
GRANBELM_PORTAL_MIN_DISTANCE_CHECK = 5.0 * NEOX_UNIT_SCALE
GRANBELM_TIME_BEFORE_PORTAL_REFRESH = 3
GRANBELM_PORTAL_MAP_MARK_ID_POISON = 2015
GRANBELM_PORTAL_MAP_MARK_ID_PARADROP = 2016
GRANBELM_TELE_CALLBACK_STATE_FAIL = -1
GRANBELM_PORTAL_OVERLAY_DIST = 3 * NEOX_UNIT_SCALE
GRANBELM_TELEPORT_CD = 10
GRANBELM_PORTAL_MAX_DURATION = 210
GRANBELM_TELEPORT_Y_ADJUST = 2480
GRANBELM_TELEPORT_Y_LIFT_UP = 13
TRANSFER_PORTAL_MIN_DISTANCE_CHECK = 5.0 * NEOX_UNIT_SCALE
TRANSFER_PORTAL_CD = 10
TRANSFER_OFFSET_RANGE = 20
GRAVITY_REGION_START_POISON_LV = 1
GRAVITY_REGION_END_POISON_LV = 6
FIRE_REGION_END_POISON_LV = 6
MOVE_X_LIMIT = (-28000, 28000)
MOVE_Z_LIMIT = (-28000, 28000)
MOVE_Y_LIMIT = (-20000, 20000)
MOVE_LENGTH_LIMIT = 30000 * 1.7320508075688772
MAX_BIG_POS_ERR_UPLOAD_CNT = 3
AFK_CHECK_OPERATION_TYPE_POS_CHANGED = 'pos_changed'
AFK_CHECK_OPERATION_TYPE_DO_FIGHT = 'do_fight'
AFK_CHECK_OPERATION_TYPE_YAW_CHANGED = 'yaw_changed'
ROUND_TYPE_PURE_HUMAN = 1
ROUND_TYPE_MECHA = 2
IMPROVISE_DEFEATED_SPECTATE_DELAY = 5
CRIT_MULTIPLIER = 0.2
BATTLE_FIRST_MECHA_RECALL_CD_REDUCE_MIN_SCORE = 600
BATTLE_FIRST_MECHA_RECALL_CD_REDUCE_RANGE = (10, 25)
BATTLE_SIGNAL_WARNING_LEFT_TIME_MIN = 50
BATTLE_SIGNAL_WARNING_LEFT_VALUE_MIN = 50
BATTLE_SIGNAL_SHOW_UP_TIP_MIN_PERCENT = 75
PLAY_TYPE_CHIKEN_SIGNAL_PLAY_TIPS_ID = 18
PLAY_TYPE_MEOW_PLAY_TIPS_ID = 22
PLAY_TYPE_MEOW_PLAY_TIPS_ID_STEAM = 30
MECHA_KILL_MECHA = 'mecha_mecha'
MECHA_KILL_HUMAN = 'mecha_human'
HUMAN_KILL_MECHA = 'human_mecha'
HUMAN_KILL_HUMAN = 'human_human'
HIGHLIGHT_MAX_KILL = 6
SORT_KILL_TYPES = [
 MECHA_KILL_MECHA, HUMAN_KILL_MECHA, MECHA_KILL_HUMAN, HUMAN_KILL_HUMAN]
EMULATOR_MATCH_TIME_RATE = 1.2
EMULATOR_DAN_RATE = 0.9
ANTICHEAT_BATTLE_REWARD_RATE = 0.15
ANTICHEAT_MATCH_TIME_RATE = 1.2
BATTLE_MATCH_TYPE_NORMAL = 1
BATTLE_MATCH_TYPE_AFK = 2
BATTLE_MATCH_TYPE_EMULATOR = 3
BATTLE_MATCH_TYPE_ROOM = 4
BATTLE_MATCH_TYPE_COMPETITION = 5
BATTLE_MATCH_TYPE_CHEATER = 6
SEASON_POINT_PRO_REASON_SGU = 'spring_gang_up_pro'
SEASON_POINT_PRO_REASON_CI = 'cost_pro_item'
SEASON_POINT_PRO_REASON_FGU = 'fairyland_gang_up_pro'
SETTLE_OB_SYNC_SOUL_KEYS = {
 'role_id', 'uid', 'char_name', 'head_frame', 'head_photo'}
SETTLE_OB_SYNC_STAT_KEYS = {
 statistics_const.KILL_HUMAN, statistics_const.KILL_MECHA,
 statistics_const.DAMAGE_TO_HUMAN, statistics_const.DAMAGE_TO_MECHA,
 statistics_const.MECHA_TIME, statistics_const.CALL_MECHA_TIMES,
 statistics_const.SAVE_CNT, statistics_const.HUMAN_STATE_TIME,
 statistics_const.ASSIST_MECHA, statistics_const.ASSIST_HUAMN,
 statistics_const.HUMAN_HURT, statistics_const.MECHA_HURT}
ILLEGAL_TEAM_TIME = 1200
CLOSE_DELAY_TIME = 120
DEFAULT_EJECT_SPEED = 60 * NEOX_UNIT_SCALE
DEFAULT_EJECT_ACC = 10
DEFAULT_EJECT_TIME = 0.6
DEFAULT_EJECT_GRAVITY = 70 * NEOX_UNIT_SCALE
BOOM_DMG_REDUCE_IN_VEHICLE = 0.2
MAX_BOOM_DMG_REDUCE = 0.5
CARRY_SHIELD_DAMAGE_RATIO_RANGE = (
 (0, 0), (math.cos(math.pi / 3), 0.5), (1, 1))
CONCERT_WAIT_STAGE = 0
CONCERT_SING_STAGE = 10
CONCERT_STOP_SING_STAGE = 11
CONCERT_STOP_RELAX_STAGE = 20
CONCERT_STOP_SING_PRE_SETTLE = 21
CONCERT_CONFIRM_STAGE = 1
CONCERT_FIGHT_STAGE = 2
CONCERT_STOP_DUEL_STAGE = 3
COMMON_FACTION_ID = 18
DUEL_FACTION_IDS = [99, 100]
PVE_MONSTER_FACTION_ID = 999
CHART_EVENT_LAND = 1
CHART_EVENT_KILL_HUMAN = 2
CHART_EVENT_KILL_MECHA = 3
CHART_EVENT_KILL_GROUP = 4
CHART_EVENT_PRRADROP = 5
CHART_EVENT_MOVE = 6
CHART_EVENT_DIE = 7
CHART_EVENT_BE_RESCUED = 8
CHART_EVENT_RESCUE = 9
CHART_EVENT_RECRUIT = 10
CHART_EVENT_WIN = 11
CHART_EVENT_BE_RECRUITED = 12
CHART_EVENT_GULAG_REVIVE = 13
DEATH_POINT_RECORD_DURATION = 30
KD_FALL_STAGE_NONE = 0
KD_FALL_STAGE_WARN = 1
KD_FALL_STAGE_UNDERGROUND = 2
KD_FALL_STAGE_SCN_SFX = 3
KD_FALL_STAGE_FORCE_CLOSE = 4
KD_TRAIN_START_PRE_SPEED_UP = 'pre_speed_up'
KD_TRAIN_START_SPEED_UP = 'start'
KD_TRAIN_START_SPEED_REDUCE = 'end'
KD_TRAIN_START_IDLE = 'idle'
KD_TRAIN_START_SPEED_MAINTAIN = 'run'
BP_MODE_PLAY = 1
BP_MODE_MAP = 2
CROWN_OTHER_FACTION = 1
CROWN_TEAM_FACTION = 2
CROWN_SELF_FACTION = 3
WEEK_COMPETITION_MEMBERS_KEY = 'week_competition_members'
PRE_SCORE_DIFF_MINUTES = 5
PRE_SCORE_DIFF = -2
LATER_SCORE_DIFF = -2
CRYSTAL_LENGTH = 37
CRYSTAL_WIDTH = 31
CRYSTAL_HEIGHT = 54
CRYSTAL_COVER_H = 77
CRYSTAL_COVER_COL_W = 2
CRYSTAL_COVER_R = 47
CRYSTAL_COVER_OPEN_SECTOR_RADIAN = 135 * math.pi / 180
RADIAN_A = (math.pi - CRYSTAL_COVER_OPEN_SECTOR_RADIAN) * 0.5
RADIAN_B = math.pi * 0.5 - RADIAN_A
RADIAN_C = (math.pi - RADIAN_B) * 0.5
RADIAN_D = RADIAN_B * 0.5
SIDE_COL_LEN = CRYSTAL_COVER_R * math.sin(RADIAN_A) * 2
BOTTOM_COL_LEN = CRYSTAL_COVER_R * (1 - math.sin(RADIAN_A)) / math.cos(RADIAN_C)
SIDE_COL_OFFSET_0 = math3d.vector(-1, 0, 0) * math.cos(RADIAN_A) * CRYSTAL_COVER_R
SIDE_COL_OFFSET_1 = math3d.vector(1, 0, 0) * math.cos(RADIAN_A) * CRYSTAL_COVER_R
BOTTON_COL_OFFSET_0 = math3d.vector(math.sin(RADIAN_D), 0, math.cos(RADIAN_D)) * math.sin(RADIAN_C) * CRYSTAL_COVER_R
BOTTON_COL_OFFSET_1 = math3d.vector(-math.sin(RADIAN_D), 0, math.cos(RADIAN_D)) * math.sin(RADIAN_C) * CRYSTAL_COVER_R
SIDE_COL_size_0 = math3d.vector(CRYSTAL_COVER_COL_W, CRYSTAL_COVER_H, SIDE_COL_LEN) * 0.5
SIDE_COL_size_1 = math3d.vector(CRYSTAL_COVER_COL_W, CRYSTAL_COVER_H, SIDE_COL_LEN) * 0.5
BOTTOM_COL_size_0 = math3d.vector(BOTTOM_COL_LEN, CRYSTAL_COVER_H, CRYSTAL_COVER_COL_W) * 0.5
BOTTOM_COL_size_1 = math3d.vector(BOTTOM_COL_LEN, CRYSTAL_COVER_H, CRYSTAL_COVER_COL_W) * 0.5
CRYSTAL_COVER_EXTRA_COL_OFFSET_LIST = (
 SIDE_COL_OFFSET_0, SIDE_COL_OFFSET_1, BOTTON_COL_OFFSET_0, BOTTON_COL_OFFSET_1)
CRYSTAL_COVER_EXTRA_COL_SIZE_LIST = (SIDE_COL_size_0, SIDE_COL_size_1, BOTTOM_COL_size_0, BOTTOM_COL_size_1)
CRYSTAL_COVER_EXTRA_COL_YAW_LIST = (None, None, RADIAN_D, -RADIAN_D)
CRYSTAL_MARK_RED = 2045
CRYSTAL_MARK_BLUE = 2046
CRYSTAL_LORE_DAMAGE = 3600.0
ADCRYSTAL_LORE_DAMAGE_DIFF = 1000
ADCRYSTAL_LORE_TIME_DIFF = 5
CRYSTAL_ROUND_PREPARE = 0
CRYSTAL_ROUND_ONE = 1
CRYSTAL_ROUND_DELAY_INTERVAL = 2
CRYSTAL_ROUND_INTERVAL = 3
CRYSTAL_ROUND_TWO = 4
CRYSTAL_ROUND_END = 5
ROUND_STATUS_INIT = 0
ROUND_STATUS_PREPARE = 1
ROUND_STATUS_PLAYING = 2
ROUND_STATUS_INTERVAL = 3
ROUND_STATUS_FINISH = 4
if G_IS_SERVER:
    from mobile.distserver.game import GameServerRepo
    WEEK_COMPETITION_RET = lambda comp_id: 'WeekCompResult:%s:%s' % (GameServerRepo.hostnum, comp_id)
SUMMER_COMP_WHITE_UIDS = [
 1500948722,
 1513462839,
 1501693414,
 1502298722,
 1509737069,
 1501736613,
 1510362187,
 1511569200,
 1503847011,
 1519923130,
 1519924161,
 1519923550,
 1519923557,
 1519923958,
 1519923926,
 1519924070,
 1519924127,
 1519924221,
 1519924260,
 1520088174,
 1520088273,
 1520088427,
 1520088489,
 1507042189,
 1501043838]
OCCUPY_POINT_STATE_IDLE = 0
OCCUPY_POINT_STATE_INC = 1
OCCUPY_POINT_STATE_DEC = 2
OCCUPY_POINT_STATE_SNATCH = 3
STATE_OCCUPY_EMPTY = 0
STATE_OCCUPY_SELF = 1
STATE_OCCUPY_ENEMY = 2
STATE_OCCUPY_SNATCH = 3
SKILL_EFFECT_SOUL = 1
SKILL_EFFECT_MECHA = 2
SKILL_EFFECT_MONSTER = 4
CTRL_TRAIN_STATE_IDLE = 1
CTRL_TRAIN_STATE_NORMAL_FORWARD = 2
CTRL_TRAIN_STATE_NORMAL_BACKWARD = 3
CTRL_TRAIN_STATE_FORCE_FORWARD = 4
CTRL_TRAIN_STATE_FORCE_STOP = 5
PLAYER_STATE_AWAY_TRAIN_RANGE = 1
PLAYER_STATE_ENTER_TRAIN_RANGE = 2
CTRL_TRAIN_GROUP_ATTACK = '1'
CTRL_TRAIN_GROUP_DEFENCE = '2'
CTRL_TRAIN_STATE_HEAL = 6
CTRL_TRAIN_STATE_DAMAGE = 7
MAGIC_MAX_HUNTER_COIN_COUNT = 10
SURRENDER_VOTE_DURATION = 20
MAGIC_MAX_HUNTER_COIN_COUNT = 10
MONEY_BOX_STATUS_UNACTIVATED = 1
MONEY_BOX_STATUS_ACTIVATING = 2
MONEY_BOX_STATUS_DESTROYED = 3
MONEY_BOX_STATUS_ACTIVATED = 4
BTN_DROP_EGG = 1
DEAD_DROP_EGG = 2
THROW_EGG = 3
GOLDEN_EGG_WP = 10601
EGG_NOT_PICKED = 1
EGG_PICKED = 2
EGG_DROPPED = 3
EGG_VRF_LENGTH = 70
MAX_REAL_DAMAGE_INTERVAL = 30.0
EXECUTE_HIT_HINT_NUM = 9999
ST_IDLE = 0
ST_IN_QUEUE = 1
ST_IN_GAME = 2
ST_GULAG_PARACHUTE = 3
ST_REVIVE_PENDING = 4
CANCEL_REASON_NONE = 0
CANCEL_REASON_TIMEOUT = 1
CANCEL_REASON_SURVIVAL_NUM = 2
REVIVE_NONE = 'revive_none'
REVIVE_WAIT = 'revive_wait'
TP_REASON_GULAG_REVIVE = 'gulag_revive'
TP_REASON_GULAG_ENTER_GAME = 'gulag_enter_game'
NBOMB_TIP_NBOMB_START = 'nbomb_start'
NBOMB_TIP_NBOMB_EXPLODE = 'nbomb_explode'
NBOMB_TIP_NBOMB_DESTROY = 'nbomb_destroy'
NBOMB_TIP_NBOMB_ILLEGAL_AREA = 'nbomb_illegal_area'
NBOMB_TIP_CORE_SPAWNED = 'core_spawned'
NBOMB_TIP_COLLECT_ALL_CORES = 'collect_all_cores'
NBOMB_TIP_PICK_CORE = 'pick_core'
NBOMB_TIP_LOST_CORE = 'lost_core'
NBOMB_TIP_FIRST_HIT = 'first_hit'
NBOMB_TIP_BLEED = 'bleed'
NBOMB_TIP_CORE_MOVE = 'core_move'
FACTION_ROOM_BATTLE_TYPE = 90102