"""
Combine all .py files under script_patch and script_week into a single text file.
The output is a plain concatenation with clear separators so code origins stay trackable.
Note: the resulting file can be extremely large; ensure you have disk space.
"""

import argparse
import io
import sys
from pathlib import Path
from typing import Iterable, List


def find_python_files(dirs: Iterable[Path]) -> List[Path]:
    files: List[Path] = []
    for base in dirs:
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.py")):
            # Skip hidden paths or caches if any
            if any(part.startswith("__pycache__") for part in path.parts):
                continue
            files.append(path)
    return files


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        # Fallback to latin-1 to avoid crashes on unexpected encodings
        return path.read_text(encoding="latin-1")


def combine(files: List[Path], output: Path) -> None:
    with io.open(output, "w", encoding="utf-8") as fh:
        fh.write("# Combined scripts generated by combine_scripts.py\n")
        fh.write("# Source folders: script_patch, script_week\n\n")
        for idx, path in enumerate(files, 1):
            fh.write("# BEGIN FILE {} -- {}\n".format(idx, path.as_posix()))
            fh.write(read_text(path))
            fh.write("\n# END FILE {} -- {}\n\n".format(idx, path.as_posix()))
    print("Wrote {} files into {}".format(len(files), output))


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description="Concatenate all scripts into one file.")
    parser.add_argument(
        "--output",
        default="combined_scripts.py",
        help="Destination file path (default: combined_scripts.py in current directory)",
    )
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parent
    targets = [root / "script_patch", root / "script_week"]
    files = find_python_files(targets)
    if not files:
        print("No Python files found under script_patch/script_week", file=sys.stderr)
        return 1

    output_path = Path(args.output).resolve()
    combine(files, output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
