# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/cdata/battle_statistics_data.py
_reload_all = True
from ..common_const import statistics_const as sconst
data = {sconst.KILL_HUMAN: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98',
                       'target': 0,
                       'normal': True,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_KILL,
                       'method': 'add',
                       'rank': 5
                       },
   sconst.DEAD_HUMAN: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe8\xa2\xab\xe6\x9d\x80',
                       'target': 1,
                       'normal': True,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_KILL,
                       'method': 'add'
                       },
   sconst.KILLER: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\x87\xbb\xe6\x9d\x80\xe8\x80\x85',
                   'target': 1,
                   'normal': False,
                   'init_value': '',
                   'type': sconst.BATTLE_STATISTICS_KILL,
                   'method': 'set'
                   },
   sconst.CRASH_KILL_HUMAN: {'desc': '\xe6\x92\x9e\xe5\x87\xbb\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98',
                             'target': 0,
                             'normal': True,
                             'init_value': 0,
                             'type': sconst.BATTLE_STATISTICS_CRASH_KILL,
                             'method': 'add'
                             },
   sconst.KILL_DROP_HUMAN: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe9\xa3\x9e\xe8\xa1\x8c\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98',
                            'target': 0,
                            'normal': True,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_KILL_DROP,
                            'method': 'add'
                            },
   sconst.KILL_MECHA: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe6\x9c\xba\xe7\x94\xb2',
                       'target': 0,
                       'normal': True,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_KILL_MECHA,
                       'method': 'add'
                       },
   sconst.KILL_MECHA_CNT: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe6\x9c\xba\xe7\x94\xb2\xe8\xae\xa1\xe6\x95\xb0',
                           'target': 0,
                           'normal': False,
                           'init_value': 0,
                           'type': sconst.BATTLE_STATISTICS_KILL_MECHA_CNT,
                           'method': 'uda'
                           },
   sconst.KILL_MONSTER: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe6\x80\xaa\xe7\x89\xa9',
                         'target': 0,
                         'normal': True,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_KILL_MONSTER,
                         'method': 'add'
                         },
   sconst.KILL_HUAMN_MECHA: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\x92\x8c\xe6\x9c\xba\xe7\x94\xb2',
                             'target': 0,
                             'normal': False,
                             'init_value': 0,
                             'types': (
                                     sconst.BATTLE_STATISTICS_KILL, sconst.BATTLE_STATISTICS_KILL_MECHA),
                             'method': 'add',
                             'factor': (
                                      sconst.KILL_HUMAN, sconst.KILL_MECHA)
                             },
   sconst.MECHA_KILL_HUMAN_MECHA: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\x92\x8c\xe6\x9c\xba\xe7\x94\xb2',
                                   'target': 0,
                                   'normal': False,
                                   'init_value': 0,
                                   'type': sconst.BATTLE_STATISTICS_MECHA_KILL_HUMAN_MECHA,
                                   'method': 'uda'
                                   },
   sconst.HUMAN_KILL_MECHA: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\x87\xbb\xe6\x9d\x80\xe6\x9c\xba\xe7\x94\xb2',
                             'target': 0,
                             'normal': True,
                             'init_value': 0,
                             'type': sconst.BATTLE_STATISTICS_HUMAN_KILL_MECHA,
                             'method': 'add'
                             },
   sconst.HUMAN_KILL_HUMAN: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98',
                             'target': 0,
                             'normal': True,
                             'init_value': 0,
                             'type': sconst.BATTLE_STATISTICS_HUMAN_KILL_HUMAN,
                             'method': 'add'
                             },
   sconst.MECHA_KILL_MECHA: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe5\x87\xbb\xe6\x9d\x80\xe6\x9c\xba\xe7\x94\xb2',
                             'target': 0,
                             'normal': False,
                             'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_KILL_MECHA,
                             'method': 'uda'
                             },
   sconst.MECHA_KILL_HUMAN: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe5\x87\xbb\xe6\x9d\x80\xe7\x8e\xa9\xe5\xae\xb6',
                             'target': 0,
                             'normal': False,
                             'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_KILL_HUMAN,
                             'method': 'uda'
                             },
   sconst.COMBO_KILL: {'desc': '\xe8\xbf\x9e\xe6\x9d\x80',
                       'target': 0,
                       'normal': True,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_COMBO_KILL,
                       'method': 'add',
                       'death_mode_refresh': [
                                            'human']
                       },
   sconst.WEAPON_ELEVATION_KILL: {'desc': '\xe6\xad\xa6\xe5\x99\xa8\xe5\x9c\xb0\xe9\x9d\xa2\xe9\xab\x98\xe5\xba\xa6\xe5\x87\xbb\xe6\xaf\x81\xe5\x92\x8c\xe5\x87\xbb\xe6\x9d\x80',
                                  'target': 0,
                                  'normal': False,
                                  'init_value': {},'type': sconst.BATTLE_STATISTICS_WEAPON_ELEVATION_KILL,
                                  'method': 'udap'
                                  },
   sconst.HUMAN_DAMAGE: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe4\xbc\xa4\xe5\xae\xb3',
                         'target': 0,
                         'normal': False,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_HUMAN_DAMAGE,
                         'method': 'add'
                         },
   sconst.MAX_DAMAGE: {'desc': '\xe6\x9c\x80\xe5\xa4\xa7\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe4\xbc\xa4\xe5\xae\xb3',
                       'target': 0,
                       'normal': False,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_HUMAN_DAMAGE,
                       'method': 'max'
                       },
   sconst.MECHA_DAMAGE: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe4\xbc\xa4\xe5\xae\xb3',
                         'target': 0,
                         'normal': False,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_MECHA_DAMAGE,
                         'method': 'add'
                         },
   sconst.MAX_MECHA_DAMAGE: {'desc': '\xe6\x9c\x80\xe5\xa4\xa7\xe6\x9c\xba\xe7\x94\xb2\xe4\xbc\xa4\xe5\xae\xb3',
                             'target': 0,
                             'normal': False,
                             'init_value': 0,
                             'type': sconst.BATTLE_STATISTICS_MECHA_DAMAGE,
                             'method': 'max'
                             },
   sconst.MECHA_TRANS_DAMAGE: {'desc': '\xe8\xbd\xbd\xe5\x85\xb7\xef\xbc\x88\xe5\xb0\x8f\xe9\xb8\xa1\xef\xbc\x89\xe4\xbc\xa4\xe5\xae\xb3',
                               'target': 0,
                               'normal': False,
                               'init_value': 0,
                               'type': sconst.BATTLE_STATISTICS_MECHA_TRANS_DAMAGE,
                               'method': 'add'
                               },
   sconst.MAX_HURT: {'desc': '\xe6\x9c\x80\xe5\xa4\xa7\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\x8f\x97\xe4\xbc\xa4',
                     'target': 0,
                     'normal': False,
                     'init_value': 0,
                     'type': sconst.BATTLE_STATISTICS_HUMAN_HURT,
                     'method': 'max'
                     },
   sconst.HUMAN_HURT: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe6\x89\xbf\xe4\xbc\xa4',
                       'target': 0,
                       'normal': False,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_HUMAN_HURT,
                       'method': 'add'
                       },
   sconst.MECHA_HURT: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\x89\xbf\xe4\xbc\xa4',
                       'target': 0,
                       'normal': False,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_MECHA_HURT,
                       'method': 'add'
                       },
   sconst.MAX_MECHA_HURT: {'desc': '\xe6\x9c\x80\xe5\xa4\xa7\xe6\x9c\xba\xe7\x94\xb2\xe5\x8f\x97\xe4\xbc\xa4',
                           'target': 0,
                           'normal': False,
                           'init_value': 0,
                           'type': sconst.BATTLE_STATISTICS_MECHA_HURT,
                           'method': 'max'
                           },
   sconst.MECHA_TYPE_HURT: {'desc': '\xe5\x90\x84\xe7\xb1\xbb\xe5\x9e\x8b\xe6\x9c\xba\xe7\x94\xb2\xe7\x9a\x84\xe6\x89\xbf\xe4\xbc\xa4\xe5\x80\xbc',
                            'target': 0,
                            'normal': False,
                            'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_TYPE_HURT,
                            'method': 'uda'
                            },
   sconst.MECHA_CURE: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\x81\xa2\xe5\xa4\x8d\xe8\x80\x90\xe4\xb9\x85',
                       'target': 0,
                       'normal': False,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_MECHA_CURE,
                       'method': 'add'
                       },
   sconst.HUMAN_CURE: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe6\x81\xa2\xe5\xa4\x8d\xe8\xa1\x80\xe9\x87\x8f',
                       'target': 0,
                       'normal': False,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_HUMAN_CURE,
                       'method': 'add'
                       },
   sconst.ASSIST_HUAMN: {'desc': '\xe5\x8a\xa9\xe6\x94\xbb\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98',
                         'target': 0,
                         'normal': True,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_ASSIST_HUMAN,
                         'method': 'add'
                         },
   sconst.ASSIST_MECHA: {'desc': '\xe5\x8a\xa9\xe6\x94\xbb\xe5\x87\xbb\xe6\xaf\x81\xe6\x9c\xba\xe7\x94\xb2',
                         'target': 0,
                         'normal': True,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_ASSIST_MECHA,
                         'method': 'add'
                         },
   sconst.MOVE_DIST: {'desc': '\xe8\xa1\x8c\xe8\xbf\x9b\xe8\xb7\x9d\xe7\xa6\xbb',
                      'target': 0,
                      'normal': False,
                      'init_value': 0,
                      'type': sconst.BATTLE_STATISTICS_MOVE_DIS,
                      'method': 'add'
                      },
   sconst.PICK_ITEM: {'desc': '\xe6\x8b\xbe\xe5\x8f\x96\xe7\x89\xa9\xe8\xb5\x84',
                      'target': 0,
                      'normal': True,
                      'init_value': 0,
                      'type': sconst.BATTLE_STATISTICS_PICK_ITEM,
                      'method': 'add'
                      },
   sconst.SAVE_CNT: {'desc': '\xe6\x95\x91\xe6\x8f\xb4',
                     'target': 0,
                     'normal': True,
                     'init_value': 0,
                     'type': sconst.BATTLE_STATISTICS_SAVE,
                     'method': 'add'
                     },
   sconst.SAVED_CNT: {'desc': '\xe8\xa2\xab\xe6\x95\x91\xe4\xbf\xa1\xe6\x81\xaf',
                      'target': 1,
                      'normal': True,
                      'init_value': 0,
                      'type': sconst.BATTLE_STATISTICS_SAVE,
                      'method': 'add'
                      },
   sconst.SAVE_IN_MECHA_CNT: {'desc': '\xe5\x9c\xa8\xe6\x9c\xba\xe7\x94\xb2\xe4\xb8\x8a\xe6\x95\x91\xe6\x8f\xb4',
                              'target': 0,
                              'normal': True,
                              'init_value': 0,
                              'type': sconst.BATTLE_STATISTICS_SAVE_IN_MECHA,
                              'method': 'add'
                              },
   sconst.POISON_HURT: {'desc': '\xe6\xaf\x92\xe4\xbc\xa4',
                        'target': 0,
                        'normal': False,
                        'init_value': 0,
                        'type': sconst.BATTLE_STATISTICS_POISON,
                        'method': 'add'
                        },
   sconst.MECHA_POISON_HURT: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\xaf\x92\xe6\x9d\x80',
                              'target': 0,
                              'normal': False,
                              'init_value': 0,
                              'type': sconst.BATTLE_STATISTICS_MECHA_POISON,
                              'method': 'add'
                              },
   sconst.HUMAN_HIT: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\x91\xbd\xe4\xb8\xad',
                      'target': 0,
                      'normal': True,
                      'init_value': 0,
                      'type': sconst.BATTLE_STATISTICS_HUMAN_DAMAGE,
                      'method': 'add'
                      },
   sconst.MECHA_HIT: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe5\x91\xbd\xe4\xb8\xad',
                      'target': 0,
                      'normal': True,
                      'init_value': 0,
                      'type': sconst.BATTLE_STATISTICS_MECHA_DAMAGE,
                      'method': 'add'
                      },
   sconst.HEAD_HIT: {'desc': '\xe7\x88\x86\xe5\xa4\xb4\xe6\x95\xb0',
                     'target': 0,
                     'normal': True,
                     'init_value': 0,
                     'type': sconst.BATTLE_STATISTICS_HEADHIT,
                     'method': 'add'
                     },
   sconst.LIKE_OTHER_NUM: {'desc': '\xe7\x82\xb9\xe8\xb5\x9e\xe5\x88\xab\xe4\xba\xba\xe7\x9a\x84\xe6\xac\xa1\xe6\x95\xb0',
                           'target': 0,
                           'normal': False,
                           'init_value': 0,
                           'type': sconst.BATTLE_STATISTICS_LIKENUM,
                           'method': 'add'
                           },
   sconst.LIKENUM: {'desc': '\xe8\x8e\xb7\xe8\xb5\x9e\xe6\x95\xb0',
                    'target': 1,
                    'normal': False,
                    'init_value': 0,
                    'type': sconst.BATTLE_STATISTICS_LIKENUM,
                    'method': 'add'
                    },
   sconst.SURVIVAL_TIME: {'desc': '\xe5\xad\x98\xe6\xb4\xbb\xe6\x97\xb6\xe9\x97\xb4',
                          'target': 0,
                          'normal': False,
                          'init_value': 0,
                          'type': sconst.BATTLE_STATISTICS_SURVIVALTIME,
                          'method': 'set'
                          },
   sconst.MECHA_MOVE_DIST: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe8\xa1\x8c\xe8\xbf\x9b\xe8\xb7\x9d\xe7\xa6\xbb',
                            'target': 0,
                            'normal': False,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_MECHA_MOVE_DIS,
                            'method': 'add'
                            },
   sconst.HUMAN_FIGHT: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\x91\xbd\xe4\xb8\xad',
                        'target': 0,
                        'normal': True,
                        'init_value': 0,
                        'type': sconst.BATTLE_STATISTICS_HUMAN_FIGHT,
                        'method': 'add'
                        },
   sconst.MECHA_FIGHT: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe5\x91\xbd\xe4\xb8\xad',
                        'target': 0,
                        'normal': True,
                        'init_value': 0,
                        'type': sconst.BATTLE_STATISTICS_MECHA_FIGHT,
                        'method': 'add'
                        },
   sconst.MECHA_DEAD: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe8\xa2\xab\xe6\x9d\x80',
                       'target': 1,
                       'normal': True,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_KILL_MECHA,
                       'method': 'add'
                       },
   sconst.MECHA_TIME: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe9\xa9\xbe\xe9\xa9\xb6\xe6\x97\xb6\xe9\x97\xb4',
                       'target': 0,
                       'normal': False,
                       'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_TIME,
                       'method': 'uda'
                       },
   sconst.DAMAGE_TO_HUMAN: {'desc': '\xe5\xaf\xb9\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe7\x9a\x84\xe4\xbc\xa4\xe5\xae\xb3',
                            'target': 1,
                            'normal': False,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_HUMAN_HURT,
                            'method': 'add'
                            },
   sconst.DAMAGE_TO_MONSTER: {'desc': '\xe5\xaf\xb9\xe9\x87\x8e\xe6\x80\xaa\xe7\x9a\x84\xe4\xbc\xa4\xe5\xae\xb3',
                              'target': 1,
                              'normal': False,
                              'init_value': 0,
                              'type': sconst.BATTLE_STATISTICS_MONSTER_HURT,
                              'method': 'add'
                              },
   sconst.DAMAGE_TO_MECHA: {'desc': '\xe5\xaf\xb9\xe6\x9c\xba\xe7\x94\xb2\xe7\x9a\x84\xe4\xbc\xa4\xe5\xae\xb3',
                            'target': 1,
                            'normal': False,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_MECHA_HURT,
                            'method': 'add'
                            },
   sconst.HAS_CREATE_MECHA: {'desc': '\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\xac\xe5\x94\xa4\xe8\xbf\x87\xe6\x9c\xba\xe7\x94\xb2',
                             'target': 0,
                             'normal': False,
                             'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_TIME,
                             'method': 'udt'
                             },
   sconst.CREATE_MECHA_TIME: {'desc': '\xe7\xac\xac\xe4\xb8\x80\xe6\xac\xa1\xe5\x8f\xac\xe5\x94\xa4\xe6\x9c\xba\xe7\x94\xb2\xe6\x97\xb6\xe9\x95\xbf',
                              'target': 0,
                              'normal': False,
                              'init_value': 0,
                              'type': sconst.BATTLE_STATISTICS_CREATE_MECHA,
                              'method': 'min'
                              },
   sconst.PICK_AIRDROP: {'desc': '\xe6\x8d\xa1\xe7\xa9\xba\xe6\x8a\x95',
                         'target': 0,
                         'normal': False,
                         'init_value': {},'type': sconst.BATTLE_STATISTICS_PICK_AIRDROP,
                         'method': 'uda'
                         },
   sconst.MECAH_WP_DAMAGE: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\xad\xa6\xe5\x99\xa8\xe8\xbe\x93\xe5\x87\xba\xe4\xbc\xa4\xe5\xae\xb3',
                            'target': 0,
                            'normal': False,
                            'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_WEAPON_DAMAGE,
                            'method': 'uda'
                            },
   sconst.MECAH_SKILL_DAMAGE: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\x8a\x80\xe8\x83\xbd\xe8\xbe\x93\xe5\x87\xba\xe4\xbc\xa4\xe5\xae\xb3',
                               'target': 0,
                               'normal': False,
                               'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_SKILL_DAMAGE,
                               'method': 'uda'
                               },
   sconst.MECHA_BUILDING_DAMAGE: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe5\xbb\xba\xe7\xad\x91\xe8\xbe\x93\xe5\x87\xba\xe4\xbc\xa4\xe5\xae\xb3',
                                  'target': 0,
                                  'normal': False,
                                  'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_BUILDING_DAMAGE,
                                  'method': 'uda'
                                  },
   sconst.MECHA_TYPE_DAMAGE: {'desc': '\xe5\x90\x84\xe7\xb1\xbb\xe5\x9e\x8b\xe6\x9c\xba\xe7\x94\xb2\xe7\x9a\x84\xe4\xbc\xa4\xe5\xae\xb3\xe5\x80\xbc',
                              'target': 0,
                              'normal': False,
                              'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_TYPE_DAMAGE,
                              'method': 'uda'
                              },
   sconst.ACHIEVE_SCORE: {'desc': '\xe6\x88\x90\xe5\xb0\xb1\xe7\xa7\xaf\xe5\x88\x86',
                          'target': 0,
                          'normal': False,
                          'init_value': 0,
                          'type': sconst.BATTLE_STATISTICS_ACHIEVE_SCORE,
                          'method': 'add'
                          },
   sconst.MECHA_FIRE_CNT: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\xad\xa6\xe5\x99\xa8\xe8\xbe\x93\xe5\x87\xba\xe6\xac\xa1\xe6\x95\xb0',
                           'target': 0,
                           'normal': False,
                           'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_FIRE_CNT,
                           'method': 'knt'
                           },
   sconst.MECHA_FIRE_HIT: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\xad\xa6\xe5\x99\xa8\xe5\x91\xbd\xe4\xb8\xad\xe6\xac\xa1\xe6\x95\xb0',
                           'target': 0,
                           'normal': False,
                           'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_FIRE_HIT_CNT,
                           'method': 'knt'
                           },
   sconst.HANG_UP: {'desc': '\xe6\x8c\x82\xe6\x9c\xba\xe5\x88\xa4\xe5\xae\x9a',
                    'target': 0,
                    'normal': False,
                    'init_value': 0,
                    'type': sconst.BATTLE_STATISTICS_HANG_UP,
                    'method': 'set'
                    },
   sconst.ESCAPE_BATTLE: {'desc': '\xe9\x80\x83\xe8\xb7\x91\xe6\xac\xa1\xe6\x95\xb0',
                          'target': 0,
                          'normal': False,
                          'init_value': 0,
                          'type': sconst.BATTLE_STATISTICS_ESCAPE_BATTLE,
                          'method': 'add'
                          },
   sconst.IN_ACE_TIME: {'desc': '\xe6\xb4\xbb\xe7\x9d\x80\xe8\xbf\x9b\xe5\x85\xa5ACE\xe6\x97\xb6\xe9\x97\xb4',
                        'target': 0,
                        'normal': True,
                        'init_value': 0,
                        'type': sconst.BATTLE_STATISTICS_ACE_TIME,
                        'method': 'set'
                        },
   sconst.ACE_GROUP_SURVIAL_IDS: {'desc': '\xe8\xbf\x9b\xe5\x85\xa5ACE\xe6\x97\xb6\xe9\x97\xb4\xe9\x98\x9f\xe4\xbc\x8d\xe5\xad\x98\xe6\xb4\xbb\xe5\x88\x97\xe8\xa1\xa8',
                                  'target': 0,
                                  'normal': False,
                                  'init_value': 0,
                                  'type': sconst.BATTLE_STATISTICS_ACE_TIME,
                                  'method': 'set'
                                  },
   sconst.WEAPON_KILL_MECHA: {'desc': '\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe6\x9c\xba\xe7\x94\xb2\xe7\x9a\x84\xe6\x83\x85\xe5\x86\xb5',
                              'target': 0,
                              'normal': False,
                              'init_value': {},'type': sconst.BATTLE_STATISTICS_WEAPON_KILL_MECHA,
                              'method': 'uda'
                              },
   sconst.WEAPON_KILL_HUMAN: {'desc': '\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe7\x9a\x84\xe6\x83\x85\xe5\x86\xb5',
                              'target': 0,
                              'normal': False,
                              'init_value': {},'type': sconst.BATTLE_STATISTICS_WEAPON_KILL_HUMAN,
                              'method': 'uda'
                              },
   sconst.WEAPON_KILL_TARGET: {'desc': '\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe6\x95\x8c\xe4\xba\xba\xe7\x9a\x84\xe6\x83\x85\xe5\x86\xb5',
                               'target': 0,
                               'normal': False,
                               'init_value': {},'type': sconst.BATTLE_STATISTICS_WEAPON_KILL_TARGET,
                               'method': 'uda'
                               },
   sconst.HUMAN_WEAPON_DAMAGE: {'desc': '\xe4\xba\xba\xe7\xb1\xbb\xe4\xbd\xbf\xe7\x94\xa8\xe7\x9a\x84\xe6\xad\xa6\xe5\x99\xa8\xe4\xbc\xa4\xe5\xae\xb3\xe6\x83\x85\xe5\x86\xb5',
                                'target': 0,
                                'normal': False,
                                'init_value': {},'type': sconst.BATTLE_STATISTICS_HUMAN_WEAPON_DAMAGE,
                                'method': 'uda'
                                },
   sconst.USE_ITEM: {'desc': '\xe9\x81\x93\xe5\x85\xb7\xe4\xbd\xbf\xe7\x94\xa8\xe6\xac\xa1\xe6\x95\xb0',
                     'target': 0,
                     'normal': False,
                     'init_value': {},'type': sconst.BATTLE_STATISTICS_USE_ITEM,
                     'method': 'ududa'
                     },
   sconst.COLLECT_ITEM: {'desc': '\xe9\x81\x93\xe5\x85\xb7\xe6\x94\xb6\xe9\x9b\x86\xe6\x83\x85\xe5\x86\xb5',
                         'target': 0,
                         'normal': False,
                         'init_value': {},'type': sconst.BATTLE_STATISTICS_COLLECT_ITEM,
                         'method': 'ududa'
                         },
   sconst.KILL_MONSTER_BY_TYPE: {'desc': '\xe6\x91\xa7\xe6\xaf\x81\xe5\x90\x84\xe7\xa7\x8d\xe9\x87\x8e\xe6\x80\xaa\xe6\x95\xb0\xe9\x87\x8f\xe7\x9a\x84\xe7\xbb\x9f\xe8\xae\xa1',
                                 'target': 0,
                                 'normal': False,
                                 'init_value': {},'type': sconst.BATTLE_STATISTICS_KILL_MONSTER,
                                 'method': 'uda'
                                 },
   sconst.DAMAGE_TO_MONSTER_BY_TYPE: {'desc': '\xe5\xaf\xb9\xe5\x90\x84\xe7\xa7\x8d\xe9\x87\x8e\xe6\x80\xaa\xe4\xbc\xa4\xe5\xae\xb3\xe7\x9a\x84\xe7\xbb\x9f\xe8\xae\xa1',
                                      'target': 1,
                                      'normal': False,
                                      'init_value': {},'type': sconst.BATTLE_STATISTICS_DAMAGE_TO_MONSTER_BY_TYPE,
                                      'method': 'uda'
                                      },
   sconst.GET_MVP: {'desc': '\xe8\x8e\xb7\xe5\xbe\x97MVP',
                    'target': 0,
                    'normal': False,
                    'init_value': 0,
                    'type': sconst.BATTLE_STATISTICS_GET_MVP,
                    'method': 'add'
                    },
   sconst.MECHA_MOVE_DIST_BY_TYPE: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x90\x84\xe7\xb1\xbb\xe6\x9c\xba\xe7\x94\xb2\xe7\xa7\xbb\xe5\x8a\xa8\xe7\x9a\x84\xe8\xb7\x9d\xe7\xa6\xbb',
                                    'target': 0,
                                    'normal': False,
                                    'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_MOVE_DIS_BY_TYPE,
                                    'method': 'uda'
                                    },
   sconst.KILL_HUMAN_ON_SKATEBOARD: {'desc': '\xe5\x9c\xa8\xe6\xbb\x91\xe6\x9d\xbf\xe4\xb8\x8a\xe6\xb7\x98\xe6\xb1\xb0\xe7\x8e\xa9\xe5\xae\xb6',
                                     'target': 0,
                                     'normal': False,
                                     'init_value': 0,
                                     'type': sconst.BATTLE_STATISTICS_KILL_HUMAN_ON_SKATEBOARD,
                                     'method': 'add'
                                     },
   sconst.KILL_MECHA_ON_SKATEBOARD: {'desc': '\xe5\x9c\xa8\xe6\xbb\x91\xe6\x9d\xbf\xe4\xb8\x8a\xe6\x91\xa7\xe6\xaf\x81\xe6\x9c\xba\xe7\x94\xb2',
                                     'target': 0,
                                     'normal': False,
                                     'init_value': 0,
                                     'type': sconst.BATTLE_STATISTICS_KILL_MECHA_ON_SKATEBOARD,
                                     'method': 'add'
                                     },
   sconst.USE_BOUNCING_PLAT: {'desc': '\xe4\xbd\xbf\xe7\x94\xa8\xe5\xbc\xb9\xe8\xb7\xb3\xe5\x8f\xb0',
                              'target': 0,
                              'normal': False,
                              'init_value': 0,
                              'type': sconst.BATTLE_STATISTICS_USE_BOUNCING_PLAT,
                              'method': 'add'
                              },
   sconst.PARACHUTE_AREA: {'desc': '\xe8\xb7\xb3\xe4\xbc\x9e\xe9\x99\x8d\xe8\x90\xbd\xe5\x8c\xba\xe5\x9f\x9f',
                           'target': 0,
                           'normal': False,
                           'init_value': -1,
                           'type': sconst.BATTLE_STATISTICS_PARACHUTE_AREA,
                           'method': 'set'
                           },
   sconst.INSTALL_MECHA_MODULE: {'desc': '\xe5\xae\x89\xe8\xa3\x85\xe6\xa8\xa1\xe7\xbb\x84',
                                 'target': 0,
                                 'normal': False,
                                 'init_value': {},'type': sconst.BATTLE_STATISTICS_INSTALL_MECHA_MODULE,
                                 'method': 'uda'
                                 },
   sconst.KILL_HUMAN_AI: {'desc': '\xe5\x87\xbb\xe6\x9d\x80AI\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98',
                          'target': 0,
                          'normal': True,
                          'init_value': 0,
                          'type': sconst.BATTLE_STATISTICS_KILL_AI,
                          'method': 'add',
                          'rank': 5
                          },
   sconst.KILL_MECHA_AI: {'desc': '\xe5\x87\xbb\xe6\x9d\x80AI\xe6\x9c\xba\xe7\x94\xb2',
                          'target': 0,
                          'normal': True,
                          'init_value': 0,
                          'type': sconst.BATTLE_STATISTICS_KILL_MECHA_AI,
                          'method': 'add'
                          },
   sconst.HUMAN_DAMAGE_AI: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\xaf\xb9AI\xe4\xbc\xa4\xe5\xae\xb3',
                            'target': 0,
                            'normal': False,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_HUMAN_DAMAGE_AI,
                            'method': 'add'
                            },
   sconst.MECHA_DAMAGE_AI: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe5\xaf\xb9AI\xe4\xbc\xa4\xe5\xae\xb3',
                            'target': 0,
                            'normal': False,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_MECHA_DAMAGE_AI,
                            'method': 'add'
                            },
   sconst.KILLED_BY_AI: {'desc': '\xe8\xa2\xabAI\xe5\x87\xbb\xe6\x9d\x80',
                         'target': 1,
                         'normal': True,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_AI_KILL,
                         'method': 'add'
                         },
   sconst.CALL_MECHA_TIMES: {'desc': '\xe5\x8f\xac\xe5\x94\xa4\xe6\x9c\xba\xe7\x94\xb2\xe6\xac\xa1\xe6\x95\xb0',
                             'target': 0,
                             'normal': True,
                             'init_value': 0,
                             'type': sconst.BATTLE_STATISTICS_CALL_MECHA,
                             'method': 'add'
                             },
   sconst.KILL_HUMAN_DIST: {'desc': '\xe4\xbd\xbf\xe7\x94\xa8\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe7\x9a\x84\xe8\xb7\x9d\xe7\xa6\xbb',
                            'target': 0,
                            'normal': False,
                            'init_value': {},'type': sconst.BATTLE_STATISTICS_KILL_HUMAN_DIST,
                            'method': 'udap'
                            },
   sconst.KILL_MECHA_DIST: {'desc': '\xe4\xbd\xbf\xe7\x94\xa8\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe6\x9c\xba\xe7\x94\xb2\xe7\x9a\x84\xe8\xb7\x9d\xe7\xa6\xbb',
                            'target': 0,
                            'normal': False,
                            'init_value': {},'type': sconst.BATTLE_STATISTICS_KILL_MECHA_DIST,
                            'method': 'udap'
                            },
   sconst.KILL_TARGET_DIST: {'desc': '\xe4\xbd\xbf\xe7\x94\xa8\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe6\x95\x8c\xe4\xba\xba\xe7\x9a\x84\xe8\xb7\x9d\xe7\xa6\xbb',
                             'target': 0,
                             'normal': False,
                             'init_value': {},'type': sconst.BATTLE_STATISTICS_KILL_TARGET_DIST,
                             'method': 'udap'
                             },
   sconst.KILL_HUMAN_AREA: {'desc': '\xe5\x9c\xa8\xe5\x90\x84\xe4\xb8\xaa\xe5\x8c\xba\xe5\x9f\x9f\xe4\xbd\xbf\xe7\x94\xa8\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe7\x8e\xa9\xe5\xae\xb6\xe6\x95\xb0',
                            'target': 0,
                            'normal': False,
                            'init_value': {},'type': sconst.BATTLE_STATISTICS_KILL_HUMAN_AREA,
                            'method': 'ududa'
                            },
   sconst.KILL_MECHA_AREA: {'desc': '\xe5\x9c\xa8\xe5\x90\x84\xe4\xb8\xaa\xe5\x8c\xba\xe5\x9f\x9f\xe4\xbd\xbf\xe7\x94\xa8\xe6\xad\xa6\xe5\x99\xa8\xe6\x91\xa7\xe6\xaf\x81\xe6\x9c\xba\xe7\x94\xb2\xe6\x95\xb0',
                            'target': 0,
                            'normal': False,
                            'init_value': {},'type': sconst.BATTLE_STATISTICS_KILL_MECHA_AREA,
                            'method': 'ududa'
                            },
   sconst.MECHA_HURT_DETAIL_REFRESH: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe5\x8f\x97\xe4\xbc\xa4\xe8\xaf\xa6\xe6\x83\x85(\xe6\xad\xbb\xe4\xba\xa1\xe5\x88\xb7\xe6\x96\xb0)',
                                      'target': 0,
                                      'normal': False,
                                      'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_HURT_DETAIL,
                                      'method': 'uda',
                                      'death_mode_refresh': [
                                                           'human', 'mecha'],
                                      'survival_mode_refresh': [
                                                              'human', 'mecha']
                                      },
   sconst.MECHA_HURT_DETAIL: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe5\x8f\x97\xe4\xbc\xa4\xe8\xaf\xa6\xe6\x83\x85',
                              'target': 0,
                              'normal': False,
                              'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_HURT_DETAIL,
                              'method': 'uda'
                              },
   sconst.HUMAN_HURT_DETAIL: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\x8f\x97\xe4\xbc\xa4\xe8\xaf\xa6\xe6\x83\x85',
                              'target': 0,
                              'normal': False,
                              'init_value': {},'type': sconst.BATTLE_STATISTICS_HUMAN_HURT_DETAIL,
                              'method': 'uda',
                              'death_mode_refresh': [
                                                   'human']
                              },
   sconst.KILL_MECHA_TRANS: {'desc': '\xe6\x91\xa7\xe6\xaf\x81\xe5\x8f\x98\xe5\xbd\xa2\xe8\xbd\xa6\xe6\x95\xb0\xe9\x87\x8f',
                             'target': 0,
                             'normal': False,
                             'init_value': 0,
                             'type': sconst.BATTLE_STATISTICS_KILL_MECHA_TRANS,
                             'method': 'add'
                             },
   sconst.SKATE_MOVE_DIST: {'desc': '\xe6\xbb\x91\xe6\x9d\xbf\xe8\xa1\x8c\xe8\xbf\x9b\xe8\xb7\x9d\xe7\xa6\xbb',
                            'target': 0,
                            'normal': False,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_SKATE_MOVE_DIS,
                            'method': 'add'
                            },
   sconst.DRIVER_LEVEL: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe7\xad\x89\xe7\xba\xa7',
                         'target': 0,
                         'normal': False,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_DRIVER_LEVEL,
                         'method': 'set'
                         },
   sconst.KILL_GROUP: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe5\x90\x84\xe5\xb0\x8f\xe9\x98\x9f\xe7\x9a\x84\xe4\xba\xba\xe6\x95\xb0\xe7\xbb\x9f\xe8\xae\xa1',
                       'target': 0,
                       'normal': False,
                       'init_value': {},'type': sconst.BATTLE_STATISTICS_KILL_GROUP,
                       'method': 'uda'
                       },
   sconst.MECHA_SKIN: {'desc': '\xe4\xbd\xbf\xe7\x94\xa8\xe7\x9a\x84\xe6\x9c\xba\xe7\x94\xb2\xe7\x9a\xae\xe8\x82\xa4',
                       'target': 0,
                       'normal': False,
                       'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_SKIN,
                       'method': 'udas'
                       },
   sconst.FIGHT_BACK: {'desc': '\xe5\x8f\x8d\xe5\x87\xbb',
                       'target': 0,
                       'normal': True,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_FIGHT_BACK,
                       'method': 'add'
                       },
   sconst.TERMINATOR: {'desc': '\xe7\xbb\x88\xe7\xbb\x93\xe8\x80\x85',
                       'target': 0,
                       'normal': True,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_TERMINATOR,
                       'method': 'add'
                       },
   sconst.PERFECT_ATK: {'desc': '\xe5\xae\x8c\xe7\xbe\x8e\xe6\x94\xbb\xe5\x87\xbb',
                        'target': 0,
                        'normal': True,
                        'init_value': 0,
                        'type': sconst.BATTLE_STATISTICS_PERFECT_ATK,
                        'method': 'add'
                        },
   sconst.RIGHT_ON_TARGET: {'desc': '\xe6\xad\xa3\xe4\xb8\xad\xe9\x9d\xb6\xe5\xbf\x83',
                            'target': 0,
                            'normal': True,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_RIGHT_ON_TARGET,
                            'method': 'add'
                            },
   sconst.GOAL_POACHER: {'desc': '\xe5\x81\xb7\xe7\x8c\x8e\xe8\x80\x85',
                         'target': 0,
                         'normal': True,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_GOAL_POACHER,
                         'method': 'add'
                         },
   sconst.FIRST_BLOOD: {'desc': '\xe7\xac\xac\xe4\xb8\x80\xe6\xbb\xb4\xe8\xa1\x80',
                        'target': 0,
                        'normal': True,
                        'init_value': 0,
                        'type': sconst.BATTLE_STATISTICS_FIRST_BLOOD,
                        'method': 'add'
                        },
   sconst.DESTROY_BREAKABLE: {'desc': '\xe6\x91\xa7\xe6\xaf\x81\xe7\xa0\xb4\xe7\xa2\x8e\xe7\x89\xa9',
                              'target': 0,
                              'normal': False,
                              'init_value': {},'type': sconst.BATTLE_STATISTICS_DESTROY_BREAKABLE,
                              'method': 'uda'
                              },
   sconst.DESTROY_DOOR: {'desc': '\xe6\x91\xa7\xe6\xaf\x81\xe9\x97\xa8',
                         'target': 0,
                         'normal': False,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_DESTROY_DOOR,
                         'method': 'add'
                         },
   sconst.USE_ACTION_ITEM: {'desc': '\xe4\xbd\xbf\xe7\x94\xa8\xe8\xa1\xa8\xe6\x83\x85\xe3\x80\x81\xe5\x96\xb7\xe7\xbb\x98\xe5\x92\x8c\xe4\xba\xa4\xe4\xba\x92\xe5\x8a\xa8\xe4\xbd\x9c\xe7\x89\xa9\xe5\x93\x81\xe7\xbb\x9f\xe8\xae\xa1',
                            'target': 0,
                            'normal': False,
                            'init_value': {},'type': sconst.BATTLE_STATISTICS_ACTION_ITEM,
                            'method': 'ududa'
                            },
   sconst.KILL_MECHA_BY_REAL_HUMAN: {'desc': '\xe8\xa2\xab\xe7\x9c\x9f\xe5\xae\x9e\xe7\x8e\xa9\xe5\xae\xb6\xe6\x91\xa7\xe6\xaf\x81\xe6\x9c\xba\xe7\x94\xb2\xe6\x95\xb0',
                                     'target': 1,
                                     'normal': False,
                                     'init_value': 0,
                                     'type': sconst.BATTLE_STATISTICS_KILL_MECHA_BY_REAL_HUMAN,
                                     'method': 'add'
                                     },
   sconst.KILL_MECHA_BY_REAL_MECHA: {'desc': '\xe8\xa2\xab\xe7\x9c\x9f\xe5\xae\x9e\xe7\x8e\xa9\xe5\xae\xb6\xe6\x9c\xba\xe7\x94\xb2\xe6\x91\xa7\xe6\xaf\x81\xe6\x9c\xba\xe7\x94\xb2\xe6\x95\xb0',
                                     'target': 1,
                                     'normal': False,
                                     'init_value': 0,
                                     'type': sconst.BATTLE_STATISTICS_KILL_MECHA_BY_REAL_MECHA,
                                     'method': 'add'
                                     },
   sconst.KILL_SEE_THROUGH_HUMAN: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe7\x83\xad\xe8\x83\xbd\xe6\x8e\xa2\xe6\xb5\x8b\xe5\x88\xb0\xe7\x9a\x84\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98',
                                   'target': 0,
                                   'normal': False,
                                   'init_value': 0,
                                   'type': sconst.BATTLE_STATISTICS_KILL_SEE_THROUGH_HUMAN,
                                   'method': 'add'
                                   },
   sconst.KILL_SEE_THROUGH_MECHA: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe7\x83\xad\xe8\x83\xbd\xe6\x8e\xa2\xe6\xb5\x8b\xe5\x88\xb0\xe7\x9a\x84\xe6\x9c\xba\xe7\x94\xb2',
                                   'target': 0,
                                   'normal': False,
                                   'init_value': 0,
                                   'type': sconst.BATTLE_STATISTICS_KILL_SEE_THROUGH_MECHA,
                                   'method': 'add'
                                   },
   sconst.HUMAN_WALK_DIS: {'desc': '\xe4\xba\xba\xe7\x89\xa9\xe8\xa1\x8c\xe8\xbf\x9b\xe8\xb7\x9d\xe7\xa6\xbb',
                           'target': 0,
                           'normal': False,
                           'init_value': 0,
                           'type': sconst.BATTLE_STATISTICS_HUMAN_WALK_DIS,
                           'method': 'add'
                           },
   sconst.WP_KILL_HUMAN_ON_SKATE: {'desc': '\xe5\x9c\xa8\xe6\xbb\x91\xe6\x9d\xbf\xe4\xb8\x8a\xe4\xbd\xbf\xe7\x94\xa8\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe7\xbb\x9f\xe8\xae\xa1',
                                   'target': 0,
                                   'normal': False,
                                   'init_value': {},'type': sconst.BATTLE_STATISTICS_WP_KILL_HUMAN_ON_SKATE,
                                   'method': 'uda'
                                   },
   sconst.WP_KILL_MECHA_ON_SKATE: {'desc': '\xe5\x9c\xa8\xe6\xbb\x91\xe6\x9d\xbf\xe4\xb8\x8a\xe4\xbd\xbf\xe7\x94\xa8\xe6\xad\xa6\xe5\x99\xa8\xe6\x91\xa7\xe6\xaf\x81\xe6\x9c\xba\xe7\x94\xb2\xe7\xbb\x9f\xe8\xae\xa1',
                                   'target': 0,
                                   'normal': False,
                                   'init_value': {},'type': sconst.BATTLE_STATISTICS_WP_KILL_MECHA_ON_SKATE,
                                   'method': 'uda'
                                   },
   sconst.DESTROY_DEATH_DOOR: {'desc': '\xe6\x91\xa7\xe6\xaf\x81\xe6\xad\xbb\xe6\x96\x97\xe7\x9a\x84\xe9\x97\xa8',
                               'target': 0,
                               'normal': False,
                               'init_value': 0,
                               'type': sconst.BATTLE_STATISTICS_DESTROY_DEATH_DOOR,
                               'method': 'add'
                               },
   sconst.KILL_PROMPT: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe6\x8f\x90\xe7\xa4\xba\xe7\xbb\x9f\xe8\xae\xa1',
                        'target': 0,
                        'normal': False,
                        'init_value': {},'type': sconst.BATTLE_STATISTICS_KILL_PROMPT,
                        'method': 'uda'
                        },
   sconst.BREAK_SCENE_BOX: {'desc': '\xe6\x91\xa7\xe6\xaf\x81\xe5\x9c\xba\xe6\x99\xaf\xe5\xae\x9d\xe7\xae\xb1',
                            'target': 0,
                            'normal': False,
                            'init_value': {},'type': sconst.BATTLE_STATISTICS_BREAK_SCENE_BOX,
                            'method': 'uda'
                            },
   sconst.PARACHUTE_DIST: {'desc': '\xe9\x99\x8d\xe8\x90\xbd\xe4\xbc\x9e\xe6\xbb\x91\xe5\x8a\xa8\xe8\xb7\x9d\xe7\xa6\xbb',
                           'target': 0,
                           'normal': False,
                           'init_value': 0,
                           'type': sconst.BATTLE_STATISTICS_PARACHUTE_DIST,
                           'method': 'add'
                           },
   sconst.HUMAN_STATE_TIME: {'desc': '\xe4\xba\xba\xe5\xbd\xa2\xe6\x80\x81\xe6\x97\xb6\xe9\x97\xb4',
                             'target': 0,
                             'normal': False,
                             'init_value': 0,
                             'type': sconst.BATTLE_STATISTICS_HUMAN_STATE_TIME,
                             'method': 'set'
                             },
   sconst.OPEN_BOX_POS: {'desc': '\xe7\xbb\x9f\xe8\xae\xa1\xe7\x8e\xa9\xe5\xae\xb6\xe6\x89\x93\xe5\xbc\x80\xe5\xae\x9d\xe7\xae\xb1\xe7\x9a\x84\xe5\x9d\x90\xe6\xa0\x87\xe4\xbf\xa1\xe6\x81\xaf',
                         'target': 0,
                         'normal': False,
                         'init_value': {},'type': sconst.BATTLE_STATISTICS_OPEN_BOX_POS,
                         'method': 'udap'
                         },
   sconst.GRANBELM_APPLY_RUNE: {'desc': '\xe6\xbf\x80\xe6\xb4\xbb\xe7\xac\xa6\xe7\x9f\xb3\xe8\x83\xbd\xe5\x8a\x9b',
                                'target': 0,
                                'normal': False,
                                'init_value': 0,
                                'type': sconst.BATTLE_STATISTICS_GRANBELM_APPLY_RUNE,
                                'method': 'add'
                                },
   sconst.GRANBELM_TELEPORT: {'desc': '\xe4\xbd\xbf\xe7\x94\xa8\xe4\xbc\xa0\xe9\x80\x81\xe6\xb3\x95\xe9\x98\xb5',
                              'target': 0,
                              'normal': False,
                              'init_value': 0,
                              'type': sconst.BATTLE_STATISTICS_GRANBELM_TELEPORT,
                              'method': 'add'
                              },
   sconst.MECHA_CONTINUE_POINT: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe8\xbf\x9e\xe7\xbb\xad\xe5\xbe\x97\xe5\x88\x86',
                                 'target': 0,
                                 'normal': False,
                                 'init_value': 0,
                                 'type': sconst.BATTLE_STATISTICS_MECHA_CONTINUE_POINT,
                                 'method': 'max'
                                 },
   sconst.HUMAN_BLEED: {'desc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe8\xa2\xab\xe5\x87\xbb\xe5\x80\x92',
                        'target': 1,
                        'normal': True,
                        'init_value': 0,
                        'type': sconst.BATTLE_STATISTICS_HUMAN_BLEED,
                        'method': 'add'
                        },
   sconst.BATTLE_START: {'desc': '\xe5\xbc\x80\xe5\xb1\x80',
                         'target': 0,
                         'normal': True,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_MARK_LAND,
                         'method': 'add'
                         },
   sconst.CONCERT_DUEL_JOIN: {'desc': '\xe6\xbc\x94\xe5\x94\xb1\xe4\xbc\x9a\xe5\x8f\x82\xe4\xb8\x8e\xe6\x89\x93\xe6\x93\x82',
                              'target': 0,
                              'normal': False,
                              'init_value': 0,
                              'type': sconst.BATTLE_STATISTICS_CONCERT_DUEL_JOIN,
                              'method': 'add'
                              },
   sconst.CONCERT_DUEL_WIN: {'desc': '\xe6\xbc\x94\xe5\x94\xb1\xe4\xbc\x9a\xe6\x89\x93\xe6\x93\x82\xe8\x83\x9c\xe5\x88\xa9',
                             'target': 0,
                             'normal': False,
                             'init_value': 0,
                             'type': sconst.BATTLE_STATISTICS_CONCERT_DUEL_WIN,
                             'method': 'add'
                             },
   sconst.CONCERT_DANCE_CALL: {'desc': '\xe6\xbc\x94\xe5\x94\xb1\xe4\xbc\x9a\xe6\x89\x93call',
                               'target': 0,
                               'normal': False,
                               'init_value': 0,
                               'type': sconst.BATTLE_STATISTICS_CONCERT_DANCE_CALL,
                               'method': 'add'
                               },
   sconst.CONCERT_SEND_DANMU: {'desc': '\xe6\xbc\x94\xe5\x94\xb1\xe4\xbc\x9a\xe5\x8f\x91\xe9\x80\x81\xe5\xbc\xb9\xe5\xb9\x95',
                               'target': 0,
                               'normal': False,
                               'init_value': 0,
                               'type': sconst.BATTLE_STATISTICS_CONCERT_SEND_DANMU,
                               'method': 'add'
                               },
   sconst.CONTROL_POINT_TIME: {'desc': '\xe5\x8d\xa0\xe7\x82\xb9\xe6\xa8\xa1\xe5\xbc\x8f\xe5\x8d\xa0\xe7\x82\xb9\xe6\x97\xb6\xe9\x95\xbf',
                               'target': 0,
                               'normal': False,
                               'init_value': 0,
                               'type': sconst.BATTLE_STATISTICS_CONTROL_POINT_TIME,
                               'method': 'add'
                               },
   sconst.BATTLE_CAST_SKILL_WEAPONL_EFFECT: {'desc': '\xe6\x96\xbd\xe6\x94\xbe\xe6\x8a\x80\xe8\x83\xbd/\xe6\xad\xa6\xe5\x99\xa8\xe6\x95\x88\xe6\x9e\x9c\xe7\xbb\x9f\xe8\xae\xa1',
                                             'target': 0,
                                             'normal': False,
                                             'init_value': 1,
                                             'type': sconst.BATTLE_STATISTICS_BATTLE_SKILL_WEAPON,
                                             'method': 'uda'
                                             },
   sconst.BATTLE_ANSWER: {'desc': '\xe5\xb1\x80\xe5\x86\x85\xe5\x9b\x9e\xe7\xad\x94\xe9\x97\xae\xe9\xa2\x98',
                          'target': 0,
                          'normal': False,
                          'init_value': 0,
                          'type': sconst.BATTLE_STATISTICS_BATTLE_ANSWER,
                          'method': 'add'
                          },
   sconst.PLANT_FLAG: {'desc': '\xe5\xa4\xba\xe6\x97\x97\xe6\x94\xbb\xe9\x98\xb2\xe6\x8f\x92\xe6\x97\x97\xe5\xad\x90',
                       'target': 0,
                       'normal': False,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_PLANT_FLAG,
                       'method': 'add'
                       },
   sconst.KILL_KING: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe5\x9b\xbd\xe7\x8e\x8b',
                      'target': 0,
                      'normal': True,
                      'init_value': 0,
                      'type': sconst.BATTLE_STATISTICS_KILL_KING,
                      'method': 'add'
                      },
   sconst.KING_KILL_MECHA: {'desc': '\xe5\x9b\xbd\xe7\x8e\x8b\xe5\x87\xbb\xe6\x9d\x80\xe6\x9c\xba\xe7\x94\xb2',
                            'target': 0,
                            'normal': True,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_KING_KILL_MECHA,
                            'method': 'add'
                            },
   sconst.KING_KILL_HUMAN: {'desc': '\xe5\x9b\xbd\xe7\x8e\x8b\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98',
                            'target': 0,
                            'normal': True,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_KING_KILL_HUMAN,
                            'method': 'add'
                            },
   sconst.KING_ALIVE: {'desc': '\xe5\x9b\xbd\xe7\x8e\x8b\xe5\xad\x98\xe6\xb4\xbb',
                       'target': 0,
                       'normal': True,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_KING_ALIVE,
                       'method': 'add'
                       },
   sconst.DAMAGE_TO_CRYSTAL: {'desc': '\xe5\xaf\xb9\xe6\xb0\xb4\xe6\x99\xb6\xe7\x9a\x84\xe4\xbc\xa4\xe5\xae\xb3',
                              'target': 1,
                              'normal': False,
                              'init_value': 0,
                              'type': sconst.BATTLE_STATISTICS_CRYSTAL_HURT,
                              'method': 'add'
                              },
   sconst.KILL_CRYSTAL: {'desc': '\xe5\x87\xbb\xe6\xaf\x81\xe6\xb0\xb4\xe6\x99\xb6',
                         'target': 0,
                         'normal': True,
                         'init_value': 0,
                         'type': sconst.BATTLE_STATISTICS_KILL_CRYSTAL,
                         'method': 'add'
                         },
   sconst.OCCUPY_PERSONAL_SCORE: {'desc': '\xe5\x8d\xa0\xe7\x82\xb9\xe4\xb8\xaa\xe4\xba\xba\xe5\x88\x86',
                                  'target': 0,
                                  'normal': False,
                                  'init_value': 0,
                                  'type': sconst.BATTLE_STATISTICS_OCCUPY_PERSONAL_SCORE,
                                  'method': 'add'
                                  },
   sconst.PUSH_TRAIN: {'desc': '\xe6\x8e\xa8\xe7\x81\xab\xe8\xbd\xa6',
                       'target': 0,
                       'normal': False,
                       'init_value': 0,
                       'type': sconst.BATTLE_STATISTICS_PUSH_TRAIN,
                       'method': 'add'
                       },
   sconst.EGG_STORE: {'desc': '\xe5\xad\x98\xe5\x82\xa8\xe9\x87\x91\xe8\x9b\x8b',
                      'target': 0,
                      'normal': False,
                      'init_value': 0,
                      'type': sconst.BATTLE_STATICS_EGG_STORE,
                      'method': 'add'
                      },
   sconst.MECHA_KILL_MECHA_BY_SKIN: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe7\x9a\xae\xe8\x82\xa4\xe5\x87\xbb\xe6\x9d\x80\xe6\x9c\xba\xe7\x94\xb2',
                                     'target': 0,
                                     'normal': 0,
                                     'init_value': {},'type': sconst.BATTLE_STATICS_MECHA_KILL_MECHA_BY_SKIN,
                                     'method': 'uda'
                                     },
   sconst.MECHA_KILL_HUMAN_BY_SKIN: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe7\x9a\xae\xe8\x82\xa4\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98',
                                     'target': 0,
                                     'normal': 0,
                                     'init_value': {},'type': sconst.BATTLE_STATICS_MECHA_KILL_HUMAN_BY_SKIN,
                                     'method': 'uda'
                                     },
   sconst.MECHA_KILL_HUMAN_MECHA_BY_SKIN: {'desc': '\xe6\x9c\xba\xe7\x94\xb2\xe7\x9a\xae\xe8\x82\xa4\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe5\x92\x8c\xe6\x9c\xba\xe7\x94\xb2',
                                           'target': 0,
                                           'normal': 0,
                                           'init_value': {},'type': sconst.BATTLE_STATICS_MECHA_KILL_HUMAN_MECHA_BY_SKIN,
                                           'method': 'uda'
                                           },
   sconst.ASSIST_HUAMN_DETAIL: {'desc': '\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe9\xa9\xbe\xe9\xa9\xb6\xe5\x91\x98\xe7\x9a\x84\xe6\x83\x85\xe5\x86\xb5',
                                'target': 0,
                                'normal': False,
                                'init_value': {},'type': sconst.BATTLE_STATISTICS_ASSIST_HUMAN_DETAIL,
                                'method': 'uda'
                                },
   sconst.ASSIST_MECHA_DETAIL: {'desc': '\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe6\x9c\xba\xe7\x94\xb2\xe7\x9a\x84\xe6\x83\x85\xe5\x86\xb5',
                                'target': 0,
                                'normal': False,
                                'init_value': {},'type': sconst.BATTLE_STATISTICS_ASSIST_MECHA_DETAIL,
                                'method': 'uda'
                                },
   sconst.SAVE_CNT_DETAIL: {'desc': '\xe6\x95\x91\xe6\x8f\xb4\xef\xbc\x88\xe8\xaf\xa6\xe7\xbb\x86\xef\xbc\x89',
                            'target': 0,
                            'normal': False,
                            'init_value': {},'type': sconst.BATTLE_STATISTICS_SAVE_DETAIL,
                            'method': 'uda'
                            },
   sconst.KILL_MONSTER_PVE_TYPE: {'desc': 'PVE\xe5\x87\xbb\xe6\x9d\x80\xe6\x80\xaa\xe7\x89\xa9\xe7\xb1\xbb\xe5\x9e\x8b',
                                  'target': 0,
                                  'normal': False,
                                  'init_value': 0,
                                  'type': sconst.BATTLE_STATISTICS_KILL_MONSTER_PVE_TYPE,
                                  'method': 'uda'
                                  },
   sconst.PVE_SHOP_BUY_NUM: {'desc': 'PVE\xe5\x95\x86\xe5\xba\x97\xe8\xb4\xad\xe4\xb9\xb0\xe6\xac\xa1\xe6\x95\xb0',
                             'target': 0,
                             'normal': False,
                             'init_value': 0,
                             'type': sconst.BATTLE_STAT_PVE_SHOP_BUY_NUM,
                             'method': 'add'
                             },
   sconst.PVE_ITEM_PICK: {'desc': 'PVE\xe9\x81\x93\xe5\x85\xb7\xe6\x8b\xbe\xe5\x8f\x96\xe6\x95\xb0\xe9\x87\x8f\xef\xbc\x88\xe5\x8c\x85\xe6\x8b\xac\xe5\x8a\xa0\xe6\x88\x90\xef\xbc\x89',
                          'target': 0,
                          'normal': False,
                          'init_value': {},'type': sconst.BATTLE_STAT_PVE_ITEM_PICK,
                          'method': 'uda'
                          },
   sconst.MECHA_TYPE_ASSIST: {'desc': '\xe5\x90\x84\xe7\xb1\xbb\xe5\x9e\x8b\xe6\x9c\xba\xe7\x94\xb2\xe5\x8a\xa9\xe6\x94\xbb',
                              'target': 0,
                              'normal': False,
                              'init_value': {},'type': sconst.BATTLE_STATISTICS_MECHA_TYPE_ASSIST,
                              'method': 'uda'
                              },
   sconst.PVE_CHOOSED_BLESSES: {'desc': 'PVE\xe6\x8d\xa1\xe7\xa5\x9d\xe7\xa6\x8f',
                                'target': 0,
                                'normal': False,
                                'init_value': {},'type': sconst.BATTLE_STATISTICS_PVE_CHOOSED_BLESSES,
                                'method': 'uda'
                                },
   sconst.PVE_CHOOSED_BREAKTHROUGH: {'desc': 'PVE\xe6\x8d\xa1\xe7\xaa\x81\xe7\xa0\xb4',
                                     'target': 0,
                                     'normal': False,
                                     'init_value': {},'type': sconst.BATTLE_STATISTICS_PVE_CHOOSED_BREAKTHROUGH,
                                     'method': 'uda'
                                     },
   sconst.PVE_BOX_OPEN_NUM: {'desc': 'PVE\xe5\xbc\x80\xe5\x90\xaf\xe7\xae\xb1\xe5\xad\x90\xe6\xac\xa1\xe6\x95\xb0',
                             'target': 0,
                             'normal': False,
                             'init_value': 0,
                             'type': sconst.BATTLE_STAT_PVE_SHOP_BUY_NUM,
                             'method': 'add'
                             },
   sconst.RECOVER_SHIELD: {'desc': '\xe5\x9b\x9e\xe5\xa4\x8d\xe6\x8a\xa4\xe7\x9b\xbe\xe7\xbb\x9f\xe8\xae\xa1',
                           'target': 0,
                           'normal': False,
                           'init_value': 0,
                           'type': sconst.BATTLE_STATISTICS_RECOVER_SHIELD,
                           'method': 'add'
                           },
   sconst.PVE_OPEN_SHOP: {'desc': 'PVE\xe5\xbc\x80\xe5\x90\xaf\xe5\x95\x86\xe5\xba\x97',
                          'target': 0,
                          'normal': False,
                          'init_value': 0,
                          'type': sconst.BATTLE_STATISTICS_PVE_OPEN_SHOP,
                          'method': 'add'
                          },
   sconst.PVE_ADD_CRYSTAL_STONE: {'desc': 'PVE\xe8\x8e\xb7\xe5\xbe\x97\xe6\x95\xb0\xe6\x8d\xae\xe5\xb8\x81',
                                  'target': 0,
                                  'normal': False,
                                  'init_value': 0,
                                  'type': sconst.BATTLE_STATISTICS_PVE_ADD_CRYSTAL_STONE,
                                  'method': 'add'
                                  },
   sconst.PVE_ADD_PVE_COIN: {'desc': 'PVE\xe8\x8e\xb7\xe5\xbe\x97\xe6\xac\xa1\xe5\x85\x83\xe5\xb8\x81',
                             'target': 0,
                             'normal': False,
                             'init_value': 0,
                             'type': sconst.BATTLE_STATISTICS_PVE_ADD_PVE_COIN,
                             'method': 'add'
                             },
   sconst.PVE_ADD_STORY_DEBRIS: {'desc': 'PVE\xe8\x8e\xb7\xe5\xbe\x97\xe6\x95\x85\xe4\xba\x8b\xe7\xa2\x8e\xe7\x89\x87',
                                 'target': 0,
                                 'normal': False,
                                 'init_value': 0,
                                 'type': sconst.BATTLE_STATISTICS_PVE_ADD_STORY_DEBRIS,
                                 'method': 'add'
                                 },
   sconst.PVE_ADD_MECHA_DEBRIS: {'desc': 'PVE\xe8\x8e\xb7\xe5\xbe\x97\xe6\x9c\xba\xe7\x94\xb2\xe7\xa2\x8e\xe7\x89\x87',
                                 'target': 0,
                                 'normal': False,
                                 'init_value': 0,
                                 'type': sconst.BATTLE_STATISTICS_PVE_ADD_MECHA_DEBRIS,
                                 'method': 'add'
                                 },
   sconst.PVE_SHOP_REFRESH: {'desc': 'PVE\xe5\x95\x86\xe5\xba\x97\xe5\x88\xb7\xe6\x96\xb0',
                             'target': 0,
                             'normal': False,
                             'init_value': 0,
                             'type': sconst.BATTLE_STATISTICS_PVE_SHOP_REFRESH,
                             'method': 'add'
                             },
   sconst.PVE_SHOP_REVIVE_TEAMMATE: {'desc': 'PVE\xe5\x95\x86\xe5\xba\x97\xe5\xa4\x8d\xe6\xb4\xbb\xe9\x98\x9f\xe5\x8f\x8b',
                                     'target': 0,
                                     'normal': False,
                                     'init_value': 0,
                                     'type': sconst.BATTLE_STATISTICS_PVE_SHOP_REVIVE_TEAMMATE,
                                     'method': 'add'
                                     },
   sconst.PVE_MAIN_WEAPON_HIT: {'desc': 'PVE\xe4\xb8\xbb\xe6\xad\xa6\xe5\x99\xa8\xe5\x91\xbd\xe4\xb8\xad',
                                'target': 0,
                                'normal': False,
                                'init_value': 0,
                                'type': sconst.BATTLE_STATISTICS_PVE_MAIN_WEAPON_HIT,
                                'method': 'add'
                                },
   sconst.PVE_SEC_WEAPON_HIT: {'desc': 'PVE\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe5\x91\xbd\xe4\xb8\xad',
                               'target': 0,
                               'normal': False,
                               'init_value': 0,
                               'type': sconst.BATTLE_STATISTICS_PVE_SEC_WEAPON_HIT,
                               'method': 'add'
                               },
   sconst.PVE_MAIN_WEAPON_ELITE_DMG: {'desc': 'PVE\xe4\xb8\xbb\xe6\xad\xa6\xe5\x99\xa8\xe5\xaf\xb9\xe7\xb2\xbe\xe8\x8b\xb1\xe4\xbc\xa4\xe5\xae\xb3',
                                      'target': 0,
                                      'normal': False,
                                      'init_value': 0,
                                      'type': sconst.BATTLE_STATISTICS_PVE_MAIN_WEAPON_ELITE_DMG,
                                      'method': 'add'
                                      },
   sconst.PVE_MAIN_WEAPON_BOSS_DMG: {'desc': 'PVE\xe4\xb8\xbb\xe6\xad\xa6\xe5\x99\xa8\xe5\xaf\xb9boss\xe4\xbc\xa4\xe5\xae\xb3',
                                     'target': 0,
                                     'normal': False,
                                     'init_value': 0,
                                     'type': sconst.BATTLE_STATISTICS_PVE_MAIN_WEAPON_BOSS_DMG,
                                     'method': 'add'
                                     },
   sconst.PVE_SEC_WEAPON_ELITE_DMG: {'desc': 'PVE\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe5\xaf\xb9\xe7\xb2\xbe\xe8\x8b\xb1\xe4\xbc\xa4\xe5\xae\xb3',
                                     'target': 0,
                                     'normal': False,
                                     'init_value': 0,
                                     'type': sconst.BATTLE_STATISTICS_PVE_SEC_WEAPON_ELITE_DMG,
                                     'method': 'add'
                                     },
   sconst.PVE_SEC_WEAPON_BOSS_DMG: {'desc': 'PVE\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe5\xaf\xb9boss\xe4\xbc\xa4\xe5\xae\xb3',
                                    'target': 0,
                                    'normal': False,
                                    'init_value': 0,
                                    'type': sconst.BATTLE_STATISTICS_PVE_SEC_WEAPON_BOSS_DMG,
                                    'method': 'add'
                                    },
   sconst.PVE_KILL_MONSTER_BY_ELEM: {'desc': 'PVE\xe5\x85\x83\xe7\xb4\xa0\xe5\x87\xbb\xe6\x9d\x80\xe6\x80\xaa\xe7\x89\xa9\xe6\x95\xb0\xe9\x87\x8f',
                                     'target': 0,
                                     'normal': False,
                                     'init_value': 0,
                                     'type': sconst.BATTLE_STATISTICS_PVE_KILL_MONSTER_BY_ELEM,
                                     'method': 'add'
                                     },
   sconst.PVE_DMG_BY_ELEM: {'desc': 'PVE\xe5\x85\x83\xe7\xb4\xa0\xe6\x94\xbb\xe5\x87\xbb\xe9\x80\xa0\xe6\x88\x90\xe4\xbc\xa4\xe5\xae\xb3',
                            'target': 0,
                            'normal': False,
                            'init_value': 0,
                            'type': sconst.BATTLE_STATISTICS_PVE_DMG_BY_ELEM,
                            'method': 'add'
                            },
   sconst.DO_JUMP_SKILL: {'desc': '\xe9\x87\x8a\xe6\x94\xbe\xe8\xb7\xb3\xe8\xb7\x83\xe5\x9e\x8b\xe6\x8a\x80\xe8\x83\xbd',
                          'target': 0,
                          'normal': False,
                          'init_value': 0,
                          'type': sconst.BATTLE_STATISTICS_DO_JUMP_SKILL,
                          'method': 'add'
                          },
   sconst.KILL_MONSTER_IN_AIR: {'desc': '\xe5\x9c\xa8\xe7\xa9\xba\xe4\xb8\xad\xe5\x87\xbb\xe6\x9d\x80\xe6\x80\xaa\xe7\x89\xa9',
                                'target': 0,
                                'normal': False,
                                'init_value': 0,
                                'type': sconst.BATTLE_STATISTICS_KILL_MONSTER_IN_AIR,
                                'method': 'add'
                                },
   sconst.MISS_OPEN_BOX: {'desc': 'PVE\xe9\x94\x99\xe8\xbf\x87\xe5\xbc\x80\xe5\xae\x9d\xe7\xae\xb1',
                          'target': 0,
                          'normal': False,
                          'init_value': 0,
                          'type': sconst.BATTLE_STATISTICS_MISS_OPEN_BOX,
                          'method': 'add'
                          },
   sconst.PVE_KILLED_BY_BOSS: {'desc': 'PVE\xe8\xa2\xabboss\xe5\x87\xbb\xe8\xb4\xa5',
                               'target': 0,
                               'normal': False,
                               'init_value': 0,
                               'type': sconst.BATTLE_STATISTICS_PVE_KILLED_BY_BOSS,
                               'method': 'add'
                               },
   sconst.DO_DASH_SKILL: {'desc': '\xe9\x87\x8a\xe6\x94\xbe\xe5\x86\xb2\xe5\x88\xba\xe6\x8a\x80\xe8\x83\xbd',
                          'target': 0,
                          'normal': False,
                          'init_value': 0,
                          'type': sconst.BATTLE_STATISTICS_DO_DASH_SKILL,
                          'method': 'add'
                          },
   sconst.ASSIST_KILL_MONSTER: {'desc': '\xe5\x8a\xa9\xe6\x94\xbb\xe5\x87\xbb\xe6\x9d\x80\xe6\x80\xaa\xe7\x89\xa9',
                                'target': 0,
                                'normal': False,
                                'init_value': {},'type': sconst.BATTLE_STATISTICS_ASSIST_KILL_MONSTER,
                                'method': 'uda'
                                },
   sconst.PVE_SELL_BLESSES: {'desc': 'PVE\xe5\x87\xba\xe5\x94\xae\xe7\x9a\x84\xe7\xa5\x9d\xe7\xa6\x8f',
                             'target': 0,
                             'normal': False,
                             'init_value': {},'type': sconst.BATTLE_STATISTICS_PVE_SELL_BLESSES,
                             'method': 'uda'
                             },
   sconst.PVE_DONATE_BLESSES: {'desc': 'PVE\xe6\x8d\x90\xe8\xb5\xa0\xe7\x9a\x84\xe7\xa5\x9d\xe7\xa6\x8f',
                               'target': 0,
                               'normal': False,
                               'init_value': {},'type': sconst.BATTLE_STATISTICS_PVE_DONATE_BLESSES,
                               'method': 'uda'
                               },
   sconst.PVE_ELEMENT_DAMAGE: {'desc': 'PVE\xe5\x85\x83\xe7\xb4\xa0\xe4\xbc\xa4\xe5\xae\xb3',
                               'target': 0,
                               'normal': False,
                               'init_value': {},'type': sconst.BATTLE_STATISTICS_PVE_ELEMENT_DAMAGE,
                               'method': 'uda'
                               },
   sconst.ASSIST_KILL_MONSTER_BY_ID: {'desc': '\xe5\x8a\xa9\xe6\x94\xbb\xe5\x87\xbb\xe6\x9d\x80\xe6\x80\xaa\xe7\x89\xa9(\xe8\xaf\xa6\xe7\xbb\x86id)',
                                      'target': 0,
                                      'normal': False,
                                      'init_value': {},'type': sconst.BATTLE_STATISTICS_ASSIST_KILL_MONSTER_BY_ID,
                                      'method': 'uda'
                                      },
   sconst.KILL_HUMAN_CNT: {'desc': '\xe5\x87\xbb\xe6\x9d\x80\xe5\xb0\x8f\xe4\xba\xba\xe8\xae\xa1\xe6\x95\xb0',
                           'target': 0,
                           'normal': False,
                           'init_value': 0,
                           'type': sconst.BATTLE_STATISTICS_KILL_HUMAN_CNT,
                           'method': 'uda'
                           },
   sconst.LAND_KILL_TIME: {'desc': '\xe7\x9d\x80\xe9\x99\x86\xe5\x90\x8e\xe9\xa6\x96\xe6\xac\xa1\xe6\xb7\x98\xe6\xb1\xb0\xe6\x97\xb6\xe9\x97\xb4',
                           'target': 0,
                           'normal': False,
                           'init_value': 0,
                           'type': sconst.BATTLE_STATISTICS_LAND_KILL_TIME,
                           'method': 'min'
                           },
   sconst.MAX_COMBO_KILL: {'desc': '\xe6\x9c\x80\xe5\xa4\xa7\xe8\xbf\x9e\xe6\x9d\x80\xe6\x95\xb0',
                           'target': 0,
                           'normal': False,
                           'init_value': 0,
                           'type': sconst.BATTLE_STATISTICS_MAX_COMBO_KILL,
                           'method': 'max'
                           },
   sconst.KILL_HUMAN_ON_MOTORCYCLE: {'desc': '\xe6\x91\xa9\xe7\x9a\x84\xe4\xb8\x8a\xe6\xb7\x98\xe6\xb1\xb0',
                                     'target': 0,
                                     'normal': False,
                                     'init_value': 0,
                                     'type': sconst.BATTLE_STATISTICS_KILL_HUMAN_ON_MOTORCYCLE,
                                     'method': 'add'
                                     },
   sconst.PVE_BREAKTHROUGH_MAX: {'desc': 'PVE\xe7\xaa\x81\xe7\xa0\xb4\xe5\x8d\x87\xe6\xbb\xa1\xe6\xac\xa1\xe6\x95\xb0',
                                 'target': 0,
                                 'normal': False,
                                 'init_value': 0,
                                 'type': sconst.BATTLE_STATISTICS_PVE_BREAKTHROUGH_MAX,
                                 'method': 'add'
                                 },
   sconst.WEAPON_KILL_MONSTER_TYPE: {'desc': '\xe6\xad\xa6\xe5\x99\xa8\xe5\x87\xbb\xe6\x9d\x80\xe5\x90\x84\xe7\xb1\xbb\xe5\x9e\x8b\xe6\x80\xaa\xe7\x89\xa9',
                                     'target': 0,
                                     'normal': False,
                                     'init_value': {},'type': sconst.BATTLE_STATISTICS_WEAPON_KILL_MONSTER_TYPE,
                                     'method': 'ududa'
                                     }
   }
from logic.gcommon.common_const.battle_const import PLAY_TYPE_CHICKEN, PLAY_TYPE_DEATH
import six
refresh_info = {PLAY_TYPE_CHICKEN: {'human': [],'mecha': []},PLAY_TYPE_DEATH: {'human': [],'mecha': []}}

def get_battle_statistics_type(prop):
    return data.get(prop, {}).get('type', None)


for sid, sinfo in six.iteritems(data):
    if 'human' in sinfo.get('death_mode_refresh', []):
        refresh_info[PLAY_TYPE_DEATH]['human'].append(sid)
    if 'mecha' in sinfo.get('death_mode_refresh', []):
        refresh_info[PLAY_TYPE_DEATH]['mecha'].append(sid)
    if 'human' in sinfo.get('survival_mode_refresh', []):
        refresh_info[PLAY_TYPE_CHICKEN]['human'].append(sid)
    if 'mecha' in sinfo.get('survival_mode_refresh', []):
        refresh_info[PLAY_TYPE_CHICKEN]['mecha'].append(sid)

def get_human_die_refresh_list(play_type):
    return refresh_info.get(play_type, {}).get('human', [])


def get_mecha_die_refresh_list(play_type):
    return refresh_info.get(play_type, {}).get('mecha', [])


def get_battle_statistics_init_value(stat_key):
    return data.get(stat_key, {}).get('init_value', None)


if G_IS_SERVER:
    from data.task import task_template
    ALL_SETTLE_PROPS = sconst.SETTLE_PROPS.union(task_template.task_props)