# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/data/mecha_sens_preset_cfg.py
_reload_all = True
cfg = {1: {'sst_scr': 0.72,
       'sst_scr_pc': 0.72,
       'gyroscope_scr': 0.81,
       'shoot_stick_switch': True,
       'main_weapon_stick': 0.684,
       'sub_weapon_stick': 0.684,
       'scope_sst_scr': 0.612,
       'scope_sst_scr_pc': 0.612,
       'scope_gyroscope_scr': 0.54,
       'scope_shoot_stick_switch': True,
       'scope_main_weapon_stick': 0.684,
       'scope_sub_weapon_stick': 0.684,
       'sp_form_sst_scr': 0.72,
       'sp_form_sst_scr_pc': 0.72,
       'sp_form_gyroscope_scr': 0.81,
       'sp_form_shoot_stick_switch': True,
       'sp_form_main_weapon_stick': 0.684,
       'sp_form_sub_weapon_stick': 0.684
       },
   2: {'sst_scr': 1.17,
       'sst_scr_pc': 1.17,
       'gyroscope_scr': 1.125,
       'shoot_stick_switch': True,
       'main_weapon_stick': 1.125,
       'sub_weapon_stick': 1.125,
       'scope_sst_scr': 0.99,
       'scope_sst_scr_pc': 0.99,
       'scope_gyroscope_scr': 0.9,
       'scope_shoot_stick_switch': True,
       'scope_main_weapon_stick': 1.125,
       'scope_sub_weapon_stick': 1.125,
       'sp_form_sst_scr': 1.17,
       'sp_form_sst_scr_pc': 1.17,
       'sp_form_gyroscope_scr': 1.125,
       'sp_form_shoot_stick_switch': True,
       'sp_form_main_weapon_stick': 1.125,
       'sp_form_sub_weapon_stick': 1.125
       },
   3: {'sst_scr': 1.71,
       'sst_scr_pc': 1.71,
       'gyroscope_scr': 1.53,
       'shoot_stick_switch': True,
       'main_weapon_stick': 1.62,
       'sub_weapon_stick': 1.62,
       'scope_sst_scr': 1.44,
       'scope_sst_scr_pc': 1.44,
       'scope_gyroscope_scr': 1.35,
       'scope_shoot_stick_switch': True,
       'scope_main_weapon_stick': 1.62,
       'scope_sub_weapon_stick': 1.62,
       'sp_form_sst_scr': 1.71,
       'sp_form_sst_scr_pc': 1.71,
       'sp_form_gyroscope_scr': 1.53,
       'sp_form_shoot_stick_switch': True,
       'sp_form_main_weapon_stick': 1.62,
       'sp_form_sub_weapon_stick': 1.62
       }
   }