# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/data/weapon_action_config.py
_reload_all = True

def convert_to_list--- This code section failed: ---

   9       0  BUILD_LIST_0          0 
           3  STORE_FAST            1  'anim_list'

  10       6  LOAD_FAST             0  'desc'
           9  POP_JUMP_IF_TRUE     16  'to 16'

  11      12  LOAD_FAST             1  'anim_list'
          15  RETURN_END_IF    
        16_0  COME_FROM                '9'

  13      16  LOAD_FAST             0  'desc'
          19  LOAD_ATTR             0  'find'
          22  LOAD_CONST            1  ','
          25  CALL_FUNCTION_1       1 
          28  LOAD_CONST            2  ''
          31  COMPARE_OP            5  '>='
          34  POP_JUMP_IF_FALSE   437  'to 437'

  14      37  LOAD_FAST             0  'desc'
          40  LOAD_ATTR             1  'split'
          43  LOAD_CONST            1  ','
          46  CALL_FUNCTION_1       1 
          49  STORE_FAST            2  'old_anim_list'

  15      52  LOAD_FAST             2  'old_anim_list'
          55  LOAD_CONST            2  ''
          58  BINARY_SUBSCR    
          59  LOAD_ATTR             2  'isdigit'
          62  CALL_FUNCTION_0       0 
          65  POP_JUMP_IF_FALSE   428  'to 428'

  16      68  LOAD_GLOBAL           3  'int'
          71  LOAD_FAST             2  'old_anim_list'
          74  LOAD_CONST            2  ''
          77  BINARY_SUBSCR    
          78  CALL_FUNCTION_1       1 
          81  STORE_FAST            3  'anim_len'

  17      84  LOAD_FAST             2  'old_anim_list'
          87  LOAD_CONST            3  1
          90  BINARY_SUBSCR    
          91  STORE_FAST            4  'action_name'

  18      94  LOAD_CONST            4  ''
          97  STORE_FAST            5  'ori_postfix'

  19     100  LOAD_GLOBAL           4  'len'
         103  LOAD_FAST             2  'old_anim_list'
         106  CALL_FUNCTION_1       1 
         109  LOAD_CONST            5  2
         112  COMPARE_OP            4  '>'
         115  POP_JUMP_IF_FALSE   131  'to 131'

  20     118  LOAD_FAST             2  'old_anim_list'
         121  LOAD_CONST            5  2
         124  BINARY_SUBSCR    
         125  STORE_FAST            5  'ori_postfix'
         128  JUMP_FORWARD          0  'to 131'
       131_0  COME_FROM                '128'

  22     131  LOAD_FAST             3  'anim_len'
         134  LOAD_CONST            5  2
         137  COMPARE_OP            2  '=='
         140  POP_JUMP_IF_FALSE   176  'to 176'

  23     143  LOAD_FAST             1  'anim_list'
         146  LOAD_ATTR             5  'append'
         149  LOAD_FAST             4  'action_name'
         152  LOAD_CONST            6  '_f'
         155  BINARY_ADD       
         156  CALL_FUNCTION_1       1 
         159  POP_TOP          

  24     160  LOAD_FAST             1  'anim_list'
         163  LOAD_ATTR             5  'append'
         166  LOAD_FAST             4  'action_name'
         169  CALL_FUNCTION_1       1 
         172  POP_TOP          
         173  JUMP_ABSOLUTE       434  'to 434'

  25     176  LOAD_FAST             3  'anim_len'
         179  LOAD_CONST            7  5
         182  COMPARE_OP            1  '<='
         185  POP_JUMP_IF_FALSE   291  'to 291'

  26     188  LOAD_FAST             1  'anim_list'
         191  LOAD_ATTR             5  'append'
         194  LOAD_FAST             4  'action_name'
         197  LOAD_CONST            8  '_l'
         200  BINARY_ADD       
         201  CALL_FUNCTION_1       1 
         204  POP_TOP          

  27     205  LOAD_FAST             1  'anim_list'
         208  LOAD_ATTR             5  'append'
         211  LOAD_FAST             4  'action_name'
         214  LOAD_CONST            9  '_r'
         217  BINARY_ADD       
         218  CALL_FUNCTION_1       1 
         221  POP_TOP          

  28     222  LOAD_FAST             1  'anim_list'
         225  LOAD_ATTR             5  'append'
         228  LOAD_FAST             4  'action_name'
         231  LOAD_CONST            6  '_f'
         234  BINARY_ADD       
         235  CALL_FUNCTION_1       1 
         238  POP_TOP          

  29     239  LOAD_FAST             1  'anim_list'
         242  LOAD_ATTR             5  'append'
         245  LOAD_FAST             4  'action_name'
         248  LOAD_CONST           10  '_b'
         251  BINARY_ADD       
         252  CALL_FUNCTION_1       1 
         255  POP_TOP          

  30     256  LOAD_FAST             3  'anim_len'
         259  LOAD_CONST            7  5
         262  COMPARE_OP            2  '=='
         265  POP_JUMP_IF_FALSE   425  'to 425'

  31     268  LOAD_FAST             1  'anim_list'
         271  LOAD_ATTR             5  'append'
         274  LOAD_FAST             4  'action_name'
         277  LOAD_FAST             5  'ori_postfix'
         280  BINARY_ADD       
         281  CALL_FUNCTION_1       1 
         284  POP_TOP          
         285  JUMP_ABSOLUTE       425  'to 425'
         288  JUMP_ABSOLUTE       434  'to 434'

  33     291  LOAD_FAST             1  'anim_list'
         294  LOAD_ATTR             5  'append'
         297  LOAD_FAST             4  'action_name'
         300  LOAD_CONST           11  '_fl'
         303  BINARY_ADD       
         304  CALL_FUNCTION_1       1 
         307  POP_TOP          

  34     308  LOAD_FAST             1  'anim_list'
         311  LOAD_ATTR             5  'append'
         314  LOAD_FAST             4  'action_name'
         317  LOAD_CONST           12  '_fr'
         320  BINARY_ADD       
         321  CALL_FUNCTION_1       1 
         324  POP_TOP          

  35     325  LOAD_FAST             1  'anim_list'
         328  LOAD_ATTR             5  'append'
         331  LOAD_FAST             4  'action_name'
         334  LOAD_CONST            6  '_f'
         337  BINARY_ADD       
         338  CALL_FUNCTION_1       1 
         341  POP_TOP          

  36     342  LOAD_FAST             1  'anim_list'
         345  LOAD_ATTR             5  'append'
         348  LOAD_FAST             4  'action_name'
         351  LOAD_CONST           13  '_bl'
         354  BINARY_ADD       
         355  CALL_FUNCTION_1       1 
         358  POP_TOP          

  37     359  LOAD_FAST             1  'anim_list'
         362  LOAD_ATTR             5  'append'
         365  LOAD_FAST             4  'action_name'
         368  LOAD_CONST           14  '_br'
         371  BINARY_ADD       
         372  CALL_FUNCTION_1       1 
         375  POP_TOP          

  38     376  LOAD_FAST             1  'anim_list'
         379  LOAD_ATTR             5  'append'
         382  LOAD_FAST             4  'action_name'
         385  LOAD_CONST           10  '_b'
         388  BINARY_ADD       
         389  CALL_FUNCTION_1       1 
         392  POP_TOP          

  39     393  LOAD_FAST             3  'anim_len'
         396  LOAD_CONST           15  7
         399  COMPARE_OP            2  '=='
         402  POP_JUMP_IF_FALSE   434  'to 434'

  40     405  LOAD_FAST             1  'anim_list'
         408  LOAD_ATTR             5  'append'
         411  LOAD_FAST             4  'action_name'
         414  LOAD_FAST             5  'ori_postfix'
         417  BINARY_ADD       
         418  CALL_FUNCTION_1       1 
         421  POP_TOP          
         422  JUMP_ABSOLUTE       434  'to 434'
         425  JUMP_ABSOLUTE       462  'to 462'

  42     428  LOAD_FAST             2  'old_anim_list'
         431  STORE_FAST            1  'anim_list'
         434  JUMP_FORWARD         25  'to 462'

  44     437  JUMP_FORWARD          4  'to 444'
         440  COMPARE_OP            3  '!='
         443  POP_JUMP_IF_FALSE   462  'to 462'

  45     446  LOAD_FAST             1  'anim_list'
         449  LOAD_ATTR             5  'append'
         452  LOAD_FAST             0  'desc'
         455  CALL_FUNCTION_1       1 
         458  POP_TOP          
         459  JUMP_FORWARD          0  'to 462'
       462_0  COME_FROM                '459'
       462_1  COME_FROM                '434'

  47     462  LOAD_GLOBAL           6  'tuple'
         465  LOAD_FAST             1  'anim_list'
         468  CALL_FUNCTION_1       1 
         471  RETURN_VALUE     
          -1  RETURN_LAST      

Parse error at or near `COMPARE_OP' instruction at offset 440


weapon_type_2_action = {-1: {'get_new_gun': convert_to_list(''),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list(''),
        'crouch_get_new_gun': convert_to_list(''),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list(''),
        'skate_first_reload': convert_to_list(''),
        'crouch_first_reload': convert_to_list(''),
        'fire': convert_to_list(''),
        'fire_1': convert_to_list(''),
        'skate_fire': convert_to_list(''),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list(''),
        'crouch_fire_1': convert_to_list(''),
        'jump_fire': convert_to_list(''),
        'jump_fire_1': convert_to_list(''),
        'skate_jump_fire': convert_to_list(''),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list(''),
        'skate_idle': convert_to_list(''),
        'aim_idle': convert_to_list(''),
        'skate_aim_idle': convert_to_list(''),
        'crouch_idle': convert_to_list(''),
        'aim_crouch_idle': convert_to_list(''),
        'stand_move': convert_to_list(''),
        'skate_stand_move': convert_to_list(''),
        'stand_shoot_move': convert_to_list('6,s_ak_aim'),
        'skate_stand_shoot_move': convert_to_list(''),
        'run_stage_2': convert_to_list(''),
        'run_stage_3': convert_to_list(''),
        'run_2_stand_stage': convert_to_list(''),
        'squat_move': convert_to_list(''),
        'squat_run': convert_to_list(''),
        'roll': convert_to_list(''),
        'rush': convert_to_list(''),
        'use_item': convert_to_list(''),
        'use_bandage': convert_to_list(''),
        'cure': convert_to_list(''),
        'jump_stage_1': convert_to_list(''),
        'jump_high': convert_to_list(''),
        'jump_stage_2': convert_to_list(''),
        'jump_stage_3': convert_to_list(''),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list(''),
        'run_jump_stage_2': convert_to_list(''),
        'run_jump_stage_3': convert_to_list(''),
        'run_jump_stage_3_large': convert_to_list(''),
        'hit': convert_to_list(''),
        'skate_brake': convert_to_list(''),
        'skate_prepare_move': convert_to_list(''),
        'skate_leave': convert_to_list(''),
        'skate_board': convert_to_list('')
        },
   0: {'get_new_gun': convert_to_list(''),'is_two_hand': 0,
       'switch_gun_mode': convert_to_list(''),
       'skate_get_new_gun': convert_to_list(''),
       'crouch_get_new_gun': convert_to_list(''),
       'crouch_switch_gun_mode': convert_to_list(''),
       'gun_load': convert_to_list(''),
       'skate_gun_load': convert_to_list(''),
       'crouch_gun_load': convert_to_list(''),
       'first_reload': convert_to_list(''),
       'skate_first_reload': convert_to_list(''),
       'crouch_first_reload': convert_to_list(''),
       'fire': convert_to_list(''),
       'fire_1': convert_to_list(''),
       'skate_fire': convert_to_list(''),
       'skate_fire_1': convert_to_list(''),
       'crouch_fire': convert_to_list(''),
       'crouch_fire_1': convert_to_list(''),
       'jump_fire': convert_to_list(''),
       'jump_fire_1': convert_to_list(''),
       'skate_jump_fire': convert_to_list(''),
       'skate_jump_fire_1': convert_to_list(''),
       'idle': convert_to_list('s_emptyhand_idle'),
       'skate_idle': convert_to_list(''),
       'aim_idle': convert_to_list('s_emptyhand_idle'),
       'skate_aim_idle': convert_to_list(''),
       'crouch_idle': convert_to_list('c_emptyhand_idle'),
       'aim_crouch_idle': convert_to_list('c_emptyhand_idle'),
       'stand_move': convert_to_list('6,emptyhand_move'),
       'skate_stand_move': convert_to_list(''),
       'stand_shoot_move': convert_to_list(''),
       'skate_stand_shoot_move': convert_to_list(''),
       'run_stage_2': convert_to_list('emptyhand_run_start'),
       'run_stage_3': convert_to_list('emptyhand_run'),
       'run_2_stand_stage': convert_to_list('emptyhand_run_stop'),
       'squat_move': convert_to_list('c_ak_stop_f'),
       'squat_run': convert_to_list('emptyhand_run'),
       'roll': convert_to_list('4,emptyhand_roll'),
       'rush': convert_to_list(''),
       'use_item': convert_to_list(''),
       'use_bandage': convert_to_list(''),
       'cure': convert_to_list(''),
       'jump_stage_1': convert_to_list('4,emptyhand_jump_01'),
       'jump_high': convert_to_list('ak_high_jump_01'),
       'jump_stage_2': convert_to_list('4,emptyhand_jump_02'),
       'jump_stage_3': convert_to_list('4,emptyhand_jump_03'),
       'jump_stage_3_large': convert_to_list(''),
       'run_jump_stage_1': convert_to_list('run_jump_01_emptyhand'),
       'run_jump_stage_2': convert_to_list('run_jump_02_emptyhand'),
       'run_jump_stage_3': convert_to_list('run_jump_03_emptyhand'),
       'run_jump_stage_3_large': convert_to_list('ground'),
       'hit': convert_to_list('hit_emptyhand'),
       'skate_brake': convert_to_list(''),
       'skate_prepare_move': convert_to_list(''),
       'skate_leave': convert_to_list(''),
       'skate_board': convert_to_list('')
       },
   2: {'get_new_gun': convert_to_list('7,s_shield_change'),'is_two_hand': 1,
       'switch_gun_mode': convert_to_list(''),
       'skate_get_new_gun': convert_to_list('7,skate_shield_change'),
       'crouch_get_new_gun': convert_to_list('2,c_shield_change'),
       'crouch_switch_gun_mode': convert_to_list(''),
       'gun_load': convert_to_list('7,s_shield_load'),
       'skate_gun_load': convert_to_list('7,skate_shield_load'),
       'crouch_gun_load': convert_to_list('2,c_shield_load'),
       'first_reload': convert_to_list('7,s_shield_reload'),
       'skate_first_reload': convert_to_list('7,skate_shield_reload'),
       'crouch_first_reload': convert_to_list('2,c_shield_reload'),
       'fire': convert_to_list('7,s_shield_shoot'),
       'fire_1': convert_to_list(''),
       'skate_fire': convert_to_list('7,skate_shield_shoot'),
       'skate_fire_1': convert_to_list(''),
       'crouch_fire': convert_to_list('c_shield_shoot'),
       'crouch_fire_1': convert_to_list(''),
       'jump_fire': convert_to_list('s_shield_shoot'),
       'jump_fire_1': convert_to_list(''),
       'skate_jump_fire': convert_to_list('7,skate_shield_shoot'),
       'skate_jump_fire_1': convert_to_list(''),
       'idle': convert_to_list('s_shield_stop'),
       'skate_idle': convert_to_list('skate_shield_stand_idle'),
       'aim_idle': convert_to_list('s_shield_aim'),
       'skate_aim_idle': convert_to_list('skate_shield_aim'),
       'crouch_idle': convert_to_list('c_shield_stop'),
       'aim_crouch_idle': convert_to_list('2,c_shield_aim'),
       'stand_move': convert_to_list('6,s_shield_move'),
       'skate_stand_move': convert_to_list('6,skate_shield_move'),
       'stand_shoot_move': convert_to_list('6,s_shield_aim'),
       'skate_stand_shoot_move': convert_to_list('6,skate_shield_aim'),
       'run_stage_2': convert_to_list('shield_run_start'),
       'run_stage_3': convert_to_list('s_shield_run'),
       'run_2_stand_stage': convert_to_list('shield_run_stop'),
       'squat_move': convert_to_list('c_shield_stop_f'),
       'squat_run': convert_to_list('c_shield_run'),
       'roll': convert_to_list('4,shield_roll'),
       'rush': convert_to_list(''),
       'use_item': convert_to_list(''),
       'use_bandage': convert_to_list(''),
       'cure': convert_to_list(''),
       'jump_stage_1': convert_to_list('shield_jump_01'),
       'jump_high': convert_to_list('shield_high_jump_01'),
       'jump_stage_2': convert_to_list('shield_jump_02'),
       'jump_stage_3': convert_to_list('shield_jump_03'),
       'jump_stage_3_large': convert_to_list(''),
       'run_jump_stage_1': convert_to_list(''),
       'run_jump_stage_2': convert_to_list(''),
       'run_jump_stage_3': convert_to_list(''),
       'run_jump_stage_3_large': convert_to_list(''),
       'hit': convert_to_list(''),
       'skate_brake': convert_to_list('skate_shield_f_brake'),
       'skate_prepare_move': convert_to_list('skate_shield_f_start'),
       'skate_leave': convert_to_list('skate_shield_leave'),
       'skate_board': convert_to_list('skate_shield_board')
       },
   3: {'get_new_gun': convert_to_list('7,s_flamer_change'),'is_two_hand': 0,
       'switch_gun_mode': convert_to_list(''),
       'skate_get_new_gun': convert_to_list('7,skate_flamer_change'),
       'crouch_get_new_gun': convert_to_list('2,c_flamer_change'),
       'crouch_switch_gun_mode': convert_to_list(''),
       'gun_load': convert_to_list(''),
       'skate_gun_load': convert_to_list(''),
       'crouch_gun_load': convert_to_list(''),
       'first_reload': convert_to_list('7,s_flamer_reload'),
       'skate_first_reload': convert_to_list('7,skate_flamer_reload'),
       'crouch_first_reload': convert_to_list('c_flamer_reload'),
       'fire': convert_to_list('7,s_flamer_shoot'),
       'fire_1': convert_to_list(''),
       'skate_fire': convert_to_list('7,skate_flamer_shoot'),
       'skate_fire_1': convert_to_list(''),
       'crouch_fire': convert_to_list('c_flamer_shoot'),
       'crouch_fire_1': convert_to_list(''),
       'jump_fire': convert_to_list('s_flamer_shoot'),
       'jump_fire_1': convert_to_list(''),
       'skate_jump_fire': convert_to_list('7,skate_flamer_shoot'),
       'skate_jump_fire_1': convert_to_list(''),
       'idle': convert_to_list('s_flamer_stop'),
       'skate_idle': convert_to_list('skate_flamer_stand_idle'),
       'aim_idle': convert_to_list('s_flamer_aim'),
       'skate_aim_idle': convert_to_list('skate_flamer_aim'),
       'crouch_idle': convert_to_list('c_flamer_stop'),
       'aim_crouch_idle': convert_to_list('c_flamer_aim'),
       'stand_move': convert_to_list('6,s_flamer_move'),
       'skate_stand_move': convert_to_list('6,skate_flamer_move'),
       'stand_shoot_move': convert_to_list('6,s_flamer_aim'),
       'skate_stand_shoot_move': convert_to_list('6,skate_flamer_aim'),
       'run_stage_2': convert_to_list('flamer_run_start'),
       'run_stage_3': convert_to_list('s_flamer_run'),
       'run_2_stand_stage': convert_to_list('flamer_run_stop'),
       'squat_move': convert_to_list('c_flamer_stop_f'),
       'squat_run': convert_to_list('c_flamer_run'),
       'roll': convert_to_list('4,flamer_roll'),
       'rush': convert_to_list(''),
       'use_item': convert_to_list(''),
       'use_bandage': convert_to_list(''),
       'cure': convert_to_list(''),
       'jump_stage_1': convert_to_list('flamer_jump_01'),
       'jump_high': convert_to_list('flamer_high_jump_01'),
       'jump_stage_2': convert_to_list('flamer_jump_02'),
       'jump_stage_3': convert_to_list('flamer_jump_03'),
       'jump_stage_3_large': convert_to_list(''),
       'run_jump_stage_1': convert_to_list(''),
       'run_jump_stage_2': convert_to_list(''),
       'run_jump_stage_3': convert_to_list(''),
       'run_jump_stage_3_large': convert_to_list(''),
       'hit': convert_to_list(''),
       'skate_brake': convert_to_list('skate_flamer_f_brake'),
       'skate_prepare_move': convert_to_list('skate_flamer_f_start'),
       'skate_leave': convert_to_list('skate_flamer_leave'),
       'skate_board': convert_to_list('skate_flamer_board')
       },
   4: {'get_new_gun': convert_to_list('7,s_snipe_change'),'is_two_hand': 0,
       'switch_gun_mode': convert_to_list(''),
       'skate_get_new_gun': convert_to_list('7,skate_snipe_change'),
       'crouch_get_new_gun': convert_to_list('2,c_snipe_change'),
       'crouch_switch_gun_mode': convert_to_list(''),
       'gun_load': convert_to_list('7,s_snipe_load'),
       'skate_gun_load': convert_to_list('7,skate_snipe_load'),
       'crouch_gun_load': convert_to_list('c_snipe_load'),
       'first_reload': convert_to_list('7,s_snipe_reload'),
       'skate_first_reload': convert_to_list('7,skate_snipe_reload'),
       'crouch_first_reload': convert_to_list('c_snipe_reload'),
       'fire': convert_to_list('7,s_snipe_shoot'),
       'fire_1': convert_to_list(''),
       'skate_fire': convert_to_list('7,skate_snipe_shoot'),
       'skate_fire_1': convert_to_list(''),
       'crouch_fire': convert_to_list('c_snipe_shoot'),
       'crouch_fire_1': convert_to_list(''),
       'jump_fire': convert_to_list('s_snipe_shoot'),
       'jump_fire_1': convert_to_list(''),
       'skate_jump_fire': convert_to_list('7,skate_snipe_shoot'),
       'skate_jump_fire_1': convert_to_list(''),
       'idle': convert_to_list('s_snipe_stop'),
       'skate_idle': convert_to_list('skate_snipe_stand_idle'),
       'aim_idle': convert_to_list('s_snipe_aim'),
       'skate_aim_idle': convert_to_list('skate_snipe_aim'),
       'crouch_idle': convert_to_list('c_snipe_stop'),
       'aim_crouch_idle': convert_to_list('c_snipe_aim'),
       'stand_move': convert_to_list('6,s_snipe_move'),
       'skate_stand_move': convert_to_list('6,skate_snipe_move'),
       'stand_shoot_move': convert_to_list('6,s_snipe_aim'),
       'skate_stand_shoot_move': convert_to_list('6,skate_snipe_aim'),
       'run_stage_2': convert_to_list('snipe_run_start'),
       'run_stage_3': convert_to_list('s_snipe_run'),
       'run_2_stand_stage': convert_to_list(''),
       'squat_move': convert_to_list('c_snipe_stop_f'),
       'squat_run': convert_to_list('c_snipe_run'),
       'roll': convert_to_list(''),
       'rush': convert_to_list(''),
       'use_item': convert_to_list(''),
       'use_bandage': convert_to_list(''),
       'cure': convert_to_list(''),
       'jump_stage_1': convert_to_list(''),
       'jump_high': convert_to_list(''),
       'jump_stage_2': convert_to_list(''),
       'jump_stage_3': convert_to_list(''),
       'jump_stage_3_large': convert_to_list(''),
       'run_jump_stage_1': convert_to_list(''),
       'run_jump_stage_2': convert_to_list(''),
       'run_jump_stage_3': convert_to_list(''),
       'run_jump_stage_3_large': convert_to_list(''),
       'hit': convert_to_list(''),
       'skate_brake': convert_to_list('skate_snipe_f_brake'),
       'skate_prepare_move': convert_to_list('skate_snipe_f_start'),
       'skate_leave': convert_to_list('skate_snipe_leave'),
       'skate_board': convert_to_list('')
       },
   5: {'get_new_gun': convert_to_list('7,s_mgl_change'),'is_two_hand': 0,
       'switch_gun_mode': convert_to_list(''),
       'skate_get_new_gun': convert_to_list('7,skate_mgl_change'),
       'crouch_get_new_gun': convert_to_list('2,c_mgl_change'),
       'crouch_switch_gun_mode': convert_to_list(''),
       'gun_load': convert_to_list(''),
       'skate_gun_load': convert_to_list(''),
       'crouch_gun_load': convert_to_list(''),
       'first_reload': convert_to_list('7,s_mgl_reload'),
       'skate_first_reload': convert_to_list('7,skate_mgl_reload'),
       'crouch_first_reload': convert_to_list('2,c_mgl_reload'),
       'fire': convert_to_list('7,s_mgl_shoot'),
       'fire_1': convert_to_list(''),
       'skate_fire': convert_to_list('7,skate_mgl_shoot'),
       'skate_fire_1': convert_to_list(''),
       'crouch_fire': convert_to_list('2,c_mgl_shoot'),
       'crouch_fire_1': convert_to_list(''),
       'jump_fire': convert_to_list('s_mgl_shoot'),
       'jump_fire_1': convert_to_list(''),
       'skate_jump_fire': convert_to_list('7,skate_mgl_shoot'),
       'skate_jump_fire_1': convert_to_list(''),
       'idle': convert_to_list('s_mgl_stop'),
       'skate_idle': convert_to_list('skate_mgl_stand_idle'),
       'aim_idle': convert_to_list('s_mgl_aim'),
       'skate_aim_idle': convert_to_list('skate_mgl_aim'),
       'crouch_idle': convert_to_list('2,c_mgl_stop'),
       'aim_crouch_idle': convert_to_list('2,c_mgl_aim'),
       'stand_move': convert_to_list('6,s_mgl_move'),
       'skate_stand_move': convert_to_list('6,skate_mgl_move'),
       'stand_shoot_move': convert_to_list('6,s_mgl_aim'),
       'skate_stand_shoot_move': convert_to_list('6,skate_mgl_aim'),
       'run_stage_2': convert_to_list(''),
       'run_stage_3': convert_to_list(''),
       'run_2_stand_stage': convert_to_list('mgl_run_stop'),
       'squat_move': convert_to_list('c_mgl_stop_f'),
       'squat_run': convert_to_list(''),
       'roll': convert_to_list(''),
       'rush': convert_to_list(''),
       'use_item': convert_to_list(''),
       'use_bandage': convert_to_list(''),
       'cure': convert_to_list(''),
       'jump_stage_1': convert_to_list('mgl_jump_01'),
       'jump_high': convert_to_list('mgl_high_jump_01'),
       'jump_stage_2': convert_to_list('mgl_jump_02'),
       'jump_stage_3': convert_to_list('mgl_jump_03'),
       'jump_stage_3_large': convert_to_list(''),
       'run_jump_stage_1': convert_to_list(''),
       'run_jump_stage_2': convert_to_list(''),
       'run_jump_stage_3': convert_to_list(''),
       'run_jump_stage_3_large': convert_to_list(''),
       'hit': convert_to_list(''),
       'skate_brake': convert_to_list('skate_mgl_f_brake'),
       'skate_prepare_move': convert_to_list('skate_mgl_f_start'),
       'skate_leave': convert_to_list('skate_mgl_leave'),
       'skate_board': convert_to_list('skate_mgl_board')
       },
   6: {'get_new_gun': convert_to_list('7,s_bazooka_change'),'is_two_hand': 0,
       'switch_gun_mode': convert_to_list(''),
       'skate_get_new_gun': convert_to_list('7,skate_bazooka_change'),
       'crouch_get_new_gun': convert_to_list('2,c_bazooka_change'),
       'crouch_switch_gun_mode': convert_to_list(''),
       'gun_load': convert_to_list(''),
       'skate_gun_load': convert_to_list(''),
       'crouch_gun_load': convert_to_list(''),
       'first_reload': convert_to_list('7,s_bazooka_reload'),
       'skate_first_reload': convert_to_list('7,skate_bazooka_reload'),
       'crouch_first_reload': convert_to_list('c_bazooka_reload'),
       'fire': convert_to_list('7,s_bazooka_shoot'),
       'fire_1': convert_to_list(''),
       'skate_fire': convert_to_list('7,skate_bazooka_shoot'),
       'skate_fire_1': convert_to_list(''),
       'crouch_fire': convert_to_list('c_bazooka_shoot'),
       'crouch_fire_1': convert_to_list(''),
       'jump_fire': convert_to_list('s_bazooka_shoot'),
       'jump_fire_1': convert_to_list(''),
       'skate_jump_fire': convert_to_list('7,skate_bazooka_shoot'),
       'skate_jump_fire_1': convert_to_list(''),
       'idle': convert_to_list('s_bazooka_stop'),
       'skate_idle': convert_to_list('skate_bazooka_stand_idle'),
       'aim_idle': convert_to_list('s_bazooka_aim'),
       'skate_aim_idle': convert_to_list('skate_bazooka_aim'),
       'crouch_idle': convert_to_list('c_bazooka_stop'),
       'aim_crouch_idle': convert_to_list('c_bazooka_aim'),
       'stand_move': convert_to_list('6,s_bazooka_move'),
       'skate_stand_move': convert_to_list('6,skate_bazooka_move'),
       'stand_shoot_move': convert_to_list('6,s_bazooka_aim'),
       'skate_stand_shoot_move': convert_to_list('6,skate_bazooka_aim'),
       'run_stage_2': convert_to_list('bazooka_run_start'),
       'run_stage_3': convert_to_list('s_bazooka_run'),
       'run_2_stand_stage': convert_to_list('bazooka_run_stop'),
       'squat_move': convert_to_list('c_bazooka_stop_f'),
       'squat_run': convert_to_list('c_bazooka_run'),
       'roll': convert_to_list('4,bazooka_roll'),
       'rush': convert_to_list(''),
       'use_item': convert_to_list(''),
       'use_bandage': convert_to_list(''),
       'cure': convert_to_list(''),
       'jump_stage_1': convert_to_list('bazooka_jump_01'),
       'jump_high': convert_to_list('bazooka_high_jump_01'),
       'jump_stage_2': convert_to_list('bazooka_jump_02'),
       'jump_stage_3': convert_to_list('bazooka_jump_03'),
       'jump_stage_3_large': convert_to_list(''),
       'run_jump_stage_1': convert_to_list(''),
       'run_jump_stage_2': convert_to_list(''),
       'run_jump_stage_3': convert_to_list(''),
       'run_jump_stage_3_large': convert_to_list(''),
       'hit': convert_to_list(''),
       'skate_brake': convert_to_list('skate_bazooka_f_brake'),
       'skate_prepare_move': convert_to_list('skate_bazooka_f_start'),
       'skate_leave': convert_to_list('skate_bazooka_leave'),
       'skate_board': convert_to_list('skate_bazooka_board')
       },
   8: {'get_new_gun': convert_to_list('7,s_double_change'),'is_two_hand': 1,
       'switch_gun_mode': convert_to_list(''),
       'skate_get_new_gun': convert_to_list('7,skate_double_change'),
       'crouch_get_new_gun': convert_to_list('2,c_double_change'),
       'crouch_switch_gun_mode': convert_to_list(''),
       'gun_load': convert_to_list(''),
       'skate_gun_load': convert_to_list(''),
       'crouch_gun_load': convert_to_list(''),
       'first_reload': convert_to_list('7,s_double_reload'),
       'skate_first_reload': convert_to_list('7,skate_double_reload'),
       'crouch_first_reload': convert_to_list('2,c_double_reload'),
       'fire': convert_to_list('7,s_double_shoot'),
       'fire_1': convert_to_list(''),
       'skate_fire': convert_to_list('7,skate_double_shoot'),
       'skate_fire_1': convert_to_list(''),
       'crouch_fire': convert_to_list('2,c_double_shoot'),
       'crouch_fire_1': convert_to_list(''),
       'jump_fire': convert_to_list('s_double_shoot'),
       'jump_fire_1': convert_to_list(''),
       'skate_jump_fire': convert_to_list('7,skate_double_shoot'),
       'skate_jump_fire_1': convert_to_list(''),
       'idle': convert_to_list('s_double_stop'),
       'skate_idle': convert_to_list('skate_double_stand_idle'),
       'aim_idle': convert_to_list('s_double_aim'),
       'skate_aim_idle': convert_to_list('skate_double_aim'),
       'crouch_idle': convert_to_list('2,c_double_stop'),
       'aim_crouch_idle': convert_to_list('2,c_double_aim'),
       'stand_move': convert_to_list('6,s_double_move'),
       'skate_stand_move': convert_to_list('6,skate_double_move'),
       'stand_shoot_move': convert_to_list('6,s_double_aim'),
       'skate_stand_shoot_move': convert_to_list('6,skate_double_aim'),
       'run_stage_2': convert_to_list('double_run_01_start'),
       'run_stage_3': convert_to_list('s_double_run'),
       'run_2_stand_stage': convert_to_list('double_run_stop'),
       'squat_move': convert_to_list('c_double_stop_f'),
       'squat_run': convert_to_list('c_double_run'),
       'roll': convert_to_list(''),
       'rush': convert_to_list(''),
       'use_item': convert_to_list(''),
       'use_bandage': convert_to_list(''),
       'cure': convert_to_list(''),
       'jump_stage_1': convert_to_list('double_jump_01'),
       'jump_high': convert_to_list('double_high_jump_01'),
       'jump_stage_2': convert_to_list('double_jump_02'),
       'jump_stage_3': convert_to_list('double_jump_03'),
       'jump_stage_3_large': convert_to_list(''),
       'run_jump_stage_1': convert_to_list(''),
       'run_jump_stage_2': convert_to_list(''),
       'run_jump_stage_3': convert_to_list(''),
       'run_jump_stage_3_large': convert_to_list(''),
       'hit': convert_to_list(''),
       'skate_brake': convert_to_list('skate_double_f_brake'),
       'skate_prepare_move': convert_to_list('skate_double_f_start'),
       'skate_leave': convert_to_list('skate_double_leave'),
       'skate_board': convert_to_list('skate_double_board')
       },
   9: {'get_new_gun': convert_to_list('7,s_mgl_change'),'is_two_hand': 0,
       'switch_gun_mode': convert_to_list(''),
       'skate_get_new_gun': convert_to_list('7,skate_ak_change'),
       'crouch_get_new_gun': convert_to_list('2,c_mgl_change'),
       'crouch_switch_gun_mode': convert_to_list(''),
       'gun_load': convert_to_list(''),
       'skate_gun_load': convert_to_list(''),
       'crouch_gun_load': convert_to_list(''),
       'first_reload': convert_to_list('7,s_ak_reload'),
       'skate_first_reload': convert_to_list('7,skate_ak_reload'),
       'crouch_first_reload': convert_to_list('2,c_ak_reload'),
       'fire': convert_to_list('7,s_ak_shoot'),
       'fire_1': convert_to_list(''),
       'skate_fire': convert_to_list('7,skate_ak_shoot'),
       'skate_fire_1': convert_to_list(''),
       'crouch_fire': convert_to_list('2,c_ak_shoot'),
       'crouch_fire_1': convert_to_list(''),
       'jump_fire': convert_to_list('s_ak_shoot'),
       'jump_fire_1': convert_to_list(''),
       'skate_jump_fire': convert_to_list('7,skate_ak_shoot'),
       'skate_jump_fire_1': convert_to_list(''),
       'idle': convert_to_list('s_ak_stop'),
       'skate_idle': convert_to_list('skate_ak_stand_idle'),
       'aim_idle': convert_to_list('s_ak_aim'),
       'skate_aim_idle': convert_to_list('skate_ak_aim'),
       'crouch_idle': convert_to_list('2,c_ak_stop'),
       'aim_crouch_idle': convert_to_list('2,c_ak_aim'),
       'stand_move': convert_to_list('6,s_ak_move'),
       'skate_stand_move': convert_to_list('6,skate_ak_move'),
       'stand_shoot_move': convert_to_list('6,s_ak_aim'),
       'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
       'run_stage_2': convert_to_list('ak_run_start'),
       'run_stage_3': convert_to_list('s_ak_run'),
       'run_2_stand_stage': convert_to_list('ak_run_stop'),
       'squat_move': convert_to_list('c_ak_stop_f'),
       'squat_run': convert_to_list('c_ak_run'),
       'roll': convert_to_list('4,takeweapon_roll'),
       'rush': convert_to_list('4,flash'),
       'use_item': convert_to_list('s_bandage'),
       'use_bandage': convert_to_list('s_bandage_true'),
       'cure': convert_to_list('s_cure'),
       'jump_stage_1': convert_to_list(''),
       'jump_high': convert_to_list(''),
       'jump_stage_2': convert_to_list(''),
       'jump_stage_3': convert_to_list(''),
       'jump_stage_3_large': convert_to_list(''),
       'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
       'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
       'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
       'run_jump_stage_3_large': convert_to_list('ground'),
       'hit': convert_to_list('shoot01_hit_a'),
       'skate_brake': convert_to_list(''),
       'skate_prepare_move': convert_to_list(''),
       'skate_leave': convert_to_list(''),
       'skate_board': convert_to_list('')
       },
   10: {'get_new_gun': convert_to_list('7,s_ak_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list('7,s_ak_change'),
        'skate_get_new_gun': convert_to_list('7,skate_ak_change'),
        'crouch_get_new_gun': convert_to_list('2,c_ak_change'),
        'crouch_switch_gun_mode': convert_to_list('2,c_ak_change'),
        'gun_load': convert_to_list('7,s_snipe_load'),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list('2,c_snipe_load'),
        'first_reload': convert_to_list('7,s_ak_reload'),
        'skate_first_reload': convert_to_list('7,skate_ak_reload'),
        'crouch_first_reload': convert_to_list('2,c_ak_reload'),
        'fire': convert_to_list('7,s_ak_shoot'),
        'fire_1': convert_to_list('7,s_ak_shoot'),
        'skate_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_ak_shoot'),
        'crouch_fire_1': convert_to_list('2,c_ak_shoot'),
        'jump_fire': convert_to_list('s_ak_shoot'),
        'jump_fire_1': convert_to_list('s_ak_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_ak_stop'),
        'skate_idle': convert_to_list('skate_ak_stand_idle'),
        'aim_idle': convert_to_list('s_ak_aim'),
        'skate_aim_idle': convert_to_list('skate_ak_aim'),
        'crouch_idle': convert_to_list('2,c_ak_stop'),
        'aim_crouch_idle': convert_to_list('2,c_ak_aim'),
        'stand_move': convert_to_list('6,s_ak_move'),
        'skate_stand_move': convert_to_list('6,skate_ak_move'),
        'stand_shoot_move': convert_to_list('6,s_ak_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
        'run_stage_2': convert_to_list('ak_run_start'),
        'run_stage_3': convert_to_list('s_ak_run'),
        'run_2_stand_stage': convert_to_list('ak_run_stop'),
        'squat_move': convert_to_list('c_ak_stop_f'),
        'squat_run': convert_to_list('c_ak_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list('ak_jump_01'),
        'jump_high': convert_to_list('ak_high_jump_01'),
        'jump_stage_2': convert_to_list('ak_jump_02'),
        'jump_stage_3': convert_to_list('ak_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list('skate_ak_f_brake'),
        'skate_prepare_move': convert_to_list('skate_ak_f_start'),
        'skate_leave': convert_to_list('skate_ak_leave'),
        'skate_board': convert_to_list('skate_ak_board')
        },
   11: {'get_new_gun': convert_to_list('7,s_shotgun_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list('7,skate_shotgun_change'),
        'crouch_get_new_gun': convert_to_list('2,c_shotgun_change'),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list('7,s_shotgun_load'),
        'skate_gun_load': convert_to_list('7,skate_shotgun_load'),
        'crouch_gun_load': convert_to_list('2,c_shotgun_load'),
        'first_reload': convert_to_list('7,s_shotgun_reload'),
        'skate_first_reload': convert_to_list('7,skate_shotgun_reload'),
        'crouch_first_reload': convert_to_list('2,c_shotgun_reload'),
        'fire': convert_to_list('7,s_shotgun_shoot'),
        'fire_1': convert_to_list(''),
        'skate_fire': convert_to_list('7,skate_shotgun_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('c_shotgun_shoot'),
        'crouch_fire_1': convert_to_list(''),
        'jump_fire': convert_to_list('s_shotgun_shoot'),
        'jump_fire_1': convert_to_list(''),
        'skate_jump_fire': convert_to_list('7,skate_shotgun_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_shotgun_stop'),
        'skate_idle': convert_to_list('skate_shotgun_stand_idle'),
        'aim_idle': convert_to_list('s_shotgun_aim'),
        'skate_aim_idle': convert_to_list('skate_shotgun_aim'),
        'crouch_idle': convert_to_list('c_shotgun_stop'),
        'aim_crouch_idle': convert_to_list('2,c_shotgun_aim'),
        'stand_move': convert_to_list('6,s_shotgun_move'),
        'skate_stand_move': convert_to_list('6,skate_shotgun_move'),
        'stand_shoot_move': convert_to_list('6,s_shotgun_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_shotgun_aim'),
        'run_stage_2': convert_to_list('shotgun_run_start'),
        'run_stage_3': convert_to_list('s_shotgun_run'),
        'run_2_stand_stage': convert_to_list('shotgun_run_stop'),
        'squat_move': convert_to_list('c_shotgun_stop_f'),
        'squat_run': convert_to_list('c_shotgun_run'),
        'roll': convert_to_list('4,shotgun_roll'),
        'rush': convert_to_list(''),
        'use_item': convert_to_list(''),
        'use_bandage': convert_to_list(''),
        'cure': convert_to_list(''),
        'jump_stage_1': convert_to_list('shotgun_jump_01'),
        'jump_high': convert_to_list('shotgun_high_jump_01'),
        'jump_stage_2': convert_to_list('shotgun_jump_02'),
        'jump_stage_3': convert_to_list('shotgun_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list(''),
        'run_jump_stage_2': convert_to_list(''),
        'run_jump_stage_3': convert_to_list(''),
        'run_jump_stage_3_large': convert_to_list(''),
        'hit': convert_to_list(''),
        'skate_brake': convert_to_list('skate_shotgun_f_brake'),
        'skate_prepare_move': convert_to_list('skate_shotgun_f_start'),
        'skate_leave': convert_to_list('skate_shotgun_leave'),
        'skate_board': convert_to_list('skate_shotgun_board')
        },
   12: {'get_new_gun': convert_to_list('7,s_pulse_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list('7,skate_ak_change'),
        'crouch_get_new_gun': convert_to_list('2,c_pulse_change'),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list('7,s_pulse_reload'),
        'skate_first_reload': convert_to_list('7,skate_pulse_reload'),
        'crouch_first_reload': convert_to_list('2,c_pulse_reload'),
        'fire': convert_to_list('7,s_pulse_shoot'),
        'fire_1': convert_to_list(''),
        'skate_fire': convert_to_list('7,skate_pulse_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_pulse_shoot'),
        'crouch_fire_1': convert_to_list(''),
        'jump_fire': convert_to_list('s_pulse_shoot'),
        'jump_fire_1': convert_to_list(''),
        'skate_jump_fire': convert_to_list('7,skate_pulse_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_pulse_stop'),
        'skate_idle': convert_to_list('skate_ak_stand_idle'),
        'aim_idle': convert_to_list('s_pulse_aim'),
        'skate_aim_idle': convert_to_list('skate_ak_aim'),
        'crouch_idle': convert_to_list('2,c_pulse_stop'),
        'aim_crouch_idle': convert_to_list('2,c_pulse_aim'),
        'stand_move': convert_to_list('6,s_pulse_move'),
        'skate_stand_move': convert_to_list('6,skate_ak_move'),
        'stand_shoot_move': convert_to_list('6,s_pulse_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
        'run_stage_2': convert_to_list('pulse_run_start'),
        'run_stage_3': convert_to_list('s_pulse_run'),
        'run_2_stand_stage': convert_to_list('pulse_run_stop'),
        'squat_move': convert_to_list('c_pulse_stop_f'),
        'squat_run': convert_to_list('c_pulse_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list(''),
        'jump_high': convert_to_list(''),
        'jump_stage_2': convert_to_list(''),
        'jump_stage_3': convert_to_list(''),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list(''),
        'skate_prepare_move': convert_to_list(''),
        'skate_leave': convert_to_list(''),
        'skate_board': convert_to_list('')
        },
   13: {'get_new_gun': convert_to_list('7,s_double_change'),'is_two_hand': 1,
        'switch_gun_mode': convert_to_list('7,s_frozen_switch'),
        'skate_get_new_gun': convert_to_list('7,skate_frozen_change'),
        'crouch_get_new_gun': convert_to_list('2,c_double_change'),
        'crouch_switch_gun_mode': convert_to_list('2,c_frozen_switch'),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list('7,s_frozen_reload'),
        'skate_first_reload': convert_to_list('7,skate_frozen_reload'),
        'crouch_first_reload': convert_to_list('2,c_frozen_reload'),
        'fire': convert_to_list('7,s_frozen_ball_shoot'),
        'fire_1': convert_to_list('7,s_frozen_fog_shoot'),
        'skate_fire': convert_to_list('7,skate_frozen_ball_shoot'),
        'skate_fire_1': convert_to_list('7,skate_frozen_fog_shoot'),
        'crouch_fire': convert_to_list('2,c_frozen_ball_shoot'),
        'crouch_fire_1': convert_to_list('2,c_frozen_fog_shoot'),
        'jump_fire': convert_to_list('s_frozen_ball_shoot'),
        'jump_fire_1': convert_to_list('s_frozen_fog_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_frozen_ball_shoot'),
        'skate_jump_fire_1': convert_to_list('7,skate_frozen_fog_shoot'),
        'idle': convert_to_list('s_frozen_stop'),
        'skate_idle': convert_to_list('skate_frozen_stand_idle'),
        'aim_idle': convert_to_list('s_frozen_aim'),
        'skate_aim_idle': convert_to_list('skate_frozen_aim'),
        'crouch_idle': convert_to_list('2,c_frozen_stop'),
        'aim_crouch_idle': convert_to_list('2,c_frozen_aim'),
        'stand_move': convert_to_list('6,s_frozen_move'),
        'skate_stand_move': convert_to_list('6,skate_frozen_move'),
        'stand_shoot_move': convert_to_list('6,s_frozen_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_frozen_aim'),
        'run_stage_2': convert_to_list('frozen_run_01_start'),
        'run_stage_3': convert_to_list('s_frozen_run'),
        'run_2_stand_stage': convert_to_list('frozen_run_stop'),
        'squat_move': convert_to_list('c_frozen_stop_f'),
        'squat_run': convert_to_list('c_frozen_run'),
        'roll': convert_to_list(''),
        'rush': convert_to_list(''),
        'use_item': convert_to_list(''),
        'use_bandage': convert_to_list(''),
        'cure': convert_to_list(''),
        'jump_stage_1': convert_to_list('frozen_jump_01'),
        'jump_high': convert_to_list('frozen_high_jump_01'),
        'jump_stage_2': convert_to_list('frozen_jump_02'),
        'jump_stage_3': convert_to_list('frozen_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list(''),
        'run_jump_stage_2': convert_to_list(''),
        'run_jump_stage_3': convert_to_list(''),
        'run_jump_stage_3_large': convert_to_list(''),
        'hit': convert_to_list(''),
        'skate_brake': convert_to_list('skate_frozen_f_brake'),
        'skate_prepare_move': convert_to_list('skate_frozen_f_start'),
        'skate_leave': convert_to_list('skate_frozen_leave'),
        'skate_board': convert_to_list('skate_frozen_board')
        },
   14: {'get_new_gun': convert_to_list('7,s_hydra_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list('7,skate_bazooka_change'),
        'crouch_get_new_gun': convert_to_list('2,c_hydra_change'),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list('7,s_hydra_reload'),
        'skate_first_reload': convert_to_list('7,skate_bazooka_reload'),
        'crouch_first_reload': convert_to_list('c_hydra_reload'),
        'fire': convert_to_list('7,s_hydra_shoot'),
        'fire_1': convert_to_list(''),
        'skate_fire': convert_to_list('7,skate_bazooka_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('c_hydra_shoot'),
        'crouch_fire_1': convert_to_list(''),
        'jump_fire': convert_to_list('s_hydra_shoot'),
        'jump_fire_1': convert_to_list(''),
        'skate_jump_fire': convert_to_list('7,skate_bazooka_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_hydra_stop'),
        'skate_idle': convert_to_list('skate_bazooka_stand_idle'),
        'aim_idle': convert_to_list('s_hydra_aim'),
        'skate_aim_idle': convert_to_list('skate_bazooka_aim'),
        'crouch_idle': convert_to_list('c_hydra_stop'),
        'aim_crouch_idle': convert_to_list('c_hydra_aim'),
        'stand_move': convert_to_list('6,s_hydra_move'),
        'skate_stand_move': convert_to_list('6,skate_bazooka_move'),
        'stand_shoot_move': convert_to_list('6,s_hydra_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_bazooka_aim'),
        'run_stage_2': convert_to_list('hydra_run_start'),
        'run_stage_3': convert_to_list('s_hydra_run'),
        'run_2_stand_stage': convert_to_list('hydra_run_stop'),
        'squat_move': convert_to_list('c_hydra_stop_f'),
        'squat_run': convert_to_list('c_hydra_run'),
        'roll': convert_to_list(''),
        'rush': convert_to_list(''),
        'use_item': convert_to_list(''),
        'use_bandage': convert_to_list(''),
        'cure': convert_to_list(''),
        'jump_stage_1': convert_to_list(''),
        'jump_high': convert_to_list(''),
        'jump_stage_2': convert_to_list(''),
        'jump_stage_3': convert_to_list(''),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list(''),
        'run_jump_stage_2': convert_to_list(''),
        'run_jump_stage_3': convert_to_list(''),
        'run_jump_stage_3_large': convert_to_list(''),
        'hit': convert_to_list(''),
        'skate_brake': convert_to_list('skate_bazooka_f_brake'),
        'skate_prepare_move': convert_to_list('skate_bazooka_f_start'),
        'skate_leave': convert_to_list('skate_bazooka_leave'),
        'skate_board': convert_to_list('skate_bazooka_board')
        },
   15: {'get_new_gun': convert_to_list('7,s_snipe_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list('7,skate_ak_change'),
        'crouch_get_new_gun': convert_to_list('2,c_snipe_change'),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list('7,s_lmg_reload'),
        'skate_first_reload': convert_to_list('7,skate_lmg_reload'),
        'crouch_first_reload': convert_to_list('2,c_lmg_reload'),
        'fire': convert_to_list('7,s_lmg_shoot'),
        'fire_1': convert_to_list(''),
        'skate_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_lmg_shoot'),
        'crouch_fire_1': convert_to_list(''),
        'jump_fire': convert_to_list('s_lmg_shoot'),
        'jump_fire_1': convert_to_list('s_lmg_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_lmg_stop'),
        'skate_idle': convert_to_list('skate_ak_stand_idle'),
        'aim_idle': convert_to_list('s_lmg_aim'),
        'skate_aim_idle': convert_to_list('skate_ak_aim'),
        'crouch_idle': convert_to_list('2,c_pulse_stop'),
        'aim_crouch_idle': convert_to_list('2,c_lmg_aim'),
        'stand_move': convert_to_list('6,s_pulse_move'),
        'skate_stand_move': convert_to_list('6,skate_ak_move'),
        'stand_shoot_move': convert_to_list('6,s_lmg_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
        'run_stage_2': convert_to_list('pulse_run_start'),
        'run_stage_3': convert_to_list('s_pulse_run'),
        'run_2_stand_stage': convert_to_list('pulse_run_stop'),
        'squat_move': convert_to_list('c_pulse_stop_f'),
        'squat_run': convert_to_list('c_pulse_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list('ak_jump_01'),
        'jump_high': convert_to_list('ak_high_jump_01'),
        'jump_stage_2': convert_to_list('ak_jump_02'),
        'jump_stage_3': convert_to_list('ak_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list('skate_ak_f_brake'),
        'skate_prepare_move': convert_to_list('skate_ak_f_start'),
        'skate_leave': convert_to_list('skate_ak_leave'),
        'skate_board': convert_to_list('skate_ak_board')
        },
   16: {'get_new_gun': convert_to_list('7,s_mgl_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list('7,skate_mgl_change'),
        'crouch_get_new_gun': convert_to_list('2,c_mgl_change'),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list('7,s_blast_reload'),
        'skate_first_reload': convert_to_list('7,skate_blast_reload'),
        'crouch_first_reload': convert_to_list('2,c_blast_reload'),
        'fire': convert_to_list('7,s_mgl_shoot'),
        'fire_1': convert_to_list(''),
        'skate_fire': convert_to_list('7,skate_mgl_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_mgl_shoot'),
        'crouch_fire_1': convert_to_list(''),
        'jump_fire': convert_to_list('s_mgl_shoot'),
        'jump_fire_1': convert_to_list(''),
        'skate_jump_fire': convert_to_list('7,skate_mgl_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_mgl_stop'),
        'skate_idle': convert_to_list('skate_mgl_stand_idle'),
        'aim_idle': convert_to_list('s_mgl_aim'),
        'skate_aim_idle': convert_to_list('skate_mgl_aim'),
        'crouch_idle': convert_to_list('2,c_mgl_stop'),
        'aim_crouch_idle': convert_to_list('2,c_mgl_aim'),
        'stand_move': convert_to_list('6,s_mgl_move'),
        'skate_stand_move': convert_to_list('6,skate_mgl_move'),
        'stand_shoot_move': convert_to_list('6,s_mgl_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_mgl_aim'),
        'run_stage_2': convert_to_list(''),
        'run_stage_3': convert_to_list(''),
        'run_2_stand_stage': convert_to_list('mgl_run_stop'),
        'squat_move': convert_to_list('c_mgl_stop_f'),
        'squat_run': convert_to_list(''),
        'roll': convert_to_list(''),
        'rush': convert_to_list(''),
        'use_item': convert_to_list(''),
        'use_bandage': convert_to_list(''),
        'cure': convert_to_list(''),
        'jump_stage_1': convert_to_list('mgl_jump_01'),
        'jump_high': convert_to_list('mgl_high_jump_01'),
        'jump_stage_2': convert_to_list('mgl_jump_02'),
        'jump_stage_3': convert_to_list('mgl_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list(''),
        'run_jump_stage_2': convert_to_list(''),
        'run_jump_stage_3': convert_to_list(''),
        'run_jump_stage_3_large': convert_to_list(''),
        'hit': convert_to_list(''),
        'skate_brake': convert_to_list('skate_mgl_f_brake'),
        'skate_prepare_move': convert_to_list('skate_mgl_f_start'),
        'skate_leave': convert_to_list('skate_mgl_leave'),
        'skate_board': convert_to_list('skate_mgl_board')
        },
   17: {'get_new_gun': convert_to_list('7,s_m4_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list('7,s_m4_change'),
        'skate_get_new_gun': convert_to_list('7,skate_m4_change'),
        'crouch_get_new_gun': convert_to_list('2,c_m4_change'),
        'crouch_switch_gun_mode': convert_to_list('2,c_m4_change'),
        'gun_load': convert_to_list('7,s_snipe_load'),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list('2,c_snipe_load'),
        'first_reload': convert_to_list('7,s_m4_reload'),
        'skate_first_reload': convert_to_list('7,skate_m4_reload'),
        'crouch_first_reload': convert_to_list('2,c_m4_reload'),
        'fire': convert_to_list('7,s_ak_shoot'),
        'fire_1': convert_to_list('7,s_ak_shoot'),
        'skate_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_ak_shoot'),
        'crouch_fire_1': convert_to_list('2,c_ak_shoot'),
        'jump_fire': convert_to_list('s_ak_shoot'),
        'jump_fire_1': convert_to_list('s_ak_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_ak_stop'),
        'skate_idle': convert_to_list('skate_ak_stand_idle'),
        'aim_idle': convert_to_list('s_ak_aim'),
        'skate_aim_idle': convert_to_list('skate_ak_aim'),
        'crouch_idle': convert_to_list('2,c_ak_stop'),
        'aim_crouch_idle': convert_to_list('2,c_ak_aim'),
        'stand_move': convert_to_list('6,s_ak_move'),
        'skate_stand_move': convert_to_list('6,skate_ak_move'),
        'stand_shoot_move': convert_to_list('6,s_ak_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
        'run_stage_2': convert_to_list('ak_run_start'),
        'run_stage_3': convert_to_list('s_ak_run'),
        'run_2_stand_stage': convert_to_list('ak_run_stop'),
        'squat_move': convert_to_list('c_ak_stop_f'),
        'squat_run': convert_to_list('c_ak_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list('ak_jump_01'),
        'jump_high': convert_to_list('ak_high_jump_01'),
        'jump_stage_2': convert_to_list('ak_jump_02'),
        'jump_stage_3': convert_to_list('ak_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list('skate_ak_f_brake'),
        'skate_prepare_move': convert_to_list('skate_ak_f_start'),
        'skate_leave': convert_to_list('skate_ak_leave'),
        'skate_board': convert_to_list('skate_ak_board')
        },
   18: {'get_new_gun': convert_to_list('7,s_mp5_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list('7,s_mp5_change'),
        'skate_get_new_gun': convert_to_list('7,skate_mp5_change'),
        'crouch_get_new_gun': convert_to_list('2,c_mp5_change'),
        'crouch_switch_gun_mode': convert_to_list('2,c_mp5_change'),
        'gun_load': convert_to_list('7,s_snipe_load'),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list('2,c_snipe_load'),
        'first_reload': convert_to_list('7,s_mp5_reload'),
        'skate_first_reload': convert_to_list('7,skate_mp5_reload'),
        'crouch_first_reload': convert_to_list('2,c_mp5_reload'),
        'fire': convert_to_list('7,s_ak_shoot'),
        'fire_1': convert_to_list('7,s_ak_shoot'),
        'skate_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_ak_shoot'),
        'crouch_fire_1': convert_to_list('2,c_ak_shoot'),
        'jump_fire': convert_to_list('s_ak_shoot'),
        'jump_fire_1': convert_to_list('s_ak_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_ak_stop'),
        'skate_idle': convert_to_list('skate_ak_stand_idle'),
        'aim_idle': convert_to_list('s_ak_aim'),
        'skate_aim_idle': convert_to_list('skate_ak_aim'),
        'crouch_idle': convert_to_list('2,c_ak_stop'),
        'aim_crouch_idle': convert_to_list('2,c_ak_aim'),
        'stand_move': convert_to_list('6,s_ak_move'),
        'skate_stand_move': convert_to_list('6,skate_ak_move'),
        'stand_shoot_move': convert_to_list('6,s_ak_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
        'run_stage_2': convert_to_list('ak_run_start'),
        'run_stage_3': convert_to_list('s_ak_run'),
        'run_2_stand_stage': convert_to_list('ak_run_stop'),
        'squat_move': convert_to_list('c_ak_stop_f'),
        'squat_run': convert_to_list('c_ak_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list('ak_jump_01'),
        'jump_high': convert_to_list('ak_high_jump_01'),
        'jump_stage_2': convert_to_list('ak_jump_02'),
        'jump_stage_3': convert_to_list('ak_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list('skate_ak_f_brake'),
        'skate_prepare_move': convert_to_list('skate_ak_f_start'),
        'skate_leave': convert_to_list('skate_ak_leave'),
        'skate_board': convert_to_list('skate_ak_board')
        },
   19: {'get_new_gun': convert_to_list(''),'is_two_hand': 1,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list(''),
        'crouch_get_new_gun': convert_to_list(''),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list(''),
        'skate_first_reload': convert_to_list(''),
        'crouch_first_reload': convert_to_list(''),
        'fire': convert_to_list(''),
        'fire_1': convert_to_list(''),
        'skate_fire': convert_to_list(''),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list(''),
        'crouch_fire_1': convert_to_list(''),
        'jump_fire': convert_to_list(''),
        'jump_fire_1': convert_to_list(''),
        'skate_jump_fire': convert_to_list(''),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('call_s_emptyhand_idle'),
        'skate_idle': convert_to_list(''),
        'aim_idle': convert_to_list('call_s_emptyhand_idle'),
        'skate_aim_idle': convert_to_list(''),
        'crouch_idle': convert_to_list('c_emptyhand_idle'),
        'aim_crouch_idle': convert_to_list('c_emptyhand_idle'),
        'stand_move': convert_to_list('6,emptyhand_move'),
        'skate_stand_move': convert_to_list(''),
        'stand_shoot_move': convert_to_list(''),
        'skate_stand_shoot_move': convert_to_list(''),
        'run_stage_2': convert_to_list('call_double_run_start'),
        'run_stage_3': convert_to_list('call_s_double_run'),
        'run_2_stand_stage': convert_to_list('call_double_run_stop'),
        'squat_move': convert_to_list('c_ak_stop_f'),
        'squat_run': convert_to_list('emptyhand_run'),
        'roll': convert_to_list('4,emptyhand_roll'),
        'rush': convert_to_list(''),
        'use_item': convert_to_list(''),
        'use_bandage': convert_to_list(''),
        'cure': convert_to_list(''),
        'jump_stage_1': convert_to_list('call_double_jump_01'),
        'jump_high': convert_to_list('double_high_jump_01'),
        'jump_stage_2': convert_to_list('call_double_jump_02'),
        'jump_stage_3': convert_to_list('call_double_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list(''),
        'run_jump_stage_2': convert_to_list(''),
        'run_jump_stage_3': convert_to_list(''),
        'run_jump_stage_3_large': convert_to_list(''),
        'hit': convert_to_list('hit_emptyhand'),
        'skate_brake': convert_to_list(''),
        'skate_prepare_move': convert_to_list(''),
        'skate_leave': convert_to_list(''),
        'skate_board': convert_to_list('')
        },
   20: {'get_new_gun': convert_to_list('7,s_aa12_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list('7,s_aa12_change'),
        'skate_get_new_gun': convert_to_list('7,skate_aa12_change'),
        'crouch_get_new_gun': convert_to_list('2,c_aa12_change'),
        'crouch_switch_gun_mode': convert_to_list('2,c_aa12_change'),
        'gun_load': convert_to_list('7,s_snipe_load'),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list('2,c_snipe_load'),
        'first_reload': convert_to_list('7,s_aa12_reload'),
        'skate_first_reload': convert_to_list('7,skate_aa12_reload'),
        'crouch_first_reload': convert_to_list('2,c_aa12_reload'),
        'fire': convert_to_list('7,s_ak_shoot'),
        'fire_1': convert_to_list('7,s_ak_shoot'),
        'skate_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_ak_shoot'),
        'crouch_fire_1': convert_to_list('2,c_ak_shoot'),
        'jump_fire': convert_to_list('s_ak_shoot'),
        'jump_fire_1': convert_to_list('s_ak_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_ak_stop'),
        'skate_idle': convert_to_list('skate_ak_stand_idle'),
        'aim_idle': convert_to_list('s_ak_aim'),
        'skate_aim_idle': convert_to_list('skate_ak_aim'),
        'crouch_idle': convert_to_list('2,c_ak_stop'),
        'aim_crouch_idle': convert_to_list('2,c_ak_aim'),
        'stand_move': convert_to_list('6,s_ak_move'),
        'skate_stand_move': convert_to_list('6,skate_ak_move'),
        'stand_shoot_move': convert_to_list('6,s_ak_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
        'run_stage_2': convert_to_list('ak_run_start'),
        'run_stage_3': convert_to_list('s_ak_run'),
        'run_2_stand_stage': convert_to_list('ak_run_stop'),
        'squat_move': convert_to_list('c_ak_stop_f'),
        'squat_run': convert_to_list('c_ak_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list('ak_jump_01'),
        'jump_high': convert_to_list('ak_high_jump_01'),
        'jump_stage_2': convert_to_list('ak_jump_02'),
        'jump_stage_3': convert_to_list('ak_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list('skate_ak_f_brake'),
        'skate_prepare_move': convert_to_list('skate_ak_f_start'),
        'skate_leave': convert_to_list('skate_ak_leave'),
        'skate_board': convert_to_list('skate_ak_board')
        },
   21: {'get_new_gun': convert_to_list('7,s_pulse_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list('7,skate_ak_change'),
        'crouch_get_new_gun': convert_to_list('2,c_pulse_change'),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list('7,s_m14_reload'),
        'skate_first_reload': convert_to_list('7,skate_m14_reload'),
        'crouch_first_reload': convert_to_list('2,c_m14_reload'),
        'fire': convert_to_list('7,s_ak_shoot'),
        'fire_1': convert_to_list('7,s_ak_shoot'),
        'skate_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_ak_shoot'),
        'crouch_fire_1': convert_to_list('2,c_ak_shoot'),
        'jump_fire': convert_to_list('s_ak_shoot'),
        'jump_fire_1': convert_to_list('s_ak_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_ak_stop'),
        'skate_idle': convert_to_list('skate_ak_stand_idle'),
        'aim_idle': convert_to_list('s_pulse_aim'),
        'skate_aim_idle': convert_to_list('skate_ak_aim'),
        'crouch_idle': convert_to_list('2,c_pulse_stop'),
        'aim_crouch_idle': convert_to_list('2,c_pulse_aim'),
        'stand_move': convert_to_list('6,s_pulse_move'),
        'skate_stand_move': convert_to_list('6,skate_ak_move'),
        'stand_shoot_move': convert_to_list('6,s_pulse_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
        'run_stage_2': convert_to_list('pulse_run_start'),
        'run_stage_3': convert_to_list('s_pulse_run'),
        'run_2_stand_stage': convert_to_list('pulse_run_stop'),
        'squat_move': convert_to_list('c_pulse_stop_f'),
        'squat_run': convert_to_list('c_pulse_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list(''),
        'jump_high': convert_to_list(''),
        'jump_stage_2': convert_to_list(''),
        'jump_stage_3': convert_to_list(''),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list(''),
        'skate_prepare_move': convert_to_list(''),
        'skate_leave': convert_to_list(''),
        'skate_board': convert_to_list('')
        },
   22: {'get_new_gun': convert_to_list('7,s_bazooka_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list('7,skate_bazooka_change'),
        'crouch_get_new_gun': convert_to_list('2,c_bazooka_change'),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list('7,s_djfd_reload'),
        'skate_first_reload': convert_to_list('7,skate_djfd_reload'),
        'crouch_first_reload': convert_to_list('c_djfd_reload'),
        'fire': convert_to_list('7,s_bazooka_shoot'),
        'fire_1': convert_to_list(''),
        'skate_fire': convert_to_list('7,skate_bazooka_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('c_bazooka_shoot'),
        'crouch_fire_1': convert_to_list(''),
        'jump_fire': convert_to_list('s_bazooka_shoot'),
        'jump_fire_1': convert_to_list(''),
        'skate_jump_fire': convert_to_list('7,skate_bazooka_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_bazooka_stop'),
        'skate_idle': convert_to_list('skate_bazooka_stand_idle'),
        'aim_idle': convert_to_list('s_bazooka_aim'),
        'skate_aim_idle': convert_to_list('skate_bazooka_aim'),
        'crouch_idle': convert_to_list('c_bazooka_stop'),
        'aim_crouch_idle': convert_to_list('c_bazooka_aim'),
        'stand_move': convert_to_list('6,s_bazooka_move'),
        'skate_stand_move': convert_to_list('6,skate_bazooka_move'),
        'stand_shoot_move': convert_to_list('6,s_bazooka_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_bazooka_aim'),
        'run_stage_2': convert_to_list('bazooka_run_start'),
        'run_stage_3': convert_to_list('s_bazooka_run'),
        'run_2_stand_stage': convert_to_list('bazooka_run_stop'),
        'squat_move': convert_to_list('c_bazooka_stop_f'),
        'squat_run': convert_to_list('c_bazooka_run'),
        'roll': convert_to_list('4,bazooka_roll'),
        'rush': convert_to_list(''),
        'use_item': convert_to_list(''),
        'use_bandage': convert_to_list(''),
        'cure': convert_to_list(''),
        'jump_stage_1': convert_to_list('bazooka_jump_01'),
        'jump_high': convert_to_list('bazooka_high_jump_01'),
        'jump_stage_2': convert_to_list('bazooka_jump_02'),
        'jump_stage_3': convert_to_list('bazooka_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list(''),
        'run_jump_stage_2': convert_to_list(''),
        'run_jump_stage_3': convert_to_list(''),
        'run_jump_stage_3_large': convert_to_list(''),
        'hit': convert_to_list(''),
        'skate_brake': convert_to_list('skate_bazooka_f_brake'),
        'skate_prepare_move': convert_to_list('skate_bazooka_f_start'),
        'skate_leave': convert_to_list('skate_bazooka_leave'),
        'skate_board': convert_to_list('skate_bazooka_board')
        },
   23: {'get_new_gun': convert_to_list('7,s_snipe_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list('7,skate_ak_change'),
        'crouch_get_new_gun': convert_to_list('2,c_snipe_change'),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list('7,s_pulse_reload'),
        'skate_first_reload': convert_to_list('7,skate_pulse_reload'),
        'crouch_first_reload': convert_to_list('2,c_pulse_reload'),
        'fire': convert_to_list('7,s_ak_shoot'),
        'fire_1': convert_to_list(''),
        'skate_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_lmg_shoot'),
        'crouch_fire_1': convert_to_list(''),
        'jump_fire': convert_to_list('s_lmg_shoot'),
        'jump_fire_1': convert_to_list('s_lmg_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_lmg_stop'),
        'skate_idle': convert_to_list('skate_ak_stand_idle'),
        'aim_idle': convert_to_list('s_lmg_aim'),
        'skate_aim_idle': convert_to_list('skate_ak_aim'),
        'crouch_idle': convert_to_list('2,c_pulse_stop'),
        'aim_crouch_idle': convert_to_list('2,c_lmg_aim'),
        'stand_move': convert_to_list('6,s_pulse_move'),
        'skate_stand_move': convert_to_list('6,skate_ak_move'),
        'stand_shoot_move': convert_to_list('6,s_lmg_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
        'run_stage_2': convert_to_list('pulse_run_start'),
        'run_stage_3': convert_to_list('s_pulse_run'),
        'run_2_stand_stage': convert_to_list('pulse_run_stop'),
        'squat_move': convert_to_list('c_pulse_stop_f'),
        'squat_run': convert_to_list('c_pulse_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list('ak_jump_01'),
        'jump_high': convert_to_list('ak_high_jump_01'),
        'jump_stage_2': convert_to_list('ak_jump_02'),
        'jump_stage_3': convert_to_list('ak_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list('skate_ak_f_brake'),
        'skate_prepare_move': convert_to_list('skate_ak_f_start'),
        'skate_leave': convert_to_list('skate_ak_leave'),
        'skate_board': convert_to_list('skate_ak_board')
        },
   24: {'get_new_gun': convert_to_list('7,s_mgl_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list('7,s_ak_change'),
        'skate_get_new_gun': convert_to_list('7,skate_mgl_change'),
        'crouch_get_new_gun': convert_to_list('2,c_mgl_change'),
        'crouch_switch_gun_mode': convert_to_list('2,c_ak_change'),
        'gun_load': convert_to_list('7,s_snipe_load'),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list('2,c_snipe_load'),
        'first_reload': convert_to_list('7,s_mgl_reload'),
        'skate_first_reload': convert_to_list('7,skate_mgl_reload'),
        'crouch_first_reload': convert_to_list('2,c_mgl_reload'),
        'fire': convert_to_list('7,s_mgl_shoot'),
        'fire_1': convert_to_list('7,s_ak_shoot'),
        'skate_fire': convert_to_list('7,skate_mgl_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_mgl_shoot'),
        'crouch_fire_1': convert_to_list('2,c_ak_shoot'),
        'jump_fire': convert_to_list('s_mgl_shoot'),
        'jump_fire_1': convert_to_list('s_ak_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_mgl_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_mgl_stop'),
        'skate_idle': convert_to_list('skate_mgl_stand_idle'),
        'aim_idle': convert_to_list('s_mgl_aim'),
        'skate_aim_idle': convert_to_list('skate_mgl_aim'),
        'crouch_idle': convert_to_list('2,c_mgl_stop'),
        'aim_crouch_idle': convert_to_list('2,c_mgl_aim'),
        'stand_move': convert_to_list('6,s_mgl_move'),
        'skate_stand_move': convert_to_list('6,skate_mgl_move'),
        'stand_shoot_move': convert_to_list('6,s_mgl_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_mgl_aim'),
        'run_stage_2': convert_to_list('ak_run_start'),
        'run_stage_3': convert_to_list('s_ak_run'),
        'run_2_stand_stage': convert_to_list('ak_run_stop'),
        'squat_move': convert_to_list('c_ak_stop_f'),
        'squat_run': convert_to_list('c_ak_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list('mgl_jump_01'),
        'jump_high': convert_to_list('mgl_high_jump_01'),
        'jump_stage_2': convert_to_list('mgl_jump_02'),
        'jump_stage_3': convert_to_list('mgl_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list('skate_mgl_f_brake'),
        'skate_prepare_move': convert_to_list('skate_mgl_f_start'),
        'skate_leave': convert_to_list('skate_mgl_leave'),
        'skate_board': convert_to_list('skate_mgl_board')
        },
   25: {'get_new_gun': convert_to_list('7,s_ak_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list('7,s_ak_change'),
        'skate_get_new_gun': convert_to_list('7,skate_ak_change'),
        'crouch_get_new_gun': convert_to_list('2,c_ak_change'),
        'crouch_switch_gun_mode': convert_to_list('2,c_ak_change'),
        'gun_load': convert_to_list('7,s_snipe_load'),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list('2,c_snipe_load'),
        'first_reload': convert_to_list('7,s_snipe_reload'),
        'skate_first_reload': convert_to_list('7,skate_snipe_reload'),
        'crouch_first_reload': convert_to_list('7,skate_snipe_reload'),
        'fire': convert_to_list('7,s_pulse_shoot'),
        'fire_1': convert_to_list('7,s_ak_shoot'),
        'skate_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_ak_shoot'),
        'crouch_fire_1': convert_to_list('2,c_ak_shoot'),
        'jump_fire': convert_to_list('s_ak_shoot'),
        'jump_fire_1': convert_to_list('s_ak_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_ak_stop'),
        'skate_idle': convert_to_list('skate_ak_stand_idle'),
        'aim_idle': convert_to_list('s_ak_aim'),
        'skate_aim_idle': convert_to_list('skate_ak_aim'),
        'crouch_idle': convert_to_list('2,c_ak_stop'),
        'aim_crouch_idle': convert_to_list('2,c_ak_aim'),
        'stand_move': convert_to_list('6,s_ak_move'),
        'skate_stand_move': convert_to_list('6,skate_ak_move'),
        'stand_shoot_move': convert_to_list('6,s_ak_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
        'run_stage_2': convert_to_list('ak_run_start'),
        'run_stage_3': convert_to_list('s_ak_run'),
        'run_2_stand_stage': convert_to_list('ak_run_stop'),
        'squat_move': convert_to_list('c_ak_stop_f'),
        'squat_run': convert_to_list('c_ak_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list('ak_jump_01'),
        'jump_high': convert_to_list('ak_high_jump_01'),
        'jump_stage_2': convert_to_list('ak_jump_02'),
        'jump_stage_3': convert_to_list('ak_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list('skate_ak_f_brake'),
        'skate_prepare_move': convert_to_list('skate_ak_f_start'),
        'skate_leave': convert_to_list('skate_ak_leave'),
        'skate_board': convert_to_list('skate_ak_board')
        },
   26: {'get_new_gun': convert_to_list('7,s_m4_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list('7,s_m4_change'),
        'skate_get_new_gun': convert_to_list('7,skate_m4_change'),
        'crouch_get_new_gun': convert_to_list('2,c_m4_change'),
        'crouch_switch_gun_mode': convert_to_list('2,c_m4_change'),
        'gun_load': convert_to_list('7,s_snipe_load'),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list('2,c_snipe_load'),
        'first_reload': convert_to_list('7,s_m4_reload'),
        'skate_first_reload': convert_to_list('7,skate_m4_reload'),
        'crouch_first_reload': convert_to_list('2,c_m4_reload'),
        'fire': convert_to_list('7,s_ak_shoot'),
        'fire_1': convert_to_list('7,s_ak_shoot'),
        'skate_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('2,c_ak_shoot'),
        'crouch_fire_1': convert_to_list('2,c_ak_shoot'),
        'jump_fire': convert_to_list('s_ak_shoot'),
        'jump_fire_1': convert_to_list('s_ak_shoot'),
        'skate_jump_fire': convert_to_list('7,skate_ak_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_ak_stop'),
        'skate_idle': convert_to_list('skate_ak_stand_idle'),
        'aim_idle': convert_to_list('s_ak_aim'),
        'skate_aim_idle': convert_to_list('skate_ak_aim'),
        'crouch_idle': convert_to_list('2,c_ak_stop'),
        'aim_crouch_idle': convert_to_list('2,c_ak_aim'),
        'stand_move': convert_to_list('6,s_ak_move'),
        'skate_stand_move': convert_to_list('6,skate_ak_move'),
        'stand_shoot_move': convert_to_list('6,s_ak_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_ak_aim'),
        'run_stage_2': convert_to_list('ak_run_start'),
        'run_stage_3': convert_to_list('s_ak_run'),
        'run_2_stand_stage': convert_to_list('ak_run_stop'),
        'squat_move': convert_to_list('c_ak_stop_f'),
        'squat_run': convert_to_list('c_ak_run'),
        'roll': convert_to_list('4,takeweapon_roll'),
        'rush': convert_to_list('4,flash'),
        'use_item': convert_to_list('s_bandage'),
        'use_bandage': convert_to_list('s_bandage_true'),
        'cure': convert_to_list('s_cure'),
        'jump_stage_1': convert_to_list('ak_jump_01'),
        'jump_high': convert_to_list('ak_high_jump_01'),
        'jump_stage_2': convert_to_list('ak_jump_02'),
        'jump_stage_3': convert_to_list('ak_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list('run_jump_01_shoot'),
        'run_jump_stage_2': convert_to_list('run_jump_02_shoot'),
        'run_jump_stage_3': convert_to_list('run_jump_03_shoot'),
        'run_jump_stage_3_large': convert_to_list('ground'),
        'hit': convert_to_list('shoot01_hit_a'),
        'skate_brake': convert_to_list('skate_ak_f_brake'),
        'skate_prepare_move': convert_to_list('skate_ak_f_start'),
        'skate_leave': convert_to_list('skate_ak_leave'),
        'skate_board': convert_to_list('skate_ak_board')
        },
   27: {'get_new_gun': convert_to_list('7,s_bazooka_change'),'is_two_hand': 0,
        'switch_gun_mode': convert_to_list(''),
        'skate_get_new_gun': convert_to_list('7,skate_bazooka_change'),
        'crouch_get_new_gun': convert_to_list('2,c_bazooka_change'),
        'crouch_switch_gun_mode': convert_to_list(''),
        'gun_load': convert_to_list(''),
        'skate_gun_load': convert_to_list(''),
        'crouch_gun_load': convert_to_list(''),
        'first_reload': convert_to_list('7,s_bazooka_reload'),
        'skate_first_reload': convert_to_list('7,skate_bazooka_reload'),
        'crouch_first_reload': convert_to_list('c_bazooka_reload'),
        'fire': convert_to_list('7,s_bazooka_shoot'),
        'fire_1': convert_to_list(''),
        'skate_fire': convert_to_list('7,skate_bazooka_shoot'),
        'skate_fire_1': convert_to_list(''),
        'crouch_fire': convert_to_list('c_bazooka_shoot'),
        'crouch_fire_1': convert_to_list(''),
        'jump_fire': convert_to_list('s_bazooka_shoot'),
        'jump_fire_1': convert_to_list(''),
        'skate_jump_fire': convert_to_list('7,skate_bazooka_shoot'),
        'skate_jump_fire_1': convert_to_list(''),
        'idle': convert_to_list('s_bazooka_stop'),
        'skate_idle': convert_to_list('skate_bazooka_stand_idle'),
        'aim_idle': convert_to_list('s_bazooka_aim'),
        'skate_aim_idle': convert_to_list('skate_bazooka_aim'),
        'crouch_idle': convert_to_list('c_bazooka_stop'),
        'aim_crouch_idle': convert_to_list('c_bazooka_aim'),
        'stand_move': convert_to_list('6,s_bazooka_move'),
        'skate_stand_move': convert_to_list('6,skate_bazooka_move'),
        'stand_shoot_move': convert_to_list('6,s_bazooka_aim'),
        'skate_stand_shoot_move': convert_to_list('6,skate_bazooka_aim'),
        'run_stage_2': convert_to_list('bazooka_run_start'),
        'run_stage_3': convert_to_list('s_bazooka_run'),
        'run_2_stand_stage': convert_to_list('bazooka_run_stop'),
        'squat_move': convert_to_list('c_bazooka_stop_f'),
        'squat_run': convert_to_list('c_bazooka_run'),
        'roll': convert_to_list('4,bazooka_roll'),
        'rush': convert_to_list(''),
        'use_item': convert_to_list(''),
        'use_bandage': convert_to_list(''),
        'cure': convert_to_list(''),
        'jump_stage_1': convert_to_list('bazooka_jump_01'),
        'jump_high': convert_to_list('bazooka_high_jump_01'),
        'jump_stage_2': convert_to_list('bazooka_jump_02'),
        'jump_stage_3': convert_to_list('bazooka_jump_03'),
        'jump_stage_3_large': convert_to_list(''),
        'run_jump_stage_1': convert_to_list(''),
        'run_jump_stage_2': convert_to_list(''),
        'run_jump_stage_3': convert_to_list(''),
        'run_jump_stage_3_large': convert_to_list(''),
        'hit': convert_to_list(''),
        'skate_brake': convert_to_list('skate_bazooka_f_brake'),
        'skate_prepare_move': convert_to_list('skate_bazooka_f_start'),
        'skate_leave': convert_to_list('skate_bazooka_leave'),
        'skate_board': convert_to_list('skate_bazooka_board')
        }
   }

def get_main_anim--- This code section failed: ---

1623       0  LOAD_CONST            1  '_l'
           3  LOAD_CONST            2  '_r'
           6  LOAD_CONST            3  '_f'
           9  LOAD_CONST            4  '_b'
          12  LOAD_CONST            5  '_fl'
          15  LOAD_CONST            6  '_fr'
          18  LOAD_CONST            7  '_bl'
          21  LOAD_CONST            8  '_br'
          24  BUILD_LIST_8          8 
          27  STORE_FAST            1  'postfixes'

1625      30  SETUP_LOOP           96  'to 129'
          33  LOAD_FAST             1  'postfixes'
          36  GET_ITER         
          37  FOR_ITER             88  'to 128'
          40  STORE_FAST            2  'postfix'

1626      43  LOAD_FAST             0  'action_name'
          46  LOAD_ATTR             0  'endswith'
          49  LOAD_FAST             2  'postfix'
          52  CALL_FUNCTION_1       1 
          55  POP_JUMP_IF_FALSE    37  'to 37'

1627      58  POP_JUMP_IF_FALSE     0  'to 0'
          61  LOAD_CONST            0  ''
          64  LOAD_CONST            9  -1
          67  BUILD_SLICE_3         3 
          70  BINARY_SUBSCR    
          71  STORE_FAST            3  'rev_action_name'

1628      74  LOAD_FAST             3  'rev_action_name'
          77  LOAD_ATTR             1  'replace'
          80  LOAD_FAST             2  'postfix'
          83  LOAD_CONST            0  ''
          86  LOAD_CONST            0  ''
          89  LOAD_CONST            9  -1
          92  BUILD_SLICE_3         3 
          95  BINARY_SUBSCR    
          96  LOAD_CONST           10  ''
          99  LOAD_CONST           11  1
         102  CALL_FUNCTION_3       3 
         105  STORE_FAST            3  'rev_action_name'

1629     108  LOAD_FAST             3  'rev_action_name'
         111  LOAD_CONST            0  ''
         114  LOAD_CONST            0  ''
         117  LOAD_CONST            9  -1
         120  BUILD_SLICE_3         3 
         123  BINARY_SUBSCR    
         124  RETURN_END_IF    
       125_0  COME_FROM                '58'
       125_1  COME_FROM                '55'
         125  JUMP_BACK            37  'to 37'
         128  POP_BLOCK        
       129_0  COME_FROM                '30'

1631     129  LOAD_FAST             0  'action_name'
         132  RETURN_VALUE     
          -1  RETURN_LAST      

Parse error at or near `POP_JUMP_IF_FALSE' instruction at offset 58