# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/common_const/log_const.py
_reload_all = True
CURE_ACTION_TRY = 1
CURE_ACTION_SUCCESS = 2
CURE_ACTION_INTERRUPT = 3
TEAM_OPERATION_INVITE = 1
TEAM_OPERATION_JOIN = 2
TEAM_OPERATION_QUIT = 3
TEAM_OPERATION_APPOINTMENT = 4
TEAM_MODE_PUBLISH = 1
TEAM_MODE_FRIEND = 2
TEAM_MODE_RECENT = 3
TEAM_MODE_INFO = 4
TEAM_MODE_KICK = 5
TEAM_MODE_SELF = 6
TEAM_MODE_RECOMMEND = 7
TEAM_MODE_CLAN = 8
TEAM_MODE_NEAR = 9
REPORT_FROM_TYPE_CHAT = 1
REPORT_FROM_TYPE_INFO = 2
REPORT_FROM_TYPE_DEAD = 3
REPORT_FROM_TYPE_BATTLE_END = 4
REPORT_FROM_TYPE_SPECTATE = 5
REPORT_FROM_TYPE_LOBBY_NORMAL = 6
REPORT_FROM_TYPE_BATTLE_HISTORY = 7
REPORT_FROM_TYPE_CLAN = 8
REPORT_FROM_TYPE_CUSTOM_ROOM = 9
REPORT_FROM_TYPE_MESSAGE_BOARD = 10
REPORT_FROM_TYPE_COMPETITION = 11
REPORT_REASON_PLUGIN_MOD = 1
REPORT_REASON_ILLEGAL_NAME = 2
REPORT_REASON_INDECENT_SENTENCE = 3
REPORT_REASON_INDECENT_VOICE = 4
REPORT_REASON_SPREAD_ILLEGAL = 5
REPORT_REASON_AD_INCLUDE = 6
REPORT_REASON_ILLEGAL_CLAN_NAME = 9
REPORT_REASON_ILLEGAL_CLAN_INTRO = 10
REPORT_REASON_ILLEGAL_ROOM_NAME = 11
REPORT_REASON_ILLEGAL_PLAYER_INTRO = 12
REPORT_REASON_OTHERS = 100
REPORT_RESULT_OK = 0
REPORT_RESULT_NOT_EXIST = -1
REPORT_RESULT_UNKOWN_PLAYER_ID = -2
REPORT_RESULT_PLAYER_NOT_EXIST = -3
REPORT_RESULT_TIME_LIMIT = -4
REPORT_CLASS_NORMAL = 1
REPORT_CLASS_BATTLE = 2
REPORT_CLASS_CLAN = 3
REPORT_CLASS_ROOM = 4
LOG_KEY_INVISIBLE_PLAYER = 'InvisibleAttacker'
RECOMMEND_ITEM_STATE_OPEN = 0
RECOMMEND_ITEM_STATE_CLICK_ITEM = 1
RECOMMEND_ITEM_STATE_BUY_ITEM = 2
RECOMMEND_COLLOCATION_ITEM_STATE_OPEN = 0
RECOMMEND_COLLOCATION_ITEM_STATE_BUY = 2
REPORT_CLAN_DAY_LIMIT = 5
REPORT_ROOM_DAY_LIMIT = 5
REPORT_PLAYER_DAY_LIMIT = 10
REPORT_PLAYER_TIMES = 'report_player_times'
REPORT_CLAN_TIMES = 'report_clan_times'
REPORT_ROOM_TIMES = 'report_room_times'
REPORT_TYPE_2_LIMIT = {REPORT_PLAYER_TIMES: REPORT_PLAYER_DAY_LIMIT,
   REPORT_CLAN_TIMES: REPORT_CLAN_DAY_LIMIT,
   REPORT_ROOM_TIMES: REPORT_ROOM_DAY_LIMIT
   }