# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/behavior/module_path_of_states.py
state_name_to_module_path_map = {'AccumulateCastGrenade': 'logic.gcommon.behavior.CastLogic',
   'AccumulateFire8016': 'logic.gcommon.behavior.Logic8016',
   'AccumulateShoot': 'logic.gcommon.behavior.ShootLogic',
   'AccumulateShoot8006': 'logic.gcommon.behavior.Logic8006',
   'AccumulateShoot8011': 'logic.gcommon.behavior.Logic8011',
   'AccumulateShoot8013': 'logic.gcommon.behavior.Logic8013',
   'AccumulateShoot8017': 'logic.gcommon.behavior.Logic8017',
   'AccumulateShoot8019': 'logic.gcommon.behavior.Logic8019',
   'AccumulateShoot8020': 'logic.gcommon.behavior.Logic8020',
   'AccumulateShoot8022': 'logic.gcommon.behavior.Logic8022',
   'AccumulateShoot8028': 'logic.gcommon.behavior.Logic8028',
   'AccumulateShoot8029': 'logic.gcommon.behavior.Logic8029',
   'AccumulateShoot8032': 'logic.gcommon.behavior.Logic8032',
   'AccumulateShoot8035': 'logic.gcommon.behavior.Logic8035',
   'AccumulateShoot8036': 'logic.gcommon.behavior.Logic8036',
   'AccumulateShoot8037': 'logic.gcommon.behavior.Logic8037',
   'AccumulateShootHover': 'logic.gcommon.behavior.ShootLogic',
   'AccumulateShootPure': 'logic.gcommon.behavior.ShootLogic',
   'AccumulateSkill': 'logic.gcommon.behavior.SkillLogic',
   'AccumulateSkill8016': 'logic.gcommon.behavior.Logic8016',
   'AccumulateSkill_M8': 'logic.gcommon.behavior.SkillLogic',
   'AccumulateViceShoot': 'logic.gcommon.behavior.Logic8036',
   'ActionDrivenWeaponFire': 'logic.gcommon.behavior.Logic8011',
   'ActionDrivenWeaponFire8024': 'logic.gcommon.behavior.Logic8024',
   'ActionDrivenWeaponFire8031': 'logic.gcommon.behavior.Logic8031',
   'ActionDrivenWeaponFire8035': 'logic.gcommon.behavior.Logic8035',
   'Aim': 'logic.gcommon.behavior.Logic10011',
   'AimIKBase': 'logic.gcommon.behavior.Logic8016',
   'AirDash': 'logic.gcommon.behavior.Logic8022',
   'BallDash': 'logic.gcommon.behavior.Logic8012',
   'BeatBack': 'logic.gcommon.behavior.StateLogic',
   'BeatBack8028': 'logic.gcommon.behavior.Logic8028',
   'BladeSlash': 'logic.gcommon.behavior.Logic8014',
   'BoltAction': 'logic.gcommon.behavior.Logic8023',
   'Born': 'logic.gcommon.behavior.StateLogic',
   'BossDashRocket': 'logic.gcommon.behavior.PVEBossDashRocketLogic',
   'BossDashRocketBase': 'logic.gcommon.behavior.PVEBossDashRocketLogic',
   'BossExcalibur': 'logic.gcommon.behavior.PVEBossExcaliburLogic',
   'BossExcaliburBase': 'logic.gcommon.behavior.PVEBossExcaliburLogic',
   'BossFlashDash': 'logic.gcommon.behavior.PVEBossFlashDashLogic',
   'BossFlashDashBase': 'logic.gcommon.behavior.PVEBossFlashDashLogic',
   'BossInvincible': 'logic.gcommon.behavior.PVEBossSecondStageLogic',
   'BossInvincibleBase': 'logic.gcommon.behavior.PVEBossSecondStageLogic',
   'BossMultiLaser': 'logic.gcommon.behavior.PVEBossMultiLaserLogic',
   'BossMultiLaserBase': 'logic.gcommon.behavior.PVEBossMultiLaserLogic',
   'BossRangePounce': 'logic.gcommon.behavior.PVEBossRangePounceLogic',
   'BossRangePounceBase': 'logic.gcommon.behavior.PVEBossRangePounceLogic',
   'BossSecondStage': 'logic.gcommon.behavior.PVEBossSecondStageLogic',
   'BossSecondStageBase': 'logic.gcommon.behavior.PVEBossSecondStageLogic',
   'BossShieldTower': 'logic.gcommon.behavior.PVEBossShieldTowerLogic',
   'BurstForm': 'logic.gcommon.behavior.Logic8014',
   'CannonShape': 'logic.gcommon.behavior.Logic8022',
   'CannonSwitch': 'logic.gcommon.behavior.Logic8022',
   'CarDash8033': 'logic.gcommon.behavior.Logic8033',
   'CarFall': 'logic.gcommon.behavior.Logic8020',
   'CarMode': 'logic.gcommon.behavior.Logic8020',
   'CarMode8033': 'logic.gcommon.behavior.Logic8033',
   'CarOnGround': 'logic.gcommon.behavior.Logic8020',
   'CarSuperJumpUp': 'logic.gcommon.behavior.Logic8020',
   'CarSwitch': 'logic.gcommon.behavior.Logic8033',
   'CarWeaponFire8033': 'logic.gcommon.behavior.Logic8033',
   'CastGrenade': 'logic.gcommon.behavior.CastLogic',
   'CastSkill': 'logic.gcommon.behavior.CastLogic',
   'CastSkillClient': 'logic.gcommon.behavior.CastLogic',
   'Catapult': 'logic.gcommon.behavior.BoostLogic',
   'ChangeWeaponState': 'logic.gcommon.behavior.Logic8016',
   'Climb': 'logic.gcommon.behavior.Logic10011',
   'ClusterShoot': 'logic.gcommon.behavior.Logic8030',
   'ClusterShoot8034': 'logic.gcommon.behavior.Logic8034',
   'ComboSecondWeapon': 'logic.gcommon.behavior.Logic8017',
   'CommonCastSkill': 'logic.gcommon.behavior.SkillLogic',
   'CommonDash': 'logic.gcommon.behavior.BoostLogic',
   'ContinuousShoot8027': 'logic.gcommon.behavior.Logic8027',
   'ControllingSpecialWeapon': 'logic.gcommon.behavior.BoardMechaLogic',
   'CustomDisplacement': 'logic.gcommon.behavior.EditorCustomLogic',
   'CutTrack': 'logic.gcommon.behavior.MeleeLogic',
   'Dash': 'logic.gcommon.behavior.BoostLogic',
   'Dash8001': 'logic.gcommon.behavior.Logic8001',
   'Dash8007': 'logic.gcommon.behavior.Logic8007',
   'Dash8010': 'logic.gcommon.behavior.Logic8010',
   'Dash8012': 'logic.gcommon.behavior.Logic8012',
   'Dash8013': 'logic.gcommon.behavior.Logic8013',
   'Dash8017': 'logic.gcommon.behavior.Logic8017',
   'Dash8019': 'logic.gcommon.behavior.Logic8019',
   'Dash8020': 'logic.gcommon.behavior.Logic8020',
   'Dash8022': 'logic.gcommon.behavior.Logic8022',
   'Dash8024': 'logic.gcommon.behavior.Logic8024',
   'Dash8025': 'logic.gcommon.behavior.Logic8025',
   'Dash8026': 'logic.gcommon.behavior.Logic8026',
   'Dash8028': 'logic.gcommon.behavior.Logic8028',
   'Dash8030': 'logic.gcommon.behavior.Logic8030',
   'Dash8031': 'logic.gcommon.behavior.Logic8031',
   'Dash8035': 'logic.gcommon.behavior.Logic8035',
   'Dash8037': 'logic.gcommon.behavior.Logic8037',
   'DashBladeSlash': 'logic.gcommon.behavior.Logic8014',
   'DashBuff': 'logic.gcommon.behavior.Logic8006',
   'DashBuff8023': 'logic.gcommon.behavior.Logic8023',
   'DashFall8022': 'logic.gcommon.behavior.Logic8022',
   'DashMotorcycle': 'logic.gcommon.behavior.Logic4108',
   'DashPostAction8028': 'logic.gcommon.behavior.Logic8028',
   'DashPreAction8028': 'logic.gcommon.behavior.Logic8028',
   'DashVehicle': 'logic.gcommon.behavior.BoostLogic',
   'Defend': 'logic.gcommon.behavior.Logic8019',
   'Die': 'logic.gcommon.behavior.StateLogic',
   'Die4108': 'logic.gcommon.behavior.Logic4108',
   'Die8022': 'logic.gcommon.behavior.Logic8022',
   'Down': 'logic.gcommon.behavior.MoveLogic',
   'DownToStand': 'logic.gcommon.behavior.MoveLogic',
   'DownpourShell': 'logic.gcommon.behavior.Logic8033',
   'DragonRush': 'logic.gcommon.behavior.Logic8011',
   'DragonShape': 'logic.gcommon.behavior.Logic8011',
   'DragonSidestep': 'logic.gcommon.behavior.Logic8011',
   'EnhanceWeaponFire': 'logic.gcommon.behavior.Logic8017',
   'ExternBoneAnim': 'logic.gcommon.behavior.Logic8030',
   'ExternShoulderGrenade8025': 'logic.gcommon.behavior.Logic8025',
   'FairyFall': 'logic.gcommon.behavior.Logic8028',
   'FairyHover': 'logic.gcommon.behavior.Logic8028',
   'FairyRise': 'logic.gcommon.behavior.Logic8028',
   'FairyShape': 'logic.gcommon.behavior.Logic8028',
   'FairySwitch': 'logic.gcommon.behavior.Logic8028',
   'Fall': 'logic.gcommon.behavior.JumpLogic',
   'Fall4108': 'logic.gcommon.behavior.Logic4108',
   'Fall8004': 'logic.gcommon.behavior.JumpLogic',
   'Fall8006': 'logic.gcommon.behavior.Logic8006',
   'Fall8007': 'logic.gcommon.behavior.Logic8007',
   'Fall8008': 'logic.gcommon.behavior.JumpLogic',
   'Fall8010': 'logic.gcommon.behavior.Logic8010',
   'Fall8016': 'logic.gcommon.behavior.Logic8016',
   'Fall8017': 'logic.gcommon.behavior.Logic8017',
   'Fall8019': 'logic.gcommon.behavior.Logic8019',
   'Fall8020': 'logic.gcommon.behavior.Logic8020',
   'Fall8022': 'logic.gcommon.behavior.Logic8022',
   'Fall8024': 'logic.gcommon.behavior.Logic8024',
   'Fall8027': 'logic.gcommon.behavior.Logic8027',
   'Fall8037': 'logic.gcommon.behavior.Logic8037',
   'FallBack': 'logic.gcommon.behavior.Logic8022',
   'FallPure': 'logic.gcommon.behavior.JumpLogic',
   'FallPureWithoutEvent': 'logic.gcommon.behavior.JumpLogic',
   'FallWithForceDec': 'logic.gcommon.behavior.JumpLogic',
   'Flamethrower8012': 'logic.gcommon.behavior.Logic8012',
   'FlightBoost': 'logic.gcommon.behavior.Logic8010',
   'FlightBoost8016': 'logic.gcommon.behavior.Logic8016',
   'FlightLevitate': 'logic.gcommon.behavior.Logic8010',
   'FlyToFan': 'logic.gcommon.behavior.Logic8035',
   'FullForce': 'logic.gcommon.behavior.Logic8009',
   'Glide': 'logic.gcommon.behavior.Logic8006',
   'HeavyMelee': 'logic.gcommon.behavior.MeleeLogic',
   'Help': 'logic.gcommon.behavior.StateLogic',
   'Hit': 'logic.gcommon.behavior.StateLogic',
   'Hover': 'logic.gcommon.behavior.JumpLogic',
   'Hover8022': 'logic.gcommon.behavior.Logic8022',
   'HumanCelebrate': 'logic.gcommon.behavior.MoveLogic',
   'HumanContinueAction': 'logic.gcommon.behavior.StateLogic',
   'HumanCrouch': 'logic.gcommon.behavior.MoveLogic',
   'HumanCrouchRun': 'logic.gcommon.behavior.MoveLogic',
   'HumanCrouchWalk': 'logic.gcommon.behavior.MoveLogic',
   'HumanDash': 'logic.gcommon.behavior.BoostLogic',
   'HumanDie': 'logic.gcommon.behavior.StateLogic',
   'HumanFall': 'logic.gcommon.behavior.JumpLogic',
   'HumanFrozen': 'logic.gcommon.behavior.MoveLogic',
   'HumanHelp': 'logic.gcommon.behavior.StateLogic',
   'HumanHit': 'logic.gcommon.behavior.WeaponLogic10011',
   'HumanJumpUp': 'logic.gcommon.behavior.JumpLogic',
   'HumanOnGround': 'logic.gcommon.behavior.JumpLogic',
   'HumanPerformCustom': 'logic.gcommon.behavior.StateLogic',
   'HumanPerformanceAction': 'logic.gcommon.behavior.MoveLogic',
   'HumanReload': 'logic.gcommon.behavior.WeaponLogic10011',
   'HumanRun': 'logic.gcommon.behavior.MoveLogic',
   'HumanStand': 'logic.gcommon.behavior.MoveLogic',
   'HumanSuperJumpUp': 'logic.gcommon.behavior.JumpLogic',
   'HumanSwitchWeapon': 'logic.gcommon.behavior.WeaponLogic10011',
   'HumanTurn': 'logic.gcommon.behavior.MoveLogic',
   'HumanUseItem': 'logic.gcommon.behavior.StateLogic',
   'HumanWalk': 'logic.gcommon.behavior.MoveLogic',
   'HumanWeaponFire': 'logic.gcommon.behavior.WeaponLogic10011',
   'HumanWeaponLoad': 'logic.gcommon.behavior.WeaponLogic10011',
   'IgniteC48024': 'logic.gcommon.behavior.Logic8024',
   'Immobilize': 'logic.gcommon.behavior.StateLogic',
   'Immobilize8028': 'logic.gcommon.behavior.Logic8028',
   'Immobilize8037': 'logic.gcommon.behavior.Logic8037',
   'InterruptionJumpUp8016': 'logic.gcommon.behavior.Logic8016',
   'Invisibility': 'logic.gcommon.behavior.Logic8023',
   'JetJump': 'logic.gcommon.behavior.JumpLogic',
   'JetJump8004': 'logic.gcommon.behavior.JumpLogic',
   'JetJump8008': 'logic.gcommon.behavior.JumpLogic',
   'JetJump8022': 'logic.gcommon.behavior.Logic8022',
   'JumpCharge': 'logic.gcommon.behavior.Logic8030',
   'JumpUp': 'logic.gcommon.behavior.JumpLogic',
   'JumpUp8001': 'logic.gcommon.behavior.Logic8001',
   'JumpUp8003': 'logic.gcommon.behavior.JumpLogic',
   'JumpUp8006': 'logic.gcommon.behavior.Logic8006',
   'JumpUp8007': 'logic.gcommon.behavior.Logic8007',
   'JumpUp8013': 'logic.gcommon.behavior.Logic8013',
   'JumpUp8016': 'logic.gcommon.behavior.Logic8016',
   'JumpUp8019': 'logic.gcommon.behavior.Logic8019',
   'JumpUp8020': 'logic.gcommon.behavior.Logic8020',
   'JumpUp8023': 'logic.gcommon.behavior.Logic8023',
   'JumpUp8025': 'logic.gcommon.behavior.Logic8025',
   'JumpUp8030': 'logic.gcommon.behavior.Logic8030',
   'JumpUp8033': 'logic.gcommon.behavior.Logic8033',
   'JumpUp8034': 'logic.gcommon.behavior.Logic8034',
   'JumpUp8037': 'logic.gcommon.behavior.Logic8037',
   'JumpUpPure': 'logic.gcommon.behavior.JumpLogic',
   'JumpUpWithForceDec': 'logic.gcommon.behavior.JumpLogic',
   'KeepAimTimer': 'logic.gcommon.behavior.Logic8029',
   'MaxHeat': 'logic.gcommon.behavior.SkillLogic',
   'MechaBoard': 'logic.gcommon.behavior.BoardMechaLogic',
   'MechaCelebrate': 'logic.gcommon.behavior.MoveLogic',
   'MechaDriver': 'logic.gcommon.behavior.BoardMechaLogic',
   'ModeSwitch': 'logic.gcommon.behavior.Logic8020',
   'MonsterAimTurn': 'logic.gcommon.behavior.PVEMonsterAimTurnLogic',
   'MonsterAimTurnBase': 'logic.gcommon.behavior.PVEMonsterAimTurnLogic',
   'MonsterArrayBomb': 'logic.gcommon.behavior.PVEMonsterArrayBombLogic',
   'MonsterArrayBombBase': 'logic.gcommon.behavior.PVEMonsterArrayBombLogic',
   'MonsterBomb': 'logic.gcommon.behavior.PVEMonsterBombLogic',
   'MonsterBombBase': 'logic.gcommon.behavior.PVEMonsterBombLogic',
   'MonsterBoomDie': 'logic.gcommon.behavior.PVEMonsterStateLogic',
   'MonsterBorn': 'logic.gcommon.behavior.PVEMonsterStateLogic',
   'MonsterBornBase': 'logic.gcommon.behavior.PVEMonsterStateLogic',
   'MonsterBramble': 'logic.gcommon.behavior.PVEMonsterBrambleLogic',
   'MonsterBrambleBase': 'logic.gcommon.behavior.PVEMonsterBrambleLogic',
   'MonsterDash': 'logic.gcommon.behavior.PVEMonsterDashLogic',
   'MonsterDashAtk': 'logic.gcommon.behavior.PVEMonsterDashAtkLogic',
   'MonsterDashAtkBase': 'logic.gcommon.behavior.PVEMonsterDashAtkLogic',
   'MonsterDashBase': 'logic.gcommon.behavior.PVEMonsterDashLogic',
   'MonsterDie': 'logic.gcommon.behavior.PVEMonsterStateLogic',
   'MonsterDieBase': 'logic.gcommon.behavior.PVEMonsterStateLogic',
   'MonsterEscape': 'logic.gcommon.behavior.PVEMonsterStateLogic',
   'MonsterEscapeBase': 'logic.gcommon.behavior.PVEMonsterStateLogic',
   'MonsterEvade': 'logic.gcommon.behavior.PVEMonsterEvadeLogic',
   'MonsterEvadeBase': 'logic.gcommon.behavior.PVEMonsterEvadeLogic',
   'MonsterEvadeMelee': 'logic.gcommon.behavior.PVEMonsterEvadeMeleeLogic',
   'MonsterEvadeMeleeBase': 'logic.gcommon.behavior.PVEMonsterEvadeMeleeLogic',
   'MonsterEvadeMissile': 'logic.gcommon.behavior.PVEMonsterEvadeMissileLogic',
   'MonsterEvadeMissileBase': 'logic.gcommon.behavior.PVEMonsterEvadeMissileLogic',
   'MonsterFlame': 'logic.gcommon.behavior.PVEMonsterFlameLogic',
   'MonsterFlameBase': 'logic.gcommon.behavior.PVEMonsterFlameLogic',
   'MonsterFocusSwag': 'logic.gcommon.behavior.PVEMonsterAimTurnLogic',
   'MonsterFocusSwagBase': 'logic.gcommon.behavior.PVEMonsterAimTurnLogic',
   'MonsterHit': 'logic.gcommon.behavior.PVEMonsterHitLogic',
   'MonsterHitBase': 'logic.gcommon.behavior.PVEMonsterHitLogic',
   'MonsterLaser': 'logic.gcommon.behavior.PVEMonsterLaserLogic',
   'MonsterLaserBase': 'logic.gcommon.behavior.PVEMonsterLaserLogic',
   'MonsterLauncher': 'logic.gcommon.behavior.PVEMonsterLauncherLogic',
   'MonsterLauncherBase': 'logic.gcommon.behavior.PVEMonsterLauncherLogic',
   'MonsterLink': 'logic.gcommon.behavior.PVEMonsterLinkLogic',
   'MonsterLinkBase': 'logic.gcommon.behavior.PVEMonsterLinkLogic',
   'MonsterLinkHeal': 'logic.gcommon.behavior.PVEMonsterLinkHealLogic',
   'MonsterLinkHealBase': 'logic.gcommon.behavior.PVEMonsterLinkHealLogic',
   'MonsterMelee': 'logic.gcommon.behavior.PVEMonsterMeleeLogic',
   'MonsterMeleeBase': 'logic.gcommon.behavior.PVEMonsterMeleeLogic',
   'MonsterMortar': 'logic.gcommon.behavior.PVEMonsterMortarLogic',
   'MonsterMortarBase': 'logic.gcommon.behavior.PVEMonsterMortarLogic',
   'MonsterMultiMelee': 'logic.gcommon.behavior.PVEMonsterMultiMeleeLogic',
   'MonsterMultiMeleeBase': 'logic.gcommon.behavior.PVEMonsterMultiMeleeLogic',
   'MonsterMultiRange': 'logic.gcommon.behavior.PVEMonsterMultiRangeLogic',
   'MonsterMultiRangeBase': 'logic.gcommon.behavior.PVEMonsterMultiRangeLogic',
   'MonsterOblique': 'logic.gcommon.behavior.PVEMonsterObliqueLogic',
   'MonsterObliqueBase': 'logic.gcommon.behavior.PVEMonsterObliqueLogic',
   'MonsterPounce': 'logic.gcommon.behavior.PVEMonsterPounceLogic',
   'MonsterPounceBase': 'logic.gcommon.behavior.PVEMonsterPounceLogic',
   'MonsterPounceBomb': 'logic.gcommon.behavior.PVEMonsterPounceBombLogic',
   'MonsterPounceBombBase': 'logic.gcommon.behavior.PVEMonsterPounceBombLogic',
   'MonsterRaiseShield': 'logic.gcommon.behavior.PVEMonsterRaiseShieldLogic',
   'MonsterRaiseShieldBase': 'logic.gcommon.behavior.PVEMonsterRaiseShieldLogic',
   'MonsterRange': 'logic.gcommon.behavior.PVEMonsterRangeLogic',
   'MonsterRangeBase': 'logic.gcommon.behavior.PVEMonsterRangeLogic',
   'MonsterRoar': 'logic.gcommon.behavior.PVEMonsterRoarLogic',
   'MonsterRoarBase': 'logic.gcommon.behavior.PVEMonsterRoarLogic',
   'MonsterRollDash': 'logic.gcommon.behavior.PVEMonsterRollDashLogic',
   'MonsterRollDashBase': 'logic.gcommon.behavior.PVEMonsterRollDashLogic',
   'MonsterRun': 'logic.gcommon.behavior.PVEMonsterMoveLogic',
   'MonsterScout': 'logic.gcommon.behavior.PVEMonsterRoarLogic',
   'MonsterScoutBase': 'logic.gcommon.behavior.PVEMonsterRoarLogic',
   'MonsterSnipe': 'logic.gcommon.behavior.PVEMonsterSnipeLogic',
   'MonsterSnipeBase': 'logic.gcommon.behavior.PVEMonsterSnipeLogic',
   'MonsterSpurt': 'logic.gcommon.behavior.PVEMonsterSpurtLogic',
   'MonsterSpurtBase': 'logic.gcommon.behavior.PVEMonsterSpurtLogic',
   'MonsterStateBase': 'logic.gcommon.behavior.MonsterStateBase',
   'MonsterStun': 'logic.gcommon.behavior.PVEMonsterStunLogic',
   'MonsterStunBase': 'logic.gcommon.behavior.PVEMonsterStunLogic',
   'MonsterSuicide': 'logic.gcommon.behavior.PVEMonsterSuicideLogic',
   'MonsterSuicideBase': 'logic.gcommon.behavior.PVEMonsterSuicideLogic',
   'MonsterSummon': 'logic.gcommon.behavior.PVEMonsterSummonLogic',
   'MonsterSummonBase': 'logic.gcommon.behavior.PVEMonsterSummonLogic',
   'MonsterSweep': 'logic.gcommon.behavior.PVEMonsterSweepLogic',
   'MonsterSweepBase': 'logic.gcommon.behavior.PVEMonsterSweepLogic',
   'MonsterToss': 'logic.gcommon.behavior.PVEMonsterTossLogic',
   'MonsterTossBase': 'logic.gcommon.behavior.PVEMonsterTossLogic',
   'MonsterWalk': 'logic.gcommon.behavior.PVEMonsterMoveLogic',
   'Mount': 'logic.gcommon.behavior.MountLogic',
   'Mount8006': 'logic.gcommon.behavior.Logic8006',
   'MountInFreeSightMode': 'logic.gcommon.behavior.MountLogic',
   'Move8016': 'logic.gcommon.behavior.Logic8016',
   'MoveTurn': 'logic.gcommon.behavior.Logic8022',
   'MultipleJumpUp': 'logic.gcommon.behavior.JumpLogic',
   'NormalMelee': 'logic.gcommon.behavior.MeleeLogic',
   'NormalWhirlwind': 'logic.gcommon.behavior.WhirlwindLogic',
   'OnFrozen': 'logic.gcommon.behavior.StateLogic',
   'OnFrozen8028': 'logic.gcommon.behavior.Logic8028',
   'OnGround': 'logic.gcommon.behavior.JumpLogic',
   'OnGround4108': 'logic.gcommon.behavior.Logic4108',
   'OnGround8004': 'logic.gcommon.behavior.JumpLogic',
   'OnGround8007': 'logic.gcommon.behavior.Logic8007',
   'OnGround8008': 'logic.gcommon.behavior.JumpLogic',
   'OnGround8010': 'logic.gcommon.behavior.Logic8010',
   'OnGround8016': 'logic.gcommon.behavior.Logic8016',
   'OnGround8019': 'logic.gcommon.behavior.Logic8019',
   'OnGround8020': 'logic.gcommon.behavior.Logic8020',
   'OnGround8032': 'logic.gcommon.behavior.Logic8032',
   'OnGround8033': 'logic.gcommon.behavior.Logic8033',
   'OnGround8034': 'logic.gcommon.behavior.Logic8034',
   'OnGroundPure': 'logic.gcommon.behavior.JumpLogic',
   'OpenAimCamera': 'logic.gcommon.behavior.Logic8007',
   'OpenAimCamera8023': 'logic.gcommon.behavior.Logic8023',
   'OxRush8004': 'logic.gcommon.behavior.Logic8004',
   'OxRushNew': 'logic.gcommon.behavior.BoostLogic',
   'OxRushNew8015': 'logic.gcommon.behavior.Logic8015',
   'OxRushNew8018': 'logic.gcommon.behavior.Logic8018',
   'OxRushNew8027': 'logic.gcommon.behavior.Logic8027',
   'Parachute': 'logic.gcommon.behavior.Logic10011',
   'PetHide': 'logic.gcommon.behavior.PetLogic',
   'PetIdle': 'logic.gcommon.behavior.PetLogic',
   'PetMove': 'logic.gcommon.behavior.PetLogic',
   'PetShow': 'logic.gcommon.behavior.PetLogic',
   'Phantom': 'logic.gcommon.behavior.Logic8029',
   'PhotonAttack': 'logic.gcommon.behavior.SkillLogic',
   'PhotonReload': 'logic.gcommon.behavior.SkillLogic',
   'PhotonShield': 'logic.gcommon.behavior.SkillLogic',
   'Pick': 'logic.gcommon.behavior.Logic10011',
   'PoisonJump8034': 'logic.gcommon.behavior.Logic8034',
   'ReaperShape': 'logic.gcommon.behavior.Logic8031',
   'ReaperSlash': 'logic.gcommon.behavior.Logic8031',
   'RecoverSecondWeapon': 'logic.gcommon.behavior.Logic8006',
   'Reload': 'logic.gcommon.behavior.ShootLogic',
   'Reload4108': 'logic.gcommon.behavior.Logic4108',
   'Reload4108Seat': 'logic.gcommon.behavior.Logic4108',
   'Reload8007': 'logic.gcommon.behavior.Logic8007',
   'Reload8009': 'logic.gcommon.behavior.Logic8009',
   'Reload8011': 'logic.gcommon.behavior.Logic8011',
   'Reload8014': 'logic.gcommon.behavior.Logic8014',
   'Reload8016': 'logic.gcommon.behavior.Logic8016',
   'Reload8017': 'logic.gcommon.behavior.Logic8017',
   'Reload8019': 'logic.gcommon.behavior.Logic8019',
   'Reload8022': 'logic.gcommon.behavior.Logic8022',
   'Reload8023': 'logic.gcommon.behavior.Logic8023',
   'Reload8024': 'logic.gcommon.behavior.Logic8024',
   'Reload8025': 'logic.gcommon.behavior.Logic8025',
   'Reload8026': 'logic.gcommon.behavior.Logic8026',
   'Reload8027': 'logic.gcommon.behavior.Logic8027',
   'Reload8028': 'logic.gcommon.behavior.Logic8028',
   'Reload8029': 'logic.gcommon.behavior.Logic8029',
   'Reload8031': 'logic.gcommon.behavior.Logic8031',
   'Reload8032': 'logic.gcommon.behavior.Logic8032',
   'Reload8033': 'logic.gcommon.behavior.Logic8033',
   'Reload8035': 'logic.gcommon.behavior.Logic8035',
   'Reload8036': 'logic.gcommon.behavior.Logic8036',
   'RightAim': 'logic.gcommon.behavior.Logic10011',
   'RightAim4108': 'logic.gcommon.behavior.Logic4108',
   'RightAim4108Seat': 'logic.gcommon.behavior.Logic4108',
   'RisingDragon': 'logic.gcommon.behavior.Logic8011',
   'RocketJump': 'logic.gcommon.behavior.Logic8005',
   'Roll': 'logic.gcommon.behavior.Logic10011',
   'Roll8036': 'logic.gcommon.behavior.Logic8036',
   'Run': 'logic.gcommon.behavior.MoveLogic',
   'Run4108': 'logic.gcommon.behavior.Logic4108',
   'Run8009': 'logic.gcommon.behavior.Logic8009',
   'Run8016': 'logic.gcommon.behavior.Logic8016',
   'Run8019': 'logic.gcommon.behavior.Logic8019',
   'Run8021': 'logic.gcommon.behavior.Logic8021',
   'Run8022': 'logic.gcommon.behavior.Logic8022',
   'Run8024': 'logic.gcommon.behavior.Logic8024',
   'Run8028': 'logic.gcommon.behavior.Logic8028',
   'Run8029': 'logic.gcommon.behavior.Logic8029',
   'Run8030': 'logic.gcommon.behavior.Logic8030',
   'Run8032': 'logic.gcommon.behavior.Logic8032',
   'Run8033': 'logic.gcommon.behavior.Logic8033',
   'Run8035': 'logic.gcommon.behavior.Logic8035',
   'Run8036': 'logic.gcommon.behavior.Logic8036',
   'SeatStand': 'logic.gcommon.behavior.Logic4108',
   'SequenceShoot': 'logic.gcommon.behavior.ShootLogic',
   'SequenceShoot8013': 'logic.gcommon.behavior.Logic8013',
   'SequenceShoot8018': 'logic.gcommon.behavior.Logic8018',
   'Shield8026': 'logic.gcommon.behavior.Logic8026',
   'ShieldShoot': 'logic.gcommon.behavior.Logic8026',
   'ShiranuiFan': 'logic.gcommon.behavior.Logic8035',
   'ShootModeChange': 'logic.gcommon.behavior.ShootLogic',
   'ShotGunLoad': 'logic.gcommon.behavior.Logic8029',
   'ShoulderGrenade': 'logic.gcommon.behavior.Logic8009',
   'Skate': 'logic.gcommon.behavior.SkateLogic',
   'Slash8021': 'logic.gcommon.behavior.Logic8021',
   'SlashJump8021': 'logic.gcommon.behavior.Logic8021',
   'SprintFall': 'logic.gcommon.behavior.Logic8032',
   'SprintOnGround': 'logic.gcommon.behavior.Logic8032',
   'SprintSuperJumpUp': 'logic.gcommon.behavior.Logic8032',
   'Stand': 'logic.gcommon.behavior.MoveLogic',
   'Stand4108': 'logic.gcommon.behavior.Logic4108',
   'Stand8020': 'logic.gcommon.behavior.Logic8020',
   'Stand8024': 'logic.gcommon.behavior.Logic8024',
   'Stand8030': 'logic.gcommon.behavior.Logic8030',
   'StandVehicle': 'logic.gcommon.behavior.MoveLogic',
   'StandWithGuard': 'logic.gcommon.behavior.Logic8011',
   'StandWithGuard8027': 'logic.gcommon.behavior.Logic8027',
   'StandWithGuard8028': 'logic.gcommon.behavior.Logic8028',
   'StandWithGuard8034': 'logic.gcommon.behavior.Logic8034',
   'StateBase': 'logic.gcommon.behavior.StateBase',
   'SuicideState': 'logic.gcommon.behavior.Logic8024',
   'SummonWall': 'logic.gcommon.behavior.Logic8037',
   'SuperJump8016': 'logic.gcommon.behavior.Logic8016',
   'SuperJumpUp': 'logic.gcommon.behavior.JumpLogic',
   'SuperJumpUp8005': 'logic.gcommon.behavior.Logic8005',
   'SuperJumpUp8006': 'logic.gcommon.behavior.Logic8006',
   'SuperJumpUp8007': 'logic.gcommon.behavior.Logic8007',
   'SuperJumpUp8010': 'logic.gcommon.behavior.Logic8010',
   'SuperJumpUp8020': 'logic.gcommon.behavior.Logic8020',
   'SuperJumpUpPure': 'logic.gcommon.behavior.JumpLogic',
   'SuperJumpUpWithForceDec': 'logic.gcommon.behavior.JumpLogic',
   'SuspendRadialWeapon': 'logic.gcommon.behavior.Logic8017',
   'Swim': 'logic.gcommon.behavior.Logic10011',
   'SwitchDragonShape': 'logic.gcommon.behavior.Logic8011',
   'SwitchFullForce': 'logic.gcommon.behavior.Logic8009',
   'SwitchReaperShape': 'logic.gcommon.behavior.Logic8031',
   'SwitchWeapon8023': 'logic.gcommon.behavior.Logic8023',
   'SwitchWeapon8029': 'logic.gcommon.behavior.Logic8029',
   'SwitchWeaponMode': 'logic.gcommon.behavior.WeaponLogic10011',
   'SwordCore': 'logic.gcommon.behavior.SkillLogic',
   'SwordEnergy': 'logic.gcommon.behavior.SkillLogic',
   'TetrapodDash': 'logic.gcommon.behavior.Logic8032',
   'TetrapodForceSprint': 'logic.gcommon.behavior.Logic8032',
   'TetrapodReloadShoot': 'logic.gcommon.behavior.Logic8032',
   'TetrapodShoot': 'logic.gcommon.behavior.Logic8032',
   'TetrapodSprint': 'logic.gcommon.behavior.Logic8032',
   'TetrapodSprintDash': 'logic.gcommon.behavior.Logic8032',
   'TetrapodSprintShoot': 'logic.gcommon.behavior.Logic8032',
   'TetrapodSwitch': 'logic.gcommon.behavior.Logic8032',
   'ThrowGrenade8023': 'logic.gcommon.behavior.Logic8023',
   'ThrowGrenade8024': 'logic.gcommon.behavior.Logic8024',
   'ThrowGrenade8033': 'logic.gcommon.behavior.Logic8033',
   'Transform': 'logic.gcommon.behavior.TransformLogic',
   'TransformFlight': 'logic.gcommon.behavior.Logic8010',
   'TrioSwitchWeapon': 'logic.gcommon.behavior.Logic8009',
   'Turn': 'logic.gcommon.behavior.MoveLogic',
   'Turn4108': 'logic.gcommon.behavior.Logic4108',
   'Turn4108Seat': 'logic.gcommon.behavior.Logic4108',
   'Turn8019': 'logic.gcommon.behavior.Logic8019',
   'UnMount': 'logic.gcommon.behavior.MountLogic',
   'UnMount8009': 'logic.gcommon.behavior.Logic8009',
   'UnMount8020': 'logic.gcommon.behavior.Logic8020',
   'UnMount8022': 'logic.gcommon.behavior.Logic8022',
   'UseItem': 'logic.gcommon.behavior.StateLogic',
   'VehicleGunner': 'logic.gcommon.behavior.BoardMechaLogic',
   'VehiclePassenger': 'logic.gcommon.behavior.BoardMechaLogic',
   'Walk': 'logic.gcommon.behavior.MoveLogic',
   'Walk4108': 'logic.gcommon.behavior.Logic4108',
   'Walk8010': 'logic.gcommon.behavior.Logic8010',
   'Walk8022': 'logic.gcommon.behavior.Logic8022',
   'Walk8023': 'logic.gcommon.behavior.Logic8023',
   'Walk8025': 'logic.gcommon.behavior.Logic8025',
   'Walk8026': 'logic.gcommon.behavior.Logic8026',
   'Walk8031': 'logic.gcommon.behavior.Logic8031',
   'Walk8037': 'logic.gcommon.behavior.Logic8037',
   'WeaponAccumulate': 'logic.gcommon.behavior.Logic10011',
   'WeaponFire': 'logic.gcommon.behavior.ShootLogic',
   'WeaponFire4108': 'logic.gcommon.behavior.Logic4108',
   'WeaponFire4108Seat': 'logic.gcommon.behavior.Logic4108',
   'WeaponFire8001': 'logic.gcommon.behavior.Logic8001',
   'WeaponFire8004': 'logic.gcommon.behavior.Logic8004',
   'WeaponFire8010': 'logic.gcommon.behavior.Logic8010',
   'WeaponFire8012': 'logic.gcommon.behavior.Logic8012',
   'WeaponFire8014': 'logic.gcommon.behavior.Logic8014',
   'WeaponFire8015': 'logic.gcommon.behavior.Logic8015',
   'WeaponFire8016': 'logic.gcommon.behavior.Logic8016',
   'WeaponFire8017': 'logic.gcommon.behavior.Logic8017',
   'WeaponFire8019': 'logic.gcommon.behavior.Logic8019',
   'WeaponFire8020': 'logic.gcommon.behavior.Logic8020',
   'WeaponFire8021': 'logic.gcommon.behavior.Logic8021',
   'WeaponFire8022': 'logic.gcommon.behavior.Logic8022',
   'WeaponFire8023': 'logic.gcommon.behavior.Logic8023',
   'WeaponFire8026': 'logic.gcommon.behavior.Logic8026',
   'WeaponFire8028': 'logic.gcommon.behavior.Logic8028',
   'WeaponFire8029': 'logic.gcommon.behavior.Logic8029',
   'WeaponFire8033': 'logic.gcommon.behavior.Logic8033',
   'WeaponFire8036': 'logic.gcommon.behavior.Logic8036',
   'WeaponRecharge': 'logic.gcommon.behavior.Logic8036'
   }
module_path_to_state_name_list_map = {'logic.gcommon.behavior.BoardMechaLogic': ('ControllingSpecialWeapon', 'MechaBoard', 'MechaDriver', 'VehicleGunner', 'VehiclePassenger'),
   'logic.gcommon.behavior.BoostLogic': ('Catapult', 'CommonDash', 'Dash', 'DashVehicle', 'HumanDash', 'OxRushNew'),
   'logic.gcommon.behavior.CastLogic': ('AccumulateCastGrenade', 'CastGrenade', 'CastSkill', 'CastSkillClient'),
   'logic.gcommon.behavior.EditorCustomLogic': ('CustomDisplacement', ),
   'logic.gcommon.behavior.JumpLogic': ('Fall', 'Fall8004', 'Fall8008', 'FallPure', 'FallPureWithoutEvent', 'FallWithForceDec',
 'Hover', 'HumanFall', 'HumanJumpUp', 'HumanOnGround', 'HumanSuperJumpUp', 'JetJump',
 'JetJump8004', 'JetJump8008', 'JumpUp', 'JumpUp8003', 'JumpUpPure', 'JumpUpWithForceDec',
 'MultipleJumpUp', 'OnGround', 'OnGround8004', 'OnGround8008', 'OnGroundPure', 'SuperJumpUp',
 'SuperJumpUpPure', 'SuperJumpUpWithForceDec'),
   'logic.gcommon.behavior.Logic10011': ('Aim', 'Climb', 'Parachute', 'Pick', 'RightAim', 'Roll', 'Swim', 'WeaponAccumulate'),
   'logic.gcommon.behavior.Logic4108': ('DashMotorcycle', 'Die4108', 'Fall4108', 'OnGround4108', 'Reload4108', 'Reload4108Seat',
 'RightAim4108', 'RightAim4108Seat', 'Run4108', 'SeatStand', 'Stand4108', 'Turn4108',
 'Turn4108Seat', 'Walk4108', 'WeaponFire4108', 'WeaponFire4108Seat'),
   'logic.gcommon.behavior.Logic8001': ('Dash8001', 'JumpUp8001', 'WeaponFire8001'),
   'logic.gcommon.behavior.Logic8004': ('OxRush8004', 'WeaponFire8004'),
   'logic.gcommon.behavior.Logic8005': ('RocketJump', 'SuperJumpUp8005'),
   'logic.gcommon.behavior.Logic8006': ('AccumulateShoot8006', 'DashBuff', 'Fall8006', 'Glide', 'JumpUp8006', 'Mount8006',
 'RecoverSecondWeapon', 'SuperJumpUp8006'),
   'logic.gcommon.behavior.Logic8007': ('Dash8007', 'Fall8007', 'JumpUp8007', 'OnGround8007', 'OpenAimCamera', 'Reload8007',
 'SuperJumpUp8007'),
   'logic.gcommon.behavior.Logic8009': ('FullForce', 'Reload8009', 'Run8009', 'ShoulderGrenade', 'SwitchFullForce', 'TrioSwitchWeapon',
 'UnMount8009'),
   'logic.gcommon.behavior.Logic8010': ('Dash8010', 'Fall8010', 'FlightBoost', 'FlightLevitate', 'OnGround8010', 'SuperJumpUp8010',
 'TransformFlight', 'Walk8010', 'WeaponFire8010'),
   'logic.gcommon.behavior.Logic8011': ('AccumulateShoot8011', 'ActionDrivenWeaponFire', 'DragonRush', 'DragonShape', 'DragonSidestep',
 'Reload8011', 'RisingDragon', 'StandWithGuard', 'SwitchDragonShape'),
   'logic.gcommon.behavior.Logic8012': ('BallDash', 'Dash8012', 'Flamethrower8012', 'WeaponFire8012'),
   'logic.gcommon.behavior.Logic8013': ('AccumulateShoot8013', 'Dash8013', 'JumpUp8013', 'SequenceShoot8013'),
   'logic.gcommon.behavior.Logic8014': ('BladeSlash', 'BurstForm', 'DashBladeSlash', 'Reload8014', 'WeaponFire8014'),
   'logic.gcommon.behavior.Logic8015': ('OxRushNew8015', 'WeaponFire8015'),
   'logic.gcommon.behavior.Logic8016': ('AccumulateFire8016', 'AccumulateSkill8016', 'AimIKBase', 'ChangeWeaponState', 'Fall8016',
 'FlightBoost8016', 'InterruptionJumpUp8016', 'JumpUp8016', 'Move8016', 'OnGround8016',
 'Reload8016', 'Run8016', 'SuperJump8016', 'WeaponFire8016'),
   'logic.gcommon.behavior.Logic8017': ('AccumulateShoot8017', 'ComboSecondWeapon', 'Dash8017', 'EnhanceWeaponFire', 'Fall8017',
 'Reload8017', 'SuspendRadialWeapon', 'WeaponFire8017'),
   'logic.gcommon.behavior.Logic8018': ('OxRushNew8018', 'SequenceShoot8018'),
   'logic.gcommon.behavior.Logic8019': ('AccumulateShoot8019', 'Dash8019', 'Defend', 'Fall8019', 'JumpUp8019', 'OnGround8019',
 'Reload8019', 'Run8019', 'Turn8019', 'WeaponFire8019'),
   'logic.gcommon.behavior.Logic8020': ('AccumulateShoot8020', 'CarFall', 'CarMode', 'CarOnGround', 'CarSuperJumpUp', 'Dash8020',
 'Fall8020', 'JumpUp8020', 'ModeSwitch', 'OnGround8020', 'Stand8020', 'SuperJumpUp8020',
 'UnMount8020', 'WeaponFire8020'),
   'logic.gcommon.behavior.Logic8021': ('Run8021', 'Slash8021', 'SlashJump8021', 'WeaponFire8021'),
   'logic.gcommon.behavior.Logic8022': ('AccumulateShoot8022', 'AirDash', 'CannonShape', 'CannonSwitch', 'Dash8022', 'DashFall8022',
 'Die8022', 'Fall8022', 'FallBack', 'Hover8022', 'JetJump8022', 'MoveTurn', 'Reload8022',
 'Run8022', 'UnMount8022', 'Walk8022', 'WeaponFire8022'),
   'logic.gcommon.behavior.Logic8023': ('BoltAction', 'DashBuff8023', 'Invisibility', 'JumpUp8023', 'OpenAimCamera8023', 'Reload8023',
 'SwitchWeapon8023', 'ThrowGrenade8023', 'Walk8023', 'WeaponFire8023'),
   'logic.gcommon.behavior.Logic8024': ('ActionDrivenWeaponFire8024', 'Dash8024', 'Fall8024', 'IgniteC48024', 'Reload8024',
 'Run8024', 'Stand8024', 'SuicideState', 'ThrowGrenade8024'),
   'logic.gcommon.behavior.Logic8025': ('Dash8025', 'ExternShoulderGrenade8025', 'JumpUp8025', 'Reload8025', 'Walk8025'),
   'logic.gcommon.behavior.Logic8026': ('Dash8026', 'Reload8026', 'Shield8026', 'ShieldShoot', 'Walk8026', 'WeaponFire8026'),
   'logic.gcommon.behavior.Logic8027': ('ContinuousShoot8027', 'Fall8027', 'OxRushNew8027', 'Reload8027', 'StandWithGuard8027'),
   'logic.gcommon.behavior.Logic8028': ('AccumulateShoot8028', 'BeatBack8028', 'Dash8028', 'DashPostAction8028', 'DashPreAction8028',
 'FairyFall', 'FairyHover', 'FairyRise', 'FairyShape', 'FairySwitch', 'Immobilize8028',
 'OnFrozen8028', 'Reload8028', 'Run8028', 'StandWithGuard8028', 'WeaponFire8028'),
   'logic.gcommon.behavior.Logic8029': ('AccumulateShoot8029', 'KeepAimTimer', 'Phantom', 'Reload8029', 'Run8029', 'ShotGunLoad',
 'SwitchWeapon8029', 'WeaponFire8029'),
   'logic.gcommon.behavior.Logic8030': ('ClusterShoot', 'Dash8030', 'ExternBoneAnim', 'JumpCharge', 'JumpUp8030', 'Run8030',
 'Stand8030'),
   'logic.gcommon.behavior.Logic8031': ('ActionDrivenWeaponFire8031', 'Dash8031', 'ReaperShape', 'ReaperSlash', 'Reload8031',
 'SwitchReaperShape', 'Walk8031'),
   'logic.gcommon.behavior.Logic8032': ('AccumulateShoot8032', 'OnGround8032', 'Reload8032', 'Run8032', 'SprintFall', 'SprintOnGround',
 'SprintSuperJumpUp', 'TetrapodDash', 'TetrapodForceSprint', 'TetrapodReloadShoot',
 'TetrapodShoot', 'TetrapodSprint', 'TetrapodSprintDash', 'TetrapodSprintShoot',
 'TetrapodSwitch'),
   'logic.gcommon.behavior.Logic8033': ('CarDash8033', 'CarMode8033', 'CarSwitch', 'CarWeaponFire8033', 'DownpourShell', 'JumpUp8033',
 'OnGround8033', 'Reload8033', 'Run8033', 'ThrowGrenade8033', 'WeaponFire8033'),
   'logic.gcommon.behavior.Logic8034': ('ClusterShoot8034', 'JumpUp8034', 'OnGround8034', 'PoisonJump8034', 'StandWithGuard8034'),
   'logic.gcommon.behavior.Logic8035': ('AccumulateShoot8035', 'ActionDrivenWeaponFire8035', 'Dash8035', 'FlyToFan', 'Reload8035',
 'Run8035', 'ShiranuiFan'),
   'logic.gcommon.behavior.Logic8036': ('AccumulateShoot8036', 'AccumulateViceShoot', 'Reload8036', 'Roll8036', 'Run8036',
 'WeaponFire8036', 'WeaponRecharge'),
   'logic.gcommon.behavior.Logic8037': ('AccumulateShoot8037', 'Dash8037', 'Fall8037', 'Immobilize8037', 'JumpUp8037', 'SummonWall',
 'Walk8037'),
   'logic.gcommon.behavior.MeleeLogic': ('CutTrack', 'HeavyMelee', 'NormalMelee'),
   'logic.gcommon.behavior.MonsterStateBase': ('MonsterStateBase', ),
   'logic.gcommon.behavior.MountLogic': ('Mount', 'MountInFreeSightMode', 'UnMount'),
   'logic.gcommon.behavior.MoveLogic': ('Down', 'DownToStand', 'HumanCelebrate', 'HumanCrouch', 'HumanCrouchRun', 'HumanCrouchWalk',
 'HumanFrozen', 'HumanPerformanceAction', 'HumanRun', 'HumanStand', 'HumanTurn',
 'HumanWalk', 'MechaCelebrate', 'Run', 'Stand', 'StandVehicle', 'Turn', 'Walk'),
   'logic.gcommon.behavior.PVEBossDashRocketLogic': ('BossDashRocket', 'BossDashRocketBase'),
   'logic.gcommon.behavior.PVEBossExcaliburLogic': ('BossExcalibur', 'BossExcaliburBase'),
   'logic.gcommon.behavior.PVEBossFlashDashLogic': ('BossFlashDash', 'BossFlashDashBase'),
   'logic.gcommon.behavior.PVEBossMultiLaserLogic': ('BossMultiLaser', 'BossMultiLaserBase'),
   'logic.gcommon.behavior.PVEBossRangePounceLogic': ('BossRangePounce', 'BossRangePounceBase'),
   'logic.gcommon.behavior.PVEBossSecondStageLogic': ('BossInvincible', 'BossInvincibleBase', 'BossSecondStage', 'BossSecondStageBase'),
   'logic.gcommon.behavior.PVEBossShieldTowerLogic': ('BossShieldTower', ),
   'logic.gcommon.behavior.PVEMonsterAimTurnLogic': ('MonsterAimTurn', 'MonsterAimTurnBase', 'MonsterFocusSwag', 'MonsterFocusSwagBase'),
   'logic.gcommon.behavior.PVEMonsterArrayBombLogic': ('MonsterArrayBomb', 'MonsterArrayBombBase'),
   'logic.gcommon.behavior.PVEMonsterBombLogic': ('MonsterBomb', 'MonsterBombBase'),
   'logic.gcommon.behavior.PVEMonsterBrambleLogic': ('MonsterBramble', 'MonsterBrambleBase'),
   'logic.gcommon.behavior.PVEMonsterDashAtkLogic': ('MonsterDashAtk', 'MonsterDashAtkBase'),
   'logic.gcommon.behavior.PVEMonsterDashLogic': ('MonsterDash', 'MonsterDashBase'),
   'logic.gcommon.behavior.PVEMonsterEvadeLogic': ('MonsterEvade', 'MonsterEvadeBase'),
   'logic.gcommon.behavior.PVEMonsterEvadeMeleeLogic': ('MonsterEvadeMelee', 'MonsterEvadeMeleeBase'),
   'logic.gcommon.behavior.PVEMonsterEvadeMissileLogic': ('MonsterEvadeMissile', 'MonsterEvadeMissileBase'),
   'logic.gcommon.behavior.PVEMonsterFlameLogic': ('MonsterFlame', 'MonsterFlameBase'),
   'logic.gcommon.behavior.PVEMonsterHitLogic': ('MonsterHit', 'MonsterHitBase'),
   'logic.gcommon.behavior.PVEMonsterLaserLogic': ('MonsterLaser', 'MonsterLaserBase'),
   'logic.gcommon.behavior.PVEMonsterLauncherLogic': ('MonsterLauncher', 'MonsterLauncherBase'),
   'logic.gcommon.behavior.PVEMonsterLinkHealLogic': ('MonsterLinkHeal', 'MonsterLinkHealBase'),
   'logic.gcommon.behavior.PVEMonsterLinkLogic': ('MonsterLink', 'MonsterLinkBase'),
   'logic.gcommon.behavior.PVEMonsterMeleeLogic': ('MonsterMelee', 'MonsterMeleeBase'),
   'logic.gcommon.behavior.PVEMonsterMortarLogic': ('MonsterMortar', 'MonsterMortarBase'),
   'logic.gcommon.behavior.PVEMonsterMoveLogic': ('MonsterRun', 'MonsterWalk'),
   'logic.gcommon.behavior.PVEMonsterMultiMeleeLogic': ('MonsterMultiMelee', 'MonsterMultiMeleeBase'),
   'logic.gcommon.behavior.PVEMonsterMultiRangeLogic': ('MonsterMultiRange', 'MonsterMultiRangeBase'),
   'logic.gcommon.behavior.PVEMonsterObliqueLogic': ('MonsterOblique', 'MonsterObliqueBase'),
   'logic.gcommon.behavior.PVEMonsterPounceBombLogic': ('MonsterPounceBomb', 'MonsterPounceBombBase'),
   'logic.gcommon.behavior.PVEMonsterPounceLogic': ('MonsterPounce', 'MonsterPounceBase'),
   'logic.gcommon.behavior.PVEMonsterRaiseShieldLogic': ('MonsterRaiseShield', 'MonsterRaiseShieldBase'),
   'logic.gcommon.behavior.PVEMonsterRangeLogic': ('MonsterRange', 'MonsterRangeBase'),
   'logic.gcommon.behavior.PVEMonsterRoarLogic': ('MonsterRoar', 'MonsterRoarBase', 'MonsterScout', 'MonsterScoutBase'),
   'logic.gcommon.behavior.PVEMonsterRollDashLogic': ('MonsterRollDash', 'MonsterRollDashBase'),
   'logic.gcommon.behavior.PVEMonsterSnipeLogic': ('MonsterSnipe', 'MonsterSnipeBase'),
   'logic.gcommon.behavior.PVEMonsterSpurtLogic': ('MonsterSpurt', 'MonsterSpurtBase'),
   'logic.gcommon.behavior.PVEMonsterStateLogic': ('MonsterBoomDie', 'MonsterBorn', 'MonsterBornBase', 'MonsterDie', 'MonsterDieBase',
 'MonsterEscape', 'MonsterEscapeBase'),
   'logic.gcommon.behavior.PVEMonsterStunLogic': ('MonsterStun', 'MonsterStunBase'),
   'logic.gcommon.behavior.PVEMonsterSuicideLogic': ('MonsterSuicide', 'MonsterSuicideBase'),
   'logic.gcommon.behavior.PVEMonsterSummonLogic': ('MonsterSummon', 'MonsterSummonBase'),
   'logic.gcommon.behavior.PVEMonsterSweepLogic': ('MonsterSweep', 'MonsterSweepBase'),
   'logic.gcommon.behavior.PVEMonsterTossLogic': ('MonsterToss', 'MonsterTossBase'),
   'logic.gcommon.behavior.PetLogic': ('PetHide', 'PetIdle', 'PetMove', 'PetShow'),
   'logic.gcommon.behavior.ShootLogic': ('AccumulateShoot', 'AccumulateShootHover', 'AccumulateShootPure', 'Reload', 'SequenceShoot',
 'ShootModeChange', 'WeaponFire'),
   'logic.gcommon.behavior.SkateLogic': ('Skate', ),
   'logic.gcommon.behavior.SkillLogic': ('AccumulateSkill', 'AccumulateSkill_M8', 'CommonCastSkill', 'MaxHeat', 'PhotonAttack',
 'PhotonReload', 'PhotonShield', 'SwordCore', 'SwordEnergy'),
   'logic.gcommon.behavior.StateBase': ('StateBase', ),
   'logic.gcommon.behavior.StateLogic': ('BeatBack', 'Born', 'Die', 'Help', 'Hit', 'HumanContinueAction', 'HumanDie', 'HumanHelp',
 'HumanPerformCustom', 'HumanUseItem', 'Immobilize', 'OnFrozen', 'UseItem'),
   'logic.gcommon.behavior.TransformLogic': ('Transform', ),
   'logic.gcommon.behavior.WeaponLogic10011': ('HumanHit', 'HumanReload', 'HumanSwitchWeapon', 'HumanWeaponFire', 'HumanWeaponLoad',
 'SwitchWeaponMode'),
   'logic.gcommon.behavior.WhirlwindLogic': ('NormalWhirlwind', )
   }