# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/common_const/ui_operation_const.py
from __future__ import absolute_import
_reload_all = True
import math
LF_OPE_KEY = 'setting/left_fire'
LEFT_FIRE_ALWAYS_OPEN = 1
LEFT_FIRE_SHOW_WHEN_AIM = 2
LEFT_FIRE_ALWAYS_CLOSE = 0
LF_ONLY_SHOT = 1
LF_SHOT_AND_MOVE = 2
LF_OPE_DEF = [LEFT_FIRE_ALWAYS_OPEN, LF_ONLY_SHOT]
GYROSCOPE_STATE_KEY = 'setting/gyroscope'
OPEN_CONDITION_NONE = 0
OPEN_CONDITION_OPEN = 1
OPEN_CONDITION_AIM_OPEN = 2
AXIS_REVERSE = True
AXIS_NORMAL = False
GYROSCOPE_DEF_SETTING = [OPEN_CONDITION_NONE, AXIS_NORMAL, AXIS_REVERSE]
SMALL_MAP_ROTATE = 'setting/smallmap_rotate'
SMALL_MAP_ROTATE_ENABLE = False
TEAMMATE_DANMU = 'setting/teammate_danmu'
TEAMMATE_DANMU_ENABLE = False
DANMU_SHOW_DEFAULT_HEAD = 'setting/danmu_show_default_head'
PVE_RADAR_MAP_TYPE = 'setting/pve_radar_map_type'
PVE_RADAR_MAP_TYPE_ENABLE = True
PVE_MECHA_RADAR = 'setting/pve_mecha_radar'
PVE_MECHA_RADAR_NONE = 0
PVE_MECHA_RADAR_2D = 1
PVE_MECHA_RADAR_3D = 2
CHANGE_MECHA_SKIN_IN_BATTLE = 'setting/change_mecha_skin_in_battle'
CHANGE_MECHA_SKIN_IN_BATTLE_DEFAULT = True
AUTO_OPEN_DOOR = 'setting/auto_open_door'
AUTO_OPEN_DOOR_DEFAULT = True
AUTO_CLIMB = 'setting/auto_climb'
BIT_MODE = 'setting/bit_mode'
AIM_HELPER_KEY = 'setting/aim_helper'
AIM_HELPER_KEY_DEFAULT = True
AIM_HELPER_KEY_1 = 'setting/aim_helper_1'
AUTO_PICK_KEY = 'setting/auto_pick'
WEAPON_PICK_DIRECTLY_REPLACE_KEY = 'setting/weapon_pick_replace'
SOUND_VISIBLE_IN_MAP_KEY = 'setting/sound_visible_in_map'
AUTO_SHOW_PLANE_BIG_MAP = 'setting/auto_show_plane_big_map'
AUTO_SHOW_PLANE_BIG_MAP_DEFAULT = False
SOUND_VISIBLE_3D_KEY = 'setting/sound_visible_3d'
SOUND_VISIBLE_3D_KEY_DEFAULT = True
INJURE_VISIBLE_3D_KEY = 'setting/injure_visible_3d'
INJURE_VISIBLE_3D_KEY_DEFAULT = True
SOUND_TIP_CD = 'setting/sound_tip_cd'
SOUND_TIP_CD_DEFAULT = True
REVEAL_HISTORY_RECORD_KEY = 'setting/reveal_history_record'
REVEAL_HISTORY_RECORD_DEFAULT = True
REVEAL_INTIMACY_RELATION_KEY = 'setting/reveal_intimacy_relation'
REVEAL_INTIMACY_RELATION_DEFAULT = True
ENABLE_STRANGER_ADD_FRIEND = 'setting/enable_stranger_add_friend'
ENABLE_STRANGER_ADD_FRIEND_DEFAULT = True
SHIELD_STRANGER_MSG_KEY = 'setting/shield_stranger_msg'
SHIELD_STRANGER_MSG_DEFAULT = False
ENABLE_BE_SPECTATED_KEY = 'setting/enable_be_spectated'
ENABLE_BE_SPECTATED_DEFAULT = True
REVEAL_MECHA_MEMORY_RECORD_KEY = 'setting/reveal_mecha_memory_record'
REVEAL_MECHA_MEMORY_DEFAULT = False
BLOCK_ALL_MSG_KEY = 'setting/shield_all_msg'
BLOCK_ALL_MSG_DEFAULT = False
UNDERAGE_MODE_KEY = 'setting/underage_mode'
UNDERAGE_MODE_DEFAULT = ''
TEAM_ONLY_FRIEND_KEY = 'setting/team_only_friend'
TEAM_ONLY_FRIEND_DEFAULT = False
FREE_SIGHT_KEY = 'setting/free_sight'
FS_ONLY_ROCKER = 1
FS_ROCKER_AND_SWITCH = 2
FREE_SIGHT_DEF_SETTING = FS_ONLY_ROCKER
ROCKER_DASH = 'setting/rocker_dash'
ROCKER_DASH_DEFAULT = False
ITEM_SHORT_CUT = 'setting/item_short_cut'
ITEM_SHORT_CUT_ENABLE = True
MALL_RECOMMEND = 'setting/mall_recommend'
SS_SKIN_BATTLE_MSG_SHOW = 'setting/ss_skin_battle_msg_show'
USER_LOGINED_BEFORE_KEY_FORMAT = 'user_%s_logined_before'
SHORTCUT_ORDER = 'setting/shortcut_order'
BLOCK_STRANGER_VISIT = 'setting/block_stranger_visit'
ENABLE_STRANGER_LEFT_MSG = 'setting/enable_stranger_left_msg'
ENABLE_REWARD_FRIEND_REPORT = 'setting/enable_reward_friend_report'
ENABLE_PET_TRANSPARENT = 'setting/enable_pet_transparent'
ENABLE_PET_INTERACT_IN_BATTLE = 'setting/enable_pet_interact_in_battle'
WEAPON_AIM_ROCKER_DRAG_ENABLE_KEY = 'setting/enable_weapon_aim_rocker_drag'
WEAPON_AIM_PRESS_TRIGGER_KEY = 'setting/weapon_aim_press_trigger'
MANUAL_WEAPON_RE_AUTO_AIM = 'setting/manual_weapon_re_auto_aim'
SHOTGUN_WEAPON_FIRE_RELEASE_KEY = 'setting/shotgun_weapon_fire_release'
ANTI_MECHA_WEAPON_FIRE_RELEASE_KEY = 'setting/anti_mecha_weapon_fire_release'
MANUAL_SNIPER_RIFLE_FAST_AIM_AND_FIRE_KEY = 'setting/manual_sniper_fast_aim_fire_release'
SNIPER_RIFLE_FAST_AIM_AND_RELEASE_FIRE_KEY = 'setting/sniper_fast_aim_and_release_fire'
AUTO_FAST_AIM_AND_FIRE_KEY = 'setting/auto_fast_aim_and_fire'
ION_GUN_ACCUMULATE_AIM_CANCEL = 'setting/ion_gun_accumulate_aim_cancel'
ADVANCED_WEAPON_SETTINGS = frozenset([
 WEAPON_AIM_ROCKER_DRAG_ENABLE_KEY,
 WEAPON_AIM_PRESS_TRIGGER_KEY,
 MANUAL_WEAPON_RE_AUTO_AIM,
 SHOTGUN_WEAPON_FIRE_RELEASE_KEY,
 ANTI_MECHA_WEAPON_FIRE_RELEASE_KEY,
 AUTO_FAST_AIM_AND_FIRE_KEY,
 ION_GUN_ACCUMULATE_AIM_CANCEL,
 SNIPER_RIFLE_FAST_AIM_AND_RELEASE_FIRE_KEY,
 AIM_HELPER_KEY_1])
MECHA_JUMP_OPACITY_ENABLED_KEY = 'setting/mecha_jump_opacity_enabled'
AIM_TRIGGER_PRESS_8007 = 'setting/aim_trigger_press_8007'
BOOST_TRIGGER_PRESS_8010 = 'setting/boost_trigger_press_8010'
BOOST_AUTO_CAMERA_8010 = 'setting/boost_auto_camera_8010'
JUMP_TRIGGER_PRESS_8004 = 'setting/jump_trigger_press_8004'
JUMP_TRIGGER_PRESS_8008 = 'setting/jump_trigger_press_8008'
CONTINUOUSLY_SHOOT_TRIGGER_PRESS_8012 = 'setting/jump_trigger_press_8012'
BOOST_HIT_AUTO_TRIGGER_TRANSFORM_8012 = 'setting/boost_auto_transform_8012'
VICE_AUTO_FIRE_8016 = 'setting/vice_trigger_press_8016'
DRAG_DASH_BTN_8018 = 'setting/DRAG_DASH_BTN_8018'
DASH_AUTO_DEFEND_8019 = 'setting/dash_auto_defend_8019'
ROCKER_CONTROL_CAMERA_8020 = 'setting/rocker_control_camera_8020'
JUMP_TRIGGER_PRESS_8022 = 'setting/jump_trigger_press_8022'
MAIN_FIRE_ON_RELEASE_8022 = 'setting/main_fire_on_release_8022'
FAST_AIM_FIRE_8023 = 'setting/fast_aim_fire_8023'
NO_CLOSE_AIM_LOAD_8023 = 'setting/reopen_aim_8023'
JUMP_TRIGGER_PRESS_8023 = 'setting/jump_trigger_press_8023'
AUTO_INVISIBLE_8023 = 'setting/auto_invisible_8023'
AIM_RELOAD_WITHOUT_REOPEN_AIM_8023 = 'setting/aim_reload_without_re_aim_8023'
SHIELD_TRIGGER_PRESS_8026 = 'setting/shield_trigger_press_8026'
DRAG_DASH_BTN_8026 = 'setting/DRAG_DASH_BTN_8026'
SHOTGUN_FIRE_ON_NOT_AUTO_8029 = 'setting/shotgun_fire_on_release_8029'
SHOTGUN_FIRE_ON_RELEASE_8029 = 'setting/shotgun_fire_on_auto_8029'
TRANSLATION_USE_PHANTOM_FORWARD_8029 = 'setting/TRANSLATION_USE_PHANTOM_FORWARD_8029'
SUBWEAPON_FIRE_ON_AUTO_8027 = 'setting/SUBWEAPON_FIRE_ON_AUTO_8027'
DRAG_DASH_BTN_8027 = 'setting/DRAG_DASH_BTN_8027'
ROCKER_JUMP_8030 = 'setting/ROCKER_JUMP_8030'
SHOW_SLASH_TYPE_8014 = 'setting/SHOW_SLASH_TYPE_8014'
DASH_TRIGGER_TYPE_8034 = 'setting/DASH_TRIGGER_TYPE_8034'
WEAKEN_PVE_SFX_TYPE_8013 = 'setting/WEAKEN_PVE_SFX_TYPE_8013'
DASH_CAM_DIR_8016 = 'setting/DASH_DIR_TYPE_8016'
WEAPON_FAST_SWITCH_8009 = 'setting/WEAPON_FAST_SWITCH_8009'
ADVANCED_MECHA_SETTINGS = frozenset([
 AIM_TRIGGER_PRESS_8007,
 BOOST_TRIGGER_PRESS_8010,
 JUMP_TRIGGER_PRESS_8004,
 JUMP_TRIGGER_PRESS_8008,
 CONTINUOUSLY_SHOOT_TRIGGER_PRESS_8012,
 VICE_AUTO_FIRE_8016,
 BOOST_HIT_AUTO_TRIGGER_TRANSFORM_8012,
 DRAG_DASH_BTN_8018,
 DASH_AUTO_DEFEND_8019,
 ROCKER_CONTROL_CAMERA_8020,
 JUMP_TRIGGER_PRESS_8022,
 MAIN_FIRE_ON_RELEASE_8022,
 FAST_AIM_FIRE_8023,
 NO_CLOSE_AIM_LOAD_8023,
 JUMP_TRIGGER_PRESS_8023,
 AUTO_INVISIBLE_8023,
 AIM_RELOAD_WITHOUT_REOPEN_AIM_8023,
 SHIELD_TRIGGER_PRESS_8026,
 DRAG_DASH_BTN_8026,
 SHOTGUN_FIRE_ON_NOT_AUTO_8029,
 SHOTGUN_FIRE_ON_RELEASE_8029,
 TRANSLATION_USE_PHANTOM_FORWARD_8029,
 SUBWEAPON_FIRE_ON_AUTO_8027,
 DRAG_DASH_BTN_8027,
 ROCKER_JUMP_8030,
 SHOW_SLASH_TYPE_8014,
 DASH_TRIGGER_TYPE_8034,
 WEAKEN_PVE_SFX_TYPE_8013,
 DASH_CAM_DIR_8016,
 WEAPON_FAST_SWITCH_8009])
PC_CUSTOM_HOTKEY_USER_CACHE_KEY = 'pc/custom_hotkey_user_cache'
SST_TYPE_CENTER_TYPE = 1
SST_TYPE_SCREEN_TYPE = 2
SST_SCR_KEY = 'setting/sst_screen'
SST_AIM_RD_KEY = 'setting/sst_aim_rd'
SST_AIM_2M_KEY = 'setting/sst_aim_2m'
SST_AIM_4M_KEY = 'setting/sst_aim_4m'
SST_FROCKER_KEY = 'setting/sst_fire_rock'
SST_MECHA_07_KEY = 'setting/sst_mecha_07'
SST_AIM_6M_KEY = 'setting/sst_aim_6m'
SST_FS_ROCKER_KEY = 'setting/sst_free_sight_rock'
SST_AUTO_HELP_KEY = 'setting/sst_auto_help_key'
SST_ADAPT_MAGNIFICATION = 'setting/sst_adapt_magnification'
SST_GYROSCOPE_SCR_KEY = 'setting/sst_gyroscope_scr'
SST_GYROSCOPE_RD_KEY = 'setting/sst_gyroscope_rd'
SST_GYROSCOPE_2M_KEY = 'setting/sst_gyroscope_2m'
SST_GYROSCOPE_4M_KEY = 'setting/sst_gyroscope_4m'
SST_GYROSCOPE_6M_KEY = 'setting/sst_gyroscope_6m'
SST_MECHA_ACTION1 = 'setting/sst_mecha_action1'
SST_RANGE = [
 0.2, 7.6]
SST_PERCENT_SCALE = 2.0
SST_IDX_BASE = 0
SST_IDX_UP = 1
SST_IDX_DOWN = 2
SST_IDX_LEFT = 3
SST_IDX_RIGHT = 4
SST_IDX_SCR_LEFT_RIGHT = 3
SST_IDX_SCR_LEFT_RIGHT_2 = 4
MECHA_SENS_TYPE_KEY = 'setting/mecha_sens_type'
MECHA_SENS_TYPE_CUSTOM = 1
MECHA_SENS_TYPE_PRESET_LOW = 2
MECHA_SENS_TYPE_PRESET_MID = 3
MECHA_SENS_TYPE_PRESET_HIGH = 4
SST_SCR_MECHA_VAL_KEY = 'setting/sst_screen_mecha_val'
SST_GYROSCOPE_SCR_MECHA_VAL_KEY = 'setting/sst_gyroscope_scr_mecha_val'
SST_SCR_SCOPE_MECHA_VAL_KEY = 'setting/sst_screen_scope_mecha_val'
SST_GYROSCOPE_SCR_SCOPE_MECHA_VAL_KEY = 'setting/sst_gyroscope_scr_scope_mecha_val'
SST_SCR_SPECIAL_FORM_MECHA_VAL_KEY = 'setting/sst_screen_sp_form_mecha_val'
SST_GYROSCOPE_SCR_SPECIAL_FORM_MECHA_VAL_KEY = 'setting/sst_gyroscope_screen_sp_form_mecha_val'
SST_SHOOT_STICK_SWITCH_MECHA_VAL_KEY = 'setting/sst_shoot_stick_switch_mecha_val'
SST_MAIN_WEAPON_STICK_SWITCH_MECHA_VAL_KEY = 'setting/sst_main_weapon_stick_switch_mecha_val'
SST_SUB_WEAPON_STICK_SWITCH_MECHA_VAL_KEY = 'setting/sst_sub_weapon_stick_switch_mecha_val'
SST_MAIN_WEAPON_STICK_MECHA_VAL_KEY = 'setting/sst_main_weapon_stick_mecha_val'
SST_SUB_WEAPON_STICK_MECHA_VAL_KEY = 'setting/sst_sub_weapon_stick_mecha_val'
SST_MAIN_WEAPON_ROCKER_AS_SCREEN_KEY = 'setting/sst_main_weapon_rocker_as_screen_val'
SST_SUB_WEAPON_ROCKER_AS_SCREEN_KEY = 'setting/sst_sub_weapon_rocker_as_screen_val'
SST_SCOPE_SAME_AS_NORMAL_KEY = 'setting/sst_scope_same_as_normal'
SST_SCOPE_MAIN_WEAPON_STICK_SWITCH_MECHA_VAL_KEY = 'setting/sst_scope_main_weapon_stick_switch_mecha_val'
SST_SCOPE_SUB_WEAPON_STICK_SWITCH_MECHA_VAL_KEY = 'setting/sst_scope_sub_weapon_stick_switch_mecha_val'
SST_SCOPE_MAIN_WEAPON_STICK_MECHA_VAL_KEY = 'setting/sst_scope_main_weapon_stick_mecha_val'
SST_SCOPE_SUB_WEAPON_STICK_MECHA_VAL_KEY = 'setting/sst_scope_sub_weapon_stick_mecha_val'
SST_SCOPE_MAIN_WEAPON_ROCKER_AS_SCREEN_KEY = 'setting/sst_scope_main_weapon_rocker_as_screen_val'
SST_SCOPE_SUB_WEAPON_ROCKER_AS_SCREEN_KEY = 'setting/sst_scope_sub_weapon_rocker_as_screen_val'
SST_SPECIAL_FORM_SAME_AS_NORMAL_KEY = 'setting/sst_special_form_same_as_normal'
SST_SPECIAL_FORM_MAIN_WEAPON_STICK_SWITCH_MECHA_VAL_KEY = 'setting/sst_special_form_main_weapon_stick_switch_mecha_val'
SST_SPECIAL_FORM_SUB_WEAPON_STICK_SWITCH_MECHA_VAL_KEY = 'setting/sst_special_form_sub_weapon_stick_switch_mecha_val'
SST_SPECIAL_FORM_MAIN_WEAPON_STICK_MECHA_VAL_KEY = 'setting/sst_special_form_main_weapon_stick_mecha_val'
SST_SPECIAL_FORM_SUB_WEAPON_STICK_MECHA_VAL_KEY = 'setting/sst_special_form_sub_weapon_stick_mecha_val'
SST_SPECIAL_FORM_MAIN_WEAPON_ROCKER_AS_SCREEN_KEY = 'setting/sst_special_form_main_weapon_rocker_as_screen_val'
SST_SPECIAL_FORM_SUB_WEAPON_ROCKER_AS_SCREEN_KEY = 'setting/sst_special_form_sub_weapon_rocker_as_screen_val'
FLOAT_MECHA_SENS_KEYS = frozenset([
 SST_SCR_MECHA_VAL_KEY,
 SST_GYROSCOPE_SCR_MECHA_VAL_KEY,
 SST_SCR_SCOPE_MECHA_VAL_KEY,
 SST_GYROSCOPE_SCR_SCOPE_MECHA_VAL_KEY,
 SST_SCR_SPECIAL_FORM_MECHA_VAL_KEY,
 SST_GYROSCOPE_SCR_SPECIAL_FORM_MECHA_VAL_KEY,
 SST_MAIN_WEAPON_STICK_MECHA_VAL_KEY,
 SST_SUB_WEAPON_STICK_MECHA_VAL_KEY,
 SST_SCOPE_MAIN_WEAPON_STICK_MECHA_VAL_KEY,
 SST_SCOPE_SUB_WEAPON_STICK_MECHA_VAL_KEY,
 SST_SPECIAL_FORM_MAIN_WEAPON_STICK_MECHA_VAL_KEY,
 SST_SPECIAL_FORM_SUB_WEAPON_STICK_MECHA_VAL_KEY])
BOOL_MECHA_SENS_KEYS = frozenset([
 SST_SHOOT_STICK_SWITCH_MECHA_VAL_KEY,
 SST_MAIN_WEAPON_STICK_SWITCH_MECHA_VAL_KEY,
 SST_SUB_WEAPON_STICK_SWITCH_MECHA_VAL_KEY,
 SST_SCOPE_MAIN_WEAPON_STICK_SWITCH_MECHA_VAL_KEY,
 SST_SCOPE_SUB_WEAPON_STICK_SWITCH_MECHA_VAL_KEY,
 SST_SPECIAL_FORM_MAIN_WEAPON_STICK_SWITCH_MECHA_VAL_KEY,
 SST_SPECIAL_FORM_SUB_WEAPON_STICK_SWITCH_MECHA_VAL_KEY,
 SST_MAIN_WEAPON_ROCKER_AS_SCREEN_KEY,
 SST_SUB_WEAPON_ROCKER_AS_SCREEN_KEY,
 SST_SCOPE_MAIN_WEAPON_ROCKER_AS_SCREEN_KEY,
 SST_SCOPE_SUB_WEAPON_ROCKER_AS_SCREEN_KEY,
 SST_SPECIAL_FORM_MAIN_WEAPON_ROCKER_AS_SCREEN_KEY,
 SST_SPECIAL_FORM_SUB_WEAPON_ROCKER_AS_SCREEN_KEY,
 SST_SCOPE_SAME_AS_NORMAL_KEY,
 SST_SPECIAL_FORM_SAME_AS_NORMAL_KEY])
MECHA_SENS_KEYS = frozenset([
 MECHA_SENS_TYPE_KEY])
MECHA_SENS_KEYS = MECHA_SENS_KEYS | FLOAT_MECHA_SENS_KEYS | BOOL_MECHA_SENS_KEYS
MECHA_SENS_PRESET_VAL_KEYS = FLOAT_MECHA_SENS_KEYS | BOOL_MECHA_SENS_KEYS
MECHA_SENS_CFG_DEFAULTS = {SST_SCR_MECHA_VAL_KEY: 1.3,
   SST_GYROSCOPE_SCR_MECHA_VAL_KEY: 1.25,
   SST_SCR_SCOPE_MECHA_VAL_KEY: 1.1,
   SST_GYROSCOPE_SCR_SCOPE_MECHA_VAL_KEY: 1.0,
   SST_SHOOT_STICK_SWITCH_MECHA_VAL_KEY: True,
   SST_MAIN_WEAPON_STICK_SWITCH_MECHA_VAL_KEY: True,
   SST_SUB_WEAPON_STICK_SWITCH_MECHA_VAL_KEY: {8014: False,
                                               'default': True
                                               },
   SST_MAIN_WEAPON_STICK_MECHA_VAL_KEY: 1.25,
   SST_SUB_WEAPON_STICK_MECHA_VAL_KEY: 1.25,
   SST_MAIN_WEAPON_ROCKER_AS_SCREEN_KEY: False,
   SST_SUB_WEAPON_ROCKER_AS_SCREEN_KEY: False,
   SST_SCOPE_SAME_AS_NORMAL_KEY: True,
   SST_SCOPE_MAIN_WEAPON_STICK_SWITCH_MECHA_VAL_KEY: True,
   SST_SCOPE_SUB_WEAPON_STICK_SWITCH_MECHA_VAL_KEY: {8014: False,
                                                     'default': True
                                                     },
   SST_SCOPE_MAIN_WEAPON_STICK_MECHA_VAL_KEY: 1.25,
   SST_SCOPE_SUB_WEAPON_STICK_MECHA_VAL_KEY: 1.25,
   SST_SCOPE_MAIN_WEAPON_ROCKER_AS_SCREEN_KEY: False,
   SST_SCOPE_SUB_WEAPON_ROCKER_AS_SCREEN_KEY: False,
   SST_SPECIAL_FORM_SAME_AS_NORMAL_KEY: True,
   SST_SPECIAL_FORM_MAIN_WEAPON_STICK_SWITCH_MECHA_VAL_KEY: True,
   SST_SPECIAL_FORM_SUB_WEAPON_STICK_SWITCH_MECHA_VAL_KEY: {8014: False,
                                                            'default': True
                                                            },
   SST_SPECIAL_FORM_MAIN_WEAPON_STICK_MECHA_VAL_KEY: 1.25,
   SST_SPECIAL_FORM_SUB_WEAPON_STICK_MECHA_VAL_KEY: 1.25,
   SST_SPECIAL_FORM_MAIN_WEAPON_ROCKER_AS_SCREEN_KEY: False,
   SST_SPECIAL_FORM_SUB_WEAPON_ROCKER_AS_SCREEN_KEY: False
   }
OPE_POSTURE_KEY = 'setting/cur_posture'
OPE_POSTURE_LEFT = 1
OPE_POSTURE_RIGHT = 2
OPE_POSTURE_SEPARATE = 3
OPE_POSTURE_DEF_SETTING = OPE_POSTURE_SEPARATE
ThreeD_TOUCH_TOGGLE_KEY = 'setting/3d_touch'
ThreeD_TOUCH_TOGGLE_DEF_VAL = False
ThreeD_TOUCH_PERCENT_KEY = 'setting/3d_touch_per'
ThreeD_TOUCH_PERCENT_DEF_VAL = 0.5
ThreeD_TOUCH_RANGE = [0.1, 1]
FIREROCKER_OPE_KEY = 'setting/fire_rocker'
FIXED_FIREROCKER = 1
MOVABLE_FIREROCKER = 2
ALL_FIX_ROCKER = 3
FIREROCKER_OPE_DEF = FIXED_FIREROCKER
WEAPON_ROCKER_DISABLE_DRAG_KEY = 'setting/disable_weapon_rocker_drag'
ONE_SHOT_BTN_SHOW_TIME = 0.4
ONE_SHOT_BTN_ATTACK_INTERVAL = 0.2
ONE_SHOT_BTN_SHOW_TIME_RANGE = (0.3, 0.8)
ONE_SHOT_BTN_ATTACK_TIME_RANGE = (0.1, 0.4)
ONE_SHOT_ATTACK_KEY = 'setting/one_shot_attack_time'
ONE_SHOT_SHOW_KEY = 'setting/one_shot_show_time'
ONE_SHOT_SETTING_KEY = 'setting/one_shot_val'
ONE_SHOT_DEF_VAL = False
DRIVE_OPE_KEY = 'setting/drive_dir'
DRIVE_OPE_BUTTON = 1
DRIVE_OPE_FORWARD = 2
DRIVE_OPE_ROCKER = 3
DRIVE_OPE_BUTTON_DIR_KEY = 'setting/drive_button'
DRIVE_OPE_BUTTON_MOVE_LEFT = 1
DRIVE_OPE_BUTTON_MOVE_RIGHT = 2
DRIVE_OPE_BUTTON_DEF = DRIVE_OPE_BUTTON_MOVE_LEFT
MAX_DRIVE_ROTATE_IN_SECOND = 25.0 * math.pi / 180 / 30
HIGH_LIGHT_KEY = 'setting/high_light'
HIGH_LIGHT_TIMES_KEY = 'setting/high_light_times'
FREE_RECORD_VIDEO_KEY = 'setting/free_record_video'
HIGH_LIGHT_TIMES_DEF = 6
HIGH_LIGHT_DEF_KEYS = [HIGH_LIGHT_KEY, HIGH_LIGHT_TIMES_KEY, FREE_RECORD_VIDEO_KEY]
HIGH_LIGHT_DEF_SETTING = [False, HIGH_LIGHT_TIMES_DEF, False]
QUALITY_LEVEL_KEY = 'setting/quality_level'
PVE_QUALITY_LEVEL_KEY = 'setting/pve_quality_level'
QUALITY_RESOLUTION_KEY = 'setting/quality_resolution_scale'
QUALITY_RESOLUTION_KEY_KONGDAO = 'setting/quality_resolution_scale_kongdao'
QUALITY_HIGH_FRAME_RATE_KEY = 'setting/quality_high_frame_rate'
QUALITY_SHADOWMAP_KEY = 'setting/quality_shadowmap_2'
QUALITY_HDR_KEY = 'setting/quality_hdr'
QUALITY_MSAA_KEY = 'setting/quality_msaa'
QUALITY_MEADOW_KEY = 'setting/quality_meadow'
QUALITY_MECHA_EFFECT_LEVEL_KEY = 'setting/quality_mecha_effect_level'
QUALITY_OTHER_MECHA_EFFECT_LEVEL_KEY = 'setting/quality_other_mecha_effect_level'
QUALITY_RADIAL_BLUR_KEY = 'setting/quality_radial_blur'
MECHA_EFFECT_LEVEL_LOW = 0
MECHA_EFFECT_LEVEL_MEDIUM = 1
MECHA_EFFECT_LEVEL_HIGH = 2
MECHA_EFFECT_LEVEL_ULTRA = 3
PC_HOTKEY_HINT_DISPLAY_OPTION_KEY = 'pc/hotkey_hint_display_option'
PC_HOTKEY_HINT_SWITCH_KEY = 'pc/hotkey_hint_switch'
SOUND_VOLUME_MAIN_KEY = 'soundseting/sound_volume_main'
SOUND_VOLUME_SFX_KEY = 'soundseting/sound_volume_sfx'
SOUND_VOLUME_VO_KEY = 'soundseting/sound_volume_vo'
SOUND_VOLUME_ANCHOR_VO_KEY = 'soundseting/sound_volume_anchor_vo'
SOUND_VOLUME_MUSIC_KEY = 'soundseting/sound_volume_music'
SOUND_VOLUME_MAIN_ISENABLE_KEY = 'soundseting/sound_volume_main_isenable'
SOUND_VOLUME_SFX_ISENABLE_KEY = 'soundseting/sound_volume_sfx_isenable'
SOUND_VOLUME_VO_ISENABLE_KEY = 'soundseting/sound_volume_vo_isenable'
SOUND_VOLUME_ANCHOR_VO_ISENABLE_KEY = 'soundseting/sound_volume_anchor_vo_isenable'
SOUND_VOLUME_MUSIC_ISENABLE_KEY = 'soundseting/sound_volume_music_isenable'
SOUND_VOLUME_DEFAULT = 100
SOUND_VOLUME_ISENABLE_DEFAULT = True
MR_DEF_RUN_SPAN_SCALE = 1.1
MR_DEF_WALK_SPAN_SCALE = 0.8
MR_RUN_KEY = 'setting/mr_run_scale'
MR_WALK_KEY = 'setting/mr_walk_scale'
MR_SPAN_RANGE = [0.5, 2]
DOOR_DEF_EXTRA_SIZE = [
 15, 0, 45]
MAX_DOOR_SIZE = [
 28, 30, 46]
DOOR_OPEN_TIME = 0.3
DOOR_CLOSE_TIME = 0.2
PICK_ZORDER = 4
LEFT_CONTROL_ZORDER = 3
MOVE_LOCAL_ZORDER = 2
FIRE_LOCAL_ZORDER = 1
WEAPON_BAR_LOCAL_ZORDER = 4
BAG_LOCAL_ZORDER = 3
OBSERVE_UNTOUCH_ZORDER = 1
OBSERVE_UI_ZORDER = 2
OBSERVE_TOUCHABLE_ZORDER = 3
WEAPON_BAR_UI_KEY = 'setting/weapon_bar_ui'
WEAPON_BAR_CLICK_OPE = 1
WEAPON_BAR_SCROLL_OPE = 2
WEAPON_BAR_UI_DEF_SETTING = WEAPON_BAR_CLICK_OPE
CUSTOMER_UI_KEY = 'setting/ui_custom'
CUSTOM_PAGES = {'mecha', 'human'}
COMMON_SETTING_NO_LIST = [0, 1, 2]
PVE_COMMON_SETTING_NO_LIST = [100, 101, 102]
NON_SYNC_DATA_KEY = 'non_sync_data'
FIRST_SWITCH_OBSERVE_CAM = 'lsetting/first_switch_cam_mode'
NEWBIE_PASS_HIDE_UI = 'setting/newbie_pass_hide_ui'
CONF_VERSION_KEY = 'setting/conf_version'
CONF_VERSION = 2
CONF_SHAKE_KEY_PATTERN = 'setting/shaking_%s'
CONF_SHAKE_MECHA_DESTROY = 'mecha_destroy'
CONF_SHAKE_INJURE = 'injure'
CONF_SHAKE_DEFAULT = False
MODEL_CHUCHANG_RECORD = 'model_chuchang_record'
PC_FULL_SCREEN_KEY = 'pc/full_screen'
GRAPHICS_STYLE_TYPE = 'setting/graphics_style_type'
PC_REDIRECT_SCALE = 'pc/redirect_scale'
PC_REDIRECT_RANGE = (0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0)
CUSTOM_PAGE_NAME_PREFIX = 'setting/custom_page_name_'
CUSTOM_PAGE_NAME_1 = 'setting/custom_page_name_1'
CUSTOM_PAGE_NAME_2 = 'setting/custom_page_name_2'
CUSTOM_PAGE_NAME_3 = 'setting/custom_page_name_3'
CUSTOM_SETTING_NO_COUNT = 3
CUSTOM_NODE_GROUPS = 'setting/custom_node_groups'
CUSTOM_NODE_TOP_GROUP_RANK = 100
AIM_COLOR_DEFAULT = 16777215
AIM_COLOR_VAL = 'setting/aim_color_val'
AIM_COLOR_LIST = [16777215, 0, 16711680, 16580352, 61695, 65340]
DOWN_COLOR_LIST = [
 16558103, 16777215, 0, 61695, 65340, 16716067]
DOWN_COLOR_LIST_SEA = [16716067, 16777215, 0, 61695, 65340, 16558103]
DOWN_COLOR_VAL = 'setting/down_color_val'
DOWN_COLOR_DEFAULT = 16558103
DOWN_COLOR_SEA_DEFAULT = 16716067
WEAPON_BAR_SKIN_SHOW_KEY = 'setting/weapon_bar_skin_show'
WEAPON_BAR_SKIN_SHOW_DEFAULT = True
BAN_RED_PACKET_DAMMU = 'ban_red_packet_dammu'
BAN_RED_PACKET_DAMMU_DEFAULT_STATE = False
DOUBLE_CLICK_MARK_KEY = 'setting/double_click_mark'
MATCH_SUCC_VIBRATE_KEY = 'setting/match_succ_vibrate'
SEASON_LEVEL_UP_REMINDER_KEY = 'setting/season_level_up_reminder'
SETTING_CONF_STEAM = {DOWN_COLOR_VAL: DOWN_COLOR_SEA_DEFAULT
   }
SETTING_CONF_SEA = {DOWN_COLOR_VAL: DOWN_COLOR_SEA_DEFAULT
   }
SETTING_CONF = {CONF_VERSION_KEY: CONF_VERSION,
   LF_OPE_KEY: LF_OPE_DEF,
   FREE_SIGHT_KEY: FREE_SIGHT_DEF_SETTING,
   WEAPON_BAR_UI_KEY: WEAPON_BAR_UI_DEF_SETTING,
   OPE_POSTURE_KEY: OPE_POSTURE_DEF_SETTING,
   FIREROCKER_OPE_KEY: FIREROCKER_OPE_DEF,
   WEAPON_ROCKER_DISABLE_DRAG_KEY: False,
   WEAPON_AIM_ROCKER_DRAG_ENABLE_KEY: True,
   WEAPON_AIM_PRESS_TRIGGER_KEY: False,
   MANUAL_WEAPON_RE_AUTO_AIM: True,
   SHOTGUN_WEAPON_FIRE_RELEASE_KEY: True,
   ANTI_MECHA_WEAPON_FIRE_RELEASE_KEY: False,
   MANUAL_SNIPER_RIFLE_FAST_AIM_AND_FIRE_KEY: False,
   SNIPER_RIFLE_FAST_AIM_AND_RELEASE_FIRE_KEY: False,
   AUTO_FAST_AIM_AND_FIRE_KEY: False,
   ION_GUN_ACCUMULATE_AIM_CANCEL: False,
   MECHA_JUMP_OPACITY_ENABLED_KEY: True,
   AIM_TRIGGER_PRESS_8007: False,
   BOOST_TRIGGER_PRESS_8010: False,
   BOOST_AUTO_CAMERA_8010: True,
   JUMP_TRIGGER_PRESS_8004: True,
   JUMP_TRIGGER_PRESS_8008: True,
   CONTINUOUSLY_SHOOT_TRIGGER_PRESS_8012: True,
   VICE_AUTO_FIRE_8016: True,
   BOOST_HIT_AUTO_TRIGGER_TRANSFORM_8012: False,
   DRAG_DASH_BTN_8018: True,
   DASH_AUTO_DEFEND_8019: False,
   ROCKER_CONTROL_CAMERA_8020: False,
   JUMP_TRIGGER_PRESS_8022: True,
   MAIN_FIRE_ON_RELEASE_8022: False,
   FAST_AIM_FIRE_8023: False,
   NO_CLOSE_AIM_LOAD_8023: True,
   JUMP_TRIGGER_PRESS_8023: True,
   AUTO_INVISIBLE_8023: False,
   AIM_RELOAD_WITHOUT_REOPEN_AIM_8023: False,
   SHIELD_TRIGGER_PRESS_8026: True,
   DRAG_DASH_BTN_8026: True,
   SHOTGUN_FIRE_ON_RELEASE_8029: True,
   SHOTGUN_FIRE_ON_NOT_AUTO_8029: True,
   TRANSLATION_USE_PHANTOM_FORWARD_8029: False,
   SUBWEAPON_FIRE_ON_AUTO_8027: True,
   DRAG_DASH_BTN_8027: True,
   ROCKER_JUMP_8030: True,
   SHOW_SLASH_TYPE_8014: True,
   DASH_CAM_DIR_8016: True,
   WEAPON_FAST_SWITCH_8009: True,
   DASH_TRIGGER_TYPE_8034: True,
   ThreeD_TOUCH_TOGGLE_KEY: ThreeD_TOUCH_TOGGLE_DEF_VAL,
   ThreeD_TOUCH_PERCENT_KEY: ThreeD_TOUCH_PERCENT_DEF_VAL,
   DRIVE_OPE_KEY: DRIVE_OPE_FORWARD,
   DRIVE_OPE_BUTTON_DIR_KEY: DRIVE_OPE_BUTTON_DEF,
   GYROSCOPE_STATE_KEY: GYROSCOPE_DEF_SETTING,
   AIM_HELPER_KEY: True,
   SST_AUTO_HELP_KEY: str(True),
   SST_ADAPT_MAGNIFICATION: str(False),
   AUTO_PICK_KEY: True,
   WEAPON_PICK_DIRECTLY_REPLACE_KEY: False,
   AUTO_OPEN_DOOR: True,
   BIT_MODE: '64bit',
   AUTO_CLIMB: False,
   AIM_HELPER_KEY_1: True,
   ROCKER_DASH: ROCKER_DASH_DEFAULT,
   TEAMMATE_DANMU: True,
   DANMU_SHOW_DEFAULT_HEAD: True,
   CHANGE_MECHA_SKIN_IN_BATTLE: CHANGE_MECHA_SKIN_IN_BATTLE_DEFAULT,
   PVE_MECHA_RADAR: PVE_MECHA_RADAR_3D,
   MALL_RECOMMEND: True,
   SS_SKIN_BATTLE_MSG_SHOW: True,
   QUALITY_LEVEL_KEY: 2,
   PVE_QUALITY_LEVEL_KEY: 2,
   QUALITY_HIGH_FRAME_RATE_KEY: 0,
   QUALITY_RESOLUTION_KEY: 2,
   QUALITY_RESOLUTION_KEY_KONGDAO: 0,
   QUALITY_SHADOWMAP_KEY: 0,
   QUALITY_HDR_KEY: 0,
   QUALITY_MSAA_KEY: 0,
   QUALITY_MEADOW_KEY: 2,
   QUALITY_MECHA_EFFECT_LEVEL_KEY: MECHA_EFFECT_LEVEL_HIGH,
   QUALITY_OTHER_MECHA_EFFECT_LEVEL_KEY: MECHA_EFFECT_LEVEL_HIGH,
   QUALITY_RADIAL_BLUR_KEY: 1,
   CUSTOMER_UI_KEY: {},FIRST_SWITCH_OBSERVE_CAM: True,
   SOUND_VISIBLE_IN_MAP_KEY: True,
   AUTO_SHOW_PLANE_BIG_MAP: AUTO_SHOW_PLANE_BIG_MAP_DEFAULT,
   SOUND_VISIBLE_3D_KEY: SOUND_VISIBLE_3D_KEY_DEFAULT,
   INJURE_VISIBLE_3D_KEY: INJURE_VISIBLE_3D_KEY_DEFAULT,
   SOUND_TIP_CD: SOUND_TIP_CD_DEFAULT,
   REVEAL_HISTORY_RECORD_KEY: REVEAL_HISTORY_RECORD_DEFAULT,
   REVEAL_INTIMACY_RELATION_KEY: REVEAL_INTIMACY_RELATION_DEFAULT,
   ENABLE_STRANGER_ADD_FRIEND: ENABLE_STRANGER_ADD_FRIEND_DEFAULT,
   SHIELD_STRANGER_MSG_KEY: SHIELD_STRANGER_MSG_DEFAULT,
   ENABLE_BE_SPECTATED_KEY: ENABLE_BE_SPECTATED_DEFAULT,
   REVEAL_MECHA_MEMORY_RECORD_KEY: REVEAL_MECHA_MEMORY_DEFAULT,
   BLOCK_ALL_MSG_KEY: BLOCK_ALL_MSG_DEFAULT,
   TEAM_ONLY_FRIEND_KEY: TEAM_ONLY_FRIEND_DEFAULT,
   SOUND_VOLUME_MAIN_KEY: SOUND_VOLUME_DEFAULT,
   SOUND_VOLUME_SFX_KEY: SOUND_VOLUME_DEFAULT,
   SOUND_VOLUME_VO_KEY: SOUND_VOLUME_DEFAULT,
   SOUND_VOLUME_ANCHOR_VO_KEY: SOUND_VOLUME_DEFAULT,
   SOUND_VOLUME_MUSIC_KEY: SOUND_VOLUME_DEFAULT,
   SOUND_VOLUME_MAIN_ISENABLE_KEY: SOUND_VOLUME_ISENABLE_DEFAULT,
   SOUND_VOLUME_SFX_ISENABLE_KEY: SOUND_VOLUME_ISENABLE_DEFAULT,
   SOUND_VOLUME_VO_ISENABLE_KEY: SOUND_VOLUME_ISENABLE_DEFAULT,
   SOUND_VOLUME_ANCHOR_VO_ISENABLE_KEY: SOUND_VOLUME_ISENABLE_DEFAULT,
   SOUND_VOLUME_MUSIC_ISENABLE_KEY: SOUND_VOLUME_ISENABLE_DEFAULT,
   NEWBIE_PASS_HIDE_UI: 0,
   CONF_SHAKE_KEY_PATTERN % CONF_SHAKE_MECHA_DESTROY: CONF_SHAKE_DEFAULT,
   CONF_SHAKE_KEY_PATTERN % CONF_SHAKE_INJURE: CONF_SHAKE_DEFAULT,
   GRAPHICS_STYLE_TYPE: 2,
   PC_CUSTOM_HOTKEY_USER_CACHE_KEY: {},HIGH_LIGHT_TIMES_KEY: HIGH_LIGHT_TIMES_DEF,
   HIGH_LIGHT_KEY: False,
   PC_REDIRECT_SCALE: 1,
   ITEM_SHORT_CUT: ITEM_SHORT_CUT_ENABLE,
   CUSTOM_PAGE_NAME_1: '',
   CUSTOM_PAGE_NAME_2: '',
   CUSTOM_PAGE_NAME_3: '',
   CUSTOM_NODE_GROUPS: {},AIM_COLOR_VAL: AIM_COLOR_DEFAULT,
   DOWN_COLOR_VAL: DOWN_COLOR_DEFAULT,
   WEAPON_BAR_SKIN_SHOW_KEY: WEAPON_BAR_SKIN_SHOW_DEFAULT,
   DOUBLE_CLICK_MARK_KEY: True,
   MATCH_SUCC_VIBRATE_KEY: True,
   SEASON_LEVEL_UP_REMINDER_KEY: True,
   BLOCK_STRANGER_VISIT: False,
   ENABLE_STRANGER_LEFT_MSG: True,
   ENABLE_REWARD_FRIEND_REPORT: True,
   BAN_RED_PACKET_DAMMU: BAN_RED_PACKET_DAMMU_DEFAULT_STATE,
   ENABLE_PET_TRANSPARENT: False,
   ENABLE_PET_INTERACT_IN_BATTLE: True,
   WEAKEN_PVE_SFX_TYPE_8013: True
   }
if G_IS_CLIENT and global_data.is_inner_server:
    SETTING_CONF[HIGH_LIGHT_KEY] = True
LOCAL_SETTING_CONF = {PC_FULL_SCREEN_KEY: True
   }
PC_SETTING_CONF_DEFAULT_OVERRIDES = {QUALITY_HIGH_FRAME_RATE_KEY: 1,
   DRIVE_OPE_KEY: DRIVE_OPE_BUTTON,
   PC_REDIRECT_SCALE: 2
   }
PC_HIGHT_QUALITY_SETTING_CONF = {QUALITY_LEVEL_KEY: 3,
   PVE_QUALITY_LEVEL_KEY: 3,
   QUALITY_RESOLUTION_KEY: 3,
   QUALITY_RESOLUTION_KEY_KONGDAO: 3,
   QUALITY_HIGH_FRAME_RATE_KEY: 1,
   QUALITY_MSAA_KEY: 2,
   QUALITY_SHADOWMAP_KEY: 1,
   QUALITY_HDR_KEY: 1,
   QUALITY_MEADOW_KEY: 3
   }
PC_HIDDEN_SETTING_CONF = {
 QUALITY_RESOLUTION_KEY,
 QUALITY_RESOLUTION_KEY_KONGDAO}
SST_MAIN_SETTING_MOUSE_WHEEL = 0.6
SST_MAIN_SETTING_DRAG_SCROLL_BAR = 0.8
SST_TASK_MAIN_MOUSE_WHEEL = 0.2
SST_MAIN_RANK_DRAG_SCROLL_BAR = 8.0
SETTINGS_USE_NEW_2_API_FOR_OLD_CALLSITE = {
 REVEAL_HISTORY_RECORD_KEY,
 SS_SKIN_BATTLE_MSG_SHOW,
 REVEAL_INTIMACY_RELATION_KEY,
 ENABLE_STRANGER_ADD_FRIEND,
 SHIELD_STRANGER_MSG_KEY,
 ENABLE_BE_SPECTATED_KEY,
 REVEAL_MECHA_MEMORY_RECORD_KEY,
 DRIVE_OPE_KEY,
 DRIVE_OPE_BUTTON_DIR_KEY,
 QUALITY_LEVEL_KEY,
 PVE_QUALITY_LEVEL_KEY,
 QUALITY_RESOLUTION_KEY,
 QUALITY_HIGH_FRAME_RATE_KEY,
 QUALITY_SHADOWMAP_KEY,
 QUALITY_HDR_KEY,
 QUALITY_MSAA_KEY,
 QUALITY_RADIAL_BLUR_KEY,
 SST_SCR_KEY,
 SST_AIM_RD_KEY,
 SST_AIM_2M_KEY,
 SST_AIM_4M_KEY,
 SST_AIM_6M_KEY,
 SST_FROCKER_KEY,
 SST_MECHA_07_KEY,
 SST_GYROSCOPE_SCR_KEY,
 SST_GYROSCOPE_RD_KEY,
 SST_GYROSCOPE_2M_KEY,
 SST_GYROSCOPE_4M_KEY,
 SST_GYROSCOPE_6M_KEY,
 SST_FS_ROCKER_KEY,
 ThreeD_TOUCH_PERCENT_KEY,
 AUTO_CLIMB,
 AIM_HELPER_KEY_1}
SETTINGS_NEED_PLATFORM_VARIANT = {
 DRIVE_OPE_KEY,
 DRIVE_OPE_BUTTON_DIR_KEY,
 QUALITY_LEVEL_KEY,
 PVE_QUALITY_LEVEL_KEY,
 QUALITY_RESOLUTION_KEY,
 QUALITY_RESOLUTION_KEY_KONGDAO,
 QUALITY_HIGH_FRAME_RATE_KEY,
 QUALITY_SHADOWMAP_KEY,
 QUALITY_HDR_KEY,
 QUALITY_MSAA_KEY,
 QUALITY_RADIAL_BLUR_KEY,
 SST_SCR_KEY,
 SST_AIM_RD_KEY,
 SST_AIM_2M_KEY,
 SST_AIM_4M_KEY,
 SST_AIM_6M_KEY,
 SST_FROCKER_KEY,
 SST_MECHA_07_KEY,
 SST_FS_ROCKER_KEY}
SETTINGS_NEED_PLATFORM_VARIANT = SETTINGS_NEED_PLATFORM_VARIANT | ADVANCED_WEAPON_SETTINGS
SETTINGS_NEED_PLATFORM_VARIANT = SETTINGS_NEED_PLATFORM_VARIANT | ADVANCED_MECHA_SETTINGS
SETTINGS_NEED_PLATFORM_VARIANT = SETTINGS_NEED_PLATFORM_VARIANT | MECHA_SENS_KEYS
SERVER_SETTING = [
 REVEAL_INTIMACY_RELATION_KEY, ENABLE_STRANGER_ADD_FRIEND, SS_SKIN_BATTLE_MSG_SHOW, REVEAL_HISTORY_RECORD_KEY, BLOCK_STRANGER_VISIT, ENABLE_STRANGER_LEFT_MSG,
 ENABLE_BE_SPECTATED_KEY, REVEAL_MECHA_MEMORY_RECORD_KEY, BLOCK_ALL_MSG_KEY, TEAM_ONLY_FRIEND_KEY, BLOCK_ALL_MSG_KEY, DANMU_SHOW_DEFAULT_HEAD]
CUSTOM_SETTING_OPT = set()
CUSTOM_SETTING_KEY = set()
CUSTOM_PVE_SETTING_OPT = set()
CUSTOM_PVE_SETTING_KEY = set()