# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/mobile/common/proto_python/raft_pb2.py
from __future__ import absolute_import
import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_sym_db = _symbol_database.Default()
from . import common_pb2
DESCRIPTOR = _descriptor.FileDescriptor(name='raft.proto', package='mobile.server', serialized_pb=_b('\n\nraft.proto\x12\rmobile.server\x1a\x0ccommon.proto"\'\n\x0bRaftAddress\x12\n\n\x02ip\x18\x01 \x02(\x0c\x12\x0c\n\x04port\x18\x02 \x02(\r"N\n\x0fRequestVoteInfo\x12\x0c\n\x04term\x18\x01 \x02(\r\x12\x16\n\x0elast_log_index\x18\x02 \x02(\x04\x12\x15\n\rlast_log_term\x18\x03 \x02(\r" \n\x10ResponseVoteInfo\x12\x0c\n\x04term\x18\x01 \x02(\r"V\n\x0fNextNodeIdxInfo\x12\x15\n\rnext_node_idx\x18\x01 \x02(\x04\x12\x14\n\x05reset\x18\x02 \x02(\x08:\x05false\x12\x16\n\x07success\x18\x03 \x02(\x08:\x05false"8\n\x08LogEntry\x12\x0f\n\x07command\x18\x01 \x02(\x0c\x12\r\n\x05index\x18\x02 \x02(\x04\x12\x0c\n\x04term\x18\x03 \x02(\r"\x8e\x01\n\x11AppendEntriesInfo\x12\x0c\n\x04term\x18\x01 \x02(\r\x12\x14\n\x0ccommit_index\x18\x02 \x02(\x04\x12(\n\x07entries\x18\x03 \x03(\x0b2\x17.mobile.server.LogEntry\x12\x14\n\x0cprev_log_idx\x18\x04 \x02(\x04\x12\x15\n\rprev_log_term\x18\x05 \x02(\r"O\n\x1bAppendEntriesSerializedInfo\x12\x0c\n\x04term\x18\x01 \x02(\r\x12\x14\n\x0ccommit_index\x18\x02 \x02(\x04\x12\x0c\n\x04data\x18\x03 \x02(\x0c"3\n\x0cApplyCommand\x12\x0f\n\x07command\x18\x01 \x02(\x0c\x12\x12\n\nrequest_id\x18\x02 \x01(\x04"O\n\x14ApplyCommandResponse\x12\x12\n\nrequest_id\x18\x01 \x02(\x04\x12\x11\n\tlog_index\x18\x02 \x02(\x04\x12\x10\n\x08log_term\x18\x03 \x02(\r"6\n\x11ApplyCommandError\x12\x12\n\nrequest_id\x18\x01 \x02(\x04\x12\r\n\x05error\x18\x02 \x02(\r"F\n\x0cAdminMessage\x12\x0f\n\x07command\x18\x01 \x02(\x0c\x12\x11\n\targuments\x18\x02 \x02(\x0c\x12\x12\n\nrequest_id\x18\x03 \x02(\x04"C\n\rAdminResponse\x12\x12\n\nrequest_id\x18\x01 \x02(\x04\x12\x0f\n\x07message\x18\x02 \x02(\x0c\x12\r\n\x05error\x18\x03 \x02(\r2\xb6\x06\n\x05IRaft\x12G\n\x14register_replication\x12\x1a.mobile.server.RaftAddress\x1a\x13.mobile.server.Void\x12C\n\x0crequest_vote\x12\x1e.mobile.server.RequestVoteInfo\x1a\x13.mobile.server.Void\x12E\n\rresponse_vote\x12\x1f.mobile.server.ResponseVoteInfo\x1a\x13.mobile.server.Void\x12D\n\rnext_node_idx\x12\x1e.mobile.server.NextNodeIdxInfo\x1a\x13.mobile.server.Void\x12G\n\x0eappend_entries\x12 .mobile.server.AppendEntriesInfo\x1a\x13.mobile.server.Void\x12\\\n\x19append_entries_serialized\x12*.mobile.server.AppendEntriesSerializedInfo\x1a\x13.mobile.server.Void\x12A\n\rapply_command\x12\x1b.mobile.server.ApplyCommand\x1a\x13.mobile.server.Void\x12R\n\x16apply_command_response\x12#.mobile.server.ApplyCommandResponse\x1a\x13.mobile.server.Void\x12L\n\x13apply_command_error\x12 .mobile.server.ApplyCommandError\x1a\x13.mobile.server.Void\x12A\n\radmin_message\x12\x1b.mobile.server.AdminMessage\x1a\x13.mobile.server.Void\x12C\n\x0eadmin_response\x12\x1c.mobile.server.AdminResponse\x1a\x13.mobile.server.VoidB\x06\x80\x01\x01\x90\x01\x01'), dependencies=[
 common_pb2.DESCRIPTOR])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
_RAFTADDRESS = _descriptor.Descriptor(name='RaftAddress', full_name='mobile.server.RaftAddress', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='ip', full_name='mobile.server.RaftAddress.ip', index=0, number=1, type=12, cpp_type=9, label=2, has_default_value=False, default_value=_b(''), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='port', full_name='mobile.server.RaftAddress.port', index=1, number=2, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=43, serialized_end=82)
_REQUESTVOTEINFO = _descriptor.Descriptor(name='RequestVoteInfo', full_name='mobile.server.RequestVoteInfo', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='term', full_name='mobile.server.RequestVoteInfo.term', index=0, number=1, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='last_log_index', full_name='mobile.server.RequestVoteInfo.last_log_index', index=1, number=2, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='last_log_term', full_name='mobile.server.RequestVoteInfo.last_log_term', index=2, number=3, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=84, serialized_end=162)
_RESPONSEVOTEINFO = _descriptor.Descriptor(name='ResponseVoteInfo', full_name='mobile.server.ResponseVoteInfo', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='term', full_name='mobile.server.ResponseVoteInfo.term', index=0, number=1, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=164, serialized_end=196)
_NEXTNODEIDXINFO = _descriptor.Descriptor(name='NextNodeIdxInfo', full_name='mobile.server.NextNodeIdxInfo', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='next_node_idx', full_name='mobile.server.NextNodeIdxInfo.next_node_idx', index=0, number=1, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='reset', full_name='mobile.server.NextNodeIdxInfo.reset', index=1, number=2, type=8, cpp_type=7, label=2, has_default_value=True, default_value=False, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='success', full_name='mobile.server.NextNodeIdxInfo.success', index=2, number=3, type=8, cpp_type=7, label=2, has_default_value=True, default_value=False, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=198, serialized_end=284)
_LOGENTRY = _descriptor.Descriptor(name='LogEntry', full_name='mobile.server.LogEntry', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='command', full_name='mobile.server.LogEntry.command', index=0, number=1, type=12, cpp_type=9, label=2, has_default_value=False, default_value=_b(''), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='index', full_name='mobile.server.LogEntry.index', index=1, number=2, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='term', full_name='mobile.server.LogEntry.term', index=2, number=3, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=286, serialized_end=342)
_APPENDENTRIESINFO = _descriptor.Descriptor(name='AppendEntriesInfo', full_name='mobile.server.AppendEntriesInfo', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='term', full_name='mobile.server.AppendEntriesInfo.term', index=0, number=1, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='commit_index', full_name='mobile.server.AppendEntriesInfo.commit_index', index=1, number=2, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='entries', full_name='mobile.server.AppendEntriesInfo.entries', index=2, number=3, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='prev_log_idx', full_name='mobile.server.AppendEntriesInfo.prev_log_idx', index=3, number=4, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='prev_log_term', full_name='mobile.server.AppendEntriesInfo.prev_log_term', index=4, number=5, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=345, serialized_end=487)
_APPENDENTRIESSERIALIZEDINFO = _descriptor.Descriptor(name='AppendEntriesSerializedInfo', full_name='mobile.server.AppendEntriesSerializedInfo', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='term', full_name='mobile.server.AppendEntriesSerializedInfo.term', index=0, number=1, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='commit_index', full_name='mobile.server.AppendEntriesSerializedInfo.commit_index', index=1, number=2, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='data', full_name='mobile.server.AppendEntriesSerializedInfo.data', index=2, number=3, type=12, cpp_type=9, label=2, has_default_value=False, default_value=_b(''), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=489, serialized_end=568)
_APPLYCOMMAND = _descriptor.Descriptor(name='ApplyCommand', full_name='mobile.server.ApplyCommand', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='command', full_name='mobile.server.ApplyCommand.command', index=0, number=1, type=12, cpp_type=9, label=2, has_default_value=False, default_value=_b(''), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='request_id', full_name='mobile.server.ApplyCommand.request_id', index=1, number=2, type=4, cpp_type=4, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=570, serialized_end=621)
_APPLYCOMMANDRESPONSE = _descriptor.Descriptor(name='ApplyCommandResponse', full_name='mobile.server.ApplyCommandResponse', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='request_id', full_name='mobile.server.ApplyCommandResponse.request_id', index=0, number=1, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='log_index', full_name='mobile.server.ApplyCommandResponse.log_index', index=1, number=2, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='log_term', full_name='mobile.server.ApplyCommandResponse.log_term', index=2, number=3, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=623, serialized_end=702)
_APPLYCOMMANDERROR = _descriptor.Descriptor(name='ApplyCommandError', full_name='mobile.server.ApplyCommandError', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='request_id', full_name='mobile.server.ApplyCommandError.request_id', index=0, number=1, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='error', full_name='mobile.server.ApplyCommandError.error', index=1, number=2, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=704, serialized_end=758)
_ADMINMESSAGE = _descriptor.Descriptor(name='AdminMessage', full_name='mobile.server.AdminMessage', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='command', full_name='mobile.server.AdminMessage.command', index=0, number=1, type=12, cpp_type=9, label=2, has_default_value=False, default_value=_b(''), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='arguments', full_name='mobile.server.AdminMessage.arguments', index=1, number=2, type=12, cpp_type=9, label=2, has_default_value=False, default_value=_b(''), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='request_id', full_name='mobile.server.AdminMessage.request_id', index=2, number=3, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=760, serialized_end=830)
_ADMINRESPONSE = _descriptor.Descriptor(name='AdminResponse', full_name='mobile.server.AdminResponse', filename=None, file=DESCRIPTOR, containing_type=None, fields=[
 _descriptor.FieldDescriptor(name='request_id', full_name='mobile.server.AdminResponse.request_id', index=0, number=1, type=4, cpp_type=4, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='message', full_name='mobile.server.AdminResponse.message', index=1, number=2, type=12, cpp_type=9, label=2, has_default_value=False, default_value=_b(''), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None),
 _descriptor.FieldDescriptor(name='error', full_name='mobile.server.AdminResponse.error', index=2, number=3, type=13, cpp_type=3, label=2, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, options=None)], extensions=[], nested_types=[], enum_types=[], options=None, is_extendable=False, extension_ranges=[], oneofs=[], serialized_start=832, serialized_end=899)
_APPENDENTRIESINFO.fields_by_name['entries'].message_type = _LOGENTRY
DESCRIPTOR.message_types_by_name['RaftAddress'] = _RAFTADDRESS
DESCRIPTOR.message_types_by_name['RequestVoteInfo'] = _REQUESTVOTEINFO
DESCRIPTOR.message_types_by_name['ResponseVoteInfo'] = _RESPONSEVOTEINFO
DESCRIPTOR.message_types_by_name['NextNodeIdxInfo'] = _NEXTNODEIDXINFO
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
DESCRIPTOR.message_types_by_name['AppendEntriesInfo'] = _APPENDENTRIESINFO
DESCRIPTOR.message_types_by_name['AppendEntriesSerializedInfo'] = _APPENDENTRIESSERIALIZEDINFO
DESCRIPTOR.message_types_by_name['ApplyCommand'] = _APPLYCOMMAND
DESCRIPTOR.message_types_by_name['ApplyCommandResponse'] = _APPLYCOMMANDRESPONSE
DESCRIPTOR.message_types_by_name['ApplyCommandError'] = _APPLYCOMMANDERROR
DESCRIPTOR.message_types_by_name['AdminMessage'] = _ADMINMESSAGE
DESCRIPTOR.message_types_by_name['AdminResponse'] = _ADMINRESPONSE
RaftAddress = _reflection.GeneratedProtocolMessageType('RaftAddress', (_message.Message,), dict(DESCRIPTOR=_RAFTADDRESS, __module__='raft_pb2'))
_sym_db.RegisterMessage(RaftAddress)
RequestVoteInfo = _reflection.GeneratedProtocolMessageType('RequestVoteInfo', (_message.Message,), dict(DESCRIPTOR=_REQUESTVOTEINFO, __module__='raft_pb2'))
_sym_db.RegisterMessage(RequestVoteInfo)
ResponseVoteInfo = _reflection.GeneratedProtocolMessageType('ResponseVoteInfo', (_message.Message,), dict(DESCRIPTOR=_RESPONSEVOTEINFO, __module__='raft_pb2'))
_sym_db.RegisterMessage(ResponseVoteInfo)
NextNodeIdxInfo = _reflection.GeneratedProtocolMessageType('NextNodeIdxInfo', (_message.Message,), dict(DESCRIPTOR=_NEXTNODEIDXINFO, __module__='raft_pb2'))
_sym_db.RegisterMessage(NextNodeIdxInfo)
LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), dict(DESCRIPTOR=_LOGENTRY, __module__='raft_pb2'))
_sym_db.RegisterMessage(LogEntry)
AppendEntriesInfo = _reflection.GeneratedProtocolMessageType('AppendEntriesInfo', (_message.Message,), dict(DESCRIPTOR=_APPENDENTRIESINFO, __module__='raft_pb2'))
_sym_db.RegisterMessage(AppendEntriesInfo)
AppendEntriesSerializedInfo = _reflection.GeneratedProtocolMessageType('AppendEntriesSerializedInfo', (_message.Message,), dict(DESCRIPTOR=_APPENDENTRIESSERIALIZEDINFO, __module__='raft_pb2'))
_sym_db.RegisterMessage(AppendEntriesSerializedInfo)
ApplyCommand = _reflection.GeneratedProtocolMessageType('ApplyCommand', (_message.Message,), dict(DESCRIPTOR=_APPLYCOMMAND, __module__='raft_pb2'))
_sym_db.RegisterMessage(ApplyCommand)
ApplyCommandResponse = _reflection.GeneratedProtocolMessageType('ApplyCommandResponse', (_message.Message,), dict(DESCRIPTOR=_APPLYCOMMANDRESPONSE, __module__='raft_pb2'))
_sym_db.RegisterMessage(ApplyCommandResponse)
ApplyCommandError = _reflection.GeneratedProtocolMessageType('ApplyCommandError', (_message.Message,), dict(DESCRIPTOR=_APPLYCOMMANDERROR, __module__='raft_pb2'))
_sym_db.RegisterMessage(ApplyCommandError)
AdminMessage = _reflection.GeneratedProtocolMessageType('AdminMessage', (_message.Message,), dict(DESCRIPTOR=_ADMINMESSAGE, __module__='raft_pb2'))
_sym_db.RegisterMessage(AdminMessage)
AdminResponse = _reflection.GeneratedProtocolMessageType('AdminResponse', (_message.Message,), dict(DESCRIPTOR=_ADMINRESPONSE, __module__='raft_pb2'))
_sym_db.RegisterMessage(AdminResponse)
DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\x80\x01\x01\x90\x01\x01'))
_IRAFT = _descriptor.ServiceDescriptor(name='IRaft', full_name='mobile.server.IRaft', file=DESCRIPTOR, index=0, options=None, serialized_start=902, serialized_end=1724, methods=[
 _descriptor.MethodDescriptor(name='register_replication', full_name='mobile.server.IRaft.register_replication', index=0, containing_service=None, input_type=_RAFTADDRESS, output_type=common_pb2._VOID, options=None),
 _descriptor.MethodDescriptor(name='request_vote', full_name='mobile.server.IRaft.request_vote', index=1, containing_service=None, input_type=_REQUESTVOTEINFO, output_type=common_pb2._VOID, options=None),
 _descriptor.MethodDescriptor(name='response_vote', full_name='mobile.server.IRaft.response_vote', index=2, containing_service=None, input_type=_RESPONSEVOTEINFO, output_type=common_pb2._VOID, options=None),
 _descriptor.MethodDescriptor(name='next_node_idx', full_name='mobile.server.IRaft.next_node_idx', index=3, containing_service=None, input_type=_NEXTNODEIDXINFO, output_type=common_pb2._VOID, options=None),
 _descriptor.MethodDescriptor(name='append_entries', full_name='mobile.server.IRaft.append_entries', index=4, containing_service=None, input_type=_APPENDENTRIESINFO, output_type=common_pb2._VOID, options=None),
 _descriptor.MethodDescriptor(name='append_entries_serialized', full_name='mobile.server.IRaft.append_entries_serialized', index=5, containing_service=None, input_type=_APPENDENTRIESSERIALIZEDINFO, output_type=common_pb2._VOID, options=None),
 _descriptor.MethodDescriptor(name='apply_command', full_name='mobile.server.IRaft.apply_command', index=6, containing_service=None, input_type=_APPLYCOMMAND, output_type=common_pb2._VOID, options=None),
 _descriptor.MethodDescriptor(name='apply_command_response', full_name='mobile.server.IRaft.apply_command_response', index=7, containing_service=None, input_type=_APPLYCOMMANDRESPONSE, output_type=common_pb2._VOID, options=None),
 _descriptor.MethodDescriptor(name='apply_command_error', full_name='mobile.server.IRaft.apply_command_error', index=8, containing_service=None, input_type=_APPLYCOMMANDERROR, output_type=common_pb2._VOID, options=None),
 _descriptor.MethodDescriptor(name='admin_message', full_name='mobile.server.IRaft.admin_message', index=9, containing_service=None, input_type=_ADMINMESSAGE, output_type=common_pb2._VOID, options=None),
 _descriptor.MethodDescriptor(name='admin_response', full_name='mobile.server.IRaft.admin_response', index=10, containing_service=None, input_type=_ADMINRESPONSE, output_type=common_pb2._VOID, options=None)])
IRaft = service_reflection.GeneratedServiceType('IRaft', (_service.Service,), dict(DESCRIPTOR=_IRAFT, __module__='raft_pb2'))
IRaft_Stub = service_reflection.GeneratedServiceStubType('IRaft_Stub', (IRaft,), dict(DESCRIPTOR=_IRAFT, __module__='raft_pb2'))