# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/data/90208.py
_reload_all = True
DataDict = {90208: {'Content': {'MC_BEAT_BACK': {'action_param': (
                                                       0, ['gethitfront', 'lower', 1, {'loop': True}]),
                                        'action_state': 'BeatBack',
                                        'custom_param': {'max_h_speed': 50,
                                                         'min_h_speed': 10,
                                                         'max_v_speed': 30,
                                                         'min_v_speed': 10,
                                                         'max_affect_dist': 15,
                                                         'gravity': 50
                                                         }
                                        },
                       'MC_DEAD': {'action_state': 'MonsterDie',
                                   'custom_param': {'sfx_path': 'effect/fx/monster/pve/monster_dying.sfx',
                                                    'sfx_delay': 0.5,
                                                    'die_anim': 'death',
                                                    'die_anim_rate': 1.0
                                                    }
                                   },
                       'MC_FROZEN': {'action_state': 'OnFrozen'
                                     },
                       'MC_IMMOBILIZE': {'action_param': (
                                                        0, ['gethitfront', 'lower', 1, {'loop': True}]),
                                         'action_state': 'Immobilize'
                                         },
                       'MC_JUMP_1': {'action_param': (
                                                    0, ['idlebreathe', 'lower', 1]),
                                     'action_state': 'JumpUp',
                                     'custom_param': {'gravity': 57,'jump_speed': 36,'anim_duration': 1}},
                       'MC_JUMP_2': {'action_param': (
                                                    0, ['idlebreathe', 'lower', 1, {'loop': True}]),
                                     'action_state': 'Fall',
                                     'custom_param': {'gravity': 100}},
                       'MC_JUMP_3': {'action_param': (
                                                    0, ['idlebreathe', 'lower', 1]),
                                     'action_state': 'OnGround',
                                     'custom_param': {'anim_duration': 0.5,'recover_trigger_speed': 36}},
                       'MC_MECHA_BOARDING': {'action_state': 'MonsterBorn',
                                             'custom_param': {'sfx_path': 'effect/fx/monster/pve/monster_born.sfx',
                                                              'born_anim': 'groundappear',
                                                              'born_anim_rate': 1.0,
                                                              'born_anim_dur': 1.0
                                                              }
                                             },
                       'MC_MONSTER_AIMTURN': {'action_state': 'MonsterAimTurn',
                                              'custom_param': {'skill_id': 9020854,
                                                               'max_aim_dur': 1.2,
                                                               'aim_speed': 3.14,
                                                               'aim_left_anim': 'turnleft',
                                                               'aim_left_anim_rate': 1.0,
                                                               'aim_right_anim': 'turnright',
                                                               'aim_right_anim_rate': 1.0
                                                               }
                                              },
                       'MC_MONSTER_DASH': {'action_state': 'MonsterDash',
                                           'custom_param': {'skill_id': 9020852,
                                                            'dash_form': 2,
                                                            'dash_type': 1,
                                                            'dash_count': 1,
                                                            'dash_dur_list': [
                                                                            0.5],
                                                            'dash_speed_list': [
                                                                              230],
                                                            'pre_anim_list': [
                                                                            'jumplegsattack'],
                                                            'pre_anim_dur_list': [
                                                                                0.2],
                                                            'pre_anim_rate_list': [
                                                                                 1.0],
                                                            'dash_anim_list': [
                                                                             ''],
                                                            'dash_anim_rate_list': [
                                                                                  1.0],
                                                            'bac_anim_list': [
                                                                            ''],
                                                            'bac_anim_dur_list': [
                                                                                0.3],
                                                            'bac_anim_rate_list': [
                                                                                 1.0],
                                                            'begin_aoe_skill_ids': [],'end_aoe_skill_ids': [],'col_info': [
                                                                       5, 6],
                                                            'is_draw_col': False,
                                                            'aim_turn': True
                                                            }
                                           },
                       'MC_MONSTER_MELEE': {'action_state': 'MonsterMelee',
                                            'custom_param': {'hit_range': [
                                                                         5, 5, 6],
                                                             'skill_id': 9020851,
                                                             'pre_anim': 'legsattack',
                                                             'pre_anim_rate': 1.0,
                                                             'pre_anim_dur': 0.4,
                                                             'atk_anim': '',
                                                             'atk_anim_rate': 1.0,
                                                             'atk_anim_dur': 0.3,
                                                             'bac_anim': '',
                                                             'bac_anim_rate': 1.0,
                                                             'bac_anim_dur': 0.3,
                                                             'aim_turn': True
                                                             }
                                            },
                       'MC_MONSTER_SCOUT': {'action_state': 'MonsterScout',
                                            'custom_param': {'skill_id': 9020853,
                                                             'anim_name': 'idlelookaround',
                                                             'anim_rate': 1.0,
                                                             'anim_dur': 4.2
                                                             }
                                            },
                       'MC_MOVE': {'action_param': (
                                                  0, ['walk_f', 'lower', 1, {'loop': True}]),
                                   'action_state': 'Walk',
                                   'custom_param': {'walk_speed': 10,'move_acc': 30,'brake_acc': -30,'dynamic_speed_rate': 0}},
                       'MC_RUN': {'action_param': (
                                                 0, ['walk_f', 'lower', 1, {'loop': True}]),
                                  'action_state': 'Run',
                                  'custom_param': {'walk_speed': 10,'run_speed': 14,'move_acc': 30,'brake_acc': -30,'dynamic_speed_rate': 4}},
                       'MC_STAND': {'action_param': (
                                                   0, ['idlebreathe', 'lower', 1, {'loop': True}]),
                                    'action_state': 'Stand'
                                    },
                       'MC_TURN ': {'action_state': 'Turn',
                                    'custom_param': {'enable_twist_yaw': False,
                                                     'enable_twist_pitch': True
                                                     }
                                    }
                       },
           'Name': 'PVE\xe4\xb8\x80\xe5\x88\x80\xe6\x80\xaa\xe8\xb7\xb3\xe8\x9a\xa4',
           'QuickLink': 1
           },
   'status': {'Content': {'MC_BEAT_BACK': {'MC_DEAD': 2,
                                           'MC_FROZEN': 2,
                                           'MC_HIT': 1,
                                           'MC_IMMOBILIZE': 2,
                                           'MC_JUMP_1': 1,
                                           'MC_JUMP_2': 2,
                                           'MC_JUMP_3': 2,
                                           'MC_MECHA_BOARDING': 1,
                                           'MC_MONSTER_AIMTURN': 1,
                                           'MC_MONSTER_DASH': 1,
                                           'MC_MONSTER_MELEE': 1,
                                           'MC_MONSTER_SCOUT': 1,
                                           'MC_MOVE': 1,
                                           'MC_RUN': 1,
                                           'MC_STAND': 1,
                                           'MC_TURN ': 1
                                           },
                          'MC_DEAD': {'MC_BEAT_BACK': 1,
                                      'MC_FROZEN': 1,
                                      'MC_HIT': 1,
                                      'MC_IMMOBILIZE': 1,
                                      'MC_JUMP_1': 1,
                                      'MC_JUMP_2': 1,
                                      'MC_JUMP_3': 1,
                                      'MC_MECHA_BOARDING': 1,
                                      'MC_MONSTER_AIMTURN': 1,
                                      'MC_MONSTER_DASH': 1,
                                      'MC_MONSTER_MELEE': 1,
                                      'MC_MONSTER_SCOUT': 1,
                                      'MC_MOVE': 1,
                                      'MC_RUN': 1,
                                      'MC_STAND': 1,
                                      'MC_TURN ': 1
                                      },
                          'MC_FROZEN': {'MC_BEAT_BACK': 1,
                                        'MC_DEAD': 2,
                                        'MC_HIT': 1,
                                        'MC_IMMOBILIZE': 1,
                                        'MC_JUMP_1': 1,
                                        'MC_JUMP_2': 1,
                                        'MC_JUMP_3': 1,
                                        'MC_MECHA_BOARDING': 1,
                                        'MC_MONSTER_AIMTURN': 1,
                                        'MC_MONSTER_DASH': 1,
                                        'MC_MONSTER_MELEE': 1,
                                        'MC_MONSTER_SCOUT': 1,
                                        'MC_MOVE': 1,
                                        'MC_RUN': 1,
                                        'MC_STAND': 1,
                                        'MC_TURN ': 1
                                        },
                          'MC_IMMOBILIZE': {'MC_BEAT_BACK': 2,
                                            'MC_DEAD': 2,
                                            'MC_FROZEN': 2,
                                            'MC_HIT': 1,
                                            'MC_JUMP_1': 1,
                                            'MC_JUMP_2': 1,
                                            'MC_JUMP_3': 1,
                                            'MC_MECHA_BOARDING': 1,
                                            'MC_MONSTER_AIMTURN': 1,
                                            'MC_MONSTER_DASH': 1,
                                            'MC_MONSTER_MELEE': 1,
                                            'MC_MONSTER_SCOUT': 1,
                                            'MC_MOVE': 1,
                                            'MC_RUN': 1,
                                            'MC_STAND': 1,
                                            'MC_TURN ': 1
                                            },
                          'MC_JUMP_1': {'MC_BEAT_BACK': 2,
                                        'MC_DEAD': 2,
                                        'MC_FROZEN': 2,
                                        'MC_IMMOBILIZE': 2,
                                        'MC_JUMP_2': 2,
                                        'MC_JUMP_3': 2,
                                        'MC_MECHA_BOARDING': 1,
                                        'MC_MONSTER_AIMTURN': 2,
                                        'MC_MONSTER_DASH': 2,
                                        'MC_MONSTER_SCOUT': 2,
                                        'MC_RUN': 2,
                                        'MC_STAND': 1,
                                        'MC_TURN ': 1
                                        },
                          'MC_JUMP_2': {'MC_BEAT_BACK': 2,
                                        'MC_DEAD': 2,
                                        'MC_FROZEN': 2,
                                        'MC_IMMOBILIZE': 2,
                                        'MC_JUMP_1': 1,
                                        'MC_JUMP_3': 2,
                                        'MC_MECHA_BOARDING': 1,
                                        'MC_MONSTER_AIMTURN': 2,
                                        'MC_MONSTER_DASH': 2,
                                        'MC_MONSTER_SCOUT': 2,
                                        'MC_MOVE': 1,
                                        'MC_STAND': 1,
                                        'MC_TURN ': 1
                                        },
                          'MC_JUMP_3': {'MC_BEAT_BACK': 2,
                                        'MC_DEAD': 2,
                                        'MC_FROZEN': 2,
                                        'MC_IMMOBILIZE': 2,
                                        'MC_JUMP_1': 2,
                                        'MC_MECHA_BOARDING': 1,
                                        'MC_MONSTER_AIMTURN': 2,
                                        'MC_MONSTER_DASH': 2,
                                        'MC_MONSTER_SCOUT': 2,
                                        'MC_MOVE': 2,
                                        'MC_RUN': 1,
                                        'MC_STAND': 2,
                                        'MC_TURN ': 1
                                        },
                          'MC_MECHA_BOARDING': {'MC_BEAT_BACK': 1,
                                                'MC_DEAD': 2,
                                                'MC_FROZEN': 2,
                                                'MC_HIT': 1,
                                                'MC_IMMOBILIZE': 1,
                                                'MC_JUMP_1': 1,
                                                'MC_JUMP_2': 1,
                                                'MC_JUMP_3': 1,
                                                'MC_MONSTER_AIMTURN': 1,
                                                'MC_MONSTER_DASH': 1,
                                                'MC_MONSTER_SCOUT': 1,
                                                'MC_MOVE': 1,
                                                'MC_RUN': 1,
                                                'MC_STAND': 2,
                                                'MC_TURN ': 1
                                                },
                          'MC_MONSTER_AIMTURN': {'MC_BEAT_BACK': 2,
                                                 'MC_DEAD': 2,
                                                 'MC_FROZEN': 2,
                                                 'MC_HIT': 1,
                                                 'MC_IMMOBILIZE': 2,
                                                 'MC_JUMP_1': 1,
                                                 'MC_JUMP_2': 1,
                                                 'MC_JUMP_3': 1,
                                                 'MC_MECHA_BOARDING': 1,
                                                 'MC_MONSTER_DASH': 2,
                                                 'MC_MONSTER_MELEE': 1,
                                                 'MC_MONSTER_SCOUT': 2,
                                                 'MC_MOVE': 1,
                                                 'MC_RUN': 1,
                                                 'MC_STAND': 1,
                                                 'MC_TURN ': 1
                                                 },
                          'MC_MONSTER_DASH': {'MC_BEAT_BACK': 2,
                                              'MC_DEAD': 2,
                                              'MC_FROZEN': 2,
                                              'MC_HIT': 2,
                                              'MC_IMMOBILIZE': 2,
                                              'MC_JUMP_1': 1,
                                              'MC_JUMP_2': 1,
                                              'MC_JUMP_3': 1,
                                              'MC_MECHA_BOARDING': 1,
                                              'MC_MONSTER_AIMTURN': 2,
                                              'MC_MONSTER_MELEE': 1,
                                              'MC_MONSTER_SCOUT': 1,
                                              'MC_MOVE': 1,
                                              'MC_RUN': 1,
                                              'MC_STAND': 1,
                                              'MC_TURN ': 1
                                              },
                          'MC_MONSTER_MELEE': {'MC_BEAT_BACK': 2,
                                               'MC_DEAD': 2,
                                               'MC_FROZEN': 2,
                                               'MC_HIT': 2,
                                               'MC_IMMOBILIZE': 2,
                                               'MC_JUMP_1': 1,
                                               'MC_JUMP_2': 1,
                                               'MC_JUMP_3': 1,
                                               'MC_MECHA_BOARDING': 1,
                                               'MC_MONSTER_AIMTURN': 2,
                                               'MC_MONSTER_DASH': 2,
                                               'MC_MONSTER_SCOUT': 2,
                                               'MC_MOVE': 1,
                                               'MC_RUN': 1,
                                               'MC_STAND': 1,
                                               'MC_TURN ': 1
                                               },
                          'MC_MONSTER_SCOUT': {'MC_BEAT_BACK': 2,
                                               'MC_DEAD': 2,
                                               'MC_FROZEN': 2,
                                               'MC_HIT': 2,
                                               'MC_IMMOBILIZE': 2,
                                               'MC_JUMP_1': 2,
                                               'MC_JUMP_2': 2,
                                               'MC_JUMP_3': 2,
                                               'MC_MECHA_BOARDING': 2,
                                               'MC_MONSTER_AIMTURN': 2,
                                               'MC_MONSTER_DASH': 2,
                                               'MC_MONSTER_MELEE': 2,
                                               'MC_MOVE': 2,
                                               'MC_RUN': 2,
                                               'MC_STAND': 2,
                                               'MC_TURN ': 2
                                               },
                          'MC_MOVE': {'MC_DEAD': 2,
                                      'MC_FROZEN': 2,
                                      'MC_JUMP_1': 2,
                                      'MC_JUMP_2': 2,
                                      'MC_JUMP_3': 2,
                                      'MC_MECHA_BOARDING': 1,
                                      'MC_MONSTER_AIMTURN': 2,
                                      'MC_MONSTER_DASH': 2,
                                      'MC_MONSTER_MELEE': 2,
                                      'MC_MONSTER_SCOUT': 2,
                                      'MC_MOVE': 1,
                                      'MC_RUN': 2,
                                      'MC_STAND': 2,
                                      'MC_TURN ': 1
                                      },
                          'MC_RUN': {'MC_DEAD': 2,
                                     'MC_FROZEN': 2,
                                     'MC_JUMP_1': 2,
                                     'MC_JUMP_2': 2,
                                     'MC_JUMP_3': 2,
                                     'MC_MECHA_BOARDING': 1,
                                     'MC_MONSTER_AIMTURN': 2,
                                     'MC_MONSTER_DASH': 2,
                                     'MC_MONSTER_MELEE': 2,
                                     'MC_MONSTER_SCOUT': 2,
                                     'MC_MOVE': 2,
                                     'MC_STAND': 2,
                                     'MC_TURN ': 1
                                     },
                          'MC_STAND': {'MC_DEAD': 2,
                                       'MC_FROZEN': 2,
                                       'MC_JUMP_1': 2,
                                       'MC_JUMP_2': 2,
                                       'MC_JUMP_3': 2,
                                       'MC_MECHA_BOARDING': 1,
                                       'MC_MONSTER_AIMTURN': 2,
                                       'MC_MONSTER_DASH': 2,
                                       'MC_MONSTER_SCOUT': 2,
                                       'MC_MOVE': 2,
                                       'MC_RUN': 2,
                                       'MC_TURN ': 2
                                       },
                          'MC_TURN ': {'MC_DEAD': 2,
                                       'MC_FROZEN': 2,
                                       'MC_JUMP_1': 2,
                                       'MC_JUMP_2': 2,
                                       'MC_JUMP_3': 2,
                                       'MC_MECHA_BOARDING': 1,
                                       'MC_MONSTER_AIMTURN': 2,
                                       'MC_MONSTER_DASH': 2,
                                       'MC_MONSTER_SCOUT': 2,
                                       'MC_MOVE': 2,
                                       'MC_RUN': 2,
                                       'MC_STAND': 2
                                       }
                          },
              'Name': '\xe7\x8a\xb6\xe6\x80\x81\xe8\xbf\x81\xe7\xa7\xbb\xe8\xa1\xa8',
              'QuickLink': 1
              }
   }

def GetData():
    return DataDict


def Getstatus():
    return GetData()['status']['Content']


def Get90208():
    return GetData()['90208']['Content']