# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/common_const/red_packet_const.py
_reload_all = True
RED_PACKET_DELAY_SAVE = 20
RED_PACKET_VALID_DURATION = 21600
RED_PACKET_MAX_SEARCH_COUNT = 50
RED_PACKET_EXTRA_FEE = 0.01
RED_PACKET_EXTRA_CACHE_TIME = 500
RED_PACKET_RECYCLE_DELTA = 50
RED_PACKET_MAX_RECYCLE_COUNT = 500
RED_PACKET_DAY_CREATE_MAX_COUNT = 50
RED_PACKET_RICH_MONTH_CREATE_COUNT = 200
RED_PACKET_GOD_MONTH_CREATE_COUNT = 500
RED_PACKET_DAY_CREATE_RICH_MAX_COUNT = 100
RED_PACKET_DAY_RECV_MAX_COUNT = 25
LUCK_RED_PACKET_DAY_RECV_MAX_COUNT = 25
RED_PACKET_DAY_CLAN_RECV_MAX_COUNT = 10
RED_PACKET_REQ_PURGE_TIMEOUT = 10
CAN_SEND_RED_PACKET_CHANNEL = [
 0, 2, 10]
CAN_SEND_RED_PACKET_CHANNEL_LEVEL = {0: 25,2: 25,10: 25}
RICH_TITLE_ITEM = 33765023
GOD_TITLE_ITEM = 33765024
CLAIM_FLAG_EMPTY = 1
CLAIM_FLAG_REPEAT = 2
CLAIM_FLAG_SUCCEED = 3
CLAIM_FLAG_INVALID = 4
RED_PACKET_MESSAGE_NEW_PACKET = 1
RED_PACKET_MESSAGE_DANMU = 2
RED_PACKET_MESSAGE_CLAIM = 3
NORMAL_COVER_ITEM_NO = 80000001
CHOOSE_RED_PACKET_COVER = 'choose_red_packet_cover'
RED_PACKET_DANMU_SEND_INTERVAL = 5
LUCK_SCORE_RED_PACKET = 6
PRIV_RED_PACKET = 5