# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/item/backpack_item_type.py
_reload_all = True
B_ITEM_TYPE_UNKONW_ITEM = 0
B_ITEM_TYPE_WEAPON_MAIN = 1
B_ITEM_TYPE_WEAPON_BOMB = 2
B_ITEM_TYPE_ATTACHMENT = 3
B_ITEM_TYPE_SPECIAL_BULLET = 4
B_ITEM_TYPE_BULLET = 5
B_ITEM_TYPE_HEALTH = 6
B_ITEM_TYPE_FOOD = 7
B_ITEM_TYPE_DEADBOX = 8
B_ITEM_TYPE_SCENEBOX = 9
B_ITEM_TYPE_EXOSKELETON_ATTACHMENT = 10
B_ITEM_TYPE_SUMMON = 11
B_ITEM_TYPE_BUFF = 12
B_ITEM_TYPE_BUILDING = 13
B_ITEM_TYPE_CLOTHING_FACE = 20
B_ITEM_TYPE_CLOTHING_HEAD = 21
B_ITEM_TYPE_CLOTHING_BODICE = 22
B_ITEM_TYPE_CLOTHING_BOTTOMS = 23
B_ITEM_TYPE_CLOTHING_ARMOR = 24
B_ITEM_TYPE_CLOTHING_BAG = 25
B_ITEM_TYPE_CLOTHING_SUIT = 26
B_ITEM_TYPE_CLOTHING_HAIR = 27
B_ITEM_TYPE_CLOTHING_SKIN = 28
B_ITEM_TYPE_CLOTHING_HEADWEAR = 29
B_ITEM_TYPE_CLOTHING_FACEWEAR = 30
B_ITEM_TYPE_CLOTHING_MASK = 31
B_ITEM_TYPE_CLOTHING_HAND_ARMOR = 32
B_ITEM_TYPE_CLOTHING_LEG_ARMOR = 33
B_ITEM_TYPE_MECHA_BATTERY = 34
B_ITEM_TYPE_MECHA_ENERTY = 35
B_ITEM_TYPE_SPECIAL_EFFECT = 36
B_ITEM_TYPE_MECHA_MODULE = 37
B_ITEM_TYPE_ACTIVITY = 38
B_ITEM_TYPE_ACE_STAR = 39
B_ITEM_TYPE_NEUTRAL_SHOP_CANDY = 40
B_ITEM_TYPE_GRANBELM_RUNE = 41
B_ITEM_TYPE_BACK_HOME = 42
B_ITEM_TYPE_DOGTAG = 43
B_ITEM_TYPE_MEOW_COIN = 44
B_ITEM_TYPE_KIZUNAAI_FIREWORK = 45
B_ITEM_TYPE_KIZUNAAI_CALL = 46
B_ITEM_TYPE_MAGIC_SHOP_ITEM = 47
B_ITEM_TYPE_PVE_OUT_ITEM = 48
B_ITEM_TYPE_PVE_MECHA_DEBRIS = 49
B_ITEM_TYPE_PVE_SHOP_ITEM = 97
B_ITEM_TYPE_PVE_COIN = 98
B_ITEM_TYPE_UNDEFINED = 99
B_ITEM_TYPE_PVE_THROW_ITEM = 100
B_ITEM_MECHATRAN_ID = 1667
B_ITEM_MECHATRAN_ID1 = 1669
B_ITEM_MECHATRAN_ID2 = 1670
B_ITEM_MECHATRAN_ID3 = 1671
B_ITEM_ICEWALL_ID = 9924
B_ITEM_MECHATRAN_ID1 = 1669
B_ITEM_TYPE_BACK_HOME_ID = 9935
B_ITEM_BOUNCING_PLAT = 9926
B_ITEM_BOUNCING_PLAT_9927 = 9927
B_ITEM_BOUNCING_PLAT_PVE = 10007422
B_ITEM_ICEWALL_ID_PVE = 10007423
B_ITEM_TYPE_CLOTHING = frozenset([
 B_ITEM_TYPE_CLOTHING_FACE,
 B_ITEM_TYPE_CLOTHING_HEAD,
 B_ITEM_TYPE_CLOTHING_BODICE,
 B_ITEM_TYPE_CLOTHING_BOTTOMS,
 B_ITEM_TYPE_CLOTHING_ARMOR,
 B_ITEM_TYPE_CLOTHING_BAG,
 B_ITEM_TYPE_CLOTHING_SUIT,
 B_ITEM_TYPE_CLOTHING_HAIR,
 B_ITEM_TYPE_CLOTHING_SKIN,
 B_ITEM_TYPE_CLOTHING_HEADWEAR,
 B_ITEM_TYPE_CLOTHING_FACEWEAR,
 B_ITEM_TYPE_CLOTHING_MASK,
 B_ITEM_TYPE_CLOTHING_HAND_ARMOR,
 B_ITEM_TYPE_CLOTHING_LEG_ARMOR])
BOX_CFG = (
 B_ITEM_TYPE_DEADBOX, B_ITEM_TYPE_SCENEBOX)
THROW_CFG = (B_ITEM_TYPE_WEAPON_BOMB, B_ITEM_TYPE_BUILDING)

def is_box_type(t):
    return t in BOX_CFG


def is_deadbox(t):
    return t == B_ITEM_TYPE_DEADBOX


def is_scenebox_type(t):
    return t == B_ITEM_TYPE_SCENEBOX


def is_dogtag_type(t):
    return t == B_ITEM_TYPE_DOGTAG


def is_throw_type(t):
    return t in THROW_CFG