# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/item/lobby_item_type.py
_reload_all = True
L_ITEM_TYPE_UNKONW_ITEM = 0
L_ITEM_TYPE_CURRENCY = 1
L_ITEM_TYPE_EXPERIENCE_CARD = 2
L_ITEM_TYPE_ADD_CARD = 3
L_ITEM_TYPE_ROLE = 4
L_ITEM_TYPE_MECHA = 5
L_ITEM_TYPE_ROLE_SKIN = 6
L_ITEM_TYPE_MECHA_SKIN = 7
L_ITEM_TYPE_GIFTPACKAGE = 8
L_ITEM_MMODULE_CARD = 9
L_ITEM_MMODULE_SP_SLOT_ACTIVATE = 10
L_ITEM_TYPE_WALL_PICTURE = 11
L_ITEM_MECHA_SFX = 12
L_ITEM_TYPE_GUN = 13
L_ITME_TYPE_GUNSKIN = 14
L_ITEM_TYPE_HEAD_PHOTO = 15
L_ITME_YTPE_TICKET = 16
L_ITEM_TYPE_EXCHANGE_TICKET = 17
L_ITEM_YTPE_VEHICLE = 18
L_ITEM_YTPE_VEHICLE_SKIN = 19
L_ITEM_TYPE_ACTIVITY = 20
L_ITEM_TYPE_DISCOUNT = 21
L_ITEM_TYPE_TALKING = 22
L_ITEM_TYPE_GIFTPACKAGE_AUTO = 23
L_ITEM_TYPE_HEAD = 24
L_ITEM_TYPE_BODY = 25
L_ITEM_TYPE_EMOTICON = 26
L_ITEM_TYPE_SPRAY = 27
L_ITEM_TYPE_GESTURE = 28
L_ITEM_TYPE_VOICE = 29
L_ITEM_TYPE_WEAPON_SFX = 30
L_ITEM_TYPE_SUIT = 31
L_ITEM_TYPE_LOTTERY_TICKET = 32
L_ITEM_TYPE_HEAD_FRAME = 33
L_ITEM_KILL_SFX = 34
L_ITEM_ROOM_POINT = 35
L_ITEM_TYPE_BOND = 36
L_ITEM_TYPE_BOND_GIFT_ACTIVATE = 37
L_ITEM_TYPE_BOND_STORY = 38
L_ITEM_TYPE_BOND_KEEPSAKE = 39
L_ITEM_TYPE_TALKING_EMOTICON = 40
L_ITEM_TYPE_BOND_GIFT_UPGRADE = 41
L_ITEM_TYPE_FACE_DEC = 42
L_ITEM_TYPE_WAIST_DEC = 43
L_ITEM_TYPE_LEG_DEC = 44
L_ITEM_TYPE_BATTLE_FLAG_FRAME = 45
L_ITEM_TYPE_HAIR_DEC = 46
L_ITEM_TYPE_ARM_DEC = 47
L_ITEM_TYPE_BOX = 48
L_ITEM_TYPE_MECHA_COMPONENT = 49
L_ITEM_TYPE_DECAL = 50
L_ITEM_TYPE_COLOR = 51
L_ITEM_TYPE_NEW_MECHA_COMPONENT = 52
L_ITEM_TYPE_PRODUCT = 53
L_ITEM_TYPE_MECHA_GESTURE = 54
L_ITEM_TYPE_SEASON_POINT_PROTECT = 55
L_ITEM_TYPE_VIRTUAL = 56
L_ITEM_TYPE_MEOW_COIN = 57
L_ITEM_TYPE_LOBBY_SKIN = 58
L_ITEM_TYPE_POINT = 59
L_ITEM_TYPE_MECHA_SP_ACTION = 60
L_ITEM_TYPE_MUSIC = 61
L_SHOW_ITEM = 62
L_GLOBAL_STAT_POINT = 63
L_ITEM_TYPE_TITLE = 64
L_ITEM_TYPE_MVP = 65
L_ITEM_TYPE_REDPACKET = 66
L_ITEM_TYPE_PROJECTION_KILL = 67
L_ITEM_TYPE_EX_PRIVILEGE = 68
L_ITEM_GLIDE_EFFECT = 69
L_ITEM_TYPE_PET = 70
L_ITEM_TYPE_PET_SKIN = 71
L_ITEM_TYPE_PET_EXP_CARD = 72
L_ITEM_TYPE_PVE_KEY = 73
L_ITEM_TYPE_PVE_COIN = 74
L_ITEM_TYPE_PVE_STORY_DEBRIS = 75
L_ITEM_TYPE_PVE_MECHA_DEBRIS = 76
L_ITEM_TYPE_LOBBY_SKY_BOX = 77
L_ITEM_TYPE_GUANGMU = 78
L_ITEM_TYPE_ICON = 98
L_ITEM_TYPE_OTHER = 99
ITEM_TYPE_KNAPSACK = set([
 2,
 3,
 8,
 17,
 20,
 21,
 23,
 32,
 35,
 36,
 41,
 53,
 55,
 65,
 72,
 99])
ITEM_TYPE_SKIN = set([
 6,
 7,
 14,
 19,
 71])
REDPOINT_ITEM_TYPE = set([
 L_ITEM_TYPE_ROLE,
 L_ITEM_TYPE_MECHA,
 L_ITEM_TYPE_ROLE_SKIN,
 L_ITEM_TYPE_MECHA_SKIN,
 L_ITEM_MMODULE_CARD,
 L_ITEM_MMODULE_SP_SLOT_ACTIVATE,
 L_ITEM_MECHA_SFX,
 L_ITEM_TYPE_GUN,
 L_ITME_TYPE_GUNSKIN,
 L_ITEM_TYPE_HEAD_PHOTO,
 L_ITEM_YTPE_VEHICLE,
 L_ITEM_YTPE_VEHICLE_SKIN,
 L_ITEM_TYPE_HEAD,
 L_ITEM_TYPE_BODY,
 L_ITEM_TYPE_EMOTICON,
 L_ITEM_TYPE_SPRAY,
 L_ITEM_TYPE_GESTURE,
 L_ITEM_TYPE_SUIT,
 L_ITEM_TYPE_HEAD_FRAME,
 L_ITEM_KILL_SFX,
 L_ITEM_TYPE_BOND_GIFT_ACTIVATE,
 L_ITEM_TYPE_BOND_STORY,
 L_ITEM_TYPE_BOND_KEEPSAKE,
 L_ITEM_TYPE_TALKING_EMOTICON,
 L_ITEM_TYPE_FACE_DEC,
 L_ITEM_TYPE_WAIST_DEC,
 L_ITEM_TYPE_LEG_DEC,
 L_ITEM_TYPE_HAIR_DEC,
 L_ITEM_TYPE_ARM_DEC,
 L_ITEM_TYPE_LOBBY_SKIN,
 L_ITEM_TYPE_MUSIC,
 L_ITEM_GLIDE_EFFECT,
 L_ITEM_TYPE_PET_SKIN,
 L_ITEM_TYPE_GUANGMU])
L_EXPERIENCE_CARD_CATEGORY_ROLE = 1
L_EXPERIENCE_CARD_CATEGORY_ROLE_SKIN = 2
L_EXPERIENCE_CARD_CATEGORY_MECHA = 3
L_EXPERIENCE_CARD_CATEGORY_MECHA_SKIN = 4
L_EXPERIENCE_CARD_CATEGORY_WEAPON_SKIN = 5
L_EXPERIENCE_CARD_CATEGORY_VEHICLE_SKIN = 6
MODEL_DISPLAY_TYPE = {
 L_ITEM_TYPE_ROLE, L_ITEM_TYPE_MECHA, L_ITEM_TYPE_ROLE_SKIN, L_ITEM_TYPE_MECHA_SKIN, L_ITEM_TYPE_EMOTICON,
 L_ITEM_YTPE_VEHICLE, L_ITEM_YTPE_VEHICLE_SKIN, L_ITEM_TYPE_GUN, L_ITME_TYPE_GUNSKIN, L_ITEM_MECHA_SFX,
 L_ITEM_TYPE_GESTURE, L_ITEM_TYPE_BODY, L_ITEM_TYPE_HEAD, L_ITEM_TYPE_SUIT, L_ITEM_TYPE_FACE_DEC, L_ITEM_TYPE_WAIST_DEC,
 L_ITEM_TYPE_LEG_DEC, L_ITEM_TYPE_HAIR_DEC, L_ITEM_TYPE_ARM_DEC, L_ITEM_TYPE_PET_SKIN, L_ITEM_TYPE_MECHA_GESTURE}
DISPLAY_SCENE_TYPE_BATTLE_PASS = {
 L_ITEM_TYPE_ROLE, L_ITEM_TYPE_MECHA, L_ITEM_TYPE_ROLE_SKIN, L_ITEM_TYPE_MECHA_SKIN,
 L_ITEM_MECHA_SFX, L_ITEM_TYPE_EMOTICON, L_ITEM_TYPE_GESTURE, L_ITEM_TYPE_BODY,
 L_ITEM_TYPE_SUIT, L_ITEM_TYPE_HEAD, L_ITEM_TYPE_FACE_DEC, L_ITEM_TYPE_WAIST_DEC,
 L_ITEM_TYPE_LEG_DEC, L_ITEM_TYPE_HAIR_DEC, L_ITEM_TYPE_ARM_DEC, L_ITEM_TYPE_PET_SKIN,
 L_ITEM_TYPE_MECHA_GESTURE}
PENDANT_DISPLAY_TYPE = {
 L_ITEM_TYPE_BODY, L_ITEM_TYPE_HEAD, L_ITEM_TYPE_SUIT, L_ITEM_TYPE_FACE_DEC, L_ITEM_TYPE_WAIST_DEC, L_ITEM_TYPE_LEG_DEC, L_ITEM_TYPE_HAIR_DEC, L_ITEM_TYPE_ARM_DEC}
RP_ROLE_TYPE = {
 L_ITEM_TYPE_ROLE, L_ITEM_TYPE_MECHA, L_ITEM_TYPE_GUN, L_ITEM_YTPE_VEHICLE, L_ITEM_MECHA_SFX, L_ITEM_TYPE_HEAD_PHOTO, L_ITEM_TYPE_HEAD_FRAME}
RP_SKIN_TYPE = {L_ITEM_TYPE_ROLE_SKIN, L_ITEM_TYPE_MECHA_SKIN, L_ITME_TYPE_GUNSKIN, L_ITEM_YTPE_VEHICLE_SKIN}
RP_ROLE_DIY = {L_ITEM_TYPE_VOICE}
RP_ROLE_DEC_SET = {L_ITEM_TYPE_HEAD, L_ITEM_TYPE_BODY, L_ITEM_TYPE_SUIT, L_ITEM_TYPE_FACE_DEC, L_ITEM_TYPE_WAIST_DEC, L_ITEM_TYPE_LEG_DEC, L_ITEM_TYPE_HAIR_DEC, L_ITEM_TYPE_ARM_DEC}
RP_MECHA_ITEM_SET = {L_ITEM_MMODULE_CARD}
RP_BELONG_SET = RP_SKIN_TYPE | RP_ROLE_DIY | RP_ROLE_DEC_SET | RP_MECHA_ITEM_SET
ROLE_TO_SKIN = {L_ITEM_TYPE_ROLE: L_ITEM_TYPE_ROLE_SKIN,L_ITEM_TYPE_MECHA: L_ITEM_TYPE_MECHA_SKIN,
   L_ITEM_TYPE_GUN: L_ITME_TYPE_GUNSKIN,
   L_ITEM_YTPE_VEHICLE: L_ITEM_YTPE_VEHICLE_SKIN
   }
ITEM_TYPE_DEC = {
 L_ITEM_TYPE_HEAD, L_ITEM_TYPE_BODY, L_ITEM_TYPE_SUIT, L_ITEM_TYPE_FACE_DEC, L_ITEM_TYPE_WAIST_DEC, L_ITEM_TYPE_LEG_DEC, L_ITEM_TYPE_ARM_DEC, L_ITEM_TYPE_HAIR_DEC}
ROLE_SKIN_TYPE = ITEM_TYPE_DEC.union(set([L_ITEM_TYPE_ROLE_SKIN]))
MAIN_RP_TYPE = {'role_head_rp': (
                  L_ITEM_TYPE_HEAD_PHOTO, L_ITEM_TYPE_HEAD_FRAME),
   'role_info_rp': (
                  L_ITEM_TYPE_ROLE, L_ITEM_TYPE_ROLE_SKIN) + tuple(RP_ROLE_DIY),
   'mecha_info_rp': (
                   L_ITEM_TYPE_MECHA, L_ITEM_TYPE_MECHA_SKIN),
   'tech_info_rp': (
                  L_ITEM_MMODULE_CARD,),
   'item_book_rp': (
                  L_ITEM_TYPE_MECHA_SKIN, L_ITEM_TYPE_ROLE_SKIN, L_ITEM_YTPE_VEHICLE_SKIN, L_ITME_TYPE_GUNSKIN,
                  L_ITEM_TYPE_GESTURE, L_ITEM_TYPE_EMOTICON, L_ITEM_TYPE_SPRAY, L_ITEM_KILL_SFX,
                  L_ITEM_TYPE_LOBBY_SKIN, L_ITEM_TYPE_MUSIC, L_ITEM_GLIDE_EFFECT, L_ITEM_TYPE_PET_SKIN)
   }
ITEM_TYPE_CLICK_TYPE_FUNC = {L_ITEM_TYPE_GESTURE: [
                       'unimportant_gesture', 'set_interaction_item_type_rp_click_time', 'get_interaction_item_type_rp_click_time'],
   L_ITEM_TYPE_EMOTICON: [
                        'unimportant_emoticon', 'set_interaction_item_type_rp_click_time', 'get_interaction_item_type_rp_click_time'],
   L_ITEM_TYPE_SPRAY: [
                     'unimportant_spray', 'set_interaction_item_type_rp_click_time', 'get_interaction_item_type_rp_click_time']
   }
GOODS_CHECK_OWN_TYPE = {
 L_ITEM_KILL_SFX, L_ITEM_MECHA_SFX, L_ITEM_TYPE_GESTURE, L_ITEM_TYPE_BATTLE_FLAG_FRAME, L_ITEM_TYPE_HEAD_FRAME,
 L_ITEM_TYPE_EMOTICON, L_ITEM_TYPE_SPRAY, L_ITEM_TYPE_MECHA_SP_ACTION, L_ITEM_TYPE_PET_SKIN}
GOODS_CHECK_OWN_TYPE.update(RP_SKIN_TYPE)
GOODS_CHECK_OWN_TYPE.update(RP_ROLE_DEC_SET)
ITEM_SHOW_TRANSFORM_BY_BELONG_ID = [
 1051667]