# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/common_const/sync_const.py
from __future__ import absolute_import
import six_ex
MAX_ITVL_SILENT = 0.1
MAX_ITVL_PUPPET_SIM = MAX_ITVL_SILENT * 1.5
JITTER_ROLL_TIME = 0.4
TLRC_HORI_DISABLE = 10.0
DELAY_CHECK_PASS = 2.0
SYNC_TRIGGER_NAME_EULER = 'euler3'
SYNC_TRIGGER_NAME_AV_POS = 'av_pos'
SYNC_ITPLER_NAME_ROT = 'rot'
SYNC_ITPLER_NAME_EULER = 'euler3_t'
SYNC_TRIGGER_NAME_AV_POS = 'av_pos_t'
SYNC_LEVEL_GROUPMATE_AND_SPECTATE = 1
SYNC_LEVEL_GROUPMATE_AND_SELF_SPECTATE = 2
SYNC_LEVEL_SELF_AND_SPECTATE = 3
SYNC_LEVEL_SPECTATE = 4
SYNC_LEVEL_GROUPMATE = 5
SYNC_LEVEL_GROUPMATE_AND_SELF_SPECTATE_RECURSIVE = 6
VEL_MOVE_FORWARD_SEND = 30.0
ID_ATTACK_START = 10001
MOVE_ITPL_CONSUME = 10
MIN_MOVE_ITPL_ITVL = 10
MAX_MOVE_ITPL_ITVL = 30
MP_LEVEL_ITVL = {50: MIN_MOVE_ITPL_ITVL,
   100: 15,
   160: 20,
   240: 25
   }
ARR_DIS_LEVEL = sorted(six_ex.keys(MP_LEVEL_ITVL))
SENDER_MODE_NORMAL = 1
SENDER_MODE_ROTATION_ONLY = 2
SENDER_MODE_BALL_CTRL = 3
SENDER_MODE_PARACHUTE_SIMULATE_FOLLOWING = 4
Y_AXIS_RANGE_POSITIVE = 15000
Y_AXIS_RANGE_NEGATIVE = -2500
DELEGATE_TYPE_NONE = 0
DELEGATE_TYPE_EJECT = 1