# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/common/const/uiconst.py
from __future__ import absolute_import
FONT_DEFAULT = '\xe5\xbe\xae\xe8\xbd\xaf\xe9\x9b\x85\xe9\xbb\x91'
FONT_WORDART = 'droidsansfallback.ttf'
AIM_ZORDER = 1
BG_ZORDER = 1
BETWEEN_BG_AND_BSCALE_PLATE_ZORDER = 2
SCALE_PLATE_ZORDER = 3
SMALL_MAP_ZORDER = 4
HP_ZORDER = 5
LOW_MESSAGE_ZORDER = 6
ROCKER_LAYER_ZORDER = 9
BASE_LAYER_ZORDER = 10
BASE_LAYER_ZORDER_1 = 11
BATTLE_MESSAGE_ZORDER = 15
NORMAL_LAYER_ZORDER_00 = 18
NORMAL_LAYER_ZORDER_0 = 19
NORMAL_LAYER_ZORDER = 20
NORMAL_LAYER_ZORDER_1 = 21
NORMAL_LAYER_ZORDER_2 = 22
NORMAL_LAYER_ZORDER_3 = 23
DIALOG_LAYER_BAN_ZORDER = 29
GUIDE_LAYER_ZORDER = 30
DIALOG_LAYER_ZORDER_0 = 39
DIALOG_LAYER_ZORDER = 40
DIALOG_LAYER_ZORDER_1 = 41
DIALOG_LAYER_ZORDER_2 = 42
SECOND_CONFIRM_LAYER = 43
TOP_ZORDER = 50
LOADING_BG_ZORDER = 61
LOADING_ZORDER = 62
LOADING_ZORDER_ABOVE = 63
TOP_MSG_ZORDER = 68
SCREEN_LOCKER_ZORDER = 70
DISCONNECT_ZORDER = 71
UI_TYPE_NORMAL = 1
UI_TYPE_TRANS = 2
UI_TYPE_EFFECT = 3
UI_TYPE_NO_RELEASE = 4
UI_TYPE_CONFIRM = 5
UI_TYPE_MESSAGE = 6
UI_TYPE_SPECIAL = 7
UI_VKB_CLOSE = 1
UI_VKB_NO_EFFECT = 2
UI_VKB_CUSTOM = 3
UI_VKB_CLOSE_BY_DEFAULT_FUNC_NAME = 4
COCOSUI_VERSION_3_2 = 0
COCOSUI_VERSION_3_2_NEOX = 1
COCOSUI_VERSION_3_4 = 2
COCOSUI_VERSION_3_4_NEOX = 3
SHADER_PATH = 'shader/ui2'
DEPTH24_STENCIL8_OES = 21
ZERO = 1
ONE = 2
ONE_MINUS_SRC_ALPHA = 6
USE_NEOX = True
import cocosui
if hasattr(cocosui, 'COCOSUI2DX_VERSION'):
    if cocosui.COCOSUI2DX_VERSION == COCOSUI_VERSION_3_2:
        USE_NEOX = False
        SHADER_PATH = 'shader/ui'
        DEPTH24_STENCIL8_OES = 35056