# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/common_const/pve_const.py
SETTLE_WIN = 1
SETTLE_LOSE = 2
SETTLE_SAVE = 3
TIP_TYPE_COMMON = 1
TIP_TYPE_WARN = 2
TIP_TYPE_BOSS = 3
TIP_TYPE_SMALL = 4
TIP_TYPE_BIG = 5
TIP_TYPE_BOX_SHOP = 6
TIP_TYPE_BUFF = 7
TIP_TYPE_REGION = 8
TIP_TYPE_NEXT_CONFIRM = 9
TIP_TYPE_TEAMMATE_DEAD = 10
TIP_TYPE_TEAMMATE_QUIT = 11
TIP_TYPE_TEAM_DEFEAT = 12
TIP_TYPE_TEAM_REVIVE = 13
TIP_TYPE_DONATE_BLESS = 14
TARGET_TYPE_KILL_DYNAMIC_NUM_ENTITY = 1
TARGET_TYPE_KILL_ENTITY = 2
TARGET_TYPE_ARRIVE = 3
TARGET_TYPE_NEXT_LEVEL = 4
TARGET_TYPE_SURVIVE = 5
TARGET_TYPE_KILL_FIX_NUM_ENTITY = 6
TARGET_TYPE_KILL_ALL = 7
TARGET_TYPE_COMMON_TEXT = 8
BLESS_TYPE_SKILL = 1
BLESS_TYPE_ADDITION = 2
BLESS_TYPE_COMMON = 3
ALL_BLESS_TYPES = [1, 2, 3]
BLESS_TYPE_NAME = {BLESS_TYPE_SKILL: '^\xe6\x8a\x80\xe8\x83\xbd',
   BLESS_TYPE_ADDITION: '^\xe5\xa2\x9e\xe7\x9b\x8a',
   BLESS_TYPE_COMMON: '^\xe9\x80\x9a\xe7\x94\xa8'
   }
BLESS_TRIGGER_TYPE_MAIN_WP = 1
BLESS_TRIGGER_TYPE_SEC_WP = 2
BLESS_TRIGGER_TYPE_SKILL = 3
BLESS_TRIGGER_TYPE_HIT = 4
BLESS_MAX_LEVEL = 3
M_COMMON = 1
M_TARGET = 2
M_NORMAL = 1
M_TOUGH = 2
M_ELITE = 3
M_BOSS = 9
NORMAL_DIFFICUTY = 1
HARD_DIFFICUTY = 2
HELL_DIFFICUTY = 3
DIFFICUTY_LIST = [NORMAL_DIFFICUTY, HARD_DIFFICUTY, HELL_DIFFICUTY]
DIFFICULTY_TEXT_LIST = [0, 384, 385, 386]
DIFFICULTY_COLOR_LIST = ['', '0x01EBFFFF', '0xFF4923FF', '0xFF1111FF']
PVE_BOX_TYPE_ENERGY = 1
PVE_BOX_TYPE_BREAK = 2
PVE_BOX_STATE_CLOSE = 1
PVE_BOX_STATE_OPEN = 2
PVE_BOX_STATE_OPENED = 3
PVE_SHOP_STATE_CLOSED = 1
PVE_SHOP_STATE_OPENED = 2
PVE_STORY_REWARD_TYPE_CHAPTER = 0
PVE_STORY_REWARD_TYPE_CLUE = 1
PVE_STORY_TYPE_ENTRY = 1
PVE_STORY_TYPE_ENEMY = 2
PVE_STORY_TYPE_ITEM = 3
PVE_STORY_TYPE_SCENE = 4
PVE_STORY_TYPE_BOSS = 5
PVE_MECHA_NEW_CACHE = 'PVE_MECHA_NEW_CACHE'
PVE_DIFFICULTY_CACHE = 'PVE_DIFFICULTY_CACHE'
BLESS_ELEM_TYPE_FIRE = 1
BLESS_ELEM_TYPE_ELECT = 2
BLESS_ELEM_TYPE_WIND = 3
PVE_ENTER_KEY_COUNT = 10
MAX_AUTO_RECEIVE_PVE_KEY_COUNT = 20
PVE_STORY_DEBRIS_CACHE = 'PVE_STORY_DEBRIS_CACHE'
PVE_STORY_REWARD_TYPE_CHAPTER = 0
PVE_STORY_REWARD_TYPE_CLUE = 1
PVE_STORY_DECOMPOSE_COUNT = 1
OPEN_PVE_STORY_DEBRIS_DONATE = True
PVE_SUGGEST_CACHE = 'PVE_SUGGEST_CACHE'
PVE_BATTLE_COST = 10
READ_ARCHIVE_COST = {1: lambda n: 3,
   2: lambda n: 3,
   3: lambda n: 6,
   4: --- This code section failed: ---

 132       0  LOAD_CONST            1  10
           3  LOAD_CONST            2  4
           6  BINARY_SUBTRACT  
           7  LOAD_CONST            3  5
          10  BINARY_MULTIPLY  
          11  BINARY_ADD       
          12  RETURN_VALUE_LAMBDA
          -1  LAMBDA_MARKER    

Parse error at or near `BINARY_ADD' instruction at offset 11
}

def get_read_archive_cost(n):
    if n <= len(READ_ARCHIVE_COST):
        return READ_ARCHIVE_COST[n](n)
    return READ_ARCHIVE_COST[len(READ_ARCHIVE_COST)](n)


PVE_MAX_PLAYER_COUNT = 3
PVE_END_BG_PATH = 'model_new/xuanjue/xuanjue_new/textures/pve_end_bg_{}_{}.tga'
EFFECT_TYPE_BLESS = 1
EFFECT_TYPE_ITEM = 2
EFFECT_SHOW_TYPE_ALWAYS = 1
EFFECT_SHOW_TYPE_DURATION = 2
PVE_RANK_SPEED_PERSONAL = 0
PVE_RANK_MECHA = 1
PVE_RANK_SPEED_TEAM = 2
TYPE_PVE_RANK_TOTAL = 0
TYPE_PVE_RANK_MONTHLY = 4
TYPE_PVE_RANK_LIST = [
 TYPE_PVE_RANK_MONTHLY, TYPE_PVE_RANK_TOTAL]
TYPE_LIST_2_TEXT_ID = {TYPE_PVE_RANK_TOTAL: 635371,
   TYPE_PVE_RANK_MONTHLY: 635372
   }
EFFECT_SHOW_TYPE_DURATION = 2
BLESS_SELL_PRICE = 150
PVE_WEEK_TASK_CACHE_KEY = 'PVE_WEEK_TASK_CACHE_KEY'
PVE_BOOK_KEY = 'PVE_BOOK_KEY'
PVE_BOOK_DEFAULT_BG_PATH = 'model_new/xuanjue/xuanjue_new/textures/pve_book_bg.tga'
PVE_CAREER_CACHE_KEY = 'PVE_CAREER_CACHE_KEY'
POINT_TYPE_TARGET = 1
POINT_TYPE_FIGHT_TRIGGER = 2
POINT_TYPE_MONSTER = 3
POINT_TYPE_FIGHT_LIST = 4
POINT_TYPE_BORN_SFX = 5
POINT_TYPE_DYNAMIC_DOOR = 6
POINT_TYPE_JUMP_AREA = 7
POINT_TYPE_BOX = 8
POINT_TYPE_SHOP = 9
POINT_TYPE_SOUND = 10
POINT_TYPE_PUZZLE = 11
POINT_TYPE_PORTAL = 13
PUZZLE_TYPE_BOMB = 1
PVE_MAIN_UI_ENTER_RES = 'video/pve_lobby_enter.mp4'
PVE_MAIN_UI_LEAVE_RES = ''
VIDEO_RES = {1: 'video/pve_boss_chapter1.mp4',
   2: 'video/pve_boss_chapter2.mp4',
   3: 'video/pve_boss_chapter3.mp4'
   }
EMPTY_WIDGET_PATH = 'pve/info/i_info_empty'
PVE_AMB_DICT = {1: {0: 'amb_2d_factory_room',
       -1: 'amb_2d_factory'
       },
   2: {-1: 'amb_2d_alien'
       },
   3: {-1: 'amb_2d_warland'
       }
   }
PVE_MUSIC_DICT = {'01': [
        'music_factory_scene', 'music_factory_battle'],
   '02': [
        'music_ruins_scene', 'music_ruins_battle'],
   '03': [
        'music_alpha_scene', 'music_alpha_battle', 'music_alpha_boss']
   }
DEFAULT_PVE_MUSIC_RES = [
 'music_factory_scene', 'music_factory_battle']
LAB_TITLE_COLOR_DICT = {1: [60159, 857924],2: [10184191, 857924],3: [16753989, 857924],4: ['#SW', 857924]}
LAB_TITLE2_COLOR_DICT = {1: ['#SW', 857924],2: ['#SW', 857924],3: ['#SW', 857924],4: ['#SW', 857924]}
MECHA_DEFAULT_BLESS = {8012: [
        5100110]
   }
PVE_RB_SFX = 'effect/fx/scenes/common/manyue/chuansong_skcs_blue.sfx'
MATCH_AGAIN_TYPE_NONE = 0
MATCH_AGAIN_TYPE_NORMAL = 1
MATCH_AGAIN_TYPE_ARCHIVE = 2
MATCH_AGAIN_TYPE_AUTO_MATCH = 3