# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/const.py
from __future__ import absolute_import
import re
_reload_all = True
REGION_TAG_CHINA = 1
REGION_TAG_SEA = 2
REGION_TAG_JK = 3
REGION_TAG_EA = 4
SERVER_PRC = 10000
SERVER_PRC_PC = 15000
SERVER_SEA = 20000
SERVER_JK = 21000
SERVER_EA = 30000
SERVER_SEA_PC = 23000
SERVER_SEA_STEAM = 24000
SERVER_EA_PC = 31000
SERVER_EA_STEAM = 32000
SERVER_HK_MATCH = 40000
OLD_SEA_SERVERS = set([SERVER_SEA, SERVER_JK, SERVER_EA, SERVER_SEA_PC, SERVER_EA_PC])
STEAM_SERVER_SET = frozenset([SERVER_SEA_STEAM, SERVER_EA_STEAM])
SERVER_TEXT_IDS = {43: 120006,
   SERVER_EA: 120005,
   SERVER_SEA: 120004,
   SERVER_JK: 110008,
   SERVER_SEA_PC: 120006,
   SERVER_EA_PC: 120007,
   SERVER_PRC: 120008,
   SERVER_PRC_PC: 120009,
   SERVER_SEA_STEAM: 120010,
   SERVER_EA_STEAM: 120011,
   SERVER_HK_MATCH: 120015
   }
ERROR_TRACEBACK = 1
ERROR_CRASH = 2
CLIENT_UPDATE_CODE = 128
UPDATE_REASON_ACCOUNT_VERSION = 1
UPDATE_REASON_SERVER_MAINTENANCE = 2
UPDATE_REASON_KICK_VERSION = 3
HEART_BEAT_ENABLE = True
HEART_BEAT_TIME = 60
HEART_BEAT_TIMEOUT = 2
DEFAULT_ROLE_ID = 11
HIT_MODEL_VISIBLE = False
ROBOT_MOVE_SHADOW = False
ROBOT_DEBUG = False
SEX_MALE = 0
SEX_FEMALE = 1
SEX_ENABLE = (SEX_MALE, SEX_FEMALE)
AVATAR_SEX_NONE = 0
AVATAR_SEX_MALE = 1
AVATAR_SEX_FEMALE = 2
AVATAR_SEX_ENABLE = (AVATAR_SEX_MALE, AVATAR_SEX_FEMALE)
CODE_NAME_USED_ALLREADY = 110
PLAYER_INFO_BRIEF = 1
PLAYER_INFO_DETAIL = 2
SHOP_PAYMENT_YUANBAO = 1
SHOP_PAYMENT_DIAMON = 2
SHOP_PAYMENT_GOLD = 3
SHOP_PAYMENT_ITEM = 4
SHOP_PAYMENT_CASH = 5
SHOP_PAYMENT_DYNAMIC = 6
SHOP_CLIENT_PAYMENT = frozenset([SHOP_PAYMENT_YUANBAO, SHOP_PAYMENT_DIAMON, SHOP_PAYMENT_GOLD, SHOP_PAYMENT_ITEM, SHOP_PAYMENT_DYNAMIC])
CAN_DISCOUNT_PAYMENT = [SHOP_PAYMENT_YUANBAO]
SHOP_PAYMENT_ITEM_RE_MATCH_PREFIX = re.compile('^(\\d+)_\\d+')
SHOP_PAYMENT_ITEM_RE_MATCH = re.compile('^%d_(\\d+)' % SHOP_PAYMENT_ITEM)
SHOP_ITEM_YUANBAO = 50101001
SHOP_ITEM_DIAMON = 50101002
SHOP_ITEM_GOLD = 50101003
SHOP_PAYMENT_PIECE1 = 50101004
SHOP_PAYMENT_PIECE2 = 50101005
SHOP_PAYMENT_PIECE3 = 50101006
SHOP_PAYMENT_PIECE4 = 50101007
SHOP_PAYMENT_PIECE5 = 50101008
SHOP_ITEM_LOTTERY_EXCHANGE = 50101108
SHOP_ITEM_SKIN_COIN = 50101104
SHOP_ITEM_DEC_COIN = 50101105
SHOP_PAYMENT_SPECIAL_TICKET = 50101010
SHOP_PAYMENT_NORMAL_TICKET = 50101009
SHOP_PAYMENT_DIANCANG_TICKET = 50101101
SHOP_PAYMENT_ACTIVITY_TICKET = 50101102
SHOP_PAYMENT_DIANCANG_TICKET_INHERIT = 70400119
SHOP_PAYMENT_SS_SKIN_CHIP = 50101100
SHOP_PAYMENT_SPLUS_SKIN_CHIP = 70400048
SHOP_PAYMENT_VALUABLE_CATTLE_COIN = 50101112
SHOP_PAYMENT_SPRING_COUPON = 50101120
SHOP_PAYMENT_CHINESE_KNOT = 50600023
SHOP_PAYMENT_KIZUNA_AI_CHEER_LIGHT_CARD = 50600024
SHOP_PAYMENT_VALENTINE_ROSE = 50101128
SHOP_PAYMENT_VALENTINE_HEART = 50101129
SHOP_PAYMENT_KIZUNA_AI_LOTTERY_TICKET = 50101140
SHOP_PAYMENT_KIZUNA_AI_EXCHANGE = 50101141
SHOP_PAYMENT_BOND_SKILL_BOOK = 50920101
SHOP_PAYMENT_LOTTERT_POINTS = 50101108
SHOP_PAYMENT_LOTTERY_EXCHANGE = 50101110
SHOP_PAYMENT_FLASH_POINT = 50101106
SHOP_PAYMENT_PINGANJING_PAPER = 71500003

def SHOP_PAYMENT_FLASH_EXCHANGE():
    return 50101109


SHOP_ITEM_COLOR = 31600001
SHOP_PAYMENT_GOLD_GEAR = 50104004
SHOP_PAYMENT_SILVER_GEAR = 50104005
SHOP_PAYMENT_PVE_KEY = 70300001
SHOP_PAYMENT_PVE_COIN = 70300002
SHOP_PAYMENT_SEASON_PREMIUM_EXCHANGE = 71700056
TRANS_WHEELCHAIR_ITEM_ID = 208200231
SILVER_GEAR_2 = 50104004
REFORM_GEAR = 50104008
SPECIAL_TICKET_TYPE = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_SPECIAL_TICKET)
NORMAL_TICKET_TYPE = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_NORMAL_TICKET)
DIANCANG_TICKET_TYPE = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_DIANCANG_TICKET)
PIECE_TYPE = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_PIECE5)
FLASH_CARD_TYPE = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_SS_SKIN_CHIP)
ACTIVITY_CARD_TICKET = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_ACTIVITY_TICKET)
GOLD_GEAR_TICKET = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_GOLD_GEAR)
SILVER_GEAR_TICKET = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_SILVER_GEAR)
SKIN_COIN_TICKET = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_ITEM_SKIN_COIN)
DEC_COIN_TICKET = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_ITEM_DEC_COIN)
LOTTERY_EXCHANGE = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_LOTTERY_EXCHANGE)
LOTTERY_POINTS = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_LOTTERT_POINTS)
FLASH_POINT = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_FLASH_POINT)
FLASH_EXCHANGE = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_FLASH_EXCHANGE())
VALENTINE_ROSE = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_VALENTINE_ROSE)
SHOP_PAYMENT_ITEM_VALUABLE_CATTLE_COIN = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_VALUABLE_CATTLE_COIN)
SHOP_PAYMENT_ITEM_SPRING_COUPON = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_SPRING_COUPON)
SHOP_PAYMENT_ITEM_CHINESE_KNOT = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_CHINESE_KNOT)
SHOP_PAYMENT_ITEM_KIZUNA_AI_CHEER_LIGHT_CARD = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_KIZUNA_AI_CHEER_LIGHT_CARD)
SHOP_PAYMENT_ITEM_PINGANJING_PAPER = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_PINGANJING_PAPER)
SHOP_PAYMENT_ITEM_PVE_KEY = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_PVE_KEY)
SHOP_PAYMENT_ITEM_PVE_COIN = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_PVE_COIN)
SHOP_PAYMENT_ITEM_SEASON_PREMIUM_EXCHANGE = '{}_{}'.format(SHOP_PAYMENT_ITEM, SHOP_PAYMENT_SEASON_PREMIUM_EXCHANGE)
SHOP_GOODS_ITEM = 1
SHOP_GOODS_LOTTERY = 2
SHOP_GOODS_GIFT = 3
SHOP_GOODS_LOTTERY_EXCHANGE = 4
SHOP_GOODS_TASK = 5
SHOP_GOODS_TRIGGER_GIFT = 6
SHOP_GOODS_LOTTERY_TEN_TRY = 7
SHOP_LOTTERY_REASON = 'LOTTERY_GOODS'
ITEM_RECYCLE_REASON = 'RECYCLE'
AVATAR_INIT_REASON = 'AVATAR_INIT'
ITEM_USE_REASON = 'ITEM_USE'
EXPIRE_ITEM_USE_REASON = 'EXPIRE_ITEM_USE'
MECHA_ROLE_INIT_REASON = 'MECHA_ROLE_INIT'
ITEM_EXPIRE_REASON = 'ITEM_EXPIRE'
MECHA_ROLE_INIT_GIVE_FREE_ITEMS_REASON = 'MECHA_ROLE_GIVE_FREE_ITEMS'
MECHA_EXPIRE_REASON = 'MECHA_EXPIRE'
LOTTERY_ADDITIONAL_ITEMS = 'LOTTERY_ADDITIONAL_ITEMS'
SKIN_ADDITIONAL_ITEMS = 'SKIN_ADDITIONAL_ITEMS'
TASK_REWARD_NUOMA = 'TASK_REWARD_1421057'
TASK_REWARD_YUTONG = 'TASK_REWARD_1421058'
PAY_TYPE_RECHARGE = 1
PAY_TYPE_MONTHCARD = 2
PAY_TYPE_NILE = 7
PAY_TYPE_NILE2 = 8
PAY_TYPE_NILES = [PAY_TYPE_NILE, PAY_TYPE_NILE2]
WEEKLY_MAX_GOLD = 4000
WEEKLY_MAX_GOLD_CREDIT_ADD = 0
WEEKLY_MAX_GOLD_CREDIT = 110
WEEKLY_MAX_GOLD_LIMIT = 4000
MAX_UDP_PACK_ONCE = 10
USE_FLOAT_REDUCE = True
ATK_FIST = 0
ATK_GUN = 1
ATK_MELEE = 2
ATK_THROWABLE = 3
ATK_SPELL = 4
ATK_EXOSKELETON = 5
HIT_PART_HEAD = 0
HIT_PART_BODY = 1
HIT_PART_ARM = 2
HIT_PART_OTHER = 3
HIT_PART_SHIELD = 4
HIT_PART_SKATE = 5
HIT_PART_CHEST = 6
HIT_PART_TO_SOCKET_INDEX = {HIT_PART_HEAD: (0, 0),HIT_PART_BODY: (1, 1),
   HIT_PART_ARM: (3, 2),
   HIT_PART_OTHER: (5, 4)
   }
if G_IS_CLIENT:
    import render
    if 'DirectX 9' not in render.get_render_system_name():
        HEAD_COLOR = 255
        BODY_COLOR = 65535
        ARM_COLOR = 65280
        LEG_COLOR = 16777215
        COLOR_MASK = 16777215
    else:
        HEAD_COLOR = 16711680
        BODY_COLOR = 16776960
        ARM_COLOR = 65280
        LEG_COLOR = 16777215
        COLOR_MASK = 16777215
    COLOR_PART_MAP = {HEAD_COLOR: HIT_PART_HEAD,
       BODY_COLOR: HIT_PART_BODY,
       ARM_COLOR: HIT_PART_ARM,
       LEG_COLOR: HIT_PART_OTHER
       }
MECHA_SOCKET_PART_MAP = {'part_point0': HIT_PART_HEAD,
   'part_point1': HIT_PART_BODY,
   'part_point2': HIT_PART_ARM,
   'part_point3': HIT_PART_ARM,
   'part_point4': HIT_PART_OTHER,
   'part_point5': HIT_PART_OTHER
   }
MECHA_PART_NONE = -2
MECHA_PART_ALL = -1
MECHA_PART_HEAD = 0
MECHA_PART_LEFT_ARM = 1
MECHA_PART_RIGHT_ARM = 2
MECHA_PART_BODY = 3
MECHA_PART_LOWER_BODY = 4
MECHA_PART_PROPELLER = 5
WEAKNESS_ATTACK_TAG = 'key_atk_crit'
EXECUTE_HIT_HINT = 'execute_hit_hint'
MECHA_PART_MAP = {MECHA_PART_NONE: (0.0, 0.0, 0.0, 1.0),
   MECHA_PART_ALL: (1.0, 0.0, 0.0, 1.0),
   MECHA_PART_HEAD: (0.098, 0.0, 0.0, 1.0),
   MECHA_PART_LEFT_ARM: (0.196, 0.0, 0.0, 1.0),
   MECHA_PART_RIGHT_ARM: (0.294, 0.0, 0.0, 1.0),
   MECHA_PART_BODY: (0.392, 0.0, 0.0, 1.0),
   MECHA_PART_LOWER_BODY: (0.49, 0.0, 0.0, 1.0),
   MECHA_PART_PROPELLER: (0.588, 0.0, 0.0, 1.0)
   }
MECHA_COMPONENT_PART_LIST = [
 MECHA_PART_HEAD, MECHA_PART_RIGHT_ARM, MECHA_PART_LEFT_ARM, MECHA_PART_BODY, MECHA_PART_LOWER_BODY, MECHA_PART_PROPELLER]
BOLI_COLOR = -16776961
TRAJECTORY_INTERVAL_LAVATAR = 0.2
TRAJECTORY_INTERVAL = {'LAvatar': TRAJECTORY_INTERVAL_LAVATAR,
   'LMecha': 0
   }
HIT_MODE_DIRECT = 0
HIT_MODE_THROUH = 1
BREAK_TYPE_BOX = 1
BONE_EQUIP_MAX_LEVEL = 3
BACKPACK_PART_OTHERS = 1
BACKPACK_PART_CLOTHING = 2
BACKPACK_PART_WEAPON = 3
PART_WEAPON_POS_NONE = 0
PART_WEAPON_POS_MAIN1 = 1
PART_WEAPON_POS_MAIN2 = 2
PART_WEAPON_POS_MAIN3 = 3
PART_WEAPON_POS_MAIN4 = 4
PART_WEAPON_POS_MAIN5 = 5
PART_WEAPON_POS_MAIN6 = 6
PART_WEAPON_POS_MAIN7 = 7
PART_WEAPON_POS_MAIN8 = 8
PART_WEAPON_POS_MAIN9 = 9
PART_WEAPON_POS_MAIN_DF = 10
PART_WEAPON_POS_COLD = 97
PART_WEAPON_POS_BOMB = 98
PART_WEAPON_POS_SIMU1 = 99
PART_WEAPON_PVE_POS_MAIN = 101
PART_WEAPON_PVE_POS_SECOND = 102
PART_WEAPON_PVE_POS_SKILL = 103
PART_WEAPON_PVE_POS_HITTED = 104
THROW_MODE_THROW = 1
THROW_MODE_EQUIP = 2
THROW_MODE_USE = 3
THROW_MODE_UNSIMU = 4
MAIN_WEAPON_LIST = (
 PART_WEAPON_POS_MAIN1, PART_WEAPON_POS_MAIN2, PART_WEAPON_POS_MAIN3, PART_WEAPON_POS_MAIN_DF)
EXTRA_WEAPON_LIST = (PART_WEAPON_POS_MAIN1, PART_WEAPON_POS_MAIN2, PART_WEAPON_POS_MAIN3)
SIMU_WEAPON_LIST = (PART_WEAPON_POS_SIMU1,)
MEDICINE_SHORT_CUT_POS = 5
ATTACHEMNT_AIM_POS = 1
ATTACHEMNT_MUZZLE_POS = 2
ATTACHMENT_HANDLE_POS = 3
ATTACHMENT_CLIP_POS = 4
ATTACHMENT_BUTT_POS = 5
ATTACHMENT_INFRARED_POS = 6
ATTACHMENT_POS_LIST = (
 ATTACHEMNT_AIM_POS, ATTACHMENT_INFRARED_POS)
ATTACHEMNT_AIM = 1
ATTACHEMNT_SILENCER = 2
ATTACHEMNT_SUPPRESSER = 3
ATTACHEMNT_COMPENSATOR = 4
ATTACHEMNT_RECEPTACLE = 5
ATTACHEMNT_CLIP = 6
ATTACHEMNT_INFRARED = 7
TEAM_SOLO = 1
TEAM_DUO = 2
TEAM_SQUAD = 4
MAX_ITEM_PER_HOUSE = 1000
NEOX_UNIT_SCALE = 13.0
SKELETON_LOD_DIST = (
 95.0 * NEOX_UNIT_SCALE, 150.0 * NEOX_UNIT_SCALE)
PHYSX_SYNC_LOD_DIST = (
 150.0 * NEOX_UNIT_SCALE, 300.0 * NEOX_UNIT_SCALE, 100000.0 * NEOX_UNIT_SCALE)
PHYSX_SYNC_LOD_SKIP_FRAMES = (1, 2, 4)
SEA_LEVEL_HEIGHT = -0.2 * NEOX_UNIT_SCALE
DOOR_STATE_CLOSE = 0
DOOR_STATE_OPEN_OUT = 1
DOOR_STATE_OPEN_IN = 2
ENABLE_SHADOWMAP = True
FRD_KEY_FRDS = 'frds'
FRD_KEY_BALCLIST = 'bl'
FRD_KEY_RECENT_TEAM = 'rt'
FRD_KEY_RECETN_CONTACT = 'rc'
FRD_KEY_REQ = 'rq'
FRD_KEY_SEND_REQ = 'srq'
FRD_KEY_BE_BLAC = 'bbl'
FRD_KEY_RECOMMEND = 'rm'
FRD_KEY_FRD_MSG = 'msg'
FANS_SYSTEM_INFO_TYPE_FOLLOWS = 1
FANS_SYSTEM_INFO_TYPE_FANS = 2
FANS_SYSTEM_PLAYER_INFO_PAGE_SIZE = 20
FANS_SYSTEM_MAX_FOLLOW_CNT = 1000
FANS_SYSTEM_MAX_FANS_CNT = 99990000
FRD_SEARCH_MIN_INTERVAL = 5
ROLE_HEAD_QUERY_MIN_INTERVAL = 15
FRD_REMARK_MAX_BYTE_COUNT = 16
CONFIRM_NORMAL = 0
CONFIRM_TEAM_INVITE = 1
CONFIRM_TEAM_JOIN = 2
CONFIRM_CHANGE_SEAT = 3
CONFIRM_ROOM_INVITE = 4
CONFIRM_TEAM_RESERVE = 5
CONFIRM_MATCH_READY = 6
STATE_OFFLINE = 0
STATE_SINGLE = 1
STATE_TEAM = 2
STATE_BATTLE = 3
STATE_BATTLE_FIGHT = 4
STATE_SPECTATING = 5
STATE_ROOM = 6
STATE_EXERCISE = 7
STATE_INVISIBLE = 8
BATTLE_STATE_IDLE = 0
BATTLE_STATE_INROOM = 1
BATTLE_STATE_MATCHING = 2
BATTLE_STATE_FIGHTING = 3
MAX_INVISIBLE_TIMES_PER_WEEK = 5
INVISIBLE_TIMES_KEY = 'invisible_times'
INVISIBLE_TIMES_WEEK_LIMIT_KEY = 'invisible_times_week_limit'
DAY_INVISIBLE_KEY = 'day_invisible'
TODAY_HAS_COST_KEY = 'today_has_cost'
TEAM_SESSION_ID = 0
NEAR_SESSION_ID = 1
TEAM_ALL_SESSION_ID = 2
CCMINI_SPEAKER_NONE = 0
CCMINI_SPEAKER_TEAM = 1
CCMINI_SPEAKER_ALL = 2
CCMINI_MIC_NONE = 0
CCMINI_MIC_TEAM = 1
CCMINI_MIC_ALL = 2
WWISE_FOOTSTEP_MAX_DIS_SQR = (150 * NEOX_UNIT_SCALE) ** 2
WWISE_FIRE_MAX_DIS_SQR = (500 * NEOX_UNIT_SCALE) ** 2
WWISE_CAR_MAX_DIS_SQR = (200 * NEOX_UNIT_SCALE) ** 2
SOUND_2D_HIT_MIN_DISTANCE = (30 * NEOX_UNIT_SCALE) ** 2
SOUND_TYPE_FOOTSTEP = 0
SOUND_TYPE_FIRE = 1
SOUND_TYPE_CAR = 2
SOUND_TYPE_SLOW_FOOTSTEP = 3
SOUND_TYPE_SILENCER_FIRE = 4
SOUND_TYPE_MECHA_FIRE = 5
SOUND_TYPE_MECHA_FOOTSTEP = 6
SOUND_TYPE_AIM_LOCKED = 7
SOUND_TYPE_SKATE = 8
SOUND_TYPE_MAX_COUNT = 9
REPLAY_SNAPSHOT_INVTERVAL = 400
REPLAY_MIN_FRAMES_TO_SAVE = 200
REPLAY_DECODE_FRAME_SIZE_IN_LOOP = 200
REPLAY_OP_GLOBAL_SPECTATE_INIT = 10
REPLAY_OP_GLOBAL_SPECTATE_OP = 11
REPLAY_RECORD_PLAYER_UIDS = {1500931695, 1505781582, 1500931762, 1500931780, 1515802861}
REPLAY_TIP_ERROR_SERVER_FUNCITON_OFF = 1
REPLAY_TIP_ERROR_SERVER_NO_MATCHING_RECORDS = 2
REPLAY_TIP_ERROR_SERVER_NOT_FOUND_RECORD = 3
REPLAY_TIP_ERROR_SERVER_INVALID_QUERY_PARAMS = 4
REPLAY_TIP_ERROR_SERVER_INTERNAL_ERROR = 5
REPLAY_TIP_ERROR_CLIENT_FILE_DOWNLOAD_ERROR = 6
REPLAY_TIP_ERROR_CLIENT_FILE_DECOMPRESS_ERROR = 7
REPLAY_TIP_ERROR_CLIENT_FILE_DOWNLOAD_TIMEOUT = 8
REPLAY_TIP_ERROR_CLIENT_PLAYING_RECORD_ERROR = 9
REPLAY_TIP_INFO_CLIENT_RECORD_IS_PLAYING = 10
REPLAY_TIP_INFO_CLIENT_RECORD_IS_DOWNLOADING = 11
REPLAY_TIP_INFO_CLIENT_BEGIN_DOWNLOADING_FILE = 12
REPLAY_TIP_INFO_CLIENT_BEGIN_DECOMPRESS_FILE = 13
REPLAY_TIP_INFO_CLIENT_HAS_RECEIVE_PLAY_REQUEST = 14
REPLAY_TIP_INFO_CLIENT_WAIT_SCENE_TO_CLOSE = 15
REPLAY_TIP_INFO_CLIENT_DOWNLOAD_PROGRESS = 16
REPLAY_TIP_INFO_CLIENT_PLAY_BEGIN = 17
REPLAY_TIP_INFO_CLIENT_PLAY_FINISHED = 18
REPLAY_TIP_INFO_CLIENT_PLAY_STOP = 19
REPLAY_TIP_ERROR_SERVER_NOT_FOUND_VALIDATE_INFO = 20
REPLAY_TIP_INFO_CLIENT_GET_VALIDATE_INFO = 21
REPLAY_TIP_ERROR_CLIENT_VALIDATE_FAILED = 22
REPLAY_TIP_INFO_CLIENT_DECODING_RECORD = 23
REPLAY_TIP_INFO_VERSION_NOT_COMPATIBLE = 24
REPLAY_TIP_INFO_ALL_FRAME_LOADED = 25
REPLAY_TIP_INFO_NOT_SUPPORT_SPEED_UP = 26
REPLAY_TIP_INFO_SPEED_UP_WAIT = 27
REPLAY_TIP_INFO_SPEED_UP_FRAMES = 28
REPLAY_TIP_INFO_SPEED_UP_FAIL = 29
REPLAY_MESSAGE_MAX_LENGTH = 8388608
REPLAY_RECEIVER_BUFF_SIZE = REPLAY_MESSAGE_MAX_LENGTH * 2
REPLAY_SENDER_BUFF_SIZE = REPLAY_MESSAGE_MAX_LENGTH * 4
REPLAY_SENDER_QUEUE_MAX_NUM = 8000
REPLAY_SENDER_SEND_BUFF_DATA_BATCH_SIZE = 327680
REPLAY_SENDER_CONNECT_RECEIVER_TRY_MAX_TIMES = 3
REPLAY_SENDER_SERIALIZE_QUEUE_BATCH_NUM = 3
REPLAY_RECORD_CONCURRENCY_MAX_BATTLE = 6
REPLAY_LENGTH_FIELD_SIZE = 8
REPLAY_LENGTH_FIELD_MAX_VALUE = int('0x' + 'f' * (REPLAY_LENGTH_FIELD_SIZE - 2), 16)
REPLAY_MAX_READ_SIZE_PER_TRY = 327680
REPLAY_DECODE_NUM_AFTER_PER_READ = 50
REPLAY_READER_PULL_MESSAGE_INTERVAL = 0.1
REPLAY_READER_PULL_BATCH_NUM = 120
REPLAY_BATTLE_MAX_LIFE_SECONDS = 3000
REPLAY_CRASH_CLUSTERS = {SERVER_PRC, SERVER_SEA, SERVER_JK, SERVER_EA}
REPLAY_CRASH_PLAYER_MIN_CRASH_TIMES = 2
REPLAY_CRASH_PLAYER_MAX_NUM = 15
REPLAY_PIPE_MODIFIED_SIZE = 983040
SYNC_USE_CHARACTER = False
NAME_MAX_BYTE_COUNT = 16
INTIMACY_NAME_MAX_BYTE_COUNT = 10
SYS_SYNC_COIN = 0
SYS_ADD_COIN = 1
BOX_ADD_COIN = 2
KILL_ADD_COIN = 3
KILL_ADD_EXTRA_COIN = 4
ASSIST_KILL_ADD_COIN = 5
CAPSULE_SUB_COIN = 6
KILL_MECHA_ADD_COIN = 7
PICK_ITEM_COIN = 8
ACTION_GET_CAPSULE = 1
ACTION_USE_CAPSULE = 2
OB_GROUP_ID_START = OB_SIT_INDEX_START = 1000
OB_GROUP_ID_END = OB_SIT_INDEX_END = 1009
ROOM_LEAVE_FORBID = -1
ROOM_LEAVE_ACTIVE = 1
ROOM_LEAVE_KICK = 2
ROOM_LEAVE_START = 3
ROOM_LEAVE_DISSOLVE = 4
ROOM_ENTER_NOT_EXIST = -2
ROOM_ENTER_PWD_WRONG = -3
ROOM_ENTER_IN_FIGHT = -4
ROOM_ENTER_ROOM_FULL = -5
ROOM_ENTER_CREATE_WRONG = -6
ROOM_ENTER_ROOM_REPEAT = -7
ROOM_ENTER_ROOM_INFO_WRONG = -8
ROOM_ENTER_ROOM_INFO_NO_SEATS_FOR_TEAM = -9
ROOM_ENTER_ROOM_LEVEL_NOENGOUGH = -10
ROOM_ENTER_ROOM_COMPETITION_NO_EMULATOR = -11
ROOM_ENTER_ROOM_FORBID = -12
ROOM_ENTER_ROOM_UID_LIMIT = -13
ROOM_ENTER_ROOM_DAN_NOENGOUGH = -14
ROOM_ENTER_ROOM_JOIN_TIME_LIMIT = -15
ROOM_ENTER_ROOM_FORBID_COMP = -16
ROOM_ENTER_CREATE = 1
ROOM_ENTER_REQ_SUCC = 2
ROOM_ENTER_RESTORE_ROOM = 3
ROOM_ENTER_LOST_CREATOR = 4
ROOM_START_NONE = -1
ROOM_START_NOT_CREATEOR = -2
ROOM_START_IN_BATTLE = -3
ROOM_START_TEAM_NOENOUGH = -4
ROOM_START_PLAYER_NOENOUGH = -5
ROOM_CREATE_MIN_PLAYER_LEVEL = 1
ROOM_CREATE_ERROR_INFO = -1
ROOM_CREATE_REPEATED = -2
ROOM_AVATAR_DESTROY = 0
ROOM_AVATAR_ONLINE = 1
ROOM_SIT_DOWN_CREATOR_FORBID = -2
ROOM_COST_ROOM_POINT_INTERVAL = 120
ROOM_AUTO_DISSOLVE_TIME = 3600
ROOM_FIRST_AUTO_DISSOLVE_TIME = 10800
ROOM_KICK_OFFLINE_PLAYER_TIME = 600
ROOM_CREATOR_OFFLINE_TOLERANCE = 10
ROOM_ID_NOT_AVAILABLE_ALERT_NUM = 1000
ROOM_CHANGE_TYPE_SUCCESS = 0
ROOM_CHANGE_TYPE_FAILURE = -1
ROOM_TYPE_ORDINARY = 0
ROOM_TYPE_COMPETITION = 1
CLIMB_MAX_DISTANCE = 1.5 * NEOX_UNIT_SCALE
CLIMB_MIN_HIGHT = 0.8 * NEOX_UNIT_SCALE
CLIMB_MAX_HIGHT = 2.2 * NEOX_UNIT_SCALE
CLIMB_BOARD_MIN_WIDTH = 0.8 * NEOX_UNIT_SCALE
CLIMB_RAY_CHECK_HEIGHT = 1.2 * NEOX_UNIT_SCALE
CLIMB_POINT_OFFSET = 0.2 * NEOX_UNIT_SCALE
LEAVE_CLIMB_POINT_DISTANCE = 0.8 * NEOX_UNIT_SCALE
FIRST_FORWARD_OFFSET = 0.15 * NEOX_UNIT_SCALE
SECOND_FORWARD_OFFSET = 0.05 * NEOX_UNIT_SCALE
CLIMB_TO_TOP_STAND = 0
CLIMB_TO_DOWN_STAND = 1
CLIMB_TO_RUN = 2
CLIMB_TO_DROP = 3
THROW_OVER_TO_TOP_STAND = 4
THROW_OVER_TO_DOWN_STAND = 5
THROW_OVER_TO_RUN = 6
THROW_OVER_TO_DROP = 7
CLIMB_SUB_TYPY_COUNT = 4
DETECT_TYPE_VERTICAL_FREE = 0
DETECT_TYPE_VERTICAL_LOW_WALL = 1
DETECT_TYPE_VERTICAL_MIDDLE_WALL = 2
DETECT_TYPE_VERTICAL_HIGH_WALL = 3
DETECT_TYPE_HORIZONTRAL_PLANE = 0
DETECT_TYPE_HORIZONTRAL_DOWNHILL = 1
DETECT_TYPE_HORIZONTRAL_UPHILL = 2
DETECT_TYPE_HORIZONTRAL_CLIFF = 3
CAPSULE_ITEM = 1
CAPSULE_ABILITY = 2
G_SOUND_RECORD_RADIUS_SPR = 2500
G_SOUND_TRANSLATE_RIGHT_MOVE_DIST = 100
SHOOT_NORMAL_PATH = 'gui/ui_res_2/battle/icon/icon_shot_nml.png'
SHOOT_SELECT_PATH = 'gui/ui_res_2/battle/icon/icon_shot_choose.png'
AIM_NORMAL_PATH = 'gui/ui_res_2/battle/icon/icon_aim_nml.png'
AIM_SELECT_PATH = 'gui/ui_res_2/battle/icon/icon_aim_sel.png'
AIM_BI_NORMAL_PATH = 'gui/ui_res_2/battle/icon/icon_aim_2x_nml.png'
AIM_BI_SELECT_PATH = 'gui/ui_res_2/battle/icon/icon_aim_2x_sel.png'
AIM_QUAD_NORMAL_PATH = 'gui/ui_res_2/battle/icon/icon_aim_4x_nml.png'
AIM_QUAD_SELECT_PATH = 'gui/ui_res_2/battle/icon/icon_aim_4x_sel.png'
RIGHT_AIM_NORMAL_PATH = 'gui/ui_res_2/battle/icon/icon_aim2_nml.png'
RIGHT_AIM_SELECT_PATH = 'gui/ui_res_2/battle/icon/icon_aim2_sel.png'
SIGHT_NORMAL_PATH = 'gui/ui_res_2/battle/icon/icon_sight_nml.png'
ROLL_NORMAL_PATH = 'gui/ui_res_2/battle/icon/icon_roll_nml.png'
ROLL_SEL_PATH = 'gui/ui_res_2/battle/icon/icon_roll_sel.png'
BONE_RUSH_NORMAL_PATH = 'gui/ui_res_2/battle/icon/rush_nml.png'
BONE_RUSH_SEL_PATH = 'gui/ui_res_2/battle/icon/rush_sel.png'
BONE_ONE_JUMP_NORMAL_PATH = 'gui/ui_res_2/battle/icon/jump.png'
BONE_ONE_JUMP_SEL_PATH = 'gui/ui_res_2/battle/icon/jump_sel.png'
BONE_DOUBLE_JUMP_NORMAL_PATH = 'gui/ui_res_2/battle/icon/jump_2_nml.png'
BONE_DOUBLE_JUMP_SEL_PATH = 'gui/ui_res_2/battle/icon/jump_2_sel.png'
BONE_TRIPLE_JUMP_NORMAL_PATH = 'gui/ui_res_2/battle/icon/jump_3_nml.png'
BONE_TRIPLE_JUMP_SEL_PATH = 'gui/ui_res_2/battle/icon/jump_3_sel.png'
BONE_JUMP_PATHS = {1: (
     BONE_ONE_JUMP_NORMAL_PATH, BONE_ONE_JUMP_SEL_PATH, BONE_ONE_JUMP_NORMAL_PATH),
   2: (
     BONE_DOUBLE_JUMP_NORMAL_PATH, BONE_DOUBLE_JUMP_SEL_PATH, BONE_DOUBLE_JUMP_NORMAL_PATH),
   3: (
     BONE_TRIPLE_JUMP_NORMAL_PATH, BONE_TRIPLE_JUMP_SEL_PATH, BONE_TRIPLE_JUMP_NORMAL_PATH)
   }
AIRLINE_PLANE = 0
AIRLINE_AIRSHIP = 1
SOUND_SPEED = 340.0 * NEOX_UNIT_SCALE
ACHIEVE_VAR_DELTA = '_DELTA'
ACHIEVE_VAR_UPDATE = '_UPDATE'
ACHIEVE_VAR_MAX = '_MAX'
ACHIEVE_VAR_MIN = '_MIN'
ACHIEVE_VAR_FUNC_ARGS = '_args'
SEARCH_FRIEND_MIN_TIME = 5
CLICK_INTERVAL_TIME = 1.5
ARMOR_TYPE_HEAD = 2
ARMOR_TYPE_ARMOR = 1
ARMOR_TYPE_HAND = 4
ARMOR_TYPE_LEG = 5
ARMOR_TYPE_SHIELD = 3
CHARACTER_LERP_DIR_YAWS = [
 -2.3561944500000003,
 -1.9024088522222222,
 -0.534070742,
 -0.25132740800000003,
 0.25132740800000003,
 0.534070742,
 1.916371486,
 2.3561944500000003]
MAP_STATE_HUMAN = 1
MAP_STATE_MECHA = 2
CREATOR_LOCAL_BATTLE = 1
GAME_LOCAL_BATTLE = 2
NEWBIE_STAGE_HUMAN_BATTLE = 201
NEWBIE_STAGE_MECHA_BATTLE = 202
NEWBIE_STAGE_THIRD_BATTLE = 203
NEWBIE_STAGE_FOURTH_BATTLE = 204
ALL_NEWBIE_BATTLE_ID = [
 NEWBIE_STAGE_HUMAN_BATTLE,
 NEWBIE_STAGE_MECHA_BATTLE,
 NEWBIE_STAGE_THIRD_BATTLE,
 NEWBIE_STAGE_FOURTH_BATTLE]
SFX_FULL_SCREEN_SIZE = (1280.0, 720.0)
AI_BATTLE_TYPE_NO_RESULT = 0
AI_BATTLE_TYPE_KILL = 1
AI_BATTLE_TYPE_KNOCK_DOWN = 2
MOVE_TO_MODE_NONE = 0
MOVE_TO_MODE_ALWAYS_FORWARD = 1
MOVE_TO_MODE_ALWAYS_FORWARD_WITH_CAM = 2
LOBBY_MODEL_TOUCH_MAX_DISTANCE = 50.0 * NEOX_UNIT_SCALE
LOBBY_TV_TOUCH_MAX_DISTANCE = 30.0 * NEOX_UNIT_SCALE
LOBBY_MECHA_RANK_MAX_DISTANCE = 38.0 * NEOX_UNIT_SCALE
LOBBY_COMPUTER_TOUCH_MAX_DISTANCE = 16.0 * NEOX_UNIT_SCALE
LOBBY_MIRROR_TOUCH_DISTANCE = 7 * NEOX_UNIT_SCALE
MECHA_SCALE = 2.97
ROLE_SCALE = 1.0
PET_SCALE = 1.0
MECHA_ROTATION_Y = 14.0
ROLE_ROTATION_Y = 26.0
PET_ROTATION_Y = 36.0
PET_OFF_POSITION = [
 0, 18, 12]
SWITCH_LOG_SKILL = False
FILE_SERVICE_UPLOAD_TYPE_HIGHLIGHT_IMG = 'fp_hl_img'
FILE_SERVICE_UPLOAD_TYPE_HM_IMG = 'fp_hm_img'
FILE_SERVICE_UPLOAD_TYPE_HIGHLIGHT_VIDEO = 'fp_hl_video'
FILE_SERVICE_UPLOAD_TYPE_SHADER_COLLECT = 'fp_shader_collect'
FILE_SERVICE_UPLOAD_TYPE_USAGE_COLLECT = 'fp_usage_collect'
FILE_SERVICE_UPLOAD_FILE_TYPE_SET = {FILE_SERVICE_UPLOAD_TYPE_HM_IMG, FILE_SERVICE_UPLOAD_TYPE_HIGHLIGHT_IMG, FILE_SERVICE_UPLOAD_TYPE_HIGHLIGHT_VIDEO, FILE_SERVICE_UPLOAD_TYPE_SHADER_COLLECT, FILE_SERVICE_UPLOAD_TYPE_USAGE_COLLECT}
FILE_SERVICE_FUNCTION_KEY_HIGHLIGHT_MOMENT = 'fs_key_high_light'
FILE_SERVICE_FUNCTION_KEY_SHADER_COLLECT = 'fs_key_shader_collect'
FILE_SERVICE_FUNCTION_KEY_USAGE_COLLECT = 'fs_key_usage_collect'
FILE_SERVICE_FUNCTION_KEY_HOMELAND_IMG = 'fs_key_hm_img'
FILE_SERVICE_UPLOAD_DAY_NUM_LIMIT_DICT = {FILE_SERVICE_FUNCTION_KEY_HIGHLIGHT_MOMENT: 50,
   FILE_SERVICE_FUNCTION_KEY_SHADER_COLLECT: 500,
   FILE_SERVICE_FUNCTION_KEY_USAGE_COLLECT: 50,
   FILE_SERVICE_FUNCTION_KEY_HOMELAND_IMG: 100
   }
FILE_SERVICE_FUNCTION_KEY_2_FILE_TYPES = {FILE_SERVICE_FUNCTION_KEY_HIGHLIGHT_MOMENT: [
                                              FILE_SERVICE_UPLOAD_TYPE_HIGHLIGHT_IMG, FILE_SERVICE_UPLOAD_TYPE_HIGHLIGHT_VIDEO],
   FILE_SERVICE_FUNCTION_KEY_SHADER_COLLECT: [
                                            FILE_SERVICE_UPLOAD_TYPE_SHADER_COLLECT],
   FILE_SERVICE_FUNCTION_KEY_USAGE_COLLECT: [
                                           FILE_SERVICE_UPLOAD_TYPE_USAGE_COLLECT],
   FILE_SERVICE_FUNCTION_KEY_HOMELAND_IMG: [
                                          FILE_SERVICE_UPLOAD_TYPE_HM_IMG]
   }
FILE_SERVICE_TIME_OUT_MAX_DAYS = 14
FILE_SERVICE_UPLOAD_FAIL_REASON_UNKNOWN_TYPE = 1
FILE_SERVICE_UPLOAD_FAIL_REASON_NUM_LIMIT = 2
FILE_SERVICE_UPLOAD_FAIL_REASON_TIME_LIMIT = 3
FILE_SERVICE_UPLOAD_FAIL_REASON_TOKEN_ERROR = 4
FILE_SERVICE_UPLOAD_FAIL_REASON_NEED_FILE_TYPE = 5
FILE_SERVICE_UPLOAD_FAIL_FILE_TYPE_NOT_MATCH_FUNCTION = 6
FILE_SERVICE_UPLOAD_FAIL_UNKNOWN_FUNCTION = 7
PLAYER_INFO_BLACK_KEYS = {
 'career_stat',
 'career_history'}
AGE_RANGE_UNKONWN = -1
AGE_RANGE_UNREALNAME = 0
AGE_RANGE_BELOW_8 = 1
AGE_RANGE_BETWEEN_8_16 = 2
AGE_RANGE_BETWEEN_16_18 = 3
AGE_RANGE_ADULT = 4
REALNAME_VERIFY_UNKNOWN = 0
REALNAME_NOT_VERIFY = 1
REALNAME_VERIFY_PASS = 2
REALNAME_VERIFY_FAIL = 3
NEWBIE_ATTEND_REWARDS_COMPENSATION = 'newbie_attend_compensation'
WECHAT_BIND_ROLE_BIND_CODE_VALID_MAX_TIME = 600
INTIMACY_RELATION_TYPE_BESTIE = 'bestie'
INTIMACY_RELATION_TYPE_PARTNER = 'partner'
INTIMACY_RELATION_TYPE_MECHAFRD = 'mechafrd'
INTIMACY_RELATION_TYPE_LOVERS = 'lovers'
INTIMACY_RELATION_DEFAULT_ORDER = [
 INTIMACY_RELATION_TYPE_LOVERS,
 INTIMACY_RELATION_TYPE_PARTNER,
 INTIMACY_RELATION_TYPE_MECHAFRD,
 INTIMACY_RELATION_TYPE_BESTIE]
INTIMACY_NAME_MAP = {INTIMACY_RELATION_TYPE_BESTIE: 3225,
   INTIMACY_RELATION_TYPE_PARTNER: 3223,
   INTIMACY_RELATION_TYPE_MECHAFRD: 3224,
   INTIMACY_RELATION_TYPE_LOVERS: 3222
   }
INTIMACY_INTRODUCE_MAP = {INTIMACY_RELATION_TYPE_BESTIE: 860283,
   INTIMACY_RELATION_TYPE_PARTNER: 860284,
   INTIMACY_RELATION_TYPE_MECHAFRD: 860283,
   INTIMACY_RELATION_TYPE_LOVERS: 860272
   }
INTIMACY_COLOR_MAP = {INTIMACY_RELATION_TYPE_BESTIE: '0xF16987FF',
   INTIMACY_RELATION_TYPE_PARTNER: '0x39D4DEFF',
   INTIMACY_RELATION_TYPE_MECHAFRD: '0x5E8EDFFF',
   INTIMACY_RELATION_TYPE_LOVERS: '0xE55F9CFF'
   }
INTIMACY_SHARE_COLOR_MAP = {INTIMACY_RELATION_TYPE_BESTIE: '0xF2678DFF',
   INTIMACY_RELATION_TYPE_PARTNER: '0x6684DEFF',
   INTIMACY_RELATION_TYPE_MECHAFRD: '0x0DC8D3FF',
   INTIMACY_RELATION_TYPE_LOVERS: '0xF174AAFF'
   }
INTIMACY_RELATION_TYPE_SET = (
 INTIMACY_RELATION_TYPE_BESTIE,
 INTIMACY_RELATION_TYPE_PARTNER,
 INTIMACY_RELATION_TYPE_MECHAFRD,
 INTIMACY_RELATION_TYPE_LOVERS)
INTIMACY_RELATION_NUM_LIMIT = {INTIMACY_RELATION_TYPE_BESTIE: 5,
   INTIMACY_RELATION_TYPE_PARTNER: 5,
   INTIMACY_RELATION_TYPE_MECHAFRD: 5,
   INTIMACY_RELATION_TYPE_LOVERS: 1
   }
INTIMACY_MSG_TYPE_BUILD_REQUEST = 'build_req'
INTIMACY_MSG_TYPE_BUILD_RECV = 'build_recv'
INTIMACY_MSG_TYPE_BUILD_AGREE = 'build_agree'
INTIMACY_MSG_TYPE_BUILD_REFUSE = 'build_refuse'
INTIMACY_MSG_TYPE_DELETE_REQUEST = 'delete_req'
INTIMACY_MSG_TYPE_DELETE_RECV = 'delete_recv'
INTIMACY_MSG_TYPE_DELETE_AGREE = 'delete_agree'
INTIMACY_MSG_TYPE_DELETE_REFUSE = 'delete_refuse'
INTIMACY_MSG_TYPE_DELETE_FORCE = 'delete_force'
INTIMACY_MSG_TYPE_DELETE_NOT_FRIEND = 'delete_not_friend'
INTIMACY_MSG_TYPE_CHANGE_RELATION_NAME = 'change_name'
INTIMACY_MSG_TYPE_OPERATION_FAIL = 'oper_fail'
INTIMACY_MSG_TYPE_REVOKE_BUILD_REQUEST = 'revoke_build_req'
INTIMACY_MSG_TYPE_NOTIFY_REWARD = 'notify_reward'
INTIMACY_MSG_TYPE_LEVEL_UP = 'level_up'
INTIMACY_HISTORICAL_EVENT_KEY = 'INTIMACY_HISTORICAL_EVENT_KEY_{}'
OPEN_INTIMACY_REQUEST_KEY = 'OPEN_INTIMACY_REQUEST_KEY'
INTIMACY_MSG_TYPE_RECORD_SET = (
 INTIMACY_MSG_TYPE_BUILD_REQUEST, INTIMACY_MSG_TYPE_BUILD_RECV, INTIMACY_MSG_TYPE_DELETE_REQUEST, INTIMACY_MSG_TYPE_DELETE_RECV)
INTIMACY_ERR_SAME_UID = -1
INTIMACY_ERR_NOT_FRD = -2
INTIMACY_ERR_WRONG_TYPE = -3
INTIMACY_ERR_EXIST_RELATION = -4
INTIMACY_ERR_NUM_LIMIT = -5
INTIMACY_ERR_UNENOUGH_INTIMACY = -6
INTIMACY_ERR_NOT_CD = -7
INTIMACY_ERR_ALREADY_SEND = -8
DELETE_DIRECTLY_DURATION = 1209600
INTIMACY_RELATION_REBUILD_CD = 604800
INTIMACY_TEAM_SHOW_LV = 2
INTIMACY_BADGE_LV = [
 1, 4, 7]
INTIMACY_MECHA_SHARE_LV = 3
INTIMACY_EXTRA_PROF_LV = 6
INTIMACY_EXTRA_GOLD_LV = 8
INTIMACY_CHANGE_NAME_LV = 10
INTIMACY_POINT_BY_GOLD_GIFT = 2
INTIMACY_POINT_BY_SPECTATE_LIKE = 1
INTIMACY_POINT_BY_GANG = 3
INTIMACY_POINT_BY_GANG_WIN = 4
IDX_INTIMACY_PT = 0
IDX_INTIMACY_TYPE = 1
IDX_INTIMACY_NAME = 2
IDX_INTIMACY_LV = 3
IDX_INTIMACY_REWARD_LV = 4
IDX_INTIMACY_RECORD_GANG = 0
IDX_INTIMACY_RECORD_GANG_WIN = 1
INTIMACY_MEMORY_EVENT_BUILT = 'event_built'
INTIMACY_MEMORY_EVENT_RELATION_DAY = 'event_relation_day'
INTIMACY_MEMORY_EVENT_RELATION_SPECIAL_DAY = 'event_relation_special_day'
INTIMACY_MEMORY_EVENT_RELATION_YEAR = 'event_relation_year'
INTIMACY_MEMORY_EVENT_LV = 'event_lv'
INTIMACY_MEMORY_EVENT_GANG = 'event_gang'
INTIMACY_MEMORY_EVENT_GANG_WIN = 'event_gang_win'
INTIMACY_MEMORY_EVENT_ASSIST = 'event_assist'
INTIMACY_MEMORY_EVENT_SAVE = 'event_save'
ALL_INTIMACY_MEMORY_EVENTS = {
 INTIMACY_MEMORY_EVENT_BUILT,
 INTIMACY_MEMORY_EVENT_RELATION_DAY,
 INTIMACY_MEMORY_EVENT_RELATION_SPECIAL_DAY,
 INTIMACY_MEMORY_EVENT_RELATION_YEAR,
 INTIMACY_MEMORY_EVENT_LV,
 INTIMACY_MEMORY_EVENT_GANG,
 INTIMACY_MEMORY_EVENT_GANG_WIN,
 INTIMACY_MEMORY_EVENT_ASSIST,
 INTIMACY_MEMORY_EVENT_SAVE}
INTIMACY_MEMORY_RELATION_EVENTS = {
 INTIMACY_MEMORY_EVENT_BUILT,
 INTIMACY_MEMORY_EVENT_RELATION_DAY,
 INTIMACY_MEMORY_EVENT_RELATION_SPECIAL_DAY,
 INTIMACY_MEMORY_EVENT_RELATION_YEAR}
INTIMACY_MEMORY_SPECIAL_RELATION_EVENTS = {
 INTIMACY_MEMORY_EVENT_RELATION_SPECIAL_DAY,
 INTIMACY_MEMORY_EVENT_RELATION_YEAR}
RANDOM_QUESTION_TYPE_NUM = 4
RANDOM_QUESTION_NUM_PER_TYPE = 1
YUEKA_DAILY_YUANBAO_RESERVE_NUM = 7
PRIV_SHOW_BADGE = 'priv_show_badge'
PRIV_SHOW_PURPLE_ID = 'priv_show_purple_id'
PRIV_SHOW_COLORFUL_FONT = 'priv_show_colorful_font'
PRIV_SHARE_MECHA_FASHION = 'priv_share_mecha_fashion'
PRIV_RED_PACKET = 'priv_red_packet'
PRIV_SHARE_LOBBY_MECHA_FASHION = 'priv_share_lobby_mecha_fashion'
PRIV_BADGE_RED_POINT = 'priv_badge_red_point'
PRIV_PURPLE_ID_RED_POINT = 'priv_purple_id_red_point'
PRIV_COLORFUL_FONT_RED_POINT = 'priv_colorful_font_red_point'
PRIV_SHARE_MECHA_FASHION_RED_POINT = 'priv_share_mecha_fashion_red_point'
PRIV_RED_PACKET_RED_POINT = 'priv_red_packet_red_point'
PRIV_SHARE_LOBBY_MECHA_FASHION_RED_POINT = 'priv_share_lobby_mecha_fashion_point'
PRIV_SETTING_KEYS = {
 PRIV_SHOW_BADGE,
 PRIV_SHOW_PURPLE_ID,
 PRIV_SHOW_COLORFUL_FONT,
 PRIV_SHARE_MECHA_FASHION,
 PRIV_RED_PACKET,
 PRIV_SHARE_LOBBY_MECHA_FASHION}
PRIVILEGE_LEVEL_TO_SETTING = {1: [
     PRIV_SHOW_BADGE],
   5: [
     PRIV_SHOW_COLORFUL_FONT],
   8: [
     PRIV_SHOW_PURPLE_ID],
   10: [
      PRIV_SHARE_MECHA_FASHION, PRIV_SHARE_LOBBY_MECHA_FASHION],
   12: [
      PRIV_RED_PACKET]
   }
PRIVILEGE_SETTING_TO_RED_POINT = {PRIV_SHOW_BADGE: PRIV_BADGE_RED_POINT,
   PRIV_SHOW_PURPLE_ID: PRIV_PURPLE_ID_RED_POINT,
   PRIV_SHOW_COLORFUL_FONT: PRIV_COLORFUL_FONT_RED_POINT,
   PRIV_SHARE_MECHA_FASHION: PRIV_SHARE_MECHA_FASHION_RED_POINT,
   PRIV_RED_PACKET: PRIV_RED_PACKET_RED_POINT,
   PRIV_SHARE_LOBBY_MECHA_FASHION: PRIV_SHARE_LOBBY_MECHA_FASHION_RED_POINT
   }
PRIV_ENJOY_FREE_TIMES_PER_WEEK = 5
PRIV_RED_PACKET_TIMES_PER_DAY = 1
SEASON_RUSHING_STAR = 1
SEASON_RUSHING_KILL = 2
FIRST_PAY_ITEM_ID = 50303005
GEV_ONLY_ME = 1
GEV_ONLY_FRIEND = 2
GEV_ALL = 3
ACTIVITY_CREATOR_DISPLAY_KEY = 'ACTIVITY_CREATOR_DISPLAY_KEY'
HAS_CLICK_FRIEND_CHAT_HINT_KEY = 'HAS_CLICK_FRIEND_CHAT_HINT_KEY'
EX_SKIN_IMPROVE_RED_POINT_KEY = 'EX_SKIN_IMPROVE_RED_POINT_KEY_{}'
ACTIVITY_PEAK_WEEKEND_MATCH_KEY = 'ACTIVITY_PEAK_WEEKEND_MATCH_KEY'
ACTIVITY_PEAK_WEEKEND_MATCH_KEY_NEW = 'ACTIVITY_PEAK_WEEKEND_MATCH_KEY_NEW'
SKIN_SHARE_TYPE_PRIV = 'privilege'
SKIN_SHARE_TYPE_INTIMACY = 'intimacy'
LOBBY_TV_TEXTURE_KEY = 'LOBBY_TV_TEXTURE_KEY'
NEARBY_STREAM_MAX_COUNT = 5