# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/data/90151.py
_reload_all = True
DataDict = {90151: {'Content': {'MC_BEAT_BACK': {'action_param': (
                                                       0, ['hit', 'lower', 1, {'loop': True}]),
                                        'action_state': 'BeatBack',
                                        'custom_param': {'max_h_speed': 50,
                                                         'min_h_speed': 10,
                                                         'max_v_speed': 30,
                                                         'min_v_speed': 10,
                                                         'max_affect_dist': 15,
                                                         'gravity': 50
                                                         }
                                        },
                       'MC_DEAD': {'action_param': (
                                                  0, ['die', 'lower', 1]),
                                   'action_state': 'Die'
                                   },
                       'MC_FROZEN': {'action_param': (
                                                    0, ['hit', 'lower', 1]),
                                     'action_state': 'OnFrozen'
                                     },
                       'MC_IMMOBILIZE': {'action_param': (
                                                        0, ['hit', 'lower', 1, {'loop': True}]),
                                         'action_state': 'Immobilize'
                                         },
                       'MC_JUMP_1': {'action_param': (
                                                    0, ['idle', 'lower', 1]),
                                     'action_state': 'JumpUp',
                                     'custom_param': {'gravity': 57,'jump_speed': 36,'anim_duration': 1}},
                       'MC_JUMP_2': {'action_param': (
                                                    0, ['idle', 'lower', 1, {'loop': True}]),
                                     'action_state': 'Fall',
                                     'custom_param': {'gravity': 100}},
                       'MC_JUMP_3': {'action_param': (
                                                    0, ['idle', 'lower', 1]),
                                     'action_state': 'OnGround',
                                     'custom_param': {'anim_duration': 0.5,'recover_trigger_speed': 36}},
                       'MC_MECHA_BOARDING': {'action_param': (
                                                            0, ['attack_03', 'lower', 1]),
                                             'action_state': 'Born',
                                             'custom_param': {'anim_duration': 2
                                                              }
                                             },
                       'MC_MONSTER_DASHATK': {'action_state': 'MonsterDashAtk',
                                              'custom_param': {'max_rush_duration': 2.5,
                                                               'max_rush_speed': 300,
                                                               'dash_stepheight': 3.0,
                                                               'pre_anim': 'charge_start',
                                                               'pre_anim_rate': 1.0,
                                                               'pre_anim_duration': 1.67,
                                                               'rush_anim': 'charge_loop',
                                                               'rush_anim_rate': 1.0,
                                                               'miss_anim': 'charge_atk01',
                                                               'miss_anim_rate': 1.0,
                                                               'miss_anim_duration': 1.5,
                                                               'end_brake_time': 0.2,
                                                               'air_dash_end_speed': 30,
                                                               'skill_id': 9010153,
                                                               'tick_interval': 0.03,
                                                               'is_draw_col': False,
                                                               'col_info': (20, 50),
                                                               'begin_aoe_skill_id': 9010155,
                                                               'end_aoe_skill_id': 9010156
                                                               }
                                              },
                       'MC_MONSTER_LASER': {'action_state': 'MonsterLaser',
                                            'custom_param': {'skill_id': 9015155,
                                                             'max_atk_dur': 5.0,
                                                             'pre_track_ratio': 0.05,
                                                             'atk_track_ratio': 0.05,
                                                             'max_laser_dis': 100,
                                                             'hit_interval': 0.1,
                                                             'pre_socket': 'fx_kaihuo1',
                                                             'pre_sfx_res': 'effect/fx/mecha/8008/8008_aux_aim.sfx',
                                                             'pre_sfx_scale': 1.0,
                                                             'atk_socket': 'fx_kaihuo1',
                                                             'atk_sfx_res': 'effect/fx/mecha/8008/8008_aux_aim.sfx',
                                                             'atk_sfx_scale': 4.0,
                                                             'hit_sfx': 'effect/fx/mecha/8008/8008_main_hit.sfx',
                                                             'int_anim': 'remote_atk_start',
                                                             'int_anim_dur': 0.93,
                                                             'int_anim_rate': 1.0,
                                                             'pre_anim': 'remote_atk_loop',
                                                             'pre_anim_dur': 0.7,
                                                             'pre_anim_rate': 1.0,
                                                             'atk_anim': 'remote_atk_loop',
                                                             'atk_anim_rate': 1.0,
                                                             'bac_anim': 'remote_atk_end',
                                                             'bac_anim_dur': 0.5,
                                                             'bac_anim_rate': 1.0
                                                             }
                                            },
                       'MC_MONSTER_MELEE': {'action_state': 'MonsterMelee',
                                            'custom_param': {'hit_range': (28, 26, 14),
                                                             'skill_id': 9010151,
                                                             'anim_name': 'attack_02',
                                                             'anim_rate': 1.2,
                                                             'anim_dur': 1.9,
                                                             'pre_anim_dur': 0.7,
                                                             'atk_anim_dur': 0.4
                                                             }
                                            },
                       'MC_MONSTER_POUNCE': {'action_state': 'MonsterPounce',
                                             'custom_param': {'skill_id': 9015154,
                                                              'focus_time': 0.6,
                                                              'focus_dis': 5,
                                                              'base_height': 3.0,
                                                              'dash_speed': 800,
                                                              'max_dash_time': 0.8,
                                                              'pre_dash_anim': 'dash_start',
                                                              'pre_dash_anim_dur': 1.96,
                                                              'pre_dash_anim_rate': 0.8,
                                                              'dash_anim': 'dash_loop',
                                                              'dash_anim_rate': 1.0,
                                                              'bac_dash_anim': 'dash_end',
                                                              'bac_dash_anim_dur': 1.43,
                                                              'bac_dash_anim_rate': 1.0,
                                                              'atk_state': 216
                                                              }
                                             },
                       'MC_MONSTER_POWER_MELEE': {'action_state': 'MonsterMelee',
                                                  'custom_param': {'hit_range': (28, 26, 14),
                                                                   'skill_id': 9010152,
                                                                   'anim_name': 'charge_atk01',
                                                                   'anim_rate': 1.0,
                                                                   'anim_dur': 1.5,
                                                                   'pre_anim_dur': 0.25,
                                                                   'atk_anim_dur': 0.4
                                                                   }
                                                  },
                       'MC_MONSTER_ROAR': {'action_param': (
                                                          0, ['attack_03', 'lower', 1]),
                                           'action_state': 'MonsterRoar',
                                           'custom_param': {'skill_id': 9015153,
                                                            'anim_name': 'attack_03',
                                                            'anim_rate': 1.0,
                                                            'anim_dur': 2.9
                                                            }
                                           },
                       'MC_MONSTER_STUN': {'action_state': 'MonsterStun',
                                           'custom_param': {'pre_anim': 'beaten_start',
                                                            'pre_anim_dur': 1.07,
                                                            'pre_anim_rate': 1.0,
                                                            'stun_anim': 'beaten_loop',
                                                            'stun_anim_rate': 1.0,
                                                            'bac_anim': 'beaten_end',
                                                            'bac_anim_dur': 1.47,
                                                            'bac_anim_rate': 1.0
                                                            }
                                           },
                       'MC_MONSTER_SUMMON': {'action_state': 'MonsterSummon',
                                             'custom_param': {'skill_id': 9015156,
                                                              'fire_socket': 'fx_kaihuo',
                                                              'pre_anim': 'missile_start',
                                                              'pre_anim_dur': 0.93,
                                                              'pre_anim_rate': 1.0,
                                                              'sum_anim': 'missile_atk',
                                                              'sum_anim_dur': 0.8,
                                                              'sum_anim_rate': 1.0,
                                                              'bac_anim': 'missile_atk',
                                                              'bac_anim_dur': 0.67,
                                                              'bac_anim_rate': 1.0
                                                              }
                                             },
                       'MC_MOVE': {'action_param': (
                                                  0, ['run', 'lower', 1, {'loop': True}]),
                                   'action_state': 'Walk',
                                   'custom_param': {'walk_speed': 14,'move_acc': 30,'brake_acc': -30,'dynamic_speed_rate': 0.1}},
                       'MC_RUN': {'action_param': (
                                                 0, ['run', 'lower', 1, {'loop': True}]),
                                  'action_state': 'Run',
                                  'custom_param': {'walk_speed': 14,'run_speed': 18,'move_acc': 30,'brake_acc': -30,'dynamic_speed_rate': 0.2}},
                       'MC_SHOOT': {'action_param': (
                                                   0, ['shoot', 'upper', 1, {'loop': True}]),
                                    'action_state': 'WeaponFire',
                                    'custom_param': {'shoot_anim': ('shoot', 'upper', 1)}},
                       'MC_STAND': {'action_param': (
                                                   0, ['idle', 'lower', 1, {'loop': True}]),
                                    'action_state': 'Stand'
                                    },
                       'MC_TURN ': {'action_state': 'Turn',
                                    'custom_param': {'enable_twist_yaw': False,
                                                     'enable_twist_pitch': True
                                                     }
                                    }
                       },
           'Name': 'PVE\xe7\xb4\xab\xe7\x9a\xae\xe6\x80\xaa',
           'QuickLink': 1
           },
   'status': {'Content': {'MC_BEAT_BACK': {'MC_DEAD': 2,
                                           'MC_FROZEN': 2,
                                           'MC_IMMOBILIZE': 2,
                                           'MC_JUMP_1': 1,
                                           'MC_JUMP_2': 2,
                                           'MC_JUMP_3': 2,
                                           'MC_MECHA_BOARDING': 1,
                                           'MC_MONSTER_DASHATK': 1,
                                           'MC_MONSTER_LASER': 1,
                                           'MC_MONSTER_MELEE': 1,
                                           'MC_MONSTER_POUNCE': 1,
                                           'MC_MONSTER_POUNCE_ATK': 1,
                                           'MC_MONSTER_POWER_MELEE': 1,
                                           'MC_MONSTER_ROAR': 1,
                                           'MC_MONSTER_STUN': 2,
                                           'MC_MONSTER_SUMMON': 1,
                                           'MC_MOVE': 1,
                                           'MC_RUN': 1,
                                           'MC_SHOOT': 1,
                                           'MC_STAND': 1,
                                           'MC_TURN ': 1
                                           },
                          'MC_DEAD': {'MC_BEAT_BACK': 1,
                                      'MC_FROZEN': 1,
                                      'MC_IMMOBILIZE': 1,
                                      'MC_JUMP_1': 1,
                                      'MC_JUMP_2': 1,
                                      'MC_JUMP_3': 1,
                                      'MC_MECHA_BOARDING': 1,
                                      'MC_MONSTER_DASHATK': 1,
                                      'MC_MONSTER_LASER': 1,
                                      'MC_MONSTER_MELEE': 1,
                                      'MC_MONSTER_POUNCE': 1,
                                      'MC_MONSTER_POUNCE_ATK': 1,
                                      'MC_MONSTER_POWER_MELEE': 1,
                                      'MC_MONSTER_ROAR': 1,
                                      'MC_MONSTER_STUN': 1,
                                      'MC_MONSTER_SUMMON': 1,
                                      'MC_MOVE': 1,
                                      'MC_RUN': 1,
                                      'MC_SHOOT': 1,
                                      'MC_STAND': 1,
                                      'MC_TURN ': 1
                                      },
                          'MC_FROZEN': {'MC_BEAT_BACK': 2,
                                        'MC_DEAD': 2,
                                        'MC_IMMOBILIZE': 1,
                                        'MC_JUMP_1': 1,
                                        'MC_JUMP_2': 1,
                                        'MC_JUMP_3': 1,
                                        'MC_MECHA_BOARDING': 1,
                                        'MC_MONSTER_DASHATK': 1,
                                        'MC_MONSTER_LASER': 1,
                                        'MC_MONSTER_MELEE': 1,
                                        'MC_MONSTER_POUNCE': 1,
                                        'MC_MONSTER_POUNCE_ATK': 1,
                                        'MC_MONSTER_POWER_MELEE': 1,
                                        'MC_MONSTER_ROAR': 1,
                                        'MC_MONSTER_STUN': 2,
                                        'MC_MONSTER_SUMMON': 1,
                                        'MC_MOVE': 1,
                                        'MC_RUN': 1,
                                        'MC_SHOOT': 1,
                                        'MC_STAND': 1,
                                        'MC_TURN ': 1
                                        },
                          'MC_IMMOBILIZE': {'MC_BEAT_BACK': 2,
                                            'MC_DEAD': 2,
                                            'MC_FROZEN': 2,
                                            'MC_JUMP_1': 1,
                                            'MC_JUMP_2': 1,
                                            'MC_JUMP_3': 1,
                                            'MC_MECHA_BOARDING': 1,
                                            'MC_MONSTER_DASHATK': 1,
                                            'MC_MONSTER_LASER': 1,
                                            'MC_MONSTER_MELEE': 1,
                                            'MC_MONSTER_POUNCE': 1,
                                            'MC_MONSTER_POUNCE_ATK': 1,
                                            'MC_MONSTER_POWER_MELEE': 1,
                                            'MC_MONSTER_ROAR': 1,
                                            'MC_MONSTER_STUN': 2,
                                            'MC_MONSTER_SUMMON': 1,
                                            'MC_MOVE': 1,
                                            'MC_RUN': 1,
                                            'MC_SHOOT': 1,
                                            'MC_STAND': 1,
                                            'MC_TURN ': 1
                                            },
                          'MC_JUMP_1': {'MC_BEAT_BACK': 2,
                                        'MC_DEAD': 2,
                                        'MC_FROZEN': 2,
                                        'MC_JUMP_2': 2,
                                        'MC_JUMP_3': 2,
                                        'MC_MECHA_BOARDING': 1,
                                        'MC_MONSTER_STUN': 2,
                                        'MC_MOVE': 1,
                                        'MC_RUN': 1,
                                        'MC_STAND': 1,
                                        'MC_TURN ': 1
                                        },
                          'MC_JUMP_2': {'MC_BEAT_BACK': 2,
                                        'MC_DEAD': 2,
                                        'MC_FROZEN': 2,
                                        'MC_JUMP_1': 1,
                                        'MC_JUMP_3': 2,
                                        'MC_MECHA_BOARDING': 1,
                                        'MC_MONSTER_STUN': 2,
                                        'MC_MOVE': 1,
                                        'MC_RUN': 1,
                                        'MC_STAND': 1,
                                        'MC_TURN ': 1
                                        },
                          'MC_JUMP_3': {'MC_BEAT_BACK': 2,
                                        'MC_DEAD': 2,
                                        'MC_FROZEN': 2,
                                        'MC_JUMP_1': 1,
                                        'MC_JUMP_2': 1,
                                        'MC_MECHA_BOARDING': 1,
                                        'MC_MONSTER_STUN': 2,
                                        'MC_MOVE': 2,
                                        'MC_RUN': 1,
                                        'MC_STAND': 2,
                                        'MC_TURN ': 1
                                        },
                          'MC_MECHA_BOARDING': {'MC_BEAT_BACK': 1,
                                                'MC_DEAD': 2,
                                                'MC_FROZEN': 1,
                                                'MC_IMMOBILIZE': 1,
                                                'MC_JUMP_1': 1,
                                                'MC_JUMP_2': 1,
                                                'MC_JUMP_3': 1,
                                                'MC_MOVE': 1,
                                                'MC_RUN': 1,
                                                'MC_SHOOT': 1,
                                                'MC_STAND': 2,
                                                'MC_TURN ': 1
                                                },
                          'MC_MONSTER_DASHATK': {'MC_BEAT_BACK': 1,
                                                 'MC_DEAD': 2,
                                                 'MC_FROZEN': 1,
                                                 'MC_IMMOBILIZE': 1,
                                                 'MC_JUMP_1': 1,
                                                 'MC_JUMP_2': 1,
                                                 'MC_JUMP_3': 1,
                                                 'MC_MONSTER_LASER': 1,
                                                 'MC_MONSTER_MELEE': 1,
                                                 'MC_MONSTER_POUNCE': 1,
                                                 'MC_MONSTER_POUNCE_ATK': 1,
                                                 'MC_MONSTER_POWER_MELEE': 1,
                                                 'MC_MONSTER_ROAR': 1,
                                                 'MC_MONSTER_STUN': 2,
                                                 'MC_MONSTER_SUMMON': 1,
                                                 'MC_MOVE': 1,
                                                 'MC_RUN': 1,
                                                 'MC_SHOOT': 1,
                                                 'MC_STAND': 1,
                                                 'MC_TURN ': 1
                                                 },
                          'MC_MONSTER_LASER': {'MC_BEAT_BACK': 2,
                                               'MC_DEAD': 2,
                                               'MC_FROZEN': 2,
                                               'MC_IMMOBILIZE': 2,
                                               'MC_JUMP_1': 1,
                                               'MC_JUMP_2': 1,
                                               'MC_JUMP_3': 1,
                                               'MC_MONSTER_DASHATK': 1,
                                               'MC_MONSTER_MELEE': 1,
                                               'MC_MONSTER_POUNCE': 1,
                                               'MC_MONSTER_POUNCE_ATK': 1,
                                               'MC_MONSTER_POWER_MELEE': 1,
                                               'MC_MONSTER_ROAR': 1,
                                               'MC_MONSTER_STUN': 2,
                                               'MC_MONSTER_SUMMON': 1,
                                               'MC_MOVE': 1,
                                               'MC_RUN': 1,
                                               'MC_SHOOT': 1,
                                               'MC_STAND': 1,
                                               'MC_TURN ': 1
                                               },
                          'MC_MONSTER_MELEE': {'MC_BEAT_BACK': 2,
                                               'MC_DEAD': 2,
                                               'MC_FROZEN': 2,
                                               'MC_IMMOBILIZE': 2,
                                               'MC_JUMP_1': 1,
                                               'MC_JUMP_2': 1,
                                               'MC_JUMP_3': 1,
                                               'MC_MONSTER_DASHATK': 1,
                                               'MC_MONSTER_LASER': 1,
                                               'MC_MONSTER_POUNCE': 1,
                                               'MC_MONSTER_POUNCE_ATK': 1,
                                               'MC_MONSTER_POWER_MELEE': 1,
                                               'MC_MONSTER_ROAR': 1,
                                               'MC_MONSTER_STUN': 2,
                                               'MC_MONSTER_SUMMON': 1,
                                               'MC_MOVE': 1,
                                               'MC_RUN': 1,
                                               'MC_SHOOT': 1,
                                               'MC_STAND': 1,
                                               'MC_TURN ': 1
                                               },
                          'MC_MONSTER_POUNCE': {'MC_BEAT_BACK': 1,
                                                'MC_DEAD': 2,
                                                'MC_FROZEN': 1,
                                                'MC_IMMOBILIZE': 1,
                                                'MC_JUMP_1': 1,
                                                'MC_JUMP_2': 1,
                                                'MC_JUMP_3': 1,
                                                'MC_MONSTER_DASHATK': 1,
                                                'MC_MONSTER_LASER': 1,
                                                'MC_MONSTER_ROAR': 1,
                                                'MC_MONSTER_STUN': 2,
                                                'MC_MONSTER_SUMMON': 1,
                                                'MC_MOVE': 1,
                                                'MC_RUN': 1,
                                                'MC_SHOOT': 1,
                                                'MC_STAND': 1,
                                                'MC_TURN ': 1
                                                },
                          'MC_MONSTER_POWER_MELEE': {'MC_BEAT_BACK': 2,
                                                     'MC_DEAD': 2,
                                                     'MC_FROZEN': 2,
                                                     'MC_IMMOBILIZE': 2,
                                                     'MC_JUMP_1': 1,
                                                     'MC_JUMP_2': 1,
                                                     'MC_JUMP_3': 1,
                                                     'MC_MONSTER_DASHATK': 1,
                                                     'MC_MONSTER_LASER': 1,
                                                     'MC_MONSTER_MELEE': 1,
                                                     'MC_MONSTER_POUNCE': 1,
                                                     'MC_MONSTER_POUNCE_ATK': 1,
                                                     'MC_MONSTER_ROAR': 1,
                                                     'MC_MONSTER_STUN': 2,
                                                     'MC_MONSTER_SUMMON': 1,
                                                     'MC_MOVE': 1,
                                                     'MC_RUN': 1,
                                                     'MC_SHOOT': 1,
                                                     'MC_STAND': 1,
                                                     'MC_TURN ': 1
                                                     },
                          'MC_MONSTER_ROAR': {'MC_BEAT_BACK': 2,
                                              'MC_DEAD': 2,
                                              'MC_FROZEN': 2,
                                              'MC_IMMOBILIZE': 2,
                                              'MC_JUMP_1': 1,
                                              'MC_JUMP_2': 1,
                                              'MC_JUMP_3': 1,
                                              'MC_MONSTER_DASHATK': 1,
                                              'MC_MONSTER_LASER': 1,
                                              'MC_MONSTER_MELEE': 1,
                                              'MC_MONSTER_POUNCE': 1,
                                              'MC_MONSTER_POUNCE_ATK': 1,
                                              'MC_MONSTER_POWER_MELEE': 1,
                                              'MC_MONSTER_STUN': 2,
                                              'MC_MONSTER_SUMMON': 1,
                                              'MC_MOVE': 1,
                                              'MC_RUN': 1,
                                              'MC_SHOOT': 1,
                                              'MC_STAND': 1,
                                              'MC_TURN ': 1
                                              },
                          'MC_MONSTER_STUN': {'MC_BEAT_BACK': 1,
                                              'MC_DEAD': 2,
                                              'MC_FROZEN': 1,
                                              'MC_IMMOBILIZE': 1,
                                              'MC_JUMP_1': 1,
                                              'MC_JUMP_2': 1,
                                              'MC_JUMP_3': 1,
                                              'MC_MONSTER_DASHATK': 1,
                                              'MC_MONSTER_LASER': 1,
                                              'MC_MONSTER_MELEE': 1,
                                              'MC_MONSTER_POUNCE': 1,
                                              'MC_MONSTER_POUNCE_ATK': 1,
                                              'MC_MONSTER_POWER_MELEE': 1,
                                              'MC_MONSTER_ROAR': 1,
                                              'MC_MONSTER_SUMMON': 1,
                                              'MC_MOVE': 1,
                                              'MC_RUN': 1,
                                              'MC_SHOOT': 1,
                                              'MC_STAND': 1,
                                              'MC_TURN ': 1
                                              },
                          'MC_MONSTER_SUMMON': {'MC_BEAT_BACK': 2,
                                                'MC_DEAD': 2,
                                                'MC_FROZEN': 2,
                                                'MC_IMMOBILIZE': 2,
                                                'MC_JUMP_1': 1,
                                                'MC_JUMP_2': 1,
                                                'MC_JUMP_3': 1,
                                                'MC_MONSTER_DASHATK': 1,
                                                'MC_MONSTER_LASER': 1,
                                                'MC_MONSTER_MELEE': 1,
                                                'MC_MONSTER_POUNCE': 1,
                                                'MC_MONSTER_POUNCE_ATK': 1,
                                                'MC_MONSTER_POWER_MELEE': 1,
                                                'MC_MONSTER_ROAR': 1,
                                                'MC_MONSTER_STUN': 2,
                                                'MC_MOVE': 1,
                                                'MC_RUN': 1,
                                                'MC_SHOOT': 1,
                                                'MC_STAND': 1,
                                                'MC_TURN ': 1
                                                },
                          'MC_MOVE': {'MC_BEAT_BACK': 2,
                                      'MC_DEAD': 2,
                                      'MC_FROZEN': 2,
                                      'MC_JUMP_1': 2,
                                      'MC_JUMP_2': 2,
                                      'MC_JUMP_3': 2,
                                      'MC_MECHA_BOARDING': 1,
                                      'MC_MONSTER_STUN': 2,
                                      'MC_RUN': 2,
                                      'MC_STAND': 2,
                                      'MC_TURN ': 1
                                      },
                          'MC_RUN': {'MC_BEAT_BACK': 2,
                                     'MC_DEAD': 2,
                                     'MC_FROZEN': 2,
                                     'MC_JUMP_1': 2,
                                     'MC_JUMP_2': 2,
                                     'MC_JUMP_3': 2,
                                     'MC_MECHA_BOARDING': 1,
                                     'MC_MONSTER_STUN': 2,
                                     'MC_MOVE': 2,
                                     'MC_STAND': 2,
                                     'MC_TURN ': 1
                                     },
                          'MC_SHOOT': {'MC_BEAT_BACK': 2,
                                       'MC_DEAD': 2,
                                       'MC_FROZEN': 2,
                                       'MC_IMMOBILIZE': 1,
                                       'MC_MECHA_BOARDING': 1,
                                       'MC_MONSTER_STUN': 2,
                                       'MC_RUN': 1,
                                       'MC_SHOOT': 1
                                       },
                          'MC_STAND': {'MC_BEAT_BACK': 2,
                                       'MC_DEAD': 2,
                                       'MC_FROZEN': 2,
                                       'MC_JUMP_1': 2,
                                       'MC_JUMP_2': 2,
                                       'MC_JUMP_3': 2,
                                       'MC_MECHA_BOARDING': 1,
                                       'MC_MONSTER_STUN': 2,
                                       'MC_MOVE': 2,
                                       'MC_RUN': 2,
                                       'MC_TURN ': 2
                                       },
                          'MC_TURN ': {'MC_BEAT_BACK': 2,
                                       'MC_DEAD': 2,
                                       'MC_FROZEN': 2,
                                       'MC_JUMP_1': 2,
                                       'MC_JUMP_2': 2,
                                       'MC_JUMP_3': 2,
                                       'MC_MECHA_BOARDING': 1,
                                       'MC_MONSTER_STUN': 2,
                                       'MC_MOVE': 2,
                                       'MC_RUN': 2,
                                       'MC_STAND': 2
                                       }
                          },
              'Name': '\xe7\x8a\xb6\xe6\x80\x81\xe8\xbf\x81\xe7\xa7\xbb\xe8\xa1\xa8',
              'QuickLink': 1
              }
   }

def GetData():
    return DataDict


def Getstatus():
    return GetData()['status']['Content']


def Get90151():
    return GetData()['90151']['Content']