# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/cdata/mecha_attr_config.py
_reload_all = True
data = {'affect_radius_add': {'cKey': 'affect_radius_add',
                         'cType': 'VAR_FLOAT',
                         'iPercent': 0,
                         'cInit': '0',
                         'iSyncType': 1,
                         'cDesc': '\xe7\x88\x86\xe7\x82\xb8\xe7\x89\xa9\xe5\xbd\xb1\xe5\x93\x8d\xe8\x8c\x83\xe5\x9b\xb4\xe5\x8a\xa0\xe6\x88\x90',
                         'fExtremum': 5
                         },
   'affect_radius_factor': {'cKey': 'affect_radius_factor',
                            'cType': 'VAR_FLOAT',
                            'iPercent': 1,
                            'cInit': '0',
                            'iSyncType': 1,
                            'cDesc': '\xe7\x88\x86\xe7\x82\xb8\xe7\x89\xa9\xe5\xbd\xb1\xe5\x93\x8d\xe8\x8c\x83\xe5\x9b\xb4\xe5\x8a\xa0\xe6\x88\x90',
                            'fExtremum': 2
                            },
   'col_radius': {'cKey': 'col_radius',
                  'cType': 'VAR_FLOAT',
                  'iPercent': 1,
                  'cInit': '0',
                  'iSyncType': 1,
                  'cDesc': '\xe7\x88\x86\xe7\x82\xb8\xe7\x89\xa9\xe7\xa2\xb0\xe6\x92\x9e\xe4\xbd\x93\xe5\xa4\xa7\xe5\xb0\x8f\xe5\x8a\xa0\xe6\x88\x90'
                  },
   'base_power_add': {'cKey': 'base_power_add',
                      'cType': 'VAR_INT',
                      'iPercent': 0,
                      'cInit': '0',
                      'iSyncType': 0,
                      'cDesc': '\xe5\x9f\xba\xe7\xa1\x80\xe4\xbc\xa4\xe5\xae\xb3\xe5\xa2\x9e\xe9\x87\x8f'
                      },
   'base_power_factor': {'cKey': 'base_power_factor',
                         'cType': 'VAR_FLOAT',
                         'iPercent': 1,
                         'cInit': '0',
                         'iSyncType': 0,
                         'cDesc': '\xe5\x9f\xba\xe7\xa1\x80\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90',
                         'fExtremum': 3
                         },
   'shield_dmg_factor': {'cKey': 'shield_dmg_factor',
                         'cType': 'VAR_FLOAT',
                         'iPercent': 1,
                         'cInit': '0',
                         'iSyncType': 0,
                         'cDesc': '\xe6\x8a\xa4\xe7\x9b\xbe\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90'
                         },
   'max_hp_factor': {'cKey': 'max_hp_factor',
                     'cType': 'VAR_FLOAT',
                     'iPercent': 1,
                     'cInit': '0',
                     'iSyncType': 0,
                     'cDesc': '\xe6\x9c\x80\xe5\xa4\xa7\xe8\xa1\x80\xe9\x87\x8f\xe5\x8a\xa0\xe6\x88\x90'
                     },
   'speed_up_factor': {'cKey': 'speed_up_factor',
                       'cType': 'VAR_FLOAT',
                       'iPercent': 1,
                       'cInit': '0',
                       'iSyncType': 1,
                       'cDesc': '\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                       },
   'dist_damage_factor': {'cKey': 'dist_damage_factor',
                          'cType': 'VAR_FLOAT',
                          'iPercent': 1,
                          'cInit': '0',
                          'iSyncType': 0,
                          'cDesc': '\xe4\xbc\xa4\xe5\xae\xb3\xe8\xae\xa1\xe7\xae\x97\xe7\x9a\x84\xe8\xa1\xb0\xe5\x87\x8f\xe8\xb7\x9d\xe7\xa6\xbb\xe5\x8a\xa0\xe6\x88\x90\xef\xbc\x8c\xe7\x88\x86\xe7\x82\xb8\xe8\xb7\x9d\xe7\xa6\xbb\xef\xbc\x88\xe7\x9b\xb8\xe5\xaf\xb9\xe7\x88\x86\xe7\x82\xb8\xe7\x82\xb9\xef\xbc\x89'
                          },
   'max_hp_add': {'cKey': 'max_hp_add',
                  'cType': 'VAR_INT',
                  'iPercent': 1,
                  'cInit': '0',
                  'iSyncType': 0,
                  'cDesc': '\xe6\x9c\x80\xe5\xa4\xa7\xe8\xa1\x80\xe9\x87\x8f\xe5\x9b\xba\xe5\xae\x9a\xe5\x8a\xa0\xe6\x88\x90'
                  },
   'dist_shoot_damage_factor': {'cKey': 'dist_shoot_damage_factor',
                                'cType': 'VAR_FLOAT',
                                'iPercent': 1,
                                'cInit': '0',
                                'iSyncType': 0,
                                'cDesc': '\xe4\xbc\xa4\xe5\xae\xb3\xe8\xae\xa1\xe7\xae\x97\xe7\x9a\x84\xe8\xa1\xb0\xe5\x87\x8f\xe8\xb7\x9d\xe7\xa6\xbb\xe5\x8a\xa0\xe6\x88\x90\xef\xbc\x8c\xe5\xb0\x84\xe5\x87\xbb\xe8\xb7\x9d\xe7\xa6\xbb\xef\xbc\x88\xe7\x9b\xb8\xe5\xaf\xb9\xe5\xb0\x84\xe5\x87\xba\xe7\x82\xb9\xef\xbc\x89'
                                },
   'reload_speed_factor': {'cKey': 'reload_speed_factor',
                           'cType': 'VAR_FLOAT',
                           'iPercent': 1,
                           'cInit': '0',
                           'iSyncType': 1,
                           'cDesc': '\xe6\x8d\xa2\xe5\xbc\xb9\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                           },
   'reload_speed_factor_pos_1': {'cKey': 'reload_speed_factor_pos_1',
                                 'cType': 'VAR_FLOAT',
                                 'iPercent': 1,
                                 'cInit': '0',
                                 'iSyncType': 1,
                                 'cDesc': '\xe6\x8d\xa2\xe5\xbc\xb9\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                                 },
   'reload_speed_factor_pos_2': {'cKey': 'reload_speed_factor_pos_2',
                                 'cType': 'VAR_FLOAT',
                                 'iPercent': 1,
                                 'cInit': '0',
                                 'iSyncType': 1,
                                 'cDesc': '\xe6\x8d\xa2\xe5\xbc\xb9\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                                 },
   'reload_speed_factor_pos_3': {'cKey': 'reload_speed_factor_pos_3',
                                 'cType': 'VAR_FLOAT',
                                 'iPercent': 1,
                                 'cInit': '0',
                                 'iSyncType': 1,
                                 'cDesc': '\xe6\x8d\xa2\xe5\xbc\xb9\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                                 },
   'reload_speed_factor_pos_4': {'cKey': 'reload_speed_factor_pos_4',
                                 'cType': 'VAR_FLOAT',
                                 'iPercent': 1,
                                 'cInit': '0',
                                 'iSyncType': 1,
                                 'cDesc': '\xe6\x8d\xa2\xe5\xbc\xb9\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                                 },
   'reload_speed_factor_pos_5': {'cKey': 'reload_speed_factor_pos_5',
                                 'cType': 'VAR_FLOAT',
                                 'iPercent': 1,
                                 'cInit': '0',
                                 'iSyncType': 1,
                                 'cDesc': '\xe6\x8d\xa2\xe5\xbc\xb9\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                                 },
   'reload_speed_factor_pos_6': {'cKey': 'reload_speed_factor_pos_6',
                                 'cType': 'VAR_FLOAT',
                                 'iPercent': 1,
                                 'cInit': '0',
                                 'iSyncType': 1,
                                 'cDesc': '\xe6\x8d\xa2\xe5\xbc\xb9\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                                 },
   'fShootSpeedFactor': {'cKey': 'fShootSpeedFactor',
                         'cType': 'VAR_FLOAT',
                         'iPercent': 1,
                         'cInit': '0',
                         'iSyncType': 1,
                         'cDesc': '\xe5\xb0\x84\xe9\x80\x9f\xe5\x8a\xa0\xe6\x88\x90'
                         },
   'fShootSpeedFactor_pos_1': {'cKey': 'fShootSpeedFactor_pos_1',
                               'cType': 'VAR_FLOAT',
                               'iPercent': 1,
                               'cInit': '0',
                               'iSyncType': 1,
                               'cDesc': '\xe4\xb8\xbb\xe6\xad\xa6\xe5\x99\xa8\xe5\xb0\x84\xe5\x87\xbb\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                               },
   'fShootSpeedFactor_pos_2': {'cKey': 'fShootSpeedFactor_pos_2',
                               'cType': 'VAR_FLOAT',
                               'iPercent': 1,
                               'cInit': '0',
                               'iSyncType': 1,
                               'cDesc': '\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe5\xb0\x84\xe5\x87\xbb\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                               },
   'spread_factor': {'cKey': 'spread_factor',
                     'cType': 'VAR_FLOAT',
                     'iPercent': 1,
                     'cInit': '0',
                     'iSyncType': 1,
                     'cDesc': '\xe6\x95\xa3\xe5\xb0\x84\xe8\x8c\x83\xe5\x9b\xb4\xe5\x8a\xa0\xe6\x88\x90'
                     },
   'spread_factor_pos_1': {'cKey': 'spread_factor_pos_1',
                           'cType': 'VAR_FLOAT',
                           'iPercent': 1,
                           'cInit': '0',
                           'iSyncType': 1,
                           'cDesc': '\xe4\xb8\xbb\xe6\xad\xa6\xe5\x99\xa8\xe6\x95\xa3\xe5\xb0\x84\xe8\x8c\x83\xe5\x9b\xb4\xe5\x8a\xa0\xe6\x88\x90'
                           },
   'spread_factor_pos_2': {'cKey': 'spread_factor_pos_2',
                           'cType': 'VAR_FLOAT',
                           'iPercent': 1,
                           'cInit': '0',
                           'iSyncType': 1,
                           'cDesc': '2\xe5\x8f\xb7\xe4\xbd\x8d\xe6\x95\xa3\xe5\xb0\x84\xe8\x8c\x83\xe5\x9b\xb4\xe5\x8a\xa0\xe6\x88\x90'
                           },
   'spread_max_factor': {'cKey': 'spread_max_factor',
                         'cType': 'VAR_FLOAT',
                         'iPercent': 1,
                         'cInit': '0',
                         'iSyncType': 1,
                         'cDesc': '\xe6\x95\xa3\xe5\xb8\x83\xe9\x80\x92\xe5\xa2\x9e\xe4\xb8\x8a\xe9\x99\x90\xe5\x8a\xa0\xe6\x88\x90'
                         },
   'spread_inc_factor': {'cKey': 'spread_inc_factor',
                         'cType': 'VAR_FLOAT',
                         'iPercent': 1,
                         'cInit': '0',
                         'iSyncType': 1,
                         'cDesc': '\xef\xbc\x88\xe8\x85\xb0\xe5\xb0\x84\xef\xbc\x89\xe6\x95\xa3\xe5\xb0\x84\xe9\x80\x92\xe5\xa2\x9e\xe5\x8a\xa0\xe6\x88\x90'
                         },
   'throw_speed_add_rate': {'cKey': 'throw_speed_add_rate',
                            'cType': 'VAR_FLOAT',
                            'iPercent': 1,
                            'cInit': '0',
                            'iSyncType': 1,
                            'cDesc': '\xe6\x8a\x95\xe6\x8e\xb7\xe7\x89\xa9\xe9\xa3\x9e\xe8\xa1\x8c\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                            },
   'attr_vampire_factor': {'cKey': 'attr_vampire_factor',
                           'cType': 'VAR_FLOAT',
                           'iPercent': 1,
                           'cInit': '0',
                           'iSyncType': 0,
                           'cDesc': '\xe4\xbc\xa4\xe5\xae\xb3\xe5\x90\xb8\xe8\xa1\x80\xe7\xb3\xbb\xe6\x95\xb0'
                           },
   'accumulate_init_energy_ratio': {'cKey': 'accumulate_init_energy_ratio',
                                    'cType': 'VAR_FLOAT',
                                    'iPercent': 1,
                                    'cInit': '0',
                                    'iSyncType': 1,
                                    'cDesc': '\xe8\x93\x84\xe5\x8a\x9b\xe6\x9e\xaa\xe5\x88\x9d\xe5\xa7\x8b\xe8\x93\x84\xe5\x8a\x9b\xe5\x80\xbc'
                                    },
   'footstep_sound_dis_factor': {'cKey': 'footstep_sound_dis_factor',
                                 'cType': 'VAR_FLOAT',
                                 'iPercent': 1,
                                 'cInit': '0',
                                 'iSyncType': 2,
                                 'cDesc': '\xe8\x84\x9a\xe6\xad\xa5\xe5\xa3\xb0\xe9\x9f\xb3\xe8\xb7\x9d\xe7\xa6\xbb\xe5\x8a\xa0\xe6\x88\x90'
                                 },
   'controlled_time_factor': {'cKey': 'controlled_time_factor',
                              'cType': 'VAR_FLOAT',
                              'iPercent': 1,
                              'cInit': '0',
                              'iSyncType': 0,
                              'cDesc': '\xe5\x8f\x97\xe6\x8e\xa7\xe6\x97\xb6\xe9\x97\xb4\xe5\x8a\xa0\xe6\x88\x90'
                              },
   'cure_factor': {'cKey': 'cure_factor',
                   'cType': 'VAR_FLOAT',
                   'iPercent': 1,
                   'cInit': '0',
                   'iSyncType': 0,
                   'cDesc': '\xe6\xb2\xbb\xe7\x96\x97\xe6\x95\x88\xe6\x9e\x9c\xe5\x8a\xa0\xe6\x88\x90'
                   },
   'crit_prate': {'cKey': 'crit_prate',
                  'cType': 'VAR_FLOAT',
                  'iPercent': 1,
                  'cInit': '0',
                  'iSyncType': 0,
                  'cDesc': '\xe6\x9a\xb4\xe5\x87\xbb\xe5\x80\x8d\xe7\x8e\x87'
                  },
   'skill_recover_factor': {'cKey': 'skill_recover_factor',
                            'cType': 'VAR_FLOAT',
                            'iPercent': 1,
                            'cInit': '0',
                            'iSyncType': 1,
                            'cDesc': '\xe6\x8a\x80\xe8\x83\xbd\xe6\x81\xa2\xe5\xa4\x8d\xe9\x80\x9f\xe5\xba\xa6',
                            'fExtremum': 3
                            },
   'skill_cd_add': {'cKey': 'skill_cd_add',
                    'cType': 'VAR_FLOAT',
                    'iPercent': 1,
                    'cInit': '0',
                    'iSyncType': 1,
                    'cDesc': '\xe6\x8a\x80\xe8\x83\xbdCD\xe5\x8a\xa0\xe6\x88\x90'
                    },
   'skill_hit_recover_factor': {'cKey': 'skill_hit_recover_factor',
                                'cType': 'VAR_FLOAT',
                                'iPercent': 1,
                                'cInit': '0',
                                'iSyncType': 1,
                                'cDesc': '\xe5\x91\xbd\xe4\xb8\xad\xe4\xb9\x8b\xe5\x90\x8e\xe6\x8a\x80\xe8\x83\xbd\xe6\x81\xa2\xe5\xa4\x8d\xe9\x80\x9f\xe5\xba\xa6'
                                },
   'hip_jump_factor': {'cKey': 'hip_jump_factor',
                       'cType': 'VAR_FLOAT',
                       'iPercent': 1,
                       'cInit': '0',
                       'iSyncType': 1,
                       'cDesc': 'HIP,\xe8\xb7\xb3\xe8\xb7\x83'
                       },
   'hip_stand_stop_factor': {'cKey': 'hip_stand_stop_factor',
                             'cType': 'VAR_FLOAT',
                             'iPercent': 1,
                             'cInit': '0',
                             'iSyncType': 1,
                             'cDesc': 'HIP,\xe7\xab\x99\xe7\xab\x8b,\xe9\x9d\x99\xe6\xad\xa2'
                             },
   'hip_stand_move_factor': {'cKey': 'hip_stand_move_factor',
                             'cType': 'VAR_FLOAT',
                             'iPercent': 1,
                             'cInit': '0',
                             'iSyncType': 1,
                             'cDesc': 'HIP,\xe7\xab\x99\xe7\xab\x8b,\xe7\xa7\xbb\xe5\x8a\xa8'
                             },
   'attr_vampire_factor_human': {'cKey': 'attr_vampire_factor_human',
                                 'cType': 'VAR_FLOAT',
                                 'iPercent': 1,
                                 'cInit': '0',
                                 'iSyncType': 0,
                                 'cDesc': '\xe4\xbc\xa4\xe5\xae\xb3\xe5\x90\xb8\xe8\xa1\x80\xe7\xb3\xbb\xe6\x95\xb0,\xe4\xb8\x93\xe5\xaf\xb9\xe4\xba\xba'
                                 },
   'attr_vampire_factor_mecha': {'cKey': 'attr_vampire_factor_mecha',
                                 'cType': 'VAR_FLOAT',
                                 'iPercent': 1,
                                 'cInit': '0',
                                 'iSyncType': 0,
                                 'cDesc': '\xe4\xbc\xa4\xe5\xae\xb3\xe5\x90\xb8\xe8\xa1\x80\xe7\xb3\xbb\xe6\x95\xb0,\xe4\xb8\x93\xe5\xaf\xb9\xe6\x9c\xba\xe7\x94\xb2'
                                 },
   'weapon_heat_dec_factor': {'cKey': 'weapon_heat_dec_factor',
                              'cType': 'VAR_FLOAT',
                              'iPercent': 1,
                              'cInit': '0',
                              'iSyncType': 1,
                              'cDesc': '\xe6\xad\xa6\xe5\x99\xa8\xe6\x95\xa3\xe7\x83\xad\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                              },
   'super_jump_vspeed_add': {'cKey': 'super_jump_vspeed_add',
                             'cType': 'VAR_FLOAT',
                             'iPercent': 1,
                             'cInit': '0',
                             'iSyncType': 0,
                             'cDesc': '\xe5\xbc\xb9\xe8\xb7\xb3\xe5\x8f\xb0\xe5\x9e\x82\xe7\x9b\xb4\xe5\x88\x9d\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                             },
   'accumulate_gun_factor': {'cKey': 'accumulate_gun_factor',
                             'cType': 'VAR_FLOAT',
                             'iPercent': 1,
                             'cInit': '0',
                             'iSyncType': 1,
                             'cDesc': '\xe6\xad\xa6\xe5\x99\xa8\xe8\x93\x84\xe5\x8a\x9b\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90',
                             'fExtremum': 1
                             },
   'weapon_interval_factor': {'cKey': 'weapon_interval_factor',
                              'cType': 'VAR_FLOAT',
                              'iPercent': 1,
                              'cInit': '0',
                              'iSyncType': 1,
                              'cDesc': '\xe6\xad\xa6\xe5\x99\xa8\xe5\xbc\x80\xe7\x81\xab\xe9\x97\xb4\xe9\x9a\x94\xe5\x8a\xa0\xe6\x88\x90',
                              'fExtremum': 1
                              },
   'weak_hit_factor': {'cKey': 'weak_hit_factor',
                       'cType': 'VAR_FLOAT',
                       'iPercent': 1,
                       'cInit': '0',
                       'iSyncType': 1,
                       'cDesc': '\xe5\xbc\xb1\xe7\x82\xb9\xe9\xa2\x9d\xe5\xa4\x96\xe5\xa2\x9e\xe4\xbc\xa4'
                       },
   'armor_factor': {'cKey': 'armor_factor',
                    'cType': 'VAR_FLOAT',
                    'iPercent': 1,
                    'cInit': '0',
                    'iSyncType': 1,
                    'cDesc': '\xe6\x8a\xa4\xe7\x94\xb2\xe5\x8f\x98\xe5\x8c\x96\xe6\xaf\x94\xe4\xbe\x8b'
                    },
   'armor_add': {'cKey': 'armor_add',
                 'cType': 'VAR_FLOAT',
                 'iPercent': 1,
                 'cInit': '0',
                 'iSyncType': 1,
                 'cDesc': '\xe6\x8a\xa4\xe7\x94\xb2\xe5\x8f\x98\xe5\x8c\x96\xe5\x8a\xa0\xe5\x87\x8f'
                 },
   'armor_pierce_factor': {'cKey': 'armor_pierce_factor',
                           'cType': 'VAR_FLOAT',
                           'iPercent': 1,
                           'cInit': '0',
                           'iSyncType': 1,
                           'cDesc': '\xe6\x8a\xa4\xe7\x94\xb2\xe7\xa9\xbf\xe9\x80\x8f\xe7\xb3\xbb\xe6\x95\xb0'
                           },
   'crit_prate_pos_1': {'cKey': 'crit_prate_pos_1',
                        'cType': 'VAR_FLOAT',
                        'iPercent': 1,
                        'cInit': '0',
                        'iSyncType': 0,
                        'cDesc': '\xe4\xb8\xbb\xe6\xad\xa6\xe5\x99\xa8\xe6\x9a\xb4\xe5\x87\xbb\xe6\xa6\x82\xe7\x8e\x87'
                        },
   'crit_prate_pos_2': {'cKey': 'crit_prate_pos_2',
                        'cType': 'VAR_FLOAT',
                        'iPercent': 1,
                        'cInit': '0',
                        'iSyncType': 0,
                        'cDesc': '\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe6\x9a\xb4\xe5\x87\xbb\xe6\xa6\x82\xe7\x8e\x87'
                        },
   'crit_dmg_add_factor': {'cKey': 'crit_dmg_add_factor',
                           'cType': 'VAR_FLOAT',
                           'iPercent': 1,
                           'cInit': '0',
                           'iSyncType': 0,
                           'cDesc': '\xe6\x9a\xb4\xe5\x87\xbb\xe4\xbc\xa4\xe5\xae\xb3\xe5\x80\x8d\xe7\x8e\x87\xe5\x8a\xa0\xe6\x88\x90'
                           },
   'recover_limit_factor': {'cKey': 'recover_limit_factor',
                            'cType': 'VAR_FLOAT',
                            'iPercent': 1,
                            'cInit': '0',
                            'iSyncType': 0,
                            'cDesc': '\xe6\x81\xa2\xe5\xa4\x8d\xe8\xa1\x80\xe9\x87\x8f\xe4\xb8\x8a\xe9\x99\x90\xe7\xb3\xbb\xe6\x95\xb0'
                            },
   'mecha_speed_up_factor': {'cKey': 'mecha_speed_up_factor',
                             'cType': 'VAR_FLOAT',
                             'iPercent': 1,
                             'cInit': '0',
                             'iSyncType': 0,
                             'cDesc': '\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90',
                             'fExtremum': 1
                             },
   'mecha_cure_item_add_factor': {'cKey': 'mecha_cure_item_add_factor',
                                  'cType': 'VAR_FLOAT',
                                  'iPercent': 1,
                                  'cInit': '0',
                                  'iSyncType': 1,
                                  'cDesc': '\xe6\x9c\xba\xe7\x94\xb2\xe5\x9b\x9e\xe8\xa1\x80\xe9\x81\x93\xe5\x85\xb7\xe5\x8a\xa0\xe6\x88\x90'
                                  },
   'mecha_heal_time': {'cKey': 'mecha_heal_time',
                       'cType': 'VAR_FLOAT',
                       'iPercent': 1,
                       'cInit': '-1',
                       'iSyncType': 0,
                       'cDesc': '\xe8\x84\xb1\xe6\x88\x98\xe6\x81\xa2\xe5\xa4\x8d\xe6\x97\xb6\xe9\x97\xb4'
                       },
   'mecha_heal_interval': {'cKey': 'mecha_heal_interval',
                           'cType': 'VAR_FLOAT',
                           'iPercent': 1,
                           'cInit': '-1',
                           'iSyncType': 0,
                           'cDesc': '\xe8\xa1\x80\xe9\x87\x8f\xe6\x81\xa2\xe5\xa4\x8d\xe9\x97\xb4\xe9\x9a\x94'
                           },
   'mecha_heal_hp': {'cKey': 'mecha_heal_hp',
                     'cType': 'VAR_INT',
                     'iPercent': 1,
                     'cInit': '0',
                     'iSyncType': 0,
                     'cDesc': '\xe8\xa1\x80\xe9\x87\x8f\xe6\x81\xa2\xe5\xa4\x8d\xe9\x87\x8f'
                     },
   'mecha_shield_add_factor': {'cKey': 'mecha_shield_add_factor',
                               'cType': 'VAR_FLOAT',
                               'iPercent': 1,
                               'cInit': '0',
                               'iSyncType': 0,
                               'cDesc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\x8a\xa4\xe7\x9b\xbe\xe5\x8a\xa0\xe6\x88\x90\xe7\xb3\xbb\xe6\x95\xb0',
                               'fExtremum': 1000
                               },
   'mecha_shield_add': {'cKey': 'mecha_shield_add',
                        'cType': 'VAR_FLOAT',
                        'iPercent': 1,
                        'cInit': '0',
                        'iSyncType': 0,
                        'cDesc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\x8a\xa4\xe7\x9b\xbe\xe5\x8a\xa0\xe6\x88\x90',
                        'fExtremum': 1000
                        },
   'mecha_shield_defense_factor': {'cKey': 'mecha_shield_defense_factor',
                                   'cType': 'VAR_FLOAT',
                                   'iPercent': 1,
                                   'cInit': '0',
                                   'iSyncType': 0,
                                   'cDesc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\x8a\xa4\xe7\x9b\xbe\xe5\x87\x8f\xe4\xbc\xa4\xe7\xb3\xbb\xe6\x95\xb0'
                                   },
   'mecha_shield_recover_factor': {'cKey': 'mecha_shield_recover_factor',
                                   'cType': 'VAR_FLOAT',
                                   'iPercent': 1,
                                   'cInit': '0',
                                   'iSyncType': 0,
                                   'cDesc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\x8a\xa4\xe7\x9b\xbe\xe6\x81\xa2\xe5\xa4\x8d\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90',
                                   'fExtremum': 4.0
                                   },
   'mecha_fuel_recover_factor': {'cKey': 'mecha_fuel_recover_factor',
                                 'cType': 'VAR_FLOAT',
                                 'iPercent': 1,
                                 'cInit': '0',
                                 'iSyncType': 1,
                                 'cDesc': '\xe6\x9c\xba\xe7\x94\xb2\xe7\x87\x83\xe6\x96\x99\xe6\x81\xa2\xe5\xa4\x8d\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90',
                                 'fExtremum': 5
                                 },
   'skill_4_recover_factor': {'cKey': 'skill_4_recover_factor',
                              'cType': 'VAR_FLOAT',
                              'iPercent': 1,
                              'cInit': '0',
                              'iSyncType': 1,
                              'cDesc': '\xe6\x88\x98\xe6\x9c\xaf\xe6\x8a\x80\xe8\x83\xbd\xe6\x81\xa2\xe5\xa4\x8d\xe9\x80\x9f\xe5\xba\xa6',
                              'fExtremum': 3
                              },
   'skill_2_recover_factor': {'cKey': 'skill_2_recover_factor',
                              'cType': 'VAR_FLOAT',
                              'iPercent': 1,
                              'cInit': '0',
                              'iSyncType': 1,
                              'cDesc': '\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe6\x8a\x80\xe8\x83\xbd\xe6\x81\xa2\xe5\xa4\x8d\xe9\x80\x9f\xe5\xba\xa6',
                              'fExtremum': 3
                              },
   'tmp_skill_4_recover_factor': {'cKey': 'tmp_skill_4_recover_factor',
                                  'cType': 'VAR_FLOAT',
                                  'iPercent': 1,
                                  'cInit': '0',
                                  'iSyncType': 1,
                                  'cDesc': '\xe4\xb8\xb4\xe6\x97\xb6\xe6\x88\x98\xe6\x9c\xaf\xe6\x8a\x80\xe8\x83\xbd\xe6\x81\xa2\xe5\xa4\x8d\xe9\x80\x9f\xe5\xba\xa6',
                                  'fExtremum': 3
                                  },
   'tmp_skill_2_recover_factor': {'cKey': 'tmp_skill_2_recover_factor',
                                  'cType': 'VAR_FLOAT',
                                  'iPercent': 1,
                                  'cInit': '0',
                                  'iSyncType': 1,
                                  'cDesc': '\xe4\xb8\xb4\xe6\x97\xb6\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe6\x8a\x80\xe8\x83\xbd\xe6\x81\xa2\xe5\xa4\x8d\xe9\x80\x9f\xe5\xba\xa6',
                                  'fExtremum': 3
                                  },
   'max_fuel_factor': {'cKey': 'max_fuel_factor',
                       'cType': 'VAR_FLOAT',
                       'iPercent': 1,
                       'cInit': '0',
                       'iSyncType': 1,
                       'cDesc': '\xe7\x87\x83\xe6\x96\x99\xe5\x80\xbc\xe4\xb8\x8a\xe9\x99\x90\xe5\x8a\xa0\xe6\x88\x90',
                       'fExtremum': 100
                       },
   'damage_factor_pos_1': {'cKey': 'damage_factor_pos_1',
                           'cType': 'VAR_FLOAT',
                           'iPercent': 1,
                           'cInit': '0',
                           'iSyncType': 0,
                           'cDesc': '\xe4\xb8\xbb\xe6\xad\xa6\xe5\x99\xa8\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90',
                           'fExtremum': 0.6
                           },
   'damage_factor_pos_2': {'cKey': 'damage_factor_pos_2',
                           'cType': 'VAR_FLOAT',
                           'iPercent': 1,
                           'cInit': '0',
                           'iSyncType': 0,
                           'cDesc': '\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90',
                           'fExtremum': 0.6
                           },
   'vehicle_speed_up_factor': {'cKey': 'vehicle_speed_up_factor',
                               'cType': 'VAR_FLOAT',
                               'iPercent': 1,
                               'cInit': '0',
                               'iSyncType': 2,
                               'cDesc': '\xe5\xb0\x8f\xe9\xb8\xa1\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90'
                               },
   'mecha_max_body_turn_speed_factor': {'cKey': 'mecha_max_body_turn_speed_factor',
                                        'cType': 'VAR_FLOAT',
                                        'iPercent': 1,
                                        'cInit': '0',
                                        'iSyncType': 1,
                                        'cDesc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\x9c\x80\xe5\xa4\xa7\xe8\xbd\xac\xe4\xbd\x93\xe9\x80\x9f\xe5\xba\xa6\xe5\x8a\xa0\xe6\x88\x90',
                                        'fExtremum': 0.6
                                        },
   'enable_weapon_max_accumulate_8016': {'cKey': 'enable_weapon_max_accumulate_8016',
                                         'cType': 'VAR_INT',
                                         'iPercent': 0,
                                         'cInit': '0',
                                         'iSyncType': 1,
                                         'cDesc': '8016\xe6\x9c\xba\xe7\x94\xb2\xe6\xad\xa6\xe5\x99\xa8\xe5\x88\x9d\xe5\xa7\x8b\xe6\x9c\x80\xe5\xa4\xa7\xe8\x93\x84\xe5\x8a\x9b'
                                         },
   'weapon_radius_add_factor_8016': {'cKey': 'weapon_radius_add_factor_8016',
                                     'cType': 'VAR_FLOAT',
                                     'iPercent': 1,
                                     'cInit': '0',
                                     'iSyncType': 1,
                                     'cDesc': '8016\xe6\x9c\xba\xe7\x94\xb2\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe5\x8d\x8a\xe5\xbe\x84\xe6\x8f\x90\xe5\x8d\x87',
                                     'fExtremum': 1
                                     },
   'weapon_power_add_factor_8016': {'cKey': 'weapon_power_add_factor_8016',
                                    'cType': 'VAR_FLOAT',
                                    'iPercent': 1,
                                    'cInit': '0',
                                    'iSyncType': 1,
                                    'cDesc': '8016\xe6\x9c\xba\xe7\x94\xb2\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe5\xa8\x81\xe5\x8a\x9b\xe6\x8f\x90\xe5\x8d\x87',
                                    'fExtremum': 1
                                    },
   'bond_mecha_out_shield_add_factor': {'cKey': 'bond_mecha_out_shield_add_factor',
                                        'cType': 'VAR_FLOAT',
                                        'iPercent': 1,
                                        'cInit': '0',
                                        'iSyncType': 0,
                                        'cDesc': '\xe5\xa4\xa9\xe8\xb5\x8b-\xe6\x9c\xba\xe7\x94\xb2\xe5\xa4\x96\xe5\xb1\x82\xe6\x8a\xa4\xe7\x9b\xbe\xe5\x8a\xa0\xe6\x88\x90\xe7\xb3\xbb\xe6\x95\xb0',
                                        'fExtremum': 0.9
                                        },
   'early_power_factor_pos_1': {'cKey': 'early_power_factor_pos_1',
                                'cType': 'VAR_FLOAT',
                                'iPercent': 1,
                                'cInit': '0',
                                'iSyncType': 0,
                                'cDesc': '\xe6\x8f\x90\xe5\x89\x8d\xe8\xae\xa1\xe7\xae\x97\xe7\x9a\x84\xe4\xb8\xbb\xe6\xad\xa6\xe5\x99\xa8\xe5\xa2\x9e\xe4\xbc\xa4\xe7\xb3\xbb\xe6\x95\xb0',
                                'fExtremum': 0.6
                                },
   'weapon_power_add_factor_8021': {'cKey': 'weapon_power_add_factor_8021',
                                    'cType': 'VAR_FLOAT',
                                    'iPercent': 1,
                                    'cInit': '0',
                                    'iSyncType': 1,
                                    'cDesc': '8021\xe6\x9c\xba\xe7\x94\xb2\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe8\xbf\x91\xe6\x88\x98\xe5\xa8\x81\xe5\x8a\x9b\xe6\x8f\x90\xe5\x8d\x87',
                                    'fExtremum': 1
                                    },
   'sec_weapon_pierce_cnt_8021': {'cKey': 'sec_weapon_pierce_cnt_8021',
                                  'cType': 'VAR_INT',
                                  'iPercent': 0,
                                  'cInit': '0',
                                  'iSyncType': 1,
                                  'cDesc': '8021\xe5\x89\x91\xe6\xb0\x94\xe7\xa9\xbf\xe9\x80\x8f\xe6\xac\xa1\xe6\x95\xb0'
                                  },
   'sec_weapon_range_factor_8021': {'cKey': 'sec_weapon_range_factor_8021',
                                    'cType': 'VAR_FLOAT',
                                    'iPercent': 1,
                                    'cInit': '0',
                                    'iSyncType': 1,
                                    'cDesc': '8021\xe6\x9c\xba\xe7\x94\xb2\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe6\x8c\xa5\xe7\xa0\x8d\xe8\xb7\x9d\xe7\xa6\xbb\xe6\x8f\x90\xe5\x8d\x87'
                                    },
   'ground_clearance_damage_factor': {'cKey': 'ground_clearance_damage_factor',
                                      'cType': 'VAR_FLOAT',
                                      'iPercent': 1,
                                      'cInit': '0',
                                      'iSyncType': 0,
                                      'cDesc': '\xe7\xa6\xbb\xe5\x9c\xb0\xe8\xb7\x9d\xe7\xa6\xbb\xe5\xa2\x9e\xe4\xbc\xa4',
                                      'fExtremum': 1
                                      },
   'extra_trigger_collsion_factor': {'cKey': 'extra_trigger_collsion_factor',
                                     'cType': 'VAR_FLOAT',
                                     'iPercent': 1,
                                     'cInit': '0',
                                     'iSyncType': 2,
                                     'cDesc': '\xe8\xbf\x91\xe7\x88\x86\xe8\x8c\x83\xe5\x9b\xb4(8025)',
                                     'fExtremum': 1
                                     },
   'attr_add_exclusive_mecha_dmg': {'cKey': 'attr_add_exclusive_mecha_dmg',
                                    'cType': 'VAR_FLOAT',
                                    'iPercent': 1,
                                    'cInit': '0',
                                    'iSyncType': 1,
                                    'cDesc': '\xe9\xa9\xbe\xe9\xa9\xb6\xe4\xb8\x93\xe5\xb1\x9e\xe6\x9c\xba\xe7\x94\xb2\xe4\xbc\xa4\xe5\xae\xb3\xe6\x8f\x90\xe5\x8d\x87'
                                    },
   'attr_add_dmg_to_same_mecha': {'cKey': 'attr_add_dmg_to_same_mecha',
                                  'cType': 'VAR_FLOAT',
                                  'iPercent': 1,
                                  'cInit': '0',
                                  'iSyncType': 1,
                                  'cDesc': '\xe5\xaf\xb9\xe7\x9b\xb8\xe5\x90\x8c\xe7\x9a\x84\xe6\x9c\xba\xe7\x94\xb2\xe4\xbc\xa4\xe5\xae\xb3\xe6\x8f\x90\xe5\x8d\x87'
                                  },
   'skill_4_fuel_cost_factor': {'cKey': 'skill_4_fuel_cost_factor',
                                'cType': 'VAR_FLOAT',
                                'iPercent': 1,
                                'cInit': '0',
                                'iSyncType': 1,
                                'cDesc': '\xe6\x88\x98\xe6\x9c\xaf\xe6\x8a\x80\xe8\x83\xbd\xe7\x87\x83\xe6\x96\x99\xe6\xb6\x88\xe8\x80\x97',
                                'fExtremum': 1
                                },
   'skill_4_dmg_factor': {'cKey': 'skill_4_dmg_factor',
                          'cType': 'VAR_FLOAT',
                          'iPercent': 1,
                          'cInit': '0',
                          'iSyncType': 1,
                          'cDesc': '\xe6\x88\x98\xe6\x9c\xaf\xe6\x8a\x80\xe8\x83\xbd\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90'
                          },
   'vampire_factor_pos_1': {'cKey': 'vampire_factor_pos_1',
                            'cType': 'VAR_FLOAT',
                            'iPercent': 1,
                            'cInit': '0',
                            'iSyncType': 1,
                            'cDesc': '\xe4\xb8\xbb\xe6\xad\xa6\xe5\x99\xa8\xe5\x90\xb8\xe8\xa1\x80\xe5\x8a\xa0\xe6\x88\x90'
                            },
   'skill_fuel_cost_factor': {'cKey': 'skill_fuel_cost_factor',
                              'cType': 'VAR_FLOAT',
                              'iPercent': 1,
                              'cInit': '0',
                              'iSyncType': 1,
                              'cDesc': '\xe6\x8a\x80\xe8\x83\xbd\xe6\xb6\x88\xe8\x80\x97\xe7\x87\x83\xe6\x96\x99\xe5\x9b\xa0\xe5\xad\x90\xef\xbc\x881-tmp\xef\xbc\x89\xef\xbc\x8c\xe6\x8c\x87\xe5\xae\x9askill id\xe6\x9d\xa5\xe6\x94\xb9\xe4\xb8\xaa\xe5\x88\xab\xe6\x8a\x80\xe8\x83\xbd\xe7\x9a\x84\xe6\xb6\x88\xe8\x80\x97',
                              'fExtremum': 1
                              },
   'base_pve_atk_factor': {'cKey': 'base_pve_atk_factor',
                           'cType': 'VAR_FLOAT',
                           'iPercent': 1,
                           'cInit': '0',
                           'iSyncType': 0,
                           'cDesc': 'PVE\xe6\x94\xbb\xe5\x87\xbb\xe5\x8a\x9b\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94\xe5\x8a\xa0\xe6\x88\x90'
                           },
   'base_pve_atk_add': {'cKey': 'base_pve_atk_add',
                        'cType': 'VAR_FLOAT',
                        'iPercent': 1,
                        'cInit': '0',
                        'iSyncType': 0,
                        'cDesc': 'PVE\xe6\x94\xbb\xe5\x87\xbb\xe5\x8a\x9b\xe5\x9b\xba\xe5\xae\x9a\xe5\x80\xbc\xe5\x8a\xa0\xe6\x88\x90'
                        },
   'fire_spd_debuff_reduce_factor': {'cKey': 'fire_spd_debuff_reduce_factor',
                                     'cType': 'VAR_FLOAT',
                                     'iPercent': 1,
                                     'cInit': '0',
                                     'iSyncType': 1,
                                     'cDesc': '\xe5\x87\x8f\xe8\xbd\xbb\xe6\xad\xa6\xe5\x99\xa8\xe5\xbc\x80\xe7\x81\xab\xe6\x97\xb6\xe7\x9a\x84\xe9\x80\x9f\xe5\xba\xa6\xe5\x87\x8f\xe7\xbc\x93\xe6\x95\x88\xe6\x9e\x9c',
                                     'fExtremum': 1
                                     },
   'auto_aim_distance_up_factor': {'cKey': 'auto_aim_distance_up_factor',
                                   'cType': 'VAR_FLOAT',
                                   'iPercent': 1,
                                   'cInit': '0',
                                   'iSyncType': 1,
                                   'cDesc': '\xe8\x87\xaa\xe7\x9e\x84\xe8\x8c\x83\xe5\x9b\xb4\xe6\x8f\x90\xe5\x8d\x87\xe5\x80\xbc\xef\xbc\x88\xe4\xb8\x8e\xe6\x9f\x90\xe6\xad\xa6\xe5\x99\xa8ID\xe7\xbb\x91\xe5\xae\x9a\xef\xbc\x89'
                                   },
   'mecha_recoil_up_sub_factor': {'cKey': 'mecha_recoil_up_sub_factor',
                                  'cType': 'VAR_FLOAT',
                                  'iPercent': 1,
                                  'cInit': '0',
                                  'iSyncType': 1,
                                  'cDesc': '\xe6\x9c\xba\xe7\x94\xb2\xe6\x9e\xaa\xe6\xa2\xb0\xe5\x90\x8e\xe5\x9d\x90\xe5\x8a\x9b\xe7\x9a\x84\xe5\x87\x8f\xe8\xbd\xbb\xe5\x80\xbc',
                                  'fExtremum': 1
                                  },
   'next_crit_prate_pos_1': {'cKey': 'next_crit_prate_pos_1',
                             'cType': 'VAR_FLOAT',
                             'iPercent': 1,
                             'cInit': '0',
                             'iSyncType': 0,
                             'cDesc': '\xe4\xb8\x8b\xe4\xb8\x80\xe5\x8f\x91\xe4\xb8\xbb\xe6\xad\xa6\xe5\x99\xa8\xe7\x9a\x84\xe6\x9a\xb4\xe5\x87\xbb\xe7\x8e\x87'
                             },
   'weapon_pierce_cnt': {'cKey': 'weapon_pierce_cnt',
                         'cType': 'VAR_INT',
                         'iPercent': 0,
                         'cInit': '0',
                         'iSyncType': 0,
                         'cDesc': '\xe6\xad\xa6\xe5\x99\xa8\xe7\xa9\xbf\xe9\x80\x8f\xe6\xac\xa1\xe6\x95\xb0\xe5\x8a\xa0\xe6\x88\x90'
                         },
   'mecha_steal_fuel_factor': {'cKey': 'mecha_steal_fuel_factor',
                               'cType': 'VAR_FLOAT',
                               'iPercent': 1,
                               'cInit': '0',
                               'iSyncType': 0,
                               'cDesc': '\xe7\xaa\x83\xe5\x8f\x96\xe7\x87\x83\xe6\x96\x99buff\xe6\x95\x88\xe7\x8e\x87\xe5\x8a\xa0\xe6\x88\x90\xe7\xb3\xbb\xe6\x95\xb0',
                               'fExtremum': 1
                               },
   'total_angle_sub_rate': {'cKey': 'total_angle_sub_rate',
                            'cType': 'VAR_FLOAT',
                            'iPercent': 1,
                            'cInit': '0',
                            'iSyncType': 2,
                            'cDesc': '\xe5\x87\x8f\xe5\xb0\x8f\xe6\xad\xa6\xe5\x99\xa8\xe5\xad\x90\xe5\xbc\xb9\xe6\x89\xa9\xe6\x95\xa3\xe8\xa7\x92\xe5\xba\xa6'
                            },
   'fuel_regtime_dec_factor': {'cKey': 'fuel_regtime_dec_factor',
                               'cType': 'VAR_FLOAT',
                               'iPercent': 1,
                               'cInit': '0',
                               'iSyncType': 1,
                               'cDesc': '\xe7\x87\x83\xe6\x96\x99\xe5\x9b\x9e\xe5\xa4\x8d\xe5\xbb\xb6\xe8\xbf\x9f\xe6\x97\xb6\xe9\x97\xb4\xe7\xbc\xa9\xe5\x87\x8f\xe5\x9b\xa0\xe5\xad\x90',
                               'fExtremum': 1
                               },
   'fuel_cost_factor': {'cKey': 'fuel_cost_factor',
                        'cType': 'VAR_FLOAT',
                        'iPercent': 1,
                        'cInit': '0',
                        'iSyncType': 1,
                        'cDesc': '\xe9\x80\x9a\xe7\x94\xa8\xe7\x87\x83\xe6\x96\x99\xe6\xb6\x88\xe8\x80\x97\xe5\x9b\xa0\xe5\xad\x90'
                        },
   'pve_element_factor': {'cKey': 'pve_element_factor',
                          'cType': 'VAR_FLOAT',
                          'iPercent': 1,
                          'cInit': '0',
                          'iSyncType': 1,
                          'cDesc': ''
                          },
   'pve_weak_hit_crit_prate': {'cKey': 'pve_weak_hit_crit_prate',
                               'cType': 'VAR_FLOAT',
                               'iPercent': 1,
                               'cInit': '0',
                               'iSyncType': 0,
                               'cDesc': 'pve\xe5\xbc\xb1\xe7\x82\xb9\xe9\xa2\x9d\xe5\xa4\x96\xe6\x9a\xb4\xe5\x87\xbb\xe7\x8e\x87'
                               },
   'sub_weapon_pellet_num': {'cKey': 'sub_weapon_pellet_num',
                             'cType': 'VAR_INT',
                             'iPercent': 0,
                             'cInit': '0',
                             'iSyncType': 0,
                             'cDesc': '\xe5\x89\xaf\xe5\xbc\xb9\xe7\x9a\x84\xe6\x95\xa3\xe5\xbc\xb9\xe6\x95\xb0\xef\xbc\x88PVE\xe6\xb8\xa1\xe9\xb8\xa6\xef\xbc\x89'
                             },
   'tactic_skill_crit_prate': {'cKey': 'tactic_skill_crit_prate',
                               'cType': 'VAR_FLOAT',
                               'iPercent': 1,
                               'cInit': '0',
                               'iSyncType': 0,
                               'cDesc': ''
                               },
   'grenade_max_distance_add_factor': {'cKey': 'grenade_max_distance_add_factor',
                                       'cType': 'VAR_FLOAT',
                                       'iPercent': 0,
                                       'cInit': '0',
                                       'iSyncType': 1,
                                       'cDesc': '\xe6\x8a\x95\xe6\x8e\xb7\xe7\x89\xa9\xe6\x9c\x80\xe5\xa4\xa7\xe9\xa3\x9e\xe8\xa1\x8c\xe8\xb7\x9d\xe7\xa6\xbb\xe5\x8a\xa0\xe6\x88\x90'
                                       },
   'phantom_add_cnt_8023': {'cKey': 'phantom_add_cnt_8023',
                            'cType': 'VAR_INT',
                            'iPercent': 0,
                            'cInit': '0',
                            'iSyncType': 0,
                            'cDesc': '\xe5\xa4\xa7\xe6\xa0\x93\xe5\x89\xaf\xe6\xad\xa6\xe5\x99\xa8\xe5\xb9\xbb\xe5\xbd\xb1\xe9\xa2\x9d\xe5\xa4\x96\xe4\xb8\xaa\xe6\x95\xb0'
                            }
   }
import six
MP_TYPE = {'VAR_INT': int,
   'VAR_FLOAT': float
   }
attr_dict = {}
attr_sync_dict = {}
for key, val in six.iteritems(data):
    type_name = val['cType']
    attr_dict[key] = MP_TYPE[type_name](val['cInit'])
    attr_sync_dict[key] = val['iSyncType']

def has_define_attr(attr_name):
    return attr_name in attr_sync_dict


def get_attr_sync_type--- This code section failed: ---

1015       0  LOAD_GLOBAL           0  'attr_sync_dict'
           3  LOAD_ATTR             1  'get'
           6  LOAD_ATTR             1  'get'
           9  CALL_FUNCTION_2       2 
          12  RETURN_VALUE     
          -1  RETURN_LAST      

Parse error at or near `CALL_FUNCTION_2' instruction at offset 9


def get_init_attr_val(key, default=0):
    if key not in attr_dict:
        return default
    return attr_dict[key]


def get_init_attr(bdict):
    d = {}
    d.update(attr_dict)
    return d


def get_attr_extremum(key):
    if key not in data:
        return None
    else:
        return data[key].get('fExtremum', None)