# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gevent/observe_event.py
from __future__ import absolute_import
from common.event.event_base import regist_event
EVENT_LIST = [
 'on_item_data_changed_event',
 'on_agent_coin_changed_event',
 'on_get_capsule_event',
 'on_clothes_data_changed_event',
 'on_pick_up_clothing_event',
 'on_armor_damage_event',
 'on_weapon_data_switched_event',
 'on_wpbar_switch_cur_event',
 'on_weapon_mode_switched',
 'on_reload_bullet_event',
 'on_cancel_reload_event',
 'disable_change_weapon_cancel_reload_ui_appearance',
 'on_begin_roll_event',
 'on_end_roll_event',
 'on_throw_enent',
 'on_skate_hp_changed',
 'on_observer_control_target_changed',
 'on_observer_aim_spread_changed',
 'on_leave_state_event',
 'on_observer_enter_state_event',
 'on_observer_action_move',
 'on_observer_action_move_stop',
 'on_observer_attack_start',
 'on_observer_attack_end',
 'on_observer_load_bullet',
 'observer_aim_gun_fire_sfx',
 'cam_aim_animation_info',
 'cam_aim_post_animation',
 'cam_aim_post_add_animation',
 'cam_aim_clear_gis_cache',
 'cam_aim_get_animator',
 'on_update_observer_like_data_event',
 'on_gun_loading_event',
 'on_cancel_gun_loading_event',
 'on_observer_pick_up_weapon',
 'on_observer_weapon_deleted',
 'on_observer_weapon_bullet_num_changed',
 'on_observer_join_mecha',
 'on_observer_leave_mecha',
 'on_player_global_leave_mecha',
 'on_observer_global_join_mecha',
 'on_observer_global_join_mecha_start',
 'on_observer_global_leave_mecha_start',
 'on_observer_global_killer_camera',
 'on_target_kill_mecha_event',
 'in_parachute_mecha_event',
 'out_parachute_mecha_event',
 'on_observer_try_use_drug',
 'on_observer_charging_event',
 'on_observer_state_change_cd',
 'on_observer_occupy_change_process',
 'on_observer_pick_up_others_event',
 'on_observer_success_aim_event',
 'on_observer_quit_aim_event',
 'on_observer_acummulate',
 'on_observer_fire',
 'on_observer_stop_auto_fire',
 'on_observer_num_changed',
 'on_be_like_num_changed',
 'on_observer_poison_status_changed',
 'on_target_observer_num_changed',
 'on_meow_coin_change_event']
regist_event(EVENT_LIST)