# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/common_const/homeland_const.py
_reload_all = True
HOMELAND_MAX_BLOCK_COUNT = 400
HOMELAND_MAX_MESSAGE_COUNT = 2
HOMELAND_MAX_BLOCK_PULL_COUNT = 20
HOMELAND_INIT_BLOCK_COUNT = 12
HOMELAND_MAX_MSG_LENGTH = 200
HOMELAND_MAX_THUMBS_COUNT = 20000
HOMELAND_HEAT_VISIT = 1
HOMELAND_HEAT_MESSAGE = 1
HOMELAND_HEAT_DAILY_LOGIN = 5
HOMELAND_HEAT_DAILY_LIMIT = 200
HOMELAND_REQUEST_NEW_MESSAGE_BLOCK = 1
HOMELAND_REQUEST_REPLAY_MESSAGE = 2
HOMELAND_REQUEST_INTRODUCE = 3
HOMELAND_REQUEST_DELETE_MESSAGE_BLOCK = 4
HOMELAND_REQUEST_PULL_MESSAGE_BLOCK_BY_RANGE = 5
HOMELAND_REQUEST_PULL_MESSAGE_BLOCK_BY_LOWER_LIMIT = 6
HOMELAND_REQUEST_PULL_MESSAGE_BLOCK_BY_HIGHER_LIMIT = 7
HOMELAND_REQUEST_MODIFY_MESSAGE = 8
HOMELAND_REQUEST_INIT_HOMEPAGE = 9
HOMELAND_REQUEST_DELETE_MESSAGE = 10
HOMELAND_REQUEST_THUMB = 11
HOMELAND_REQUEST_CANCEL_THUMB = 12
HOMELAND_REQUEST_PULL_MESSAGE_BODY = 13
HOMELAND_REQUEST_PULL_MESSAGE_BODY_BY_HIGHER_LIMIT = 14
HOMELAND_GAME_ONLY_REQUEST = set([HOMELAND_REQUEST_NEW_MESSAGE_BLOCK])
FORBIDDEN_REQ_LIST = set([HOMELAND_REQUEST_NEW_MESSAGE_BLOCK, HOMELAND_REQUEST_REPLAY_MESSAGE, HOMELAND_REQUEST_INTRODUCE])
LEFT_MESSAGE = 1
REPLY_MESSAGE = 2
HOMELAND_REPLAY_REACH_MAX_BLOCK_COUNT = 1
HOMELAND_REPLAY_UNDER_MAINTENANCE = 2
HOMELAND_REPLAY_FORBIDDEN = 3
HOMELAND_REPLAY_FORBIDDEN_STRANGER = 4
HOMELAND_REPLAY_FORBIDDEN_ALL = 5
HOMELAND_REPLAY_MSG = {HOMELAND_REPLAY_REACH_MAX_BLOCK_COUNT: 81920,
   HOMELAND_REPLAY_UNDER_MAINTENANCE: 609130,
   HOMELAND_REPLAY_FORBIDDEN: 611610,
   HOMELAND_REPLAY_FORBIDDEN_STRANGER: 611657,
   HOMELAND_REPLAY_FORBIDDEN_ALL: 635267
   }
HOMELAND_CONF_BLACKLIST_LIMIT = 30
HOMELAND_CONF_BEING_BLOCK_LIMIT = 1000
HOMELAND_SPEECH_CTRL_FIELDS = {'lv': 1,
   'create_time': 1
   }
HOMELAND_WINNING_MSG = {3: [
     72033, 72039],
   5: [
     72034, 72040],
   10: [
      72035, 72041]
   }
HOMELAND_DEFAULT_WINNING_MSG = 72033
HOMELAND_EX_WINNING_MSG = [72036, 72042]