# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gevent/message_event.py
from __future__ import absolute_import
from common.event.event_base import regist_event
EVENT_LIST = [
 'message_refresh_friends',
 'message_refresh_one_friend',
 'message_refresh_friend_apply',
 'message_refresh_friend_search',
 'message_refresh_friend_recommend',
 'message_receive_friend_msg',
 'message_receive_friend_msg_read',
 'message_receive_self_msg',
 'message_refresh_email_list',
 'message_get_reward',
 'message_del_email',
 'message_read_email',
 'message_send_friend_gold_gift',
 'message_on_friend_gold_gift',
 'message_recv_friend_gold_gift',
 'message_refresh_contact_group',
 'message_refresh_contact_chat_time',
 'message_on_player_role_head',
 'message_on_player_role_head_photo',
 'message_on_player_wish_derbis_info',
 'message_on_player_simple_inf',
 'message_on_player_detail_inf',
 'message_on_players_detail_inf',
 'message_on_player_stat_inf',
 'message_on_player_history_game_result',
 'message_on_player_chat_background_item',
 'message_on_add_chat_item',
 'message_on_regeo_location',
 'message_on_get_nearby_req_info',
 'message_on_get_neighbor_player',
 'message_respond_set_adcode',
 'message_on_set_rank_title',
 'message_on_rank_data',
 'message_on_region_rank_data',
 'message_on_region_my_rank_data',
 'message_on_pve_rank_data',
 'message_on_rank_percent_data',
 'message_on_mine_pve_rank_data',
 'message_generate_rank_data',
 'message_on_seperate_my_rank_data',
 'message_on_luck_rank_like_data',
 'message_update_global_stat',
 'message_update_global_reward_receive',
 'message_on_enlist_verify',
 'message_on_enlist_verify_gift',
 'message_on_enlist_reward',
 'message_on_enlist_my',
 'message_on_enlist_score',
 'message_refresh_language_redpoint',
 'message_facebook_friends',
 'message_social_friends',
 'message_social_coins',
 'message_refresh_intimacy_data',
 'message_refresh_intimacy_msg',
 'message_on_intimacy_event',
 'message_intimacy_operation_fail',
 'message_relation_build_success',
 'message_on_spec_enlist_verify',
 'message_on_spec_enlist_verify_gift',
 'message_on_spec_enlist_reward',
 'message_on_spec_enlist_my',
 'message_on_spec_enlist_score',
 'message_on_newbie_enlist_verify',
 'message_on_update_newbie_enlist_newbie_score',
 'message_on_receive_newbie_enlist_bind_reward',
 'message_on_newbie_enlist_succ',
 'message_on_update_newbie_enlist_team_score',
 'message_on_receive_newbie_enlist_reward_ret',
 'on_pickable_item_limit_change',
 'on_notify_rematch',
 'on_show_main_rank_model',
 'on_show_main_rank_cur_model',
 'on_show_pve_rank_model',
 'on_change_pve_rank_page_config',
 'on_change_pve_rank_condition',
 'on_switch_pve_rank_player_cnt',
 'message_pve_pass_info',
 'on_pve_rank_show_self_model']
regist_event(EVENT_LIST)