# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/data/hot_key_config_catalog.py
_reload_all = True
CATALOG_DICT = {'1': [
       'switch_big_map',
       'pick_thing',
       'scene_interaction',
       'switch_scoredetails',
       'lock_move_rocker',
       'move_forward',
       'move_backward',
       'move_left',
       'move_right',
       'run',
       'free_sight',
       'tdm_open_weapon',
       'toggle_pc_hotkey_hint',
       'human_fire',
       'human_aim',
       'human_reload',
       'human_jump'],
   '3': [
       'mecha_sub',
       'mecha_rush',
       'mecha_extra_skill',
       'first_sp_module_skill',
       'second_sp_module_skill',
       'mecha_special_skill'],
   '2': [
       'switch_battle_bag',
       'switch_scavenge_battle_bag',
       'choose_death_rogue',
       'human_roll',
       'human_squat',
       'switch_to_gun_1',
       'switch_to_gun_2',
       'switch_to_gun_3',
       'switch_to_uzi',
       'summon_call_mecha',
       'switch_gun_mode',
       'summon_call_mecha_confirm',
       'give_up_battle',
       'open_quick_summon_preview'],
   '5': [
       'use_cur_item',
       'open_drug_panel',
       'use_cur_throw_item',
       'open_throw_panel'],
   '4': [
       'get_off_skateboard_or_vehicle',
       'switch_seat',
       'reload',
       'car_rush',
       'car_transform'],
   '7': [
       'switch_setting_ui',
       'cancel_action',
       'switch_pc_mode'],
   '6': [
       'switch_mic',
       'switch_speaker',
       'open_fight_chat_dialog',
       'switch_scene_mark',
       'double_mark_item',
       'switch_interaction',
       'show_spectate_info',
       'mark_item',
       'interact_with_pet']
   }
CONFLICT_CATALOG_DICT = {1: [
     'switch_big_map',
     'pick_thing',
     'scene_interaction',
     'switch_scoredetails',
     'lock_move_rocker',
     'move_forward',
     'move_backward',
     'move_left',
     'move_right',
     'run',
     'free_sight',
     'tdm_open_weapon',
     'toggle_pc_hotkey_hint',
     'human_fire',
     'human_reload',
     'human_jump'],
   2: [
     'switch_battle_bag',
     'switch_scavenge_battle_bag',
     'choose_death_rogue',
     'human_aim',
     'human_roll',
     'human_squat',
     'switch_to_gun_1',
     'switch_to_gun_2',
     'switch_to_gun_3',
     'switch_to_uzi',
     'summon_call_mecha',
     'use_cur_throw_item',
     'open_throw_panel',
     'switch_gun_mode',
     'summon_call_mecha_confirm',
     'give_up_battle',
     'open_quick_summon_preview'],
   3: [
     'mecha_sub',
     'mecha_rush',
     'mecha_extra_skill',
     'first_sp_module_skill',
     'second_sp_module_skill',
     'mecha_special_skill'],
   4: [
     'get_off_skateboard_or_vehicle',
     'switch_seat',
     'reload'],
   5: [
     'use_cur_item',
     'open_drug_panel'],
   6: [
     'switch_mic',
     'switch_speaker',
     'open_fight_chat_dialog',
     'switch_scene_mark',
     'double_mark_item',
     'switch_interaction',
     'show_spectate_info',
     'mark_item',
     'interact_with_pet'],
   7: [
     'switch_setting_ui',
     'cancel_action',
     'switch_pc_mode'],
   41: [
      'car_rush',
      'car_transform']
   }