# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/item/item_const.py
from __future__ import absolute_import
_reload_all = True
MAX_CURRENCY = 999999999
ITEM_NO_AVATER_EQUIP = (200001, 999999)
DEFAULT_STYLE = 0
LOD_H = 'h'
LOD_L = 'l'
LOD_L1 = 'l1'
LOD_L2 = 'l2'
LOD_L3 = 'l3'
LOD_L4 = 'l4'
INV_VIEW_ALL_ITEM = 0
INV_VIEW_KNAPSACK = 1
INV_VIEW_HEAD = 2
INV_VIEW_BODICE = 3
INV_VIEW_BOTTOMS = 4
INV_VIEW_HEAD_FRAME = 5
INV_VIEW_HEAD_PHOTO = 6
INV_VIEW_HOUSE_WALL_PICTURE = 7
INV_VIEW_RED_POINT_ITEM = 8
INV_VIEW_CHAT_ITEM = 9
INV_STAT_PERMANENT_SKIN = 1
INV_STAT_MECHA_SKIN = 2
INV_STAT_ROLE_SKIN = 3
INV_STAT_OTHER_SKIN = 4
INV_STAT_MECHA_SLEVEL_SKIN = 5
INV_STAT_ROLE_SLEVEL_SKIN = 6
INV_STAT_OTHER_SLEVEL_SKIN = 7
INV_STAT_EMOTICON = 8
INV_STAT_SPRAY = 9
INV_STAT_GESTURE = 10
INV_STAT_HEAD_PHOTO = 11
INV_STAT_HEAD_FRAME = 12
INV_STAT_TALKING = 13
ITEM_CIRCULATION_UNLIMIT = 0
ITEM_CIRCULATION_TRADE = 1
ITEM_CIRCULATION_LOCK = 2
ITEM_CIRCULATION_UNTRADE = 3
DRESS_POS_FACE = '0'
DRESS_POS_HEAD = '1'
DRESS_POS_BODICE = '2'
DRESS_POS_BOTTOMS = '3'
DRESS_POS_ARMOR = '4'
DRESS_POS_BAG = '5'
DRESS_POS_SUIT = '6'
DRESS_POS_HAIR = '7'
DRESS_POS_SKIN = '8'
DRESS_POS_HEADWEAR = '9'
DRESS_POS_FACEWEAR = '10'
DRESS_POS_MASK = '11'
DRESS_POS_SHIELD = '12'
DRESS_POS_ARM = '13'
DRESS_POS_LEG = '14'
DRESS_POS_HAND = '15'
BATTLE_DRESS_LIST = (
 DRESS_POS_HEAD, DRESS_POS_ARMOR, DRESS_POS_LEG)
MECHA_SHIELD_POS = DRESS_POS_HEAD
CLOTHING_DRESS_PARTS = frozenset([
 DRESS_POS_FACE,
 DRESS_POS_HEAD,
 DRESS_POS_BODICE,
 DRESS_POS_BOTTOMS,
 DRESS_POS_ARMOR,
 DRESS_POS_BAG,
 DRESS_POS_SUIT,
 DRESS_POS_HAIR,
 DRESS_POS_SKIN,
 DRESS_POS_HEADWEAR,
 DRESS_POS_FACEWEAR,
 DRESS_POS_MASK,
 DRESS_POS_ARM,
 DRESS_POS_LEG,
 DRESS_POS_HAND])
CLOTHING_OFF_PARTS = frozenset([
 DRESS_POS_HEAD,
 DRESS_POS_ARMOR,
 DRESS_POS_BAG,
 DRESS_POS_SUIT,
 DRESS_POS_MASK,
 DRESS_POS_ARM,
 DRESS_POS_LEG])
CLOTHING_LOGIC_PARTS = {DRESS_POS_MASK: (
                  DRESS_POS_MASK, DRESS_POS_HEAD),
   DRESS_POS_HEAD: (
                  DRESS_POS_HEAD, DRESS_POS_MASK)
   }
SCENEBOX_ST_CLOSED = 1
SCENEBOX_ST_OPENED = 2
MESH_CONF = {DRESS_POS_FACE: 'face',
   DRESS_POS_HEAD: 'wgg_head',
   DRESS_POS_BODICE: 'bodice',
   DRESS_POS_BOTTOMS: 'bottoms',
   DRESS_POS_ARMOR: 'wgg_up',
   DRESS_POS_BAG: 'bag',
   DRESS_POS_SUIT: 'suit',
   DRESS_POS_HAIR: 'hair',
   DRESS_POS_HEADWEAR: 'headhair',
   DRESS_POS_FACEWEAR: 'facewear',
   DRESS_POS_MASK: 'mask',
   DRESS_POS_ARM: 'wgg_arm',
   DRESS_POS_LEG: 'wgg_down',
   DRESS_POS_HAND: 'arm'
   }
DEFAULT_MECHA_SHINY = -1
FASHION_KEY = 'fashion'
MECHA_FASHION_KEY = 'mecha_fashion'
INF_ROLE_FASHION_KEY = 'role_fashion'
MECHA_LOBBY_INFO = 'lobby_mecha_info'
MECHA_LOBBY_FASHION_KEY = 'lobby_mecha_fashion_id'
MECHA_LOBBY_ID_KEY = 'lobby_mecha_id'
MECHA_LOBBY_CUSTOM_SKIN_KEY = 'lobby_mecha_custom_skin'
MECHA_LOBBY_WP_SFX_KEY = 'lobby_mecha_weapon_sfx'
MECHA_LOBBY_POSE = 'lobby_mecha_pose'
MECHA_LOBBY_POSE_SHOW = 'apply_mecha_pose_show'
FASHION_POS_SUIT = '0'
FASHION_POS_WEAPON_SFX = '1'
FASHION_POS_HEADWEAR = '2'
FASHION_POS_BACK = '3'
FASHION_POS_SUIT_2 = '4'
FASHION_POS_FACE = '5'
FASHION_POS_WAIST = '6'
FASHION_POS_LEG = '7'
FASHION_POS_HAIR = '8'
FASHION_POS_ARM = '9'
FASHION_OTHER_PENDANT_LIST = (
 FASHION_POS_FACE, FASHION_POS_WAIST, FASHION_POS_LEG, FASHION_POS_HAIR, FASHION_POS_ARM)
FASHION_MAIN_PENDANT_LIST = (FASHION_POS_HEADWEAR, FASHION_POS_BACK, FASHION_POS_SUIT_2)
FASHION_DECORATION_TYPE_LIST = FASHION_MAIN_PENDANT_LIST + FASHION_OTHER_PENDANT_LIST
FASHION_DRESS_PARTS = frozenset([
 FASHION_POS_SUIT,
 FASHION_POS_HEADWEAR,
 FASHION_POS_BACK,
 FASHION_POS_SUIT_2,
 FASHION_POS_FACE,
 FASHION_POS_WAIST,
 FASHION_POS_LEG,
 FASHION_POS_HAIR,
 FASHION_POS_ARM])
FASHION_PLAN_POS_NAME = 0
FASHION_PLAN_POS_SUB_SKIN = 1
FASHION_PLAN_POS_HEADWEAR = 2
FASHION_PLAN_POS_BACK = 3
FASHION_PLAN_POS_SUIT_2 = 4
FASHION_PLAN_POS_FACE = 5
FASHION_PLAN_POS_WAIST = 6
FASHION_PLAN_POS_LEG = 7
FASHION_PLAN_POS_HAIR = 8
FASHION_PLAN_POS_ARM = 9
PLAN_POS_TO_TAG = {FASHION_PLAN_POS_SUB_SKIN: FASHION_POS_SUIT,
   FASHION_PLAN_POS_HEADWEAR: FASHION_POS_HEADWEAR,
   FASHION_PLAN_POS_BACK: FASHION_POS_BACK,
   FASHION_PLAN_POS_SUIT_2: FASHION_POS_SUIT_2,
   FASHION_PLAN_POS_FACE: FASHION_POS_FACE,
   FASHION_PLAN_POS_WAIST: FASHION_POS_WAIST,
   FASHION_PLAN_POS_LEG: FASHION_POS_LEG,
   FASHION_PLAN_POS_HAIR: FASHION_POS_HAIR,
   FASHION_PLAN_POS_ARM: FASHION_POS_ARM
   }
PLAN_POS_LIST = [
 FASHION_PLAN_POS_NAME,
 FASHION_PLAN_POS_SUB_SKIN,
 FASHION_PLAN_POS_HEADWEAR,
 FASHION_PLAN_POS_BACK,
 FASHION_PLAN_POS_SUIT_2,
 FASHION_PLAN_POS_FACE,
 FASHION_PLAN_POS_WAIST,
 FASHION_PLAN_POS_LEG,
 FASHION_PLAN_POS_HAIR,
 FASHION_PLAN_POS_ARM]
ACC_TAG = (
 (
  'Head', FASHION_POS_HEADWEAR),
 (
  'Bag', FASHION_POS_BACK),
 (
  'PendantSuit', FASHION_POS_SUIT_2),
 (
  'Face', FASHION_POS_FACE),
 (
  'Waist', FASHION_POS_WAIST),
 (
  'Leg', FASHION_POS_LEG),
 (
  'HairAccessories', FASHION_POS_HAIR),
 (
  'Arm', FASHION_POS_ARM))
FPOS_2_TAG_STR = {FASHION_POS_HEADWEAR: 'Head',
   FASHION_POS_BACK: 'Bag',
   FASHION_POS_SUIT_2: 'PendantSuit',
   FASHION_POS_FACE: 'Face',
   FASHION_POS_WAIST: 'Waist',
   FASHION_POS_LEG: 'Leg',
   FASHION_POS_HAIR: 'HairAccessories',
   FASHION_POS_ARM: 'Arm'
   }
REPEL_FASHION = {FASHION_POS_HEADWEAR: frozenset([FASHION_POS_SUIT_2]),
   FASHION_POS_BACK: frozenset([FASHION_POS_SUIT_2]),
   FASHION_POS_FACE: frozenset([FASHION_POS_SUIT_2]),
   FASHION_POS_WAIST: frozenset([FASHION_POS_SUIT_2]),
   FASHION_POS_LEG: frozenset([FASHION_POS_SUIT_2]),
   FASHION_POS_HAIR: frozenset([FASHION_POS_SUIT_2]),
   FASHION_POS_ARM: frozenset([FASHION_POS_SUIT_2]),
   FASHION_POS_SUIT_2: frozenset([FASHION_POS_HEADWEAR, FASHION_POS_BACK, FASHION_POS_FACE, FASHION_POS_WAIST, FASHION_POS_LEG, FASHION_POS_HAIR, FASHION_POS_ARM])
   }
FASHION_POS_2_DESC_TEXT_ID = {FASHION_POS_HEADWEAR: 81229,
   FASHION_POS_BACK: 860099,
   FASHION_POS_LEG: 860101,
   FASHION_POS_FACE: 860098,
   FASHION_POS_WAIST: 860100,
   FASHION_POS_HAIR: 81704,
   FASHION_POS_SUIT_2: 81228,
   FASHION_POS_ARM: 81926
   }
BATTLE_EFFECT_KILL = '0'
BATTLE_EFFECT_SET = frozenset([
 BATTLE_EFFECT_KILL])
WEAPON_FASHION_PART_SUIT = '0'
WEAPON_FASHION_PARTS = frozenset([
 WEAPON_FASHION_PART_SUIT])
ITEM_NO_DIAMOND = 50101002
ITEM_NO_GOLD = 50101003
ITEM_NO_EXP = 50102001
ITEM_NO_YUANBAO = 50101001
ITEM_NO_PROFICIENCY = 50102002
ITEM_NO_VITALITY = 50102003
ITEM_NO_NEWBIEPASS_POINT = 50102005
ITEM_NO_BATTLEPASS_POINT = 50102006
ITEM_NO_RETURN_VITALITY = 50102011
ITEM_NO__MODULE_SLOT_ACTIVE = 48000901
ITEM_NO_MECHA_FRAGMENT = 50101207
ITEM_NO_WEEKEND_POINT = 70400046
ITEM_NO_FLASH_POINT = 50101109
ITEM_NO_CLAN_POINT = 50103001
ITEM_NO_ROOM_POINT = 50303001
ITEM_NO_ROOM_COMPETITION_CARD = 50303003
ITEM_NO_MILA_BOW = 50930212
ITEM_NO_SKIN_PRINCESS_MILA = '201001544'
ITEM_NO_DUANWU_ZONGZI = 50600029
ITEM_NO_LOW_FIREWORKS = 1059960
ITEM_NO_MID_FIREWORKS = 1059961
ITEM_NO_ALL_FIREWORKS = [1059960, 1059961, 1059962, 1059963, 1059964, 1059965]
ITEM_NORMAL_CALL = 1059966
ITEM_SUPER_CALL = 1059967
ITEM_SWITCH_NORMAL_CALL = 1059968
ITEM_SWITCH_SUPER_CALL = 1059973
VIRTUAL_ITEMS = frozenset([
 ITEM_NO_DIAMOND,
 ITEM_NO_GOLD,
 ITEM_NO_EXP,
 ITEM_NO_YUANBAO,
 ITEM_NO_PROFICIENCY,
 ITEM_NO_VITALITY,
 ITEM_NO_NEWBIEPASS_POINT,
 ITEM_NO_BATTLEPASS_POINT,
 ITEM_NO_RETURN_VITALITY,
 ITEM_NO_CLAN_POINT])
ITEM_NO_RENAME_CARD = 50500002
ITEM_NO_PROF_CARD_LIST = [50301001, 50301003]
ITEM_NO_PET_PROF_CARD_LIST = [71700008, 71700009]
ITEM_NO_TASK_CARD = 50500008
ITEM_NO_CLAN_CREATE_TICKET = 50103002
ITEM_NO_CLAN_CHANGE_NAME = 50103003
ITEM_NO_TECH_POINT = 50104008
ITEM_NO_CB_POINT = 70100006
ITEM_NO_DAN_CARD = 50101208
ITEM_NO_MECHA_CHOOSE_CARD = 50101196
YUEAKA_EXP_ADD = 0.1
YUEAKA_GOLD_ADD = 0.1
WEEKLYCARD_GOLD_ADD = 0.3
WEEKLYCARD_EXP_ADD = 0.1
RETURN_BONUS_ADD = 0.25
RARE_DEGREE_0 = 0
RARE_DEGREE_1 = 1
RARE_DEGREE_2 = 2
RARE_DEGREE_3 = 3
RARE_DEGREE_4 = 4
RARE_DEGREE_5 = 5
RARE_DEGREE_6 = 6
RARE_DEGREE_7 = 7
SORTED_RARE_DEGREE_LIST = [
 RARE_DEGREE_7, RARE_DEGREE_5, RARE_DEGREE_6, RARE_DEGREE_4, RARE_DEGREE_3, RARE_DEGREE_2, RARE_DEGREE_1, RARE_DEGREE_0]
EXCHANGE_TICKETS = {50101007: 3800,
   50101006: 480,
   50101005: 128,
   50101004: 30
   }
EXTRA_EXCHANGE_RATE = 0.05
ITEM_NO_EXCHANGE_TICKET = 50101008
DEFAULT_HEAD_FRAME = 30100000
DEFAULT_HEAD_PHOTO = 30218001
DEFAULT_HEAD_CHAT_FRAME = 30500000
DEFAULT_WALL_PICTURE = 207011011
DEFAULT_KILL_EFFECT = 203000000
DEFAULT_LOBBY_BGM = 603000014
DEFAULT_LOBBY_SKIN = 210010000
DEFAULT_LOBBY_SKYBOX = 208000000
DEFAULT_GLIDE_EFFECT = 203900000
SKATE_LOBBY_ITEM_NO = '1051666'
TRANSFORM_LOBBY_ITEM_NO = '1051667'
AIRCRAFT_SKIN_TYPE = '1051668'

def DEFAULT_FLAG_FRAME():
    if G_IS_NA_PROJECT:
        return 31000001
    else:
        return 31000002


DEFAULT_EMOTE_PACK = (0, 30800001, 30800002, 30800003)
ITEM_NO_DEADBOX = 6000
ITEM_NO_ATTACHABLE = 6008
ITEM_NO_MECHATRANS = 8501
ITEM_NO_MECHABATTERY = 9902
ITEM_NO_MECHAENERGY = 9903
ITEM_NO_MECHA_SLOW_DRUG = 9904
ITEM_NO_ACE_STAR = 1668
ITEM_NO_JIANPAO = 1663
ITEM_NO_NIGHTMARE_BOX = 6027
ITEM_NO_SNOW_BOX = 6031
ITEM_NO_ROGUE_BOX = 6044
ITEM_NO_GRANBELM_RUNE = 9934
ITEM_NO_BACK_HOME = 9935
ITEM_NO_DOGTAG = 9936
ITEM_NO_HACKER_RUNE = 9938
ITEM_NO_GRANBELM_PARADROP_1 = 6039
ITEM_NO_GRANBELM_PARADROP_2 = 6040
ITEM_NO_GRANHACK_PARADROP_1 = 6004
ITEM_NO_GRANHACK_PARADROP_2 = 6005
ITEM_NO_FFA_PARADROP = 6035
LOBBY_ITEM_NO_MEOW_COIN = 1059951
ITEM_NO_MEOW_COIN = 9951
ITEM_NO_MAGIC_COIN = 9957
ITEM_GULOG_REVIVE_COIN = 9958
ITEM_NO_ENERGY_BOX = 10006001
ITEM_NO_BREAK_BOX = 10006002
RISE_PARADROP = (
 ITEM_NO_GRANBELM_PARADROP_1,
 ITEM_NO_GRANBELM_PARADROP_2,
 ITEM_NO_FFA_PARADROP)
NEW_MODEL_SHADOW_MALE = 'character/11/shadow/11_shadow.gim'
NEW_MODEL_SHADOW_FEMALE = 'character/11/shadow/11_shadow.gim'
VIRTUAL_WEAPONS = set([ITEM_NO_JIANPAO])
SHOW_SFX = 'show_sfx'
NONE_WHITE = 0
NORMAL_GREEN = 1
SUPERIOR_BLUE = 2
EPIC_PURPLE = 3
LEGEND_GILD = 4
LEGEND_COLORFUL = 5
TDM_DARK = 6
HUMAN_ITEM = 1
MEHCA_ITEM = 2
HUMAN_MEHCA_ITEM = 3
RANK_COLOR = {NONE_WHITE: '#SW',NORMAL_GREEN: '#SG',
   SUPERIOR_BLUE: '#SB',
   EPIC_PURPLE: '#SP',
   LEGEND_GILD: '#SO'
   }
from logic.gcommon.const import NEOX_UNIT_SCALE
FLOAT_HEIGHT = 0.6 * NEOX_UNIT_SCALE
ITEM_DROP_ANIM_NONE = 0
ITEM_DROP_ANIM_MECH = 1
ITEM_DROP_ANIM_BOX = 2
ITEM_UNGAIN = 0
ITEM_UNRECEIVED = 1
ITEM_RECEIVED = 2
ITEM_SHOW_TYPE_AUTO = None
ITEM_SHOW_TYPE_NONE = 0
ITEM_SHOW_TYPE_ITEM = 1
ITEM_SHOW_TYPE_MODEL = 2
ITEM_SHOW_TYPE_WEAPON_OR_VEHICLE = 3
LIMIT_LEVEL_NONE = 0
LIMIT_LEVEL_RED = 1
LIMIT_LEVEL_GOLD = 2
DEFAULT_KILL_EFFECT_ITEM_ID = 203000000
MIN_MECHA_COMPONENT_PAGE_CNT = 1
COMPONENT_SLOT_CNT_PER_PART = 1
MAX_MECHA_COMPONENT_LV = 1
INSCR_ATK = 1
INSCR_FAULT_TOL = 2
INSCR_SURVIVAL = 3
INSCR_RECOVER = 4
INSCR_MOB = 5
INSCR_TACTICAL = 6
VEHICLE_SKIN_SUB_SKATE_BOARD = 1
VEHICLE_SKIN_SUB_VEHICLE = 2
VEHICLE_SKIN_SUB_AIRCRAFT = 3
VEHICLE_SKIN_SUB_DESC_MAP = {VEHICLE_SKIN_SUB_SKATE_BOARD: 530004,
   VEHICLE_SKIN_SUB_VEHICLE: 530002,
   VEHICLE_SKIN_SUB_AIRCRAFT: 530003
   }
ITEM_NO_MOTORCYCLE = 4108
ITEM_NO_REWARDORDER = 9939
MOTORCYCLE_POS_GROUP_SIZE = 5
MOTORCYCLE_GROUP_RANDOM_NUM = 3
MARK_NO_OF_MECHATRANS = 2023
MARK_NO_OF_SKATEBOARD = 2024
MARK_NO_OF_MOTORCYCLE = 2025
MARK_NO_OF_REWARDORDER = 2027
MARK_NO_OF_PREY = 2028
BTN_ST_CAN_RECEIVE = 1
BTN_ST_SHARE = 2
BTN_ST_EXCHANGE = 3
BTN_ST_ONGOING = 4
BTN_ST_RECEIVED = 5
BTN_ST_EXCHANGED = 6
BTN_ST_INACTIVE = 7
BTN_ST_GO = 8
BTN_ST_UNEXCHANGE = 9
BTN_ST_OVERDUE = 10
SUMMER_COMP_CURRENCY_TYPE = 50101077
WINTER_COMP_CURRENCY_TYPE = 50101078
ITEM_NO_PVE_KEY = 70300001
ITEM_NO_CRYSTAL_STONE = 10000099
ITEM_NO_PVE_STORY_DEBRIS = 10007301