# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/cdata/status_cover_config.py
_reload_all = True
from .status_config import *
data = {ST_MOVE: set([ST_RUN, ST_TURN, ST_HELP, ST_SKATE_BRAKE, ST_DISCARD, ST_CELEBRATE]),
   ST_ROLL: set([ST_STAND, ST_CROUCH, ST_JUMP, ST_SHOOT, ST_SWITCH, ST_RELOAD, ST_LOAD, ST_TURN, ST_AIM, ST_PICK, ST_USE_ITEM, ST_HELP, ST_DISCARD, ST_WEAPON_ACCUMULATE, ST_CELEBRATE, ST_SWITCH_WP_MODE]),
   ST_JUMP: set([ST_STAND, ST_CROUCH, ST_PICK, ST_USE_ITEM, ST_HELP, ST_DISCARD, ST_RIGHT_AIM, ST_MECH_EJECTION, ST_CELEBRATE]),
   ST_RELOAD: set([ST_SHOOT, ST_AIM, ST_PICK, ST_DISCARD, ST_WEAPON_ACCUMULATE]),
   ST_SKATE_BRAKE: set([ST_SWIM, ST_SKATE_MOVE]),
   ST_TURN: set([]),
   ST_DOWN: set([ST_STAND, ST_CROUCH, ST_JUMP, ST_SHOOT, ST_MOVE, ST_SWITCH, ST_RELOAD, ST_LOAD, ST_RUN, ST_TURN, ST_AIM, ST_PICK, ST_USE_ITEM, ST_HELP, ST_SWIM, ST_PARACHUTE, ST_FLY, ST_CLIMB, ST_SKATE, ST_SKATE_MOVE, ST_SKATE_BRAKE, ST_DISCARD, ST_ROLL, ST_RIGHT_AIM, ST_MECHA_BOARDING, ST_MECHA_DRIVER, ST_MECHA_PASSENGER, ST_RUSH, ST_WEAPON_ACCUMULATE, ST_MECH_EJECTION, ST_CELEBRATE, ST_SWITCH_WP_MODE, ST_FROZEN]),
   ST_PICK: set([ST_SWITCH, ST_RELOAD, ST_LOAD, ST_PICK, ST_USE_ITEM, ST_DISCARD, ST_RIGHT_AIM, ST_CELEBRATE, ST_SWITCH_WP_MODE]),
   ST_MECH_EJECTION: set([ST_STAND, ST_CROUCH, ST_JUMP, ST_TURN, ST_PICK, ST_USE_ITEM, ST_HELP, ST_SWIM, ST_FLY, ST_CLIMB, ST_DISCARD, ST_ROLL, ST_MECHA_BOARDING, ST_MECHA_DRIVER, ST_MECHA_PASSENGER, ST_RUSH, ST_CELEBRATE]),
   ST_SWITCH_WP_MODE: set([ST_SHOOT, ST_SWITCH, ST_RELOAD, ST_AIM, ST_PICK, ST_USE_ITEM, ST_DISCARD, ST_RIGHT_AIM, ST_WEAPON_ACCUMULATE, ST_CELEBRATE]),
   ST_CELEBRATE: set([ST_STAND]),
   ST_CROUCH: set([ST_STAND, ST_CELEBRATE]),
   ST_SHOOT: set([ST_USE_ITEM, ST_HELP, ST_DISCARD, ST_WEAPON_ACCUMULATE, ST_CELEBRATE]),
   ST_WEAPON_ACCUMULATE: set([ST_USE_ITEM, ST_DISCARD, ST_CELEBRATE]),
   ST_RIGHT_AIM: set([ST_RUN, ST_PICK, ST_CELEBRATE]),
   ST_RUN: set([ST_MOVE, ST_TURN, ST_HELP, ST_SKATE_BRAKE, ST_DISCARD]),
   ST_SWIM: set([ST_STAND, ST_CROUCH, ST_JUMP, ST_SHOOT, ST_SWITCH, ST_RELOAD, ST_LOAD, ST_TURN, ST_AIM, ST_PICK, ST_HELP, ST_PARACHUTE, ST_FLY, ST_SKATE_MOVE, ST_SKATE_BRAKE, ST_DISCARD, ST_RIGHT_AIM, ST_MECHA_DRIVER, ST_MECHA_PASSENGER, ST_WEAPON_ACCUMULATE, ST_CELEBRATE, ST_SWITCH_WP_MODE]),
   ST_PARACHUTE: set([ST_STAND, ST_CROUCH, ST_JUMP, ST_SHOOT, ST_SWITCH, ST_RELOAD, ST_LOAD, ST_TURN, ST_PARACHUTE, ST_DISCARD, ST_RIGHT_AIM, ST_WEAPON_ACCUMULATE, ST_MECH_EJECTION, ST_CELEBRATE, ST_SWITCH_WP_MODE]),
   ST_HELP: set([ST_MOVE, ST_RUN, ST_USE_ITEM, ST_SKATE_BRAKE, ST_DISCARD, ST_RIGHT_AIM, ST_CELEBRATE]),
   ST_SWITCH: set([ST_SHOOT, ST_SWITCH, ST_RELOAD, ST_LOAD, ST_AIM, ST_PICK, ST_USE_ITEM, ST_DISCARD, ST_RIGHT_AIM, ST_WEAPON_ACCUMULATE, ST_CELEBRATE, ST_SWITCH_WP_MODE]),
   ST_STAND: set([ST_CROUCH, ST_FLY, ST_CELEBRATE]),
   ST_MECHA_BOARDING: set([ST_SHOOT, ST_MOVE, ST_RELOAD, ST_LOAD, ST_RUN, ST_AIM, ST_USE_ITEM, ST_HELP, ST_DISCARD, ST_RIGHT_AIM, ST_CELEBRATE]),
   ST_LOAD: set([ST_SHOOT, ST_PICK, ST_DISCARD, ST_WEAPON_ACCUMULATE]),
   ST_DEAD: set([ST_DOWN, ST_STAND, ST_CROUCH, ST_JUMP, ST_SHOOT, ST_MOVE, ST_SWITCH, ST_RELOAD, ST_LOAD, ST_RUN, ST_TURN, ST_AIM, ST_PICK, ST_USE_ITEM, ST_HELP, ST_SWIM, ST_PARACHUTE, ST_FLY, ST_CLIMB, ST_SKATE, ST_SKATE_MOVE, ST_SKATE_BRAKE, ST_DISCARD, ST_ROLL, ST_RIGHT_AIM, ST_MECHA_BOARDING, ST_MECHA_DRIVER, ST_MECHA_PASSENGER, ST_RUSH, ST_WEAPON_ACCUMULATE, ST_MECH_EJECTION, ST_CELEBRATE, ST_SWITCH_WP_MODE, ST_FROZEN]),
   ST_SKATE: set([ST_CROUCH, ST_SWIM, ST_CELEBRATE]),
   ST_FLY: set([ST_MOVE, ST_RUN, ST_TURN, ST_AIM, ST_PICK, ST_HELP, ST_PARACHUTE, ST_DISCARD, ST_RIGHT_AIM, ST_CELEBRATE]),
   ST_FROZEN: set([ST_STAND, ST_CROUCH, ST_JUMP, ST_SHOOT, ST_MOVE, ST_SWITCH, ST_RELOAD, ST_LOAD, ST_RUN, ST_TURN, ST_AIM, ST_PICK, ST_USE_ITEM, ST_HELP, ST_SWIM, ST_PARACHUTE, ST_FLY, ST_CLIMB, ST_SKATE_MOVE, ST_SKATE_BRAKE, ST_DISCARD, ST_ROLL, ST_RIGHT_AIM, ST_RUSH, ST_WEAPON_ACCUMULATE, ST_CELEBRATE, ST_SWITCH_WP_MODE]),
   ST_EMPTY_HAND: set([ST_AIM, ST_WEAPON_ACCUMULATE, ST_CELEBRATE]),
   ST_MECHA_PASSENGER: set([ST_STAND, ST_CROUCH, ST_JUMP, ST_SHOOT, ST_MOVE, ST_SWITCH, ST_RELOAD, ST_LOAD, ST_RUN, ST_TURN, ST_AIM, ST_PICK, ST_USE_ITEM, ST_SWIM, ST_SKATE, ST_SKATE_MOVE, ST_SKATE_BRAKE, ST_RIGHT_AIM, ST_MECHA_DRIVER, ST_MECHA_PASSENGER, ST_MECH_EJECTION, ST_CELEBRATE, ST_SWITCH_WP_MODE]),
   ST_MECHA_DRIVER: set([ST_STAND, ST_CROUCH, ST_JUMP, ST_SHOOT, ST_MOVE, ST_SWITCH, ST_RELOAD, ST_LOAD, ST_RUN, ST_TURN, ST_AIM, ST_PICK, ST_USE_ITEM, ST_SWIM, ST_SKATE, ST_SKATE_MOVE, ST_SKATE_BRAKE, ST_RIGHT_AIM, ST_MECHA_BOARDING, ST_MECHA_DRIVER, ST_MECHA_PASSENGER, ST_MECH_EJECTION, ST_CELEBRATE, ST_SWITCH_WP_MODE]),
   ST_RUSH: set([ST_STAND, ST_CROUCH, ST_JUMP, ST_SHOOT, ST_SWITCH, ST_RELOAD, ST_LOAD, ST_TURN, ST_AIM, ST_PICK, ST_USE_ITEM, ST_HELP, ST_DISCARD, ST_RIGHT_AIM, ST_WEAPON_ACCUMULATE, ST_CELEBRATE, ST_SWITCH_WP_MODE]),
   ST_USE_ITEM: set([ST_RELOAD, ST_LOAD, ST_PICK, ST_DISCARD, ST_RIGHT_AIM, ST_CELEBRATE]),
   ST_SKATE_MOVE: set([ST_CROUCH, ST_HELP, ST_SWIM, ST_SKATE_BRAKE]),
   ST_DISCARD: set([ST_USE_ITEM, ST_CELEBRATE]),
   ST_AIM: set([ST_USE_ITEM, ST_DISCARD, ST_RIGHT_AIM]),
   ST_CLIMB: set([ST_STAND, ST_TURN, ST_RIGHT_AIM, ST_CELEBRATE])
   }

def get_config_sets():
    return data