# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/common_const/weapon_const.py
from __future__ import absolute_import
import six
_reload_all = True
from logic.gcommon.common_const import ui_operation_const as uoc
WEAPON_TYPE_FIST = 1
WEAPON_TYPE_AMMO = 2
WEAPON_TYPE_TOOL = 3
WEAPON_TYPE_THROWABLE = 4
MANUAL_MODE = 3
HALF_AUTO_MODE = 2
AUTO_MODE = 1
BURSTS_FIRE_MODE = 0
SINGLE_FIRE_MODE = 1
CONTROL_MODEL_BEGIN = 1
CONTROL_MODEL_END = 2
CONTROL_MODEL_WEAPON_TYPE_SHOTGUN = 1
CONTROL_MODEL_WEAPON_TYPE_ANTI_MECHA = 2
CONTROL_WEAPON_MANUAL_SNIPER_RIFLE = 3
CONTROL_WEAPON_FAST_AIM_AND_RELEASE_FIRE = 4
CONTROL_WEAPON_AUTO_FAST_AIM_AND_FIRE = 5
INIT_UZI_WEAPON_ID = 1011
RELOAD_ALL = 1
RELOAD_ONE = 2
ITEM_ID_INFINITE_BULLET = 1619
ITEM_ID_LIMITED_BULLET = 1640
ITEM_ID_BULLET_SHOW_MAX_CAP = (
 ITEM_ID_INFINITE_BULLET, ITEM_ID_LIMITED_BULLET)
FIRE_STATE_NONE = 0
FIRE_STATE_READY = 1
FIRE_STATE_CD = 2
FIRE_STATE_RELOAD_EMPTY = 3
FIRE_STATE_RELOAD_LEFT = 4
FIRE_STATE_LOADING = 6
FIRE_STATE_DEPLOY = 7
FIRE_STATE_AIM = 8
FIRE_STATE_QUIT_AIM = 9
FIRE_STATE_RIGHT_AIM = 10
FIRE_STATE_QUIT_RIGHT_AIM = 11
FIRE_STATE_CUSTOM = 12
LENS_NONE = 0
LENS_RED_DOT = 1101
LENS_TWO_MAGNITUDE = 1102
LENS_FOUR_MAGNITUDE = 1103
LENS_MECHA_07 = 1104
LENS_PULSE = 1105
LENS_M82 = 1106
LENS_M4 = 1108
LENS_M14 = 1109
LENS_MECHA_23 = 1407
WP_NONE = 0
WP_PISTOL = 1
WP_SHOTGUN = 2
WP_SUBMACHINE = 3
WP_ASSAULT_RIFLES = 4
WP_SNIPER_RIFLE = 5
WP_GRENADES_GUN = 6
WP_THROWABLE = 7
WP_MELEE = 8
WP_SPELL = 9
WP_GUN_WITH_SHIELD = 10
WP_TRACK_GUN = 11
WP_NAVIGATE_GUN = 12
WP_LASER_SHOOTER = 13
WP_SUMMON_GRENADES_GUN = 14
WP_GRENADES_GROUP_GUN = 15
WP_MULTI_RAY_SHOOT = 16
WP_MULTI_PART_SHOOT = 17
WP_CONVOLUTE_BIRD = 18
WP_TOWER = 19
WP_MULTI_RAY_LASER_SHOOTER = 20
WP_ARROWS_GROUP_GUN = 21
WP_OIL_BOTTLE = 22
WP_TRACK_NAVIGATE_GUN = 23
WP_RAY_GRENADES_GUN = 24
WP_RADIAL_GRENADE_GUN = 25
WP_ARROWS_GUN = 26
WP_GRENADES_CROWD_GUN = 27
WP_SWORD_LIGHT = 28
WP_ATTACHABLE_RADIAL_GRENADES_GUN = 29
WP_COMMON_RADIAL_GRENADES_GUN = 30
WP_FLYING_ATTACH_GRENADES = 31
WP_NAVIGATE_EXTRA_TRIGGER_EXPLODE_GRENADES_GUN = 32
WP_TRACK_NAVIGATE_EXTRA_TRIGGER_EXPLODE_GRENADES_GUN = 33
WP_NAVIGATE_SWORD_LIGHT = 34
WP_CONTINUOUS_LASER = 35
WP_EXTRA_TRIGGER_EXPLODE_GRENADES_GUN = 36
WP_CLUSTER_GRENADE_GUN = 37
WP_RAIN_GRENADE_GUN = 38
WP_AIM_RAY_GRENADES_GUN = 39
WP_ARRAY_BARRAGE = 40
WP_ROUND_BARRAGE = 41
WP_COLUMN_BARRAGE = 42
WP_SPHERE_BARRAGE = 43
WP_TRACK_MISSILE = 44
WP_INFINITE_RADIAL_GRENADES_GUN = 45
WP_SHIRANUI_FAN_GRENADES_GUN = 46
WP_CLAW_GRENADES_GUN = 47
WP_RAY_EXPLOSION_WEAPON_LIST = [
 WP_RAY_GRENADES_GUN]
WP_HEAVY_WEAPON_LIST = [
 WP_SHOTGUN, WP_SUBMACHINE, WP_ASSAULT_RIFLES, WP_SNIPER_RIFLE]
SPECIAL_WEAPON_LIST = [
 WP_GRENADES_GUN, WP_SPELL, WP_GUN_WITH_SHIELD]
AUTO_AIM_WEAPON_LIST = [
 WP_SHOTGUN, WP_SUBMACHINE, WP_ASSAULT_RIFLES, WP_SNIPER_RIFLE, WP_GUN_WITH_SHIELD, WP_NAVIGATE_GUN]
SHOOT_EXPLOSIVE = frozenset((
 WP_GRENADES_GUN,
 WP_TRACK_GUN,
 WP_NAVIGATE_GUN,
 WP_SUMMON_GRENADES_GUN,
 WP_GRENADES_GROUP_GUN,
 WP_CONVOLUTE_BIRD,
 WP_MULTI_PART_SHOOT,
 WP_ARROWS_GROUP_GUN,
 WP_TRACK_NAVIGATE_GUN,
 WP_ARROWS_GUN,
 WP_RADIAL_GRENADE_GUN,
 WP_GRENADES_CROWD_GUN,
 WP_SWORD_LIGHT,
 WP_ATTACHABLE_RADIAL_GRENADES_GUN,
 WP_COMMON_RADIAL_GRENADES_GUN,
 WP_INFINITE_RADIAL_GRENADES_GUN,
 WP_FLYING_ATTACH_GRENADES,
 WP_NAVIGATE_EXTRA_TRIGGER_EXPLODE_GRENADES_GUN,
 WP_TRACK_NAVIGATE_EXTRA_TRIGGER_EXPLODE_GRENADES_GUN,
 WP_EXTRA_TRIGGER_EXPLODE_GRENADES_GUN,
 WP_CLUSTER_GRENADE_GUN,
 WP_RAIN_GRENADE_GUN,
 WP_ARRAY_BARRAGE,
 WP_ROUND_BARRAGE,
 WP_COLUMN_BARRAGE,
 WP_SPHERE_BARRAGE,
 WP_SHIRANUI_FAN_GRENADES_GUN,
 WP_CLAW_GRENADES_GUN))
HUMAN_BAN_AUTO_AIM_IN_PC_MODE_WP_TYPE_SET = {
 WP_SUBMACHINE, WP_ASSAULT_RIFLES, WP_SNIPER_RIFLE, WP_GUN_WITH_SHIELD}
HEAVY_MACHINE_MAX_COUNT = 2
ACCEPTABLE_DEVIATION = 0.05
STEALING_TIME = 0.05
WP_EQUIP_TYPE_HUMAN = 1
WP_EQUIP_TYPE_MECHA = 2
WP_RELOAD_TYPE_ALL = 1
WP_RELOAD_TYPE_ONE = 2
THROWABLE_TRIGGER_TIME = 1
THROWABLE_TRIGGER_COLLISION = 2
THROWABLE_TRIGGER_ENTITY = 3
THROWABLE_TRIGGER_ATTACH = 4
THROWABLE_TRIGGER_CYLINDER = 5
THROWABLE_TRIGGER_BIRD = 6
THROWABLE_TRIGGER_PHOTON_TOWER = 7
THROWABLE_TRIGGER_OIL_BOTTLE = 8
THROWABLE_JUMP_ITEM_DEFAULT = 8203
THROWABLE_JUMP_ITEM_ROCKET = 8205
THROWABLE_JUMP_ITEM_SLASH_JUMP = 8207
THROWABLE_JUMP_ITEM_POISON_JUMP = 803404
THROWABLE_JUMP_ITEM_8034_JUMP = 803406
THROWABLE_ATTACH_TARGET = 1
THROWABLE_ATTACH_SCENE = 2
THROWABLE_PERIOD_ATTACK = 0
THROWABLE_PERIOD_CONVOLUTE = 1
THROWABLE_PERIOD_BACK = 2
THROWABLE_PERIOD_DESTOYED = 3
THROWABLE_DAMAGE_UNHURT = 0
THROWABLE_DAMAGE_COMMON = 1
THROWABLE_DAMAGE_TARGET = 2
THROWABLE_DAMAGE_NO_BLOCK = 3
EXPLOSIVE_CREATE_TYPE_SHOOT = 1
EXPLOSIVE_CREATE_TYPE_THROW = 2
EXPLOSIVE_CREATE_TYPE_SKILL = 3
EXPLOSIVE_CREATE_TYPE_JUMP = 4
EXPLOSIVE_CREATE_TYPE_NOW = 5
SPECIAL_TARGET_GROUP = 1
BULLET_HOLE_LIFE_TIME = 6
BULLET_RIFLE_TYPE = 1
BULLET_SNIPPER_TYPE = 2
BULLET_LASER_TYPE = 3
BULLET_END_POSITION_TYPE = 4
THROWABLE_PART_DAMAGE_DISABLE = 0
THROWABLE_PART_DAMAGE_ENABLE = 1
THROWABLE_PART_DAMAGE_ONLY_MECHA = 2
NO_MULTI_SHAPE = 0
ACCUMULATE_MULTI_SHAPE = 1
COMMON_MULTI_SHAPE = 2
SWITCH_SOCKET_EACH_BULLET = 0
SWITCH_SOCKET_EACH_FIRE = 1
GUN_SHIELD_NONE = 0
GUN_SHIELD_OPEN_CONDITION_ALWAYS = 1
GUN_SHIELD_OPEN_CONDITION_RIGHT_AIM = 2
SLIDER_ADJUST_AIM_TYPES = (
 LENS_FOUR_MAGNITUDE, LENS_MECHA_07, LENS_PULSE, LENS_M82)
aim_type_dict = {LENS_RED_DOT: uoc.SST_AIM_RD_KEY,
   LENS_TWO_MAGNITUDE: uoc.SST_AIM_2M_KEY,
   LENS_FOUR_MAGNITUDE: uoc.SST_AIM_4M_KEY,
   LENS_MECHA_07: uoc.SST_MECHA_07_KEY,
   LENS_PULSE: uoc.SST_AIM_RD_KEY,
   LENS_M82: uoc.SST_AIM_6M_KEY,
   LENS_M4: uoc.SST_AIM_RD_KEY,
   LENS_M14: uoc.SST_AIM_2M_KEY
   }
mecha_aim_len = {LENS_MECHA_23: uoc.SST_AIM_6M_KEY
   }
for aim_len, sst_key in six.iteritems(mecha_aim_len):
    aim_type_dict[aim_len] = sst_key

THROWABLE_HIT_ABSORB_SHIELD = 1
THROWABLE_BALL_STAGE_FLY = 0
THROWABLE_BALL_STAGE_FLOAT = 1
THROWABLE_BALL_STAGE_ATTACH = 2
THROWABLE_BALL_STAGE_DESTROYED = 3
FROZEN_WEAPONS = (10623, 10624)
SNATCHEGG_THROW_ITEM = '10601'
EQUIP_CONDITION_10652 = 1
MAGAZINE_TYPE_NORMAL = 0
MAGAZINE_TYPE_SHARE = 1
MAGAZINE_TYPE_SKILL_NUM = 2
MAGAZINE_TYPE_SKILL_STATE = 3
MAGAZINE_TYPE_HEAT = 4
AUTO_AIM_KIND_UNIQUE = 0
AUTO_AIM_KIND_MULTIPLE = 1
STATE_NONE = 1
STATE_SHOOT = 2
STATE_NORMAL_DEC = 4
STATE_FORCE_DEC = 8
STATE_FORCE_DEC_OVERLOAD = 16
ALL_HEAT_STATE_SET = frozenset((STATE_NONE, STATE_SHOOT, STATE_NORMAL_DEC, STATE_FORCE_DEC, STATE_FORCE_DEC_OVERLOAD))
BAN_SHOOT_STATE = STATE_FORCE_DEC | STATE_FORCE_DEC_OVERLOAD
HEAT_DEC_STATE = STATE_NORMAL_DEC | STATE_FORCE_DEC | STATE_FORCE_DEC_OVERLOAD
SHOOT_FROM_MUZZLE = 0
SHOOT_FROM_CAMERA = 1
SHOOT_FROM_CAMERA_OPTIMIZED = 2
SHOOT_FROM_CAMERA_OPTIMIZED_XZ_ONLY = 3
SHOOT_FROM_CAMERA_OPTIMIZED_Y_ONLY = 4
SHOOT_FROM_CAMERA_OPTIMIZED_XZ_RAISE_Y = 5