# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gutils/pc_ui_utils.py
MOBILE_2_PC_UI_DICT = {'FightChatUI': 'FightChatUIPC',
   'SceneInteractionUI': 'SceneInteractionUIPC',
   'TeamBloodUI': 'TeamBloodUIPC',
   'BattleBuffUI': 'BattleBuffUIPC',
   'ScalePlateUI': 'ScalePlateUIPC',
   'StateChangeUI': 'StateChangeUIPC',
   'BattleRightTopUI': 'BattleRightTopUIPC',
   'MechaUI': 'MechaUIPC',
   'BattleFightCapacity': 'BattleFightCapacityPC',
   'BattleFightMeow': 'BattleFightMeowPC',
   'FightStateUI': 'FightStateUIPC',
   'HpInfoUI': 'HpInfoUIPC',
   'SmallMapUI': 'SmallMapUIPC',
   'MechaHpInfoUI': 'MechaHpInfoUIPC',
   'GMHelperUI': 'GMHelperUIPC',
   'PrepareUI': 'PrepareUIPC',
   'QuickMarkBtn': 'QuickMarkBtnPC',
   'SprayUI': 'SprayUIPC',
   'QuickMarkUI': 'QuickMarkUIPC',
   'WeaponBarSelectUI': 'WeaponBarSelectUIPC',
   'DrugUI': 'DrugUIPC',
   'ThrowRockerUI': 'ThrowRockerUIPC',
   'MechaControlMain': 'MechaControlMainPC',
   'GranbelmRuneConfUI': 'GranbelmRuneConfUIPC',
   'MagicRuneConfUI': 'MagicRuneConfUIPC',
   'BattleAceCoinUI': 'BattleAceCoinUIPC',
   'BigMapUI': 'BigMapUIPC',
   'BagUI': 'BagUIPC',
   'ObserveUI': 'ObserveUIPC',
   'MechaModuleEffectiveUI': 'MechaModuleEffectiveUIPC',
   'RogueGiftTopRightUI': 'RogueGiftTopRightUIPC',
   'MutiOccupySkillUI': 'MutiOccupySkillUIPC',
   'TrainSkillUI': 'TrainSkillUIPC',
   'JudgeObserveUINew': 'JudgeObserveUINewPC',
   'PetInteractUI': 'PetInteractUIPC',
   'PVERadarMapUI': 'PVERadarMapUIPC'
   }
PC_2_MOBILE_UI_DICT = {'BattleAceCoinUIPC': 'BattleAceCoinUI',
   'HpInfoUIPC': 'HpInfoUI',
   'BattleFightCapacityPC': 'BattleFightCapacity',
   'BattleFightMeowPC': 'BattleFightMeow',
   'QuickMarkUIPC': 'QuickMarkUI',
   'ThrowRockerUIPC': 'ThrowRockerUI',
   'StateChangeUIPC': 'StateChangeUI',
   'PrepareUIPC': 'PrepareUI',
   'TeamBloodUIPC': 'TeamBloodUI',
   'BigMapUIPC': 'BigMapUI',
   'SceneInteractionUIPC': 'SceneInteractionUI',
   'MechaUIPC': 'MechaUI',
   'BattleBuffUIPC': 'BattleBuffUI',
   'WeaponBarSelectUIPC': 'WeaponBarSelectUI',
   'FightChatUIPC': 'FightChatUI',
   'SprayUIPC': 'SprayUI',
   'SmallMapUIPC': 'SmallMapUI',
   'ScalePlateUIPC': 'ScalePlateUI',
   'BattleRightTopUIPC': 'BattleRightTopUI',
   'DrugUIPC': 'DrugUI',
   'MechaHpInfoUIPC': 'MechaHpInfoUI',
   'FightStateUIPC': 'FightStateUI',
   'GMHelperUIPC': 'GMHelperUI',
   'GranbelmRuneConfUIPC': 'GranbelmRuneConfUI',
   'MagicRuneConfUIPC': 'MagicRuneConfUI',
   'MechaControlMainPC': 'MechaControlMain',
   'QuickMarkBtnPC': 'QuickMarkBtn',
   'BagUIPC': 'BagUI',
   'ObserveUIPC': 'ObserveUI',
   'MutiOccupySkillUIPC': 'MutiOccupySkillUI',
   'TrainSkillUIPC': 'TrainSkillUI',
   'JudgeObserveUINewPC': 'JudgeObserveUINew',
   'PetInteractUIPC': 'PetInteractUI',
   'PVERadarMapUIPC': 'PVERadarMapUI'
   }