# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/common_utils/bcast_utils.py
from __future__ import absolute_import
import six
E_SET_ROLL_MOVE_DIR = 1
E_SKATE_BEGIN_BRAKE = 2
E_ATK_HIT = 3
E_CTRL_STOP_SWIM = 4
E_SUCCESS_RIGHT_AIM = 5
E_SPRING_EFFECT = 6
E_STOP_RESCUE = 7
E_COVER_THROW_BOMB = 8
E_SET_RUSH_MOVE_DIR = 9
E_ANIM_PHASE = 10
E_TRY_SWITCH = 11
E_OPEN_AIM_CAMERA_ENTER = 12
E_CLIMB_DROP = 13
E_THROW_BOMB = 14
E_TRY_RIGHT_AIM = 15
E_MOVE_ENABLE = 16
E_SHOW_TAIL = 17
E_CHANGE_WATER_INFO = 18
E_SET_CONTROL_TARGET = 19
E_ACTION_MOVE_STOP = 20
E_UPDATE_MONSTER_FIGHT = 22
E_STOP_CAPSULE_ACTION = 23
E_ACTIVE_STATE = 24
E_SHOW_AI_DEBUG = 25
E_ARMOR_ATTACK_END = 26
E_ACTION_CANCEL_RESCUE = 27
E_ACTION_HITED_BY_VEHICLE = 28
E_SWITCH_BEHAVIOR = 29
E_OPEN_AIM_CAMERA_EXIT = 30
E_TRANSFORM = 31
E_AUTO_RELOADING = 32
E_START_BOMB_ROCKER = 33
E_ON_SYNC_BEGIN_JUMP = 34
E_ACTION_SKATE_MOVE_STOP = 35
E_PLAY_WATER_EFFECT_BY_AIM_TYPE = 36
E_CANCEL_THROW_BOMB = 37
E_POST_ACTION = 38
E_CANCEL_RELOAD = 39
E_GUN_ATTACK = 40
E_RELOADING = 41
E_OPEN_AIM_CAMERA = 42
E_ON_GROUND_FINISH = 43
E_OPEN_AIM_CAMERA_ON_FIRE = 45
E_STOP_MECHA_ACTION_SOUND = 46
E_MONSTER_CAST_ACTION = 47
E_SIMULATE_FIRE = 48
E_SEAT_ON_MECHA = 49
E_EQUIP_PARACHUTE = 50
E_SUPPORT_TWIST_YAW = 51
E_CHANGE_FASHION = 52
E_HIT_BY_FORCE = 53
E_SHOW_MUZZLE_FIRE_EFFECT = 54
E_MOVE_FORCE = 55
E_SHOW_MODEL = 56
E_TWIST_YAW_PARAM = 57
E_RESET_ROTATION = 58
E_LEAVE_ATTACHABLE_ENTITY = 59
E_UPBODY_BONE = 61
E_CTRL_STAND = 62
E_ACTION_MOVE_BCAST = 63
E_ACTION_END_SWITCH = 64
E_ITEMUSE_END = 65
E_ON_LOSE_CONNECT = 66
E_SHOW_ONGROUND_SFX = 67
E_POST_EXTERN_ACTION = 68
E_REMOVE_PARACHUTE = 69
E_CTRL_SWIM = 70
E_START_BE_RESCUE = 71
E_TWIST_PITCH_PARAM = 72
E_QUIT_RIGHT_AIM = 73
E_SHOW_BACK_WEAPON_ANIM = 74
E_SHOW_SUB_MESH = 75
E_RESET_STATE = 76
E_PLAY_EFFECT_BY_STATUS = 77
E_CHANGE_MOVE_STATE = 78
E_PLAY_WATER_EFFECT_BY_PATH = 79
E_OFFSET_YAW = 80
E_ACTION_PARA_STOP = 81
E_CTRL_ACCUMULATE = 82
E_ACTION_PARA_TOWARD = 83
E_ACTION_SWITCH_TO_JUMP = 84
E_OPEN_AIM_CAMERA_ANIM = 85
E_SHOW_SYNC_SOCK_TRAJECTORY = 86
E_SHOW_SKILL_HIT_SFX = 87
E_PLAY_MECHA_ACTION_SOUND = 88
E_INSERT_TAIL = 89
E_OPEN_AIM_CAMERA_PLACE = 90
E_HIDE_SUB_MESH = 91
E_CALL_SYNC_METHOD = 92
E_QUIT_AIM = 93
E_LOADING = 94
E_CTRL_ROLL = 95
E_START_CAPSULE_ACTION = 96
E_STOP_AUTO_FIRE = 97
E_ITEMUSE_PRE = 98
E_SHOW_ALL_GUN = 99
E_CLEAR_UP_BODY_ANIM = 100
E_HIDE_JUMP_TRACK = 101
E_ATTACK_START = 102
E_SUCCESS_BOARD = 103
E_DIRECT_ROTATE = 104
E_ACTION_MOVE_STOP_BCAST = 105
S_ATTR_SET = 106
E_ATTACK_END = 107
E_CHONGCI_SYNC = 108
E_SHOW_JUMP_TRACK = 109
E_CHANGE_ANIM_MOVE_DIR = 110
E_START_UP_BODY_ANIM_TICK = 111
E_POST_ADD_ANIMATION = 112
E_CTRL_SKATE = 113
E_PLAY_SKATE_WATER_EFFECT = 114
E_CANCEL_SKATE_STATE = 116
E_START_MOVING = 117
E_SHOW_SYNC_TRAJECTORY = 118
E_MOD_MAX_HP_FACTOR = 119
E_FINISH_SWITCH_GUN = 120
E_FORWARD = 121
E_ON_SAVED = 122
E_COVERL_PUNCH = 123
E_ON_SYNC_SET_JUMP_UPBODY_BLEND = 124
E_STOP_MOVING = 125
E_SYNC_DECIDE_ATTACK_OR_CUT_RUSH = 126
E_SUCCESS_AIM = 127
E_REVIVE = 128
E_CHANGE_JUMP_STATE = 129
E_BEGIN_RESCUE = 130
E_OPEN_AIM_RELOADED = 131
E_SHOW_VISUAL_PATH = 132
E_HIDE_VISUAL_PATH = 133
E_SYNC_MECHA_8003_STATE = 135
E_ENTER_RUN = 136
E_LEAVE_RUN = 137
E_CTRL_RUSH = 138
E_EXECUTE_MECHA_ACTION_SOUND = 139
E_MECHA_CLEAN_LOOP_SOUND = 140
E_DO_REMOVE_PARACHUTE = 141
E_CREATE_SCENE_EFFECT = 142
E_CREATE_MODEL_EFFECT = 143
E_REMOVE_MODEL_EFFECT = 144
E_MECHA_FORCE_CLEAN_LOOP_SOUND = 145
E_SHOW_CD_EFFECT = 146
E_PLAY_SECOND_JUMP_EFFECT = 147
E_SET_SHAKE_ACTION = 148
E_SHOW_AI_STATE = 149
E_JUMP_ANIM_TIME_SCALE = 150
E_LAND = 151
E_CLEAR_BEHAVIOR = 152
E_ACTION_SYNC_RC_RESUME_ROLL = 153
E_SHOW_BALL_GROUND_SFX = 154
E_BALL_CAN_DAMAGE = 155
E_CLEAR_BALL_SFX = 156
E_TRANS_TO_BALL_FINISH = 157
E_SHOW_LIGHT = 158
E_ADD_EMOJI = 165
E_CELEBRATE = 166
E_FIRE_SPELL = 167
E_ATTACK_ACTION_START = 168
E_MONSTER_CAST_SOUND = 170
E_RC_OFFSET = 171
E_CLEAR_RC_OFFSET = 172
E_HOOK_MODEL_START = 173
E_SECOND_WEAPON_ATTACK = 174
E_SHOW_ACCUMULATE_SFX = 175
E_SWITCHED_WP_MODE = 176
E_SWITCH_LETTER_EFFECT = 177
E_SWITCH_FULL_FORCE_EFFECT = 178
E_FORBID_ROTATION = 179
E_TRIGGER_STATE_EFFECT = 181
E_TRIGGER_DISPOSABLE_EFFECT = 182
E_OXRUSH_8015_LOCK_TARGET = 183
E_LOCK_CHAIN_TARGET_8015 = 184
E_OPEN_AIM_CAMERA_RELOAD = 185
E_PARACHUTE_VERTICAL_SPEED_CHANGED = 186
E_CHANGE_ENHANCE_WEAPON_FIRE_8015 = 187
E_UNBIND_ALL_WEAPON = 211
E_REEQUIP_WEAPON = 212
E_ROTATE_TO_VEHICLE = 213
E_ENABLE_ROTATE = 214
E_CHANGE_SKATE_JUMP_STATE = 215
E_POST_SKATE_ACTION = 216
E_POST_BIND_OBJ_ACTION = 217
E_HIDE_ALL_GUN = 219
E_EQUIP_GUN_BY_POS = 220
E_ROTATE_MODEL = 221
E_SKATE_CHANGE_DIR_SOUND = 222
E_CREATE_GUN_MODEL_EFFECT = 223
E_SHOW_FIRESTREAM_SFX = 224
E_PLAY_GUN_FIRE_SFX = 225
E_PLAY_AIM_GUN_FIRE_SFX = 226
E_ACTION_MOVE = 227
E_SYNC_CREATE_VICE_EFFECT = 228
E_CREATE_VICE_END_EFFECT = 229
E_SYNC_UPDATE_VICE_EFFECT = 230
E_SYNC_UPDATE_VICE_HIT = 231
E_CREATE_SMOG_EFFECT = 233
E_SHOW_MAIN_ACC_IDLE_EFFECT = 234
E_SOFT_ENTER_PITCH_MODEL = 235
E_SOFT_EXIT_PITCH_MODEL = 236
E_SYNC_LAUNCH_BOOST_MECHA_POSITION_OFFSET = 237
E_SYNC_LAUNCH_BOOST_MECHA_MOVE_DIR = 238
E_SHOW_TAIL_SFX = 239
E_SET_SUSPEND_RADIAL_WEAPON_POSITION = 240
E_BEGIN_RELOAD = 241
E_8019_SEC_BEGIN = 242
E_8019_SEC_HOLD = 243
E_8019_SEC_POST = 244
E_8019_SEC_END = 245
E_8019_SEC_FULL = 246
E_CREATE_RES_EFFECT = 247
E_REMOVE_RES_EFFECT = 248
E_CACHE_MODEL_ANI_LIST = 249
E_ENABLE_ALIGN_ON_GROUND = 250
E_ENABLE_TWIST_PITCH = 251
E_8021_SHOW_SHOCKWAVE = 252
E_PLAY_MOVE_DUST_TAIL_SFX = 253
E_SET_CAM_EX_ROTATION = 254
E_SET_CAM_EX_TRANSLATION = 255
E_SET_CAM_EX_TARGET_OFFSET = 256
E_CLEAR_CAM_EX_ROTATION = 257
E_CLEAR_CAM_EX_TRANSLATION = 258
E_CLEAR_CAM_EX_TARGET_OFFSET = 259
E_STEALTH_ON = 260
E_8023_OPEN_AIM = 261
E_8023_CLOSE_AIM = 262
E_8023_OPEN_AIM_FIRE = 263
E_REFRESH_AKIMBO_MODEL = 264
E_SHOW_SPHERE_FLAMETHROWER = 265
E_CONTINUOUSSHOOT8027_FIRE = 266
E_CONTINUOUSSHOOT8027_ANIM_START = 267
E_SHOW_WEAPON8027 = 268
E_PLAY_SWITCH_FAIRY_SHAPE_EFFECT = 269
E_PLAY_SWITCH_RABBIT_SHAPE_EFFECT = 270
E_DO_SHOCK_WAVE_START_APPEARANCE = 271
E_DO_SHOCK_WAVE_SPREAD_APPEARANCE = 272
E_DO_SHOCK_WAVE_STOP_APPEARANCE = 273
E_TWIST_YAW = 280
E_SYNC_HIT_SOUND = 281
E_8016_UPDATE_WING_SFX = 282
E_UPDATE_SUICIDE_SCREEN_SFX = 283
E_UPDATE_INTERACTION_NAME = 284
E_ROTATE_WEAPON = 285
E_RESET_ROTATE_WEAPON = 286
E_UPDATE_PHANTOM_STATE = 287
E_REFRESH_WEAPON_STATE = 288
E_SWITCH_WEAPON = 289
E_REFRESH_SUB_MODEL_ANIM = 290
E_PLAY_DASH_EFFECT = 291
E_SHOW_TELEPORT_GUIDE_SFX = 292
E_SHOW_BATTLE_BROADCAST = 293
E_SHOW_GUN_8033 = 294
E_SET_MECAH_MODE = 295
E_SET_GUN_PITCH_AND_YAW_8033 = 296
E_GUN_MODEL_ANI_8033 = 297
E_SHOW_CLAW_TARGET_EFFECT = 298
E_CANCEL_CLAW_TARGET_EFFECT = 299
E_SYNC_HOOK_POS = 300
E_UPDATE_HOOK_STATE = 301
E_SHOW_GHOST_SFX = 302
E_HIDE_GHOST_SFX = 303
E_SHOW_HOOK_END_SFX = 304
E_HIDE_HOOK_END_SFX = 305
E_POST_ANIM_LIST_ACTION = 306
E_SWITCH_MECHA_MODEL = 666
E_PVE_BOSS_ENTER_INVINCIBLE = 901
E_PVE_BOSS_EXIT_INVINCIBLE = 902
E_PVE_BOSS_ENTER_SEC_STAGE = 903
E_PVE_MONSTER_SNIPE_START_PRE = 904
E_PVE_MONSTER_SNIPE_END_PRE = 905
E_PVE_MONSTER_SNIPE_EXIT = 906
E_PVE_MONSTER_SPURT_START_ATK = 907
E_PVE_MONSTER_SPURT_START_BAC = 908
E_PVE_MONSTER_SPURT_EXIT = 909
E_PVE_MONSTER_POUNCE_WARN_SFX = 910
E_PVE_BOSS_ARRAY_BOMB_WARN_SFX = 911
E_PVE_MONSTER_SWEEP_START_ATK = 912
E_PVE_MONSTER_SWEEP_START_BAC = 913
E_PVE_MONSTER_SWEEP_EXIT = 914
E_PVE_BOSS_MULTI_LASER_START_PRE = 915
E_PVE_BOSS_MULTI_LASER_INIT_SINGLE = 916
E_PVE_BOSS_MULTI_LASER_START_BAC = 917
E_PVE_BOSS_MULTI_LASER_EXIT = 918
E_PVE_BOSS_MULTI_LASER_INIT_SPOT = 919
E_PVE_BOSS_BOMB_WARN_SFX = 920
E_PVE_MONSTER_LINK_HEAL_START_HEAL = 921
E_PVE_MONSTER_LINK_HEAL_END_HEAL = 922
E_PVE_MONSTER_MORTAR_START_PRE = 923
E_PVE_MONSTER_MORTAR_START_ATK = 924
E_PVE_MONSTER_MORTAR_SUB_WARN_SFX = 925
E_PVE_MONSTER_MORTAR_EXIT = 926
E_PVE_MONSTER_RAISE_SHIELD_START = 927
E_PVE_MONSTER_RAISE_SHIELD_END = 928
E_PVE_BOSS_EXCALIBUR_WARN_SFX = 929
E_SYNC_DEBUG_DATA = 9999

def idx_2_event_name(idx):
    global mp_idx_2_name
    if idx in mp_idx_2_name:
        return mp_idx_2_name[idx]
    raise Exception('unkown bcast idx: type=%s, idx=%s.' % (type(idx), idx))


mp_idx_2_name = {}

def init_once():
    global mp_idx_2_name
    mp_idx_2_name = {}
    import sys
    import re
    mod = sys.modules[__name__]
    keys = dir(mod)
    for key in keys:
        if re.match('^[A-Z_0-9]+$', key):
            num = getattr(mod, key)
            if num in mp_idx_2_name:
                raise Exception('duplicated number: %s, %s' % (num, key))
            mp_idx_2_name[num] = key


init_once()

def convert_unicode_to_bytes(d):
    t = type(d)
    if t in (list, tuple):
        newlist = []
        for data in d:
            newlist.append(convert_unicode_to_bytes(data))

        return newlist
    else:
        if t is dict:
            newdict = {}
            for k, v in six.iteritems(d):
                if isinstance(k, six.text_type):
                    k = k.encode('utf-8')
                newdict[k] = convert_unicode_to_bytes(v)

            return newdict
        if t is six.text_type:
            return d.encode('utf-8')
        return d