# uncompyle6 version 2.13.2
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.18 (default, Sep 12 2025, 12:48:39) 
# [GCC Android (13624864, +pgo, +bolt, +lto, +mlgo, based on r530567e) Clang 19.0
# Embedded file name: /Users/netease/Documents/work/battlegrounds/gameplay/releases/rel_current/tools/patch/temp/script/logic/gcommon/common_const/web_const.py
_reload_all = True
MICRO_SERVICE_HOMELAND = 'HomelandService'
MICRO_SERVICE_CREATOR_VIDEO = 'CreatorVideoService'
MICRO_SERVICES = set([MICRO_SERVICE_HOMELAND, MICRO_SERVICE_CREATOR_VIDEO])
CREATOR_VIDEO_REQUEST_LIKE = 1
CREATOR_VIDEO_REQUEST_GET_LIKE_NUM = 2
CREATOR_VIDEO_REQUEST_PLAY_VIDEO = 3
CREATOR_VIDEO_REQUEST_GET_PLAY_VIDEO_NUM = 4
CREATOR_VIDEO_REQS = set([CREATOR_VIDEO_REQUEST_LIKE, CREATOR_VIDEO_REQUEST_GET_LIKE_NUM, CREATOR_VIDEO_REQUEST_PLAY_VIDEO, CREATOR_VIDEO_REQUEST_GET_PLAY_VIDEO_NUM])
SETTINGS_REQUEST_READ = 1
SETTINGS_REQUEST_WRITE = 2
SETTINGS_REQS = set([SETTINGS_REQUEST_READ, SETTINGS_REQUEST_WRITE])
COUNT_SERVICE_REQ_ADD = 1
COUNT_SERVICE_REQ_GET_REAL = 16
COUNT_SERVICE_REQ_GET_VIRTUAL = 256
COUNT_SERVICE_REQ_GET = 4096
COUNT_REQS = set([COUNT_SERVICE_REQ_ADD, COUNT_SERVICE_REQ_GET_REAL, COUNT_SERVICE_REQ_GET_VIRTUAL, COUNT_SERVICE_REQ_GET])
COUNT_SERVICE_REQ_TAG_DEFAULT = 4369
MECHA_MEMORY_LEVEL_1 = '1'
MECHA_MEMORY_LEVEL_2 = '2'
MECHA_MEMORY_LEVEL_3 = '3'
MECHA_MEMORY_LEVEL_4 = '4'
MECHA_MEMORY_LEVEL_5 = '5'
MECHA_MEMORY_LEVEL_6 = '6'
MECHA_MEMORY_LEVEL_7 = '7'
MECHA_MEMORY_LEVEL_8 = '8'
MECHA_MEMORY_LEVEL_9 = '9'
MECHA_MEMORY_LEVEL_10 = '10'
MECHA_MEMORY_LEVEL_11 = '11'
MECHA_MEMORY_ALL_SEASON_MODE = 0
MECHA_MEMORY_OLD_SEASON_MODE = -1